// platform/react/src/pages/CodeOfConduct.tsx
import { Link as RouterLink, useNavigate } from 'react-router-dom';
import { Link } from '@openpeepshq/react-ui';
import { useT } from '../index';
import { AuthLayout, useServerInfo } from '../components';

import { Markdown } from '../lib/Markdown';

export function CodeOfConduct() {
  const t = useT();
  const navigate = useNavigate();
  const serverInfo = useServerInfo();

  const source =
    serverInfo.communityConfig?.content?.codeOfConduct ??
    'This community has not published a code of conduct yet.';

  return (
    <AuthLayout noRedirect navigate={(url) => void navigate(url)}>
      <h1 className="h1 pb-4 font-bold">
        {t('codeOfConduct.title', { defaultValue: 'Code of conduct' })}
      </h1>

      <Markdown source={source} />

      <div className="flex justify-between px-2 pt-4">
        {serverInfo.communityConfig?.settings?.openRegistrations && (
          <span>
            Don't have an account?{' '}
            <Link action="/auth/register" className="text-sm">
              Sign Up
            </Link>
          </span>
        )}
        {serverInfo.publicContent && (
          <span>
            <RouterLink to="/feeds/local" className="op-anchor text-sm">
              See community feed
            </RouterLink>
          </span>
        )}
      </div>
    </AuthLayout>
  );
}

// platform/app/src/routes/code-of-conduct/+page.svelte
<script lang="ts">
  import {
    OpenpeepsMarkdown,
    AuthLayout,
    getServerDataContext,
  } from '@openpeeps/svelte/components';
  import { Link } from '@openpeeps/ui';

  let { serverInfo } = getServerDataContext();
</script>

<AuthLayout noRedirect>
  <h1 class="h1 pb-4 font-bold">Code of conduct</h1>

  <OpenpeepsMarkdown
    source={serverInfo?.communityConfig.content?.codeOfConduct ||
      'This community has not published a code of conduct yet.'}
  />
  <div class="flex justify-between px-2">
    {#if serverInfo.communityConfig.settings.openRegistrations}
      <span>
        Don't have an account?
        <Link action="/auth/register" class="text-sm">Sign Up</Link>
      </span>
    {/if}
    <span>
      {#if serverInfo.publicContent}
        <Link action="/feeds/local" class="text-sm">See community feed</Link>
      {/if}
    </span>
  </div>
</AuthLayout>
