// platform/web/src/pages/admin/Invites.tsx
import { useState } from 'react';
import { inviteLinkMatchesQuery } from '@openpeeps/common/lib';
import { useT, useOpenpeeps } from '@openpeeps/react';
import { UpdatingDate } from '@openpeeps/react/components';
import { Button, Input } from '@openpeeps/react-ui';

export function AdminInvites() {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const invitesQuery = openpeepsApi.admin.useInvitesList();
  const activate = openpeepsApi.admin.activateInviteAction();
  const deactivate = openpeepsApi.admin.deactivateInviteAction();
  const [search, setSearch] = useState('');

  const invites = invitesQuery.data ?? [];
  const filtered = search
    ? invites.filter((i) => inviteLinkMatchesQuery(i, search))
    : invites;

  return (
    <div className="p-4">
      <div className="mb-4 flex items-center justify-between gap-3">
        <h1 className="text-2xl font-semibold">
          {t('admin.invites.title', { defaultValue: 'Invites' })}
        </h1>
        <Button
          title={t('admin.invites.newInvite', { defaultValue: 'New Invite' })}
          variant="variant-filled-primary"
          action={() => undefined}
          data-testid="admin-new-invite-button"
        >
          {t('admin.invites.newInvite', { defaultValue: 'New Invite' })}
        </Button>
      </div>

      <div className="mb-4">
        <Input
          placeholder={t('common.search', { defaultValue: 'Search…' })}
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      <div className="rounded-md border">
        <table className="w-full text-sm">
          <thead className="bg-surface-100">
            <tr>
              <th className="p-2 text-left">Link</th>
              <th className="p-2 text-left">Created by</th>
              <th className="p-2 text-left">Expires</th>
              <th className="p-2 text-left">Uses</th>
              <th className="p-2 text-left">Status</th>
              <th className="p-2"></th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((invite) => {
              const active =
                invite.active && new Date(invite.expiresAt) > new Date();
              return (
                <tr key={invite.id} className="border-t">
                  <td className="p-2 font-mono text-xs">{invite.slug}</td>
                  <td className="p-2">@{invite.profile.handle}</td>
                  <td className="p-2 text-xs">
                    <UpdatingDate date={invite.expiresAt} />
                  </td>
                  <td className="p-2 text-xs">
                    {invite.redemptions.length}/{invite.maxUses}
                  </td>
                  <td className="p-2 text-xs">
                    <span
                      className={`rounded px-2 py-0.5 ${active ? 'bg-success/20 text-success' : 'bg-error/20 text-error'}`}
                    >
                      {active ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td className="p-2">
                    <Button
                      title={active ? 'Deactivate' : 'Activate'}
                      variant="variant-ghost-primary"
                      action={() =>
                        (active ? deactivate : activate)({
                          id: invite.id,
                        })
                      }
                    >
                      {active ? 'Deactivate' : 'Activate'}
                    </Button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// platform/app/src/routes/(protected)/(private)/admin/invites/+page.svelte
<script lang="ts">
  import {
    getModalStore,
    type ModalComponent,
    type ModalSettings,
  } from '@skeletonlabs/skeleton';
  import { page } from '$app/state';
  import {
    SearchAndFilterBar,
    Badge,
    Table,
    UpdatingDate,
  } from '@openpeeps/ui';
  import {
    SortModal,
    FilterModal,
    InvitesTablePopup,
    InviteLinksHeaderActions,
    AccessDeniedLoader,
  } from '@openpeeps/svelte/components';
  import { type ColumnDefinition } from '@openpeeps/ui';
  import { getInvitesListStore } from '@openpeeps/svelte/api';
  import type { InviteLinkWithMeta } from '@openpeeps/common/types';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { inviteLinkMatchesQuery } from '@openpeeps/common/lib';
  import { i18nContext } from '@openpeeps/svelte/components/i18n';

  const { t } = i18nContext();

  const inviteListQuery = getInvitesListStore();

  const modalStore = getModalStore();

  const pageHeaderStore = getPageHeaderStore();

  const sortComponent: ModalComponent = { ref: SortModal };
  const filterComponent: ModalComponent = { ref: FilterModal };

  let tabSet: number = $state(0);
  let search = $state('');

  export const sortModal: ModalSettings = {
    type: 'component',
    component: sortComponent,
  };

  export const filterModal: ModalSettings = {
    type: 'component',
    component: filterComponent,
  };

  const inviteListColumns: ColumnDefinition<InviteLinkWithMeta>[] = [
    {
      type: 'property',
      header: t('admin.invites.linkColumn'),
      id: 'slug',
    },
    {
      id: 'creator',
      type: 'text',
      header: t('admin.invites.createdByColumn'),
      render: (inviteLink) => '@' + inviteLink.profile.handle,
    },
    {
      id: 'dateCreated',
      header: t('admin.invites.expirationDateColumn'),
      type: 'component',
      render: (inviteLink) => ({
        component: UpdatingDate,
        props: { date: inviteLink.expiresAt },
      }),
    },
    {
      id: 'uses',
      header: t('admin.invites.usesColumn'),
      type: 'text',
      render: (invite) => `${invite.redemptions.length}/${invite.maxUses}`,
    },
    {
      id: 'status',
      header: t('admin.invites.statusColumn'),
      type: 'component',
      render: (invite) => {
        const active = invite.active && new Date(invite.expiresAt) > new Date();
        return {
          component: Badge,
          props: {
            status: active ? 'active' : 'inactive',
            variant: active ? 'variant-filled-success' : 'variant-filled-error',
          },
        };
      },
    },
    {
      id: 'action',
      type: 'component',
      header: ' ',
      render: (inviteLink) => ({
        component: InvitesTablePopup,
        props: {
          inviteLink,
        },
      }),
    },
  ];

  $effect(() => {
    if (page.url.hash.includes('link')) {
      tabSet = 1;
      pageHeaderStore.set({
        title: t('admin.invites.title'),
        actions: InviteLinksHeaderActions,
      });
    } else {
      tabSet = 0;
      pageHeaderStore.set({ title: t('admin.invites.title') });
    }
  });
</script>

<div class="relative">
  <div
    class="z-10 w-full border-b flex justify-between items-center px-5 py-2 sticky top-14"
  >
    <h4>{t('admin.invites.linkHeading')}</h4>
    <InviteLinksHeaderActions />
  </div>
  <div class="relative">
    <AccessDeniedLoader queries={[$inviteListQuery]}>
      {#snippet error()}
        <div>
          <div class="w-full flex justify-center items-center p-4">
            <h2 class="text-lg text-error-500">
              Error: {$inviteListQuery?.error?.message}
            </h2>
          </div>
        </div>
      {/snippet}
      {#if $inviteListQuery?.data?.length === 0}
        <div class="w-full flex justify-center items-center p-4">
          <h2 class="text-lg">{t('admin.invites.noInvitesFound')}</h2>
        </div>
      {:else}
        <div class="relative">
          <SearchAndFilterBar
            className="sticky top-28"
            bind:search
            placeholder={t('admin.invites.searchPlaceholder')}
            handleOnSortButtonClicked={() => modalStore.trigger(sortModal)}
            handleOnFilterButtonClicked={() => modalStore.trigger(filterModal)}
          />

          <Table
            data={$inviteListQuery.data}
            columnDefinitions={inviteListColumns}
            filter={(row) => !search || inviteLinkMatchesQuery(row, search)}
          />
        </div>
      {/if}
    </AccessDeniedLoader>
  </div>
</div>
