// libraries/ui/src/lib/form/Form.svelte
<script lang="ts" module>
  type T = unknown;
</script>

<script lang="ts" generics="T">
  import type { ZodType } from 'zod';
  import { readonly, writable } from 'svelte/store';
  import { initFormContext, zodErrorToFormMessages } from '$lib';

  import type { FormMessage, FormMessages } from './types';
  import { preventDefault } from '$lib/utils';
  import { Info } from 'lucide-svelte';

  interface Props {
    data: T;
    schema?: ZodType<T> | undefined;
    valid?: boolean;
    onsubmit?: any;
    validator?: (data: T) => FormMessages;
    children?: import('svelte').Snippet;
    onchange?: (data: T) => void;
    onPreValidate?: (data: T) => void;
    class?: string;
  }

  let {
    data = $bindable(),
    schema = undefined,
    valid = $bindable(false),
    onsubmit = () => {},
    validator = (data) => {
      if (schema) {
        const result = schema.safeParse(data);
        return result.success ? {} : zodErrorToFormMessages(result.error);
      } else {
        return {};
      }
    },
    onchange = undefined,
    onPreValidate = undefined,
    children,
    class: additionalClasses = '',
  }: Props = $props();

  const messagesStore = writable<FormMessages>({});

  const validate = () => {
    onPreValidate?.(data);
    const messages = validator(data);
    messagesStore.set(messages);
    valid = Object.keys(messages).length === 0;
    onchange?.(data);
  };

  initFormContext<T>({
    schema,
    data,
    messagesStore: readonly(messagesStore),
    validate,
    valid,
  });

  $effect(() => {
    validate();
  });

  const messageColor = (m: FormMessage) => {
    switch (m.severity) {
      case 'error':
        return 'text-error';
      case 'warning':
        return 'text-warning';
      case 'info':
        return '';
    }
  };
</script>

<form
  onsubmit={preventDefault(onsubmit)}
  class="flex flex-col gap-4 {additionalClasses}"
>
  {#each $messagesStore['__form__'] || [] as m, index (index)}
    <span class={messageColor(m)}>
      <Info class="size-4" />
      {m.text}
    </span>
  {/each}
  {@render children?.()}
</form>

// libraries/react-ui/src/components/form/Form.tsx
import * as React from 'react';
import { Info } from 'lucide-react';
import type { ZodType } from 'zod';
import { cn } from '@/lib/utils';
import {
  createMessagesStore,
  zodErrorToFormMessages,
} from './helpers';
import { FormCtx } from './context';
import type { FormContextValue, FormMessage, FormMessages } from './types';

export interface FormProps<T> {
  data: T;
  schema?: ZodType<T>;
  validator?: (data: T) => FormMessages;
  onSubmit?: (data: T) => void | Promise<void>;
  onChange?: (data: T) => void;
  onPreValidate?: (data: T) => void;
  onValidChange?: (valid: boolean) => void;
  className?: string;
  children?: React.ReactNode;
}

const messageColor = (m: FormMessage) => {
  switch (m.severity) {
    case 'error':
      return 'text-error';
    case 'warning':
      return 'text-warning';
    case 'info':
      return '';
  }
};

/**
 * Form provider. Mirrors the Svelte `Form.svelte`:
 *   - exposes a context via `useFormContext()`
 *   - holds a messages store synchronised through `useSyncExternalStore`
 *   - validates whenever `data` changes
 *
 * Note: data is treated as a mutable reference (parents pass an object/state
 * they mutate via `deepSet` from inputs). Call `validate()` from anywhere in
 * the tree to refresh messages.
 */
export function Form<T>({
  data,
  schema,
  validator,
  onSubmit,
  onChange,
  onPreValidate,
  onValidChange,
  className,
  children,
}: FormProps<T>) {
  const messagesStoreRef = React.useRef(createMessagesStore());
  const [valid, setValid] = React.useState(false);

  const validate = React.useCallback(() => {
    onPreValidate?.(data);
    const messages =
      validator?.(data) ??
      (schema
        ? (() => {
            const result = schema.safeParse(data);
            return result.success ? {} : zodErrorToFormMessages(result.error);
          })()
        : {});
    messagesStoreRef.current.set(messages);
    const isValid = Object.keys(messages).length === 0;
    setValid(isValid);
    onValidChange?.(isValid);
    onChange?.(data);
  }, [data, schema, validator, onPreValidate, onValidChange, onChange]);

  React.useEffect(() => {
    validate();
  }, [validate]);

  const ctx: FormContextValue<T> = React.useMemo(
    () => ({
      schema,
      messagesStore: messagesStoreRef.current,
      data,
      validate,
      valid,
    }),
    [schema, data, validate, valid],
  );

  const [messages, setMessages] = React.useState<FormMessages>({});
  React.useEffect(() => {
    return messagesStoreRef.current.subscribe(() => {
      setMessages(messagesStoreRef.current.get());
    });
  }, []);

  return (
    <FormCtx.Provider value={ctx as FormContextValue<unknown>}>
      <form
        className={cn('flex flex-col gap-4', className)}
        onSubmit={(e) => {
          e.preventDefault();
          void onSubmit?.(data);
        }}
      >
        {(messages['__form__'] || []).map((m, idx) => (
          <span key={idx} className={cn('flex items-center gap-2', messageColor(m))}>
            <Info className="size-4" />
            {m.text}
          </span>
        ))}
        {children}
      </form>
    </FormCtx.Provider>
  );
}
