// libraries/ui/src/lib/form/FormRadioBool.svelte
<script lang="ts" module>
	import type { ZodRawShape } from 'zod';

	type T = ZodRawShape;
</script>

<script lang="ts" generics="T extends ZodRawShape">
	import Label from './Label.svelte';
	import { getFormContext, deepGet, deepSet } from '$lib';
	import type { ChangeEventHandler } from 'svelte/elements';

	const { data, validate } = getFormContext<T>();

	interface Props {
		name: string;
		title?: string;
		description?: string;
		descriptionTrue?: string;
		titleTrue?: string;
		descriptionFalse?: string;
		titleFalse?: string;
		path: string[];
		dirty?: boolean;
		disabled?: boolean;
		value?: boolean;
		initialValue?: boolean;
	}

	let {
		name,
		title = '',
		description = undefined,
		descriptionTrue = '',
		titleTrue = '',
		descriptionFalse = '',
		titleFalse = '',
		path,
		dirty = $bindable(false),
		disabled = false,
		value = false
	}: Props = $props();

	const updateAndValidate: ChangeEventHandler<HTMLInputElement> = (e) => {
		value = e.currentTarget.value === 'true';
		deepSet(data, path, value);
		dirty = true;
		validate();
	};

	let currentValue = $derived(deepGet(data, path) === true);
</script>

<div class="flex flex-col gap-y-2 px-4" class:opacity-50={disabled}>
	<Label classes="text-lg font-medium">{title}</Label>
	{#if description}<div>{description}</div>{/if}
	<div class="flex gap-x-2">
		<input
			type="radio"
			{name}
			id={`${name}-false`}
			checked={!currentValue}
			oninput={updateAndValidate}
			class="text-primary-500 mt-1 size-4"
			value="false"
			{disabled}
		/>
		<div>
			<label class="text-surface-700 font-medium" for={`${name}-false`}>{titleFalse}</label>
			<label class="text-surface-700" for={`${name}-false`}>{descriptionFalse}</label>
		</div>
	</div>
	<div class="flex gap-x-2">
		<input
			type="radio"
			{name}
			id={`${name}-true`}
			checked={currentValue}
			oninput={updateAndValidate}
			class="text-primary-500 mt-1 size-4"
			value="true"
			{disabled}
		/>
		<div>
			<label class="text-surface-700 font-medium" for={`${name}-true`}>{titleTrue}</label>
			<label class="text-surface-700" for={`${name}-false`}>{descriptionTrue}</label>
		</div>
	</div>
</div>

// libraries/react-ui/src/components/form/FormRadioBool.tsx
import * as React from 'react';
import { cn, deepGet, deepSet } from '@/lib/utils';
import { Label } from './Label';
import { useFormContext } from './context';

export interface FormRadioBoolProps {
  name: string;
  title?: string;
  description?: string;
  descriptionTrue?: string;
  titleTrue?: string;
  descriptionFalse?: string;
  titleFalse?: string;
  path: string[];
  disabled?: boolean;
}

export function FormRadioBool({
  name,
  title = '',
  description,
  descriptionTrue = '',
  titleTrue = '',
  descriptionFalse = '',
  titleFalse = '',
  path,
  disabled = false,
}: FormRadioBoolProps) {
  const { data, validate } = useFormContext();
  const currentValue = deepGet(data, path) === true;

  const update = (e: React.ChangeEvent<HTMLInputElement>) => {
    deepSet(data as object, path, e.currentTarget.value === 'true');
    void validate();
  };

  return (
    <div className={cn('flex flex-col gap-y-2 px-4', disabled && 'opacity-50')}>
      <Label classes="text-lg font-medium" title={title} />
      {description && <div>{description}</div>}
      <div className="flex gap-x-2">
        <input
          type="radio"
          name={name}
          id={`${name}-false`}
          checked={!currentValue}
          onChange={update}
          className="mt-1 size-4 text-primary-500"
          value="false"
          disabled={disabled}
        />
        <div>
          <label className="font-medium text-surface-700" htmlFor={`${name}-false`}>
            {titleFalse}
          </label>
          <label className="text-surface-700" htmlFor={`${name}-false`}>
            {descriptionFalse}
          </label>
        </div>
      </div>
      <div className="flex gap-x-2">
        <input
          type="radio"
          name={name}
          id={`${name}-true`}
          checked={currentValue}
          onChange={update}
          className="mt-1 size-4 text-primary-500"
          value="true"
          disabled={disabled}
        />
        <div>
          <label className="font-medium text-surface-700" htmlFor={`${name}-true`}>
            {titleTrue}
          </label>
          <label className="text-surface-700" htmlFor={`${name}-true`}>
            {descriptionTrue}
          </label>
        </div>
      </div>
    </div>
  );
}
