// platform/svelte/src/lib/components/core/post/pieces/PostReactionHeader.svelte
<script lang="ts">
  import type { PublicPost } from '@openpeeps/common/types';
  import PostMenu from './PostMenu.svelte';
  import { AvatarWithName } from '../../profile';
  import { getPostStore, groupStore } from '$lib/api';
  import { i18nContext } from '@openpeeps/svelte/components/i18n';

  interface Props {
    post: PublicPost;
    deleteCallback?: () => void;
    inGroup?: boolean;
  }

  const { t } = i18nContext();

  let {
    post,
    deleteCallback = () => undefined,
    inGroup = false,
  }: Props = $props();

  const replyPostQuery = post.inReplyToId
    ? getPostStore(post.inReplyToId)
    : undefined;

  const groupQuery = groupStore(post.groupId || '');

  let group = $derived($groupQuery.data);
</script>

<div class="flex justify-between border-b py-2">
  <div class="flex w-5/6 items-center gap-2">
    {#if post.groupId && group && !inGroup}
      <!-- group post -->
      {#if post.repost && post.profile?.handle}
        <a href="/@{post.profile.handle}">
          <AvatarWithName profile={post.profile} />
        </a>
        <span class="text-sm font-light">{t('posts.reposted')}</span>
      {:else if $replyPostQuery?.data?.profile?.handle}
        <a href="/@{post.profile.handle}">
          <AvatarWithName profile={post.profile} />
        </a>
        <a class="w-max" href="/posts/{post.inReplyToId}">replied to</a>
        <a class="w-max" href="/@{$replyPostQuery.data.profile.handle}">
          <AvatarWithName profile={$replyPostQuery.data.profile} />
        </a>
        <span class="text-sm font-light">in</span>
      {:else}
        <span class="text-sm font-light">Posted in</span>
      {/if}
      <a
        href="/groups/@{group.handle}"
        class="text-primary flex-1 truncate font-semibold"
      >
        {group.displayName}
      </a>
    {:else}
      <!-- standalone post -->
      {#if post.repost && post.profile?.handle}
        <a href="/@{post.profile.handle}">
          <AvatarWithName profile={post.profile} />
        </a>
        <span class="font-sm font-light">{t('posts.reposted')}</span>
      {:else if $replyPostQuery?.data?.profile?.handle}
        <a href="/@{post.profile.handle}">
          <AvatarWithName profile={post.profile} />
        </a>
        <a href="/posts/{post.inReplyToId}" class="text-sm">
          {t('posts.replyTo')}
        </a>
        <a href="/@{$replyPostQuery.data.profile.handle}">
          <AvatarWithName profile={$replyPostQuery.data.profile} />
        </a>
      {:else}
        &nbsp;
      {/if}
    {/if}
  </div>
  <PostMenu post={post.repost || post} {deleteCallback} />
</div>

// platform/react-native/src/components/custom/post/pieces/PostReactionHeader.tsx
import { TouchableWithoutFeedback, View } from 'react-native';
import { MessageSquareIcon } from '~/components/icons';
import { type PublicPost } from '@openpeeps/common';
import { useOpenpeeps } from '@openpeeps/react';
import { ThemedText } from '~/components/ui/themed-text';
import React from 'react';
import { useTranslation } from 'react-i18next';
import { profileName, truncateText } from '~/lib/utils';
import { ProfileAvatar } from '../../profile/profile-avatar';
import { PostMenu } from './PostMenu';

interface PostReactionHeaderProps {
  post: PublicPost;
  inGroup?: boolean;
  hideReply?: boolean;
  previewMode?: boolean;
}

export const PostReactionHeader = ({
  post,
  inGroup = false,
  hideReply = false,
  previewMode = false,
}: PostReactionHeaderProps) => {
  const { t } = useTranslation();
  const { openpeepsApi } = useOpenpeeps();
  const {
    data: replypost,
    isError,
    isLoading: isReplyLoading,
  } = openpeepsApi.usePost(post.inReplyToId as string);
  const {
    data: group,
    isError: isGroupError,
    isLoading: isGroupLoading,
  } = openpeepsApi.useGroup(post.groupId as string);

  const showReply = post.inReplyToId && !hideReply && !isError;
  const showGroup = post.groupId && group && !isGroupError && !inGroup;
  const showRepost = !!post.repost;

  return (
    <>
      {!isGroupLoading && !isReplyLoading && (
        <>
          {(showReply || showGroup) && (
            <View className="px-5">
              <View className="flex-row items-center border-b border-border pb-5 justify-between gap-2 mb-2">
                <View className="flex-row items-center gap-2 flex-1 flex-wrap">
                  {showReply && (
                    <>
                      <MessageSquareIcon
                        size={18}
                        className="text-foreground"
                      />
                      <ThemedText className="truncate">
                        {truncateText(
                          profileName(post?.profile),
                          showGroup ? 10 : 20,
                        )}
                      </ThemedText>

                      <ThemedText className="text-muted-foreground">
                        {t('posts.replyTo')}
                      </ThemedText>
                      <ThemedText className="truncate">
                        {truncateText(
                          profileName(replypost?.profile),
                          showGroup ? 10 : 20,
                        )}
                      </ThemedText>
                    </>
                  )}

                  {showGroup && (
                    <>
                      {showReply && (
                        <ThemedText className="text-muted-foreground">
                          in
                        </ThemedText>
                      )}
                      {!showReply && (
                        <ThemedText className="text-muted-foreground">
                          Posted in
                        </ThemedText>
                      )}
                      <ThemedText className="truncate">
                        {truncateText(group.displayName, showReply ? 10 : 20)}
                      </ThemedText>
                    </>
                  )}
                </View>
                {!previewMode && <PostMenu post={post} />}
              </View>
            </View>
          )}

          {showRepost && (
            <View className="px-5">
              <View className="flex-row items-center border-b border-border pb-5 justify-between gap-2 mb-2">
                <View className="flex-row items-center gap-2 flex-1 flex-wrap">
                  <TouchableWithoutFeedback onPress={() => { }}>
                    <ProfileAvatar profile={post.profile} className="size-8" />
                  </TouchableWithoutFeedback>
                  <ThemedText className="truncate">
                    {profileName(post.profile)}
                  </ThemedText>
                  <ThemedText className="text-muted-foreground">
                    reposted this
                  </ThemedText>
                </View>
                {!previewMode && <PostMenu post={post} />}
              </View>
            </View>
          )}
        </>
      )}
    </>
  );
};
