// platform/svelte/src/lib/components/core/conversations/ParticipantsCard.svelte
<script lang="ts">
	import { Avatar } from '../profile';
	import type { PublicProfile } from '@openpeeps/common/types';
	import { profileName, truncateText } from '@openpeeps/common/lib';
  import ConversationProfilesAvatar from './ConversationProfilesAvatar.svelte';

	interface Props {
		participants: PublicProfile[];
		max?: number | undefined;
		truncate?: boolean;
		size?: number;
		justImage?: boolean;
		navigate?: boolean;
	}

	let { participants, max = undefined, truncate, size = 2.5, justImage = false, navigate = false }: Props = $props();
	const names = participants.map(profileName).join(', ');
</script>

<div class="flex w-full justify-between gap-4 p-5">
	<ConversationProfilesAvatar  profiles={participants}/>
	{#if !justImage}
		<div class="md:hidden">
			{truncate ? truncateText(names, 20) : names}
		</div>
		<div class="hidden md:block">
			{truncate ? truncateText(names, 100) : names}
		</div>
	{/if}
</div>

// platform/react-native/src/components/custom/common/participants-card.tsx
import {View} from 'react-native';
import React from 'react';
import type {JamState} from '@openpeeps/common/types';
import {AvatarFromId} from './avatar-from-id';

interface ParticipantsCardProps {
  jamState: JamState;
}

export const ParticipantsCard: React.FC<ParticipantsCardProps> = ({
  jamState,
}) => {
  return (
    <View className="flex w-full justify-between gap-4 p-5">
      <View className="flex items-center">
        {jamState.participants.length > 2 ? (
          <>
            {jamState.participants.slice(0, 2).map(participant => (
              <>
                <AvatarFromId id={participant} />
              </>
            ))}
          </>
        ) : (
          <>
            {jamState.participants.map(participant => (
              <>
                <AvatarFromId id={participant} />
              </>
            ))}
          </>
        )}
      </View>
    </View>
  );
};
