// platform/svelte/src/lib/components/core/notification/types/DirectMessage.svelte
<script lang="ts">
	import { MessageSquare } from 'lucide-svelte';
	import type { ExpandedNotification, PublicPost } from '@openpeeps/common/types';
	import { profileName } from '@openpeeps/common/lib';
	import { Message } from '$lib/components/core/conversations';
	import { UpdatingDate } from '@openpeeps/ui';
	import NotificationWrapper from '../NotificationWrapper.svelte';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		notification: ExpandedNotification;
	}

	let { notification }: Props = $props();
	const { t } = i18nContext();

	const { conversationStart } = notification.data as {
		conversationStart: PublicPost;
	};
</script>

<NotificationWrapper profile={notification.senderProfile!} seen={notification.seen}>
	<a class="w-full px-4" href="/conversations/{conversationStart?.id}">
		<div class="flex w-full items-center justify-between">
			<p class="flex items-center gap-2 text-sm font-semibold">
				<MessageSquare size={16} />
				{t('notification.directMessage.text', {
					profileName: profileName(notification.senderProfile!)
				})}
			</p>
		</div>
		{#if notification.post}
			<Message message={notification.post} />
			<div class="mt-2 text-xs">
				<UpdatingDate date={notification.post.createdAt} />
			</div>
		{/if}
	</a>
</NotificationWrapper>

// platform/react-native/src/components/custom/notification/types/direct-message.tsx
import { Pressable, View } from 'react-native';
import React from 'react';
import { ThemedText } from '~/components/ui/themed-text';
import { NotificationWrapper } from '../NotificationWrapper';
import { PublicNotification, PublicPost } from '@openpeeps/common';
import { MessageSquareIcon } from '~/components/icons';
import { profileName } from '~/lib/utils';
import { MessageCard } from '../../conversations/message-card';
import { useTranslation } from 'react-i18next';
import { MainStackParamList } from '~/components/navigation/types';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useNavigation } from '@react-navigation/native';

interface NotificationTypeProps {
  notification: PublicNotification;
}
export const DirectMessage: React.FC<NotificationTypeProps> = ({
  notification,
}) => {
  const profile = notification.senderProfile!;
  const { t } = useTranslation();
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  const { conversationStart } = notification.data as {
    conversationStart: PublicPost;
  };

  return (
    <NotificationWrapper
      profile={profile}
      seen={notification.seen}
      showProfile={false}>
      <Pressable
        onPress={() =>
          navigation.navigate('Conversation', { id: conversationStart.id })
        }
        className="w-full ">
        <View className="mb-2 flex flex-row items-center gap-2 font-semibold flex-wrap">
          <MessageSquareIcon className="h-4 w-4 text-foreground" />
          <ThemedText className="text-foreground">
            {t('notification.directMessage.text', {
              profileName: profileName(profile),
            })}
          </ThemedText>
        </View>
        {notification.post && <MessageCard message={notification.post} />}
      </Pressable>
    </NotificationWrapper>
  );
};
