// platform/svelte/src/lib/components/core/notification/types/Reply.svelte
<script lang="ts">
	import { FeedPost } from '$lib/components/core/post';
	import { Reply } from 'lucide-svelte';
	import type { ExpandedNotification, PublicPost } from '@openpeeps/common/types';
	import { profileName } from '@openpeeps/common/lib';
	import NotificationWrapper from '../NotificationWrapper.svelte';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		notification: ExpandedNotification;
	}

	let { notification }: Props = $props();
	const { t } = i18nContext();

	const { replyPost } = notification.data as { replyPost: PublicPost };
	const profile = notification.senderProfile!;
</script>

<NotificationWrapper {profile} seen={notification.seen} showProfile={false}>
	<a class="w-full px-4" href="/posts/{replyPost.id}">
		<div class="flex w-full items-center justify-between">
			<p class="mb-2 flex items-center gap-2 text-sm font-semibold">
				<Reply size={16} />
				{t('notification.reply.text', {
					profileName: profileName(profile)
				})}
			</p>
		</div>

		{#if replyPost}
			<FeedPost post={replyPost} />
		{/if}
	</a>
</NotificationWrapper>

// platform/react-native/src/components/custom/notification/types/reply.tsx
import React from 'react';
import { Pressable, View } from 'react-native';
import { ThemedText } from '~/components/ui/themed-text';
import { PublicNotification, PublicPost } from '@openpeeps/common';
import { NotificationWrapper } from '../NotificationWrapper';
import { ReplyIcon } from '~/components/icons';
import { profileName } from '~/lib/utils';
import { useTranslation } from 'react-i18next';
import { MainStackParamList } from '~/components/navigation/types';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useNavigation } from '@react-navigation/native';
import { FeedPost } from '../../post/feed/chronological/FeedPost';

interface NotificationTypeProps {
  notification: PublicNotification;
}
export const Reply: React.FC<NotificationTypeProps> = ({ notification }) => {
  const profile = notification.senderProfile!;
  const { replyPost } = notification.data as { replyPost: PublicPost };
  const { t } = useTranslation();
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  return (
    <NotificationWrapper
      profile={profile}
      seen={notification.seen}
      showProfile={false}>
      <Pressable
        onPress={() => navigation.navigate('Post', { id: replyPost.id })}
        className="w-full flex">
        <View className="flex w-full items-center justify-between">
          <View className="mb-2 flex flex-row items-center gap-2 font-semibold flex-wrap">
            <ReplyIcon className="h-4 w-4 text-foreground" />
            <ThemedText className="text-foreground">
              {t('notification.reply.text', {
                profileName: profileName(profile),
              })}
            </ThemedText>
          </View>
        </View>
        {replyPost && <FeedPost post={replyPost} showReplyTo={false} showMenu={false} showReactionHeader={false} />}
      </Pressable>
    </NotificationWrapper>
  );
};
