// platform/web/src/pages/settings/Theme.tsx
import { useEffect, useState } from 'react';
import { THEME_OPTIONS, type ThemeOptions } from '@openpeeps/common';
import { useT, useOpenpeeps } from '@openpeeps/react';
import { useCurrentProfile } from '@openpeeps/react/components';
import { Button } from '@openpeeps/react-ui';

export function ThemeSettings() {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const me = useCurrentProfile();
  const settingsQuery = openpeepsApi.useCurrentProfileSettings();
  const updateSettings = openpeepsApi.updateCurrentProfileSettingsAction();

  const [theme, setTheme] = useState<ThemeOptions | undefined>(undefined);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (settingsQuery.data?.theme) setTheme(settingsQuery.data.theme);
  }, [settingsQuery.data]);

  if (!me) return null;

  const submit = async () => {
    setSubmitting(true);
    try {
      await updateSettings({ id: me.id, theme });
      window.location.reload();
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex flex-col gap-4 p-3">
      <h1 className="text-2xl font-semibold">
        {t('settings.theme.title', { defaultValue: 'Theme' })}
      </h1>

      <div className="border p-4">
        <h4 className="my-2 text-lg font-semibold">
          {t('settings.theme.title', { defaultValue: 'Theme' })}
        </h4>
        <span className="text-sm text-muted-foreground">
          {t('settings.theme.themeDescription', {
            defaultValue: 'Choose how the application looks for you.',
          })}
        </span>
        <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2">
          {THEME_OPTIONS.map((option) => (
            <label key={option} className="inline-flex items-center gap-2">
              <input
                type="radio"
                className="h-4 w-4"
                name="theme"
                value={option}
                checked={theme === option}
                onChange={() => setTheme(option)}
              />
              <span>
                {t(`settings.theme.${option}.mode`, { defaultValue: option })}
              </span>
            </label>
          ))}
        </div>
      </div>

      <Button
        title="Save"
        variant="variant-ghost-primary"
        action={submit}
        disabled={submitting}
      >
        {submitting
          ? t('common.saving', { defaultValue: 'Saving…' })
          : t('common.save', { defaultValue: 'Save' })}
      </Button>
    </div>
  );
}

// platform/app/src/routes/(protected)/(private)/settings/theme/+page.svelte
<script lang="ts">
  import { i18nContext } from '@openpeeps/svelte/components';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import {
    currentProfileSettingsStore,
    updateProfileSettingsMutation,
  } from '@openpeeps/svelte/api';
  import { Button } from '@openpeeps/ui';
  import { getToastStore } from '@skeletonlabs/skeleton';
  import { toast } from '@openpeeps/svelte';
  import { getCurrentProfile } from '@openpeeps/svelte/auth';
  import { sleep, THEME_OPTIONS, type ThemeOptions } from '@openpeeps/common';

  const pageHeaderStore = getPageHeaderStore();
  let profileSettingsQuery = currentProfileSettingsStore();
  const currentProfile = getCurrentProfile();

  let profileSettings = $profileSettingsQuery.data;

  const updateSettings = updateProfileSettingsMutation();
  const toastStore = getToastStore();
  const { t } = i18nContext();

  let theme = $state<ThemeOptions | undefined>(profileSettings?.theme);

  const handleSubmit = () =>
    updateSettings({
      id: currentProfile.id,
      theme: theme,
    })
      .then(() =>
        toastStore.trigger(
          toast({
            message: t('settings.theme.updateSuccess'),
            background: 'variant-filled-success',
          }),
        ),
      )
      .then(() => sleep(5))
      .then(() => window.location.reload());

  $effect(() => {
    if ($profileSettingsQuery.data) {
      theme = $profileSettingsQuery.data.theme;
    }
  });

  $effect(() => {
    pageHeaderStore.set({
      title: t('settings.theme.title'),
    });
  });
</script>

<div class="flex flex-col gap-4 p-3">
  <div class="border p-4">
    <h4 class="my-4 text-lg font-semibold">
      {t('settings.theme.title')}
    </h4>
    <span>{t('settings.theme.themeDescription')}</span>
    <div class="flex-wrap items-center gap-x-4 gap-y-2">
      {#each THEME_OPTIONS as option}
        <div>
          <input
            type="radio"
            class="h-4 w-4"
            bind:group={theme}
            value={option}
          />
          <span>{t(`settings.theme.${option}.mode`)}</span>
        </div>
      {/each}
    </div>
  </div>
  <Button variant="variant-ghost-primary" action={handleSubmit}>Save</Button>
</div>
