// libraries/ui/src/lib/date/Timespan.svelte
<script lang="ts">
	interface Props {
		start: string;
		end?: string;
		timeZone?: string;
		truncate?: number;
	}

	let {
		start,
		end,
		truncate,
		timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone
	}: Props = $props();

	const userTimezone = $derived(typeof window !== 'undefined' ? Intl.DateTimeFormat().resolvedOptions().timeZone :'UTC')
	

	const effectiveTimeZone = $derived(timeZone || userTimezone)
	const startDate = $derived(new Date(start));
	const endDate = $derived(end && new Date(end));

	const startDateString = $derived(
		startDate.toLocaleDateString(undefined, { timeZone: effectiveTimeZone, dateStyle: 'full' })
	);
	const startTimeString = $derived(
		startDate.toLocaleTimeString(undefined, { timeZone: effectiveTimeZone, timeStyle: 'short' })
	);

	const endDateString = $derived(
		endDate && endDate.toLocaleDateString(undefined, { timeZone: effectiveTimeZone, dateStyle: 'full' })
	);
	const endTimeString = $derived(
		endDate && endDate.toLocaleTimeString(undefined, { timeZone:effectiveTimeZone, timeStyle: 'short' })
	);

	const isSameDay = $derived(startDateString === endDateString);

	const formattedTimespan = $derived(
		endDateString
			? isSameDay
				? `${startDateString}, ${startTimeString} - ${endTimeString}`
				: `${startDateString}, ${startTimeString} - ${endDateString}, ${endTimeString}`
			: `${startDateString}, ${startTimeString}`
	);

	const truncateText = (v: string) => (truncate ? `${v.substring(0, truncate)}...` : v);
</script>

{truncateText(formattedTimespan)}

// platform/rn-components/src/components/custom/date/timespan.tsx
import React from 'react';
import { ThemedText } from '../../ui/themed-text';

interface TimespanProps {
  start: string;
  end?: string;
  timeZone?: string;
  truncate?: number;
}

export const Timespan = ({
  start,
  end,
  truncate,
  timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone,
}: TimespanProps) => {
  const startDate = new Date(start);
  const endDate = end && new Date(end);

  const startDateString = startDate.toLocaleDateString(undefined, {
    timeZone,
    dateStyle: 'full',
  });
  const startTimeString = startDate.toLocaleTimeString(undefined, {
    timeZone,
    timeStyle: 'short',
  });

  const endDateString =
    endDate &&
    endDate.toLocaleDateString(undefined, { timeZone, dateStyle: 'full' });

  const endTimeString =
    endDate &&
    endDate.toLocaleTimeString(undefined, { timeZone, timeStyle: 'short' });

  const isSameDay = startDateString === endDateString;

  const formattedTimespan = endDateString
    ? isSameDay
      ? `${startDateString}, ${startTimeString} - ${endTimeString}`
      : `${startDateString}, ${startTimeString} - ${endDateString}, ${endTimeString}`
    : `${startDateString}, ${startTimeString}`;

  const truncateText = (v: string) =>
    truncate ? `${v.substring(0, truncate)}...` : v;

  return <ThemedText>{truncateText(formattedTimespan)}</ThemedText>;
};
