// platform/rn-components/src/components/custom/post/types/event/CardEvent.tsx
import { View, Image, TouchableOpacity, ActivityIndicator } from 'react-native';
import React, { useMemo } from 'react';
import { ThemedText } from '~/components/ui/themed-text';
import { Event, PublicPost, PublicRsvp } from '@openpeepshq/common';
import { truncateText } from '~/lib/utils';
import { formatEventRecurrence } from '@openpeepshq/common/lib';
import { useOpenpeeps } from '@openpeepshq/react';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { MainStackParamList } from '~/components/navigation/types';
import { calculateEffectiveRsvps } from '~/lib/utils';
import { Timespan } from '~/components/custom/date';
import { EventLocation } from '~/components/custom/post/pieces/EventLocation';
import { ProfileEventRelationship } from '~/components/custom/post/pieces/ProfileEventRelationship';
import { ParticipantsCard } from '~/components/custom/common';
import { useTranslation } from 'react-i18next';

interface CardEventProps {
  post: PublicPost;
}

export const CardEvent = ({ post }: CardEventProps) => {
  const { openpeepsApi } = useOpenpeeps();
  const { t } = useTranslation();

  const event = post.data as Event;
  const jam = event.jam;
  const occurrenceId = post.occurrenceRecurrenceId;
  const { data: jamState, isLoading } = openpeepsApi.useJamState(
    post.id || '',
    occurrenceId
  );
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();
  const rsvps = useMemo<PublicRsvp[]>(() => {
    return calculateEffectiveRsvps(post, occurrenceId) || [];
  }, [post, occurrenceId]);

  return (
    <TouchableOpacity
      onPress={() => {
        navigation.navigate('Post', {
          id: post.id,
          occurrence: occurrenceId,
        });
      }}
      className="flex mb-6 w-full border-[0.5px] border-gray-100/50 rounded-lg"
    >
      <View className="w-full aspect-video overflow-hidden rounded-t-md">
        <Image
          source={
            event.image
              ? { uri: event.image }
              : require('~/assets/images/event-placeholder.png')
          }
          className="w-full h-full"
          resizeMode="cover"
        />
      </View>
      <View className="grid gap-y-5 p-4">
        <View className="flex-row items-center gap-x-1">
          <Timespan
            start={post.occurrenceStart ?? event.start}
            end={post.occurrenceEnd ?? event.end}
            timeZone={event.timeZone}
          />
        </View>
        {event.recurrence ? (
          <ThemedText className="text-muted-foreground text-sm">
            {formatEventRecurrence(event.recurrence, t, event.start)}
          </ThemedText>
        ) : null}
        <ThemedText className="text-xl font-semibold">
          {truncateText(event?.name, 100) || '-'}
        </ThemedText>
        <View className="flex flex-row gap-x-2">
          <EventLocation post={post} truncate={true} />
          <ProfileEventRelationship post={post} />
        </View>
        {jam && (
          <View className="flex w-full">
            {isLoading && <ActivityIndicator size={'small'} />}
            {!isLoading && jamState && (
              <View
                className={`flex justify-start ${
                  jamState?.participants?.length || 0 > 1 ? 'gap-5' : 'gap-2'
                }
               text-muted-foreground text-xs ${
                 (jamState?.participants?.length ?? 0) > 0 ? '-mt-4' : ''
               }`}
              >
                <View className="flex flex-row items-center gap-x-2">
                  {jamState?.participants?.length > 0 && (
                    <View className="-ml-5 w-12">
                      <ParticipantsCard jamState={jamState} />
                    </View>
                  )}
                  <ThemedText>
                    {rsvps.length} {rsvps?.length === 1 ? 'rsvp' : 'rsvps'}
                  </ThemedText>
                </View>
              </View>
            )}
          </View>
        )}
      </View>
    </TouchableOpacity>
  );
};

// platform/svelte/src/lib/components/core/post/types/event/CardEvent.svelte
<script lang="ts">
  import { Button, Timespan } from '@openpeeps/ui';
  import type { Event, PublicPost } from '@openpeeps/common/types';
  import { page } from '$app/state';
  import ParticipantsCard from '../../pieces/ParticipantsCard.svelte';
  import { jamStateStore } from '$lib/api';
  import { getCurrentProfile } from '$lib/auth';
  import { getJamUrl } from '@openpeeps/common/lib';
  import EventLocation from '../../pieces/EventLocation.svelte';
  import { i18nContext } from '$lib/components/i18n';
  import ProfileEventRelationship from './ProfileEventRelationship.svelte';
  import { AccessDeniedLoader } from '$lib/components/layout';
  import { postViewCounter } from '$lib/utils';

  const { t } = i18nContext();

  interface Props {
    post: PublicPost;
  }

  const me = getCurrentProfile();

  const { post }: Props = $props();
  const event = $derived(post.data as Event);
  const jam = $derived(event?.jam);

  const jamLink = getJamUrl(post.id, page.url.origin);

  const jamStateQuery = $derived(jam ? jamStateStore(post.id) : undefined);
</script>

<div class="hover:bg-surface-100 overflow-hidden rounded-md px-2 pt-2" use:postViewCounter={post.id}>
  <a href="{page.url.origin}/posts/{post.id}" class="flex flex-col gap-2">
    <span class="aspect-video w-full overflow-hidden rounded-md">
      <img
        src={event.image || '/img/event-default.png'}
        alt={event?.name || event?.content}
        class="h-full w-full object-cover"
      />
    </span>
    <span class="flex flex-col gap-1">
      <div class="truncate text-sm">
        <Timespan {...event} />
      </div>
      <h3 class="truncate font-semibold">{event?.name || event?.content}</h3>
      <div class="flex flex-col gap-1">
        <div class="flex flex-row gap-x-2">
          <EventLocation {post} truncate={true} />
          <ProfileEventRelationship {post} />
        </div>
        {#if jam && me}
          {@const jamState = $jamStateQuery?.data}
          {@const attendeesLength = jamState?.participants.length ?? 0}
          <AccessDeniedLoader queries={[$jamStateQuery!]}>
            <span
              class="flex items-center justify-start {attendeesLength > 1
                ? 'gap-5'
                : 'gap-2'} 
						text-surface-600 text-xs {attendeesLength > 0 ? '-mt-4' : ''}"
            >
              {#if jamState?.active}
                <span class="-ml-5 w-12">
                  <ParticipantsCard {jamState} />
                </span>
                <span>
                  {attendeesLength}
                  {attendeesLength === 1 ? 'attendee' : 'attendees'}
                </span>
                <span>
                  <Button
                    action={jamLink}
                    variant="variant-filled-primary"
                    compact
                  >
                    {t('jam.join.submit')}
                  </Button>
                </span>
              {:else if jam.moderators.includes(me.id)}
                <span>
                  <Button action={jamLink} variant="variant-filled-primary">
                    {t('jam.start.submit')}
                  </Button>
                </span>
              {/if}
            </span>
          </AccessDeniedLoader>
        {/if}
      </div>
    </span>
  </a>
</div>
