// platform/rn-components/src/components/post/pieces/EventRsvpButton.tsx
import React, { useEffect, useRef } from 'react';
import { View } from 'react-native';
import { BottomSheetModal } from '@gorhom/bottom-sheet';
import { useTranslation } from 'react-i18next';
import Toast from 'react-native-toast-message';
import type { PublicPost } from '@openpeepshq/common/types';
import { useEventRsvp } from '@openpeepshq/react';
import { Button } from '~/components/ui/button';
import { ThemedText } from '~/components/ui/themed-text';
import { bottomSheetPresent } from '~/lib/bottom-sheet-ref';
import {
  EventRsvpScopeDialog,
  type RsvpScopeChoice,
} from './EventRsvpScopeDialog';

export interface EventRsvpButtonProps {
  post: PublicPost;
  recurrenceId?: string;
  lockToOccurrence?: boolean;
}

export const EventRsvpButton = ({
  post,
  recurrenceId,
  lockToOccurrence = false,
}: EventRsvpButtonProps) => {
  const { t } = useTranslation();
  const scopeSheetRef = useRef<BottomSheetModal>(null);
  const {
    profile,
    myEvent,
    myRsvp,
    canRsvp,
    recurring,
    defaultId,
    occurrences,
    capacityEvent,
    full,
    error,
    pending,
    submitting,
    requestRespond,
    confirmScope,
  } = useEventRsvp({
    post,
    recurrenceId,
    lockToOccurrence,
    onSuccess: () =>
      Toast.show({ type: 'success', text1: t('posts.rsvp.success') }),
    onError: (message) => Toast.show({ type: 'error', text1: message }),
  });

  const showScopeSheet = Boolean(pending && recurring && !lockToOccurrence);
  useEffect(() => {
    if (showScopeSheet) bottomSheetPresent(scopeSheetRef);
  }, [showScopeSheet]);

  const onConfirmScope = async (scope: RsvpScopeChoice) => {
    const ok = await confirmScope(scope);
    if (ok) scopeSheetRef.current?.close();
  };

  if (myEvent || !profile) return null;
  if (!canRsvp && !(myRsvp && myRsvp.response !== 'no')) return null;

  if (myRsvp?.response === 'removed') {
    return (
      <ThemedText className="mt-4 text-center text-sm text-muted-foreground">
        {t('events.rsvp.removedMessage')}
      </ThemedText>
    );
  }

  const scopeDialog = (
    <EventRsvpScopeDialog
      ref={scopeSheetRef}
      post={post}
      response={pending ?? 'yes'}
      defaultRecurrenceId={defaultId}
      occurrences={occurrences}
      error={error}
      isLoading={submitting}
      onConfirm={onConfirmScope}
    />
  );

  const errorText =
    error && !pending ? (
      <ThemedText className="mt-2 text-center text-sm text-destructive">
        {error}
      </ThemedText>
    ) : null;

  if (myRsvp && myRsvp.response !== 'no') {
    return (
      <View className="w-full">
        <Button
          variant="outline"
          className="w-full"
          disabled={submitting}
          onPress={() => requestRespond('no')}
        >
          <ThemedText className="text-destructive">
            {t('posts.rsvp.cancelRegistration')}
          </ThemedText>
        </Button>
        <ThemedText className="mt-2 text-center text-sm">
          {myRsvp.response === 'yes'
            ? t('posts.rsvp.attendingMessage')
            : t('posts.rsvp.maybeMessage')}
        </ThemedText>
        {errorText}
        {scopeDialog}
      </View>
    );
  }

  return (
    <View className="mt-4 w-full">
      <View className="w-full flex-row gap-x-2">
        <Button
          className="w-[70%]"
          disabled={full || submitting}
          onPress={() => requestRespond('yes')}
        >
          <ThemedText>
            {full ? t('events.rsvp.full') : t('posts.rsvp.register')}
          </ThemedText>
        </Button>
        {!capacityEvent ? (
          <Button
            variant="ghost"
            disabled={submitting}
            onPress={() => requestRespond('tentative')}
          >
            <ThemedText className="text-muted-foreground">
              {t('posts.rsvp.maybe')}
            </ThemedText>
          </Button>
        ) : null}
        <Button
          variant="outline"
          disabled={submitting}
          onPress={() => requestRespond('no')}
        >
          <ThemedText className="text-destructive">
            {t('posts.rsvp.no')}
          </ThemedText>
        </Button>
      </View>
      {errorText}
      {scopeDialog}
    </View>
  );
};

// platform/svelte/src/lib/components/core/post/types/event/EventRsvpButton.svelte
<script lang="ts">
	import { eventRsvpMutation, me } from '$lib/api';
	import type { PublicPost, Event } from '@openpeeps/common/types';
	import { Button } from '@openpeeps/ui';
	import { getToastStore } from '@skeletonlabs/skeleton';
	import { i18nContext } from '@openpeeps/svelte/components/i18n';
	import { calculateEffectiveRsvps } from '@openpeeps/common';

	interface Props {
		post: PublicPost;
	}

	let { post }: Props = $props();
	const toastStore = getToastStore();
	const { t } = i18nContext();
	const myEvent = $derived(post.profile?.id === $me?.id);
	const myRsvp = $derived(calculateEffectiveRsvps(post).find((r) => r.profile.id === $me?.id));

	const rsvpToEvent = eventRsvpMutation({ id: post.id });

	const handleRegister = async () => {
		if (myEvent) return;
		rsvpToEvent({ response: 'yes' })
			.then(() => {
				toastStore.trigger({
					message: t('posts.rsvp.success'),
					background: 'variant-filled-success'
				});
			})
			.catch((error) => {
				toastStore.trigger({
					message: t('posts.rsvp.error', { error: error.message }),
					background: 'variant-filled-error'
				});
			});
	};

	const handleMaybe = async () => {
		if (myEvent) return;
		rsvpToEvent({ response: 'tentative' })
			.then(() => {
				toastStore.trigger({
					message: t('posts.rsvp.success'),
					background: 'variant-filled-success'
				});
			})
			.catch((error) => {
				toastStore.trigger({
					message: t('posts.rsvp.error', { error: error.message }),
					background: 'variant-filled-error'
				});
			});
	};

	const handleNo = async () => {
		if (myEvent) return;
		await rsvpToEvent({ response: 'no' })
			.then(() => {
				toastStore.trigger({
					message: t('posts.rsvp.success'),
					background: 'variant-filled-success'
				});
			})
			.catch((error) => {
				toastStore.trigger({
					message: t('posts.rsvp.error', { error: error.message }),
					background: 'variant-filled-error'
				});
			});
	};
</script>

{#if !myEvent}
	{#if myRsvp && myRsvp.response !== 'no'}
		<div class="w-full">
			<Button variant="variant-ringed-secondary" class="text-error-500 w-full" action={handleNo}>
				{t('posts.rsvp.cancelRegistration')}</Button
			>
			<p class="mt-2 text-center">
				{myRsvp.response === 'yes'
					? t('posts.rsvp.attendingMessage')
					: t('posts.rsvp.maybeMessage')}
			</p>
		</div>
	{:else}
		<div class="mt-4 flex w-full gap-x-2">
			<Button variant="variant-filled-primary" action={handleRegister} class="w-[70%]"
				>{t('posts.rsvp.register')}</Button
			>
			<Button variant="variant-ghost-primary" action={handleMaybe}>{t('posts.rsvp.maybe')}</Button>
			<Button variant="variant-ringed-primary" action={handleNo}>{t('posts.rsvp.no')}</Button>
		</div>
	{/if}
{/if}
