// platform/react/src/components/post/types/event/FullEvent.tsx
import { Download, MoreHorizontal, Share, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import type {
  Event,
  JamRecording,
  PublicPost,
  PublicProfile,
} from '@openpeepshq/common/types';
import {
  buildThreads,
  calculateEffectiveRsvps,
  canAccessJamRecordings,
  canManageEventRsvps,
  canModerateJam,
  countYesRsvps,
  effectiveEventTimes,
  getJamUrl,
  groupName,
  isCapacityEvent,
  parseOccurrenceQuery,
  profileName,
} from '@openpeepshq/common/lib';
import {
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogHeader,
  DialogTitle,
  LoadingSpinner,
  PopupMenu,
  PopupMenuButton,
  UpdatingDate,
} from '@openpeepshq/react-ui';
import { useOpenpeeps } from '../../../../contexts/openpeeps';
import { useT } from '../../../../i18n';
import { useCurrentProfile } from '../../../layout/IdentityContext';
import { useToast } from '../../../layout/ToastProvider';
import { usePostViewRef } from '../../../../lib/postViewCounter';
import { useCreateNewConversation } from '../../../conversations';
import {
  Avatar,
  FollowUnfollowButton,
  ProfileCard,
  ProfileFromId,
} from '../../../profile';
import { OpenpeepsMarkdown } from '../../../markdown/OpenpeepsMarkdown';
import { ThreadedFeed } from '../../feed/threaded/ThreadedFeed';
import { ReplyBox } from '../../ReplyBox';
import { EventLocation } from '../../pieces/EventLocation';
import { EventMenu } from '../../pieces/EventMenu';
import { EventRsvpButton } from '../../pieces/EventRsvpButton';
import { ShareMenu } from '../../pieces/ShareMenu';
import { VideoPlayer } from '../../pieces/VideoPlayer';

export interface FullEventProps {
  post: PublicPost;
}

type EventTab =
  | 'description'
  | 'replies'
  | 'rsvps'
  | 'attendees'
  | 'recordings';

export function FullEvent({ post }: FullEventProps) {
  const t = useT();
  const profile = useCurrentProfile();
  const [searchParams] = useSearchParams();
  const occurrenceId = parseOccurrenceQuery(searchParams.get('occurrence'));
  const { openCreateConversation } = useCreateNewConversation();
  const postViewRef = usePostViewRef(post.id);
  const { openpeepsApi } = useOpenpeeps();
  const event = post.data as Event;
  const contextQuery = openpeepsApi.usePostContext(post.id);
  const jamAttendeesQuery = openpeepsApi.useJamAttendance(post.id);
  const canViewRecordings = canAccessJamRecordings(profile, post);
  const recordingsQuery = openpeepsApi.usePostRecordings(
    post.id,
    !!event.jam && canViewRecordings,
  );
  const [tab, setTab] = useState<EventTab>(
    event.content ? 'description' : 'replies',
  );

  const group = post.group;
  const myEvent = post.profile?.id === profile?.id;
  const iAmModerator = canModerateJam(profile, post);
  const canManageRsvps = canManageEventRsvps(profile, post);
  const rsvps = useMemo(
    () => calculateEffectiveRsvps(post, occurrenceId),
    [post, occurrenceId],
  );
  const slotsLeft =
    isCapacityEvent(event) && event.maxAttendees !== undefined
      ? event.maxAttendees - countYesRsvps(post, occurrenceId)
      : null;
  const times = effectiveEventTimes(event, occurrenceId);
  const jamLink = getJamUrl(post.id, undefined, occurrenceId);
  const rsvpManage = openpeepsApi.rsvpManageAction();

  const descendentThreads = useMemo(
    () =>
      (contextQuery.data && buildThreads(contextQuery.data.descendants)) || [],
    [contextQuery.data],
  );

  const eventScope = useMemo(() => {
    if (post.visibility === 'public')
      return t('events.public', { defaultValue: 'Public' });
    if (post.groupId && post.visibility === 'group')
      return t('events.group', { defaultValue: 'Group' });
    if (post.visibility === 'direct')
      return t('events.private', { defaultValue: 'Private' });
    return t('events.community', { defaultValue: 'Community' });
  }, [post, t]);

  const showJamAttendeesTab =
    !!event.jam && (myEvent || iAmModerator) && jamAttendeesQuery.isSuccess;

  return (
    <article ref={postViewRef} className="flex w-full flex-col gap-2 p-3">
      <span className="mb-3 block aspect-video w-full overflow-hidden rounded">
        <img
          src={event.image || '/img/event-default.png'}
          className="h-full w-full object-cover"
          alt={event.name ? `image for ${event.name}` : 'Event'}
        />
      </span>

      <div className="flex items-center justify-between">
        <div>
          <div className="flex gap-x-4">
            <span className="bg-surface-2 mb-3 inline-block rounded-lg px-3 py-1 text-sm">
              {eventScope}
            </span>
            {slotsLeft !== null ? (
              <span className="bg-surface-2 mb-3 inline-block rounded-lg px-3 py-1 text-sm">
                {slotsLeft <= 0
                  ? t('events.noSpotsAvailable', {
                      defaultValue: 'No spots available',
                    })
                  : t('events.slotsLeft', {
                      defaultValue: '{{count}} slots left',
                      count: slotsLeft,
                    })}
              </span>
            ) : null}
          </div>
          {post.groupId && group ? (
            <a
              href={`/groups/@${group.handle}`}
              className="text-muted-foreground block text-sm hover:underline"
            >
              {groupName(group)}
            </a>
          ) : null}
        </div>
        <div className="flex items-center gap-2">
          <ShareMenu
            post={post}
            menuButton={
              <span className="flex size-10 items-center justify-center rounded-md">
                <Share className="size-4" />
              </span>
            }
          />
          {myEvent ? (
            <EventMenu
              post={post}
              occurrence={occurrenceId}
              menuButton={
                <span className="border-input flex size-10 items-center justify-center rounded-md border">
                  <MoreHorizontal className="size-4" />
                </span>
              }
            />
          ) : null}
        </div>
      </div>

      <h1 className="text-2xl font-bold">{event.name}</h1>

      <div className="mt-2 flex items-center gap-x-2">
        <Avatar profile={post.profile as PublicProfile} size={2} />
        <span className="text-sm">
          {t('events.hostedBy', {
            defaultValue: 'Hosted by {{profileName}}',
            profileName: `${profileName(post.profile)}${myEvent ? ' · You' : ''}`,
          })}
        </span>
      </div>

      {times.start ? (
        <div className="mt-4 flex gap-x-4">
          <div className="border-foreground/20 rounded-md border px-4 py-1">
            <p className="text-center text-sm">
              {new Date(times.start).toLocaleString(undefined, {
                month: 'short',
              })}
            </p>
            <p className="text-center text-lg font-semibold">
              {new Date(times.start).getDate()}
            </p>
          </div>
          <div>
            <span className="text-muted-foreground text-sm">
              {t('events.startDate', { defaultValue: 'Starts' })}
            </span>
            <p>
              {new Date(times.start).toLocaleDateString(undefined, {
                weekday: 'long',
                month: 'long',
                day: 'numeric',
                year: 'numeric',
              })}
            </p>
            <p className="text-muted-foreground mt-2 text-sm">
              {new Date(times.start).toLocaleTimeString(undefined, {
                hour: '2-digit',
                minute: '2-digit',
              })}
            </p>
          </div>
        </div>
      ) : null}

      {times.end ? (
        <div className="mt-4 flex gap-x-4">
          <div className="border-foreground/20 rounded-md border px-4 py-1">
            <p className="text-center text-sm">
              {new Date(times.end).toLocaleString(undefined, {
                month: 'short',
              })}
            </p>
            <p className="text-center text-lg font-semibold">
              {new Date(times.end).getDate()}
            </p>
          </div>
          <div>
            <span className="text-muted-foreground text-sm">
              {t('events.endDate', { defaultValue: 'Ends' })}
            </span>
            <p>
              {new Date(times.end).toLocaleDateString(undefined, {
                weekday: 'long',
                month: 'long',
                day: 'numeric',
                year: 'numeric',
              })}
            </p>
            <p className="text-muted-foreground mt-2 text-sm">
              {new Date(times.end).toLocaleTimeString(undefined, {
                hour: '2-digit',
                minute: '2-digit',
              })}
            </p>
          </div>
        </div>
      ) : null}

      <EventLocation post={post} preview={false} occurrence={occurrenceId} />
      {event.recurrence && !occurrenceId ? (
        <p className="text-muted-foreground text-sm">
          {t('events.occurrence.seriesRsvpNote', {
            defaultValue: 'Your RSVP applies to every date in this series.',
          })}
        </p>
      ) : null}
      <EventRsvpButton post={post} recurrenceId={occurrenceId} />

      {event.jam && (myEvent || iAmModerator) ? (
        <Button variant="default" className="mt-2 w-full" action={jamLink}>
          {t('events.jam.start', { defaultValue: 'Start jam' })}
        </Button>
      ) : null}

      <nav
        aria-label={t('events.tabs.label', { defaultValue: 'Event sections' })}
        className="mt-4 flex flex-wrap gap-2 border-b"
      >
        {event.content ? (
          <TabButton
            active={tab === 'description'}
            onClick={() => setTab('description')}
          >
            {t('events.tabs.description', { defaultValue: 'Description' })}
          </TabButton>
        ) : null}
        <TabButton active={tab === 'replies'} onClick={() => setTab('replies')}>
          {t('events.tabs.discussion', { defaultValue: 'Discussion' })}
        </TabButton>
        <TabButton active={tab === 'rsvps'} onClick={() => setTab('rsvps')}>
          {t('events.tabs.rsvps', { defaultValue: 'RSVPs' })}
        </TabButton>
        {showJamAttendeesTab ? (
          <TabButton
            active={tab === 'attendees'}
            onClick={() => setTab('attendees')}
          >
            {t('events.tabs.jamAttendees', { defaultValue: 'Jam attendees' })}
          </TabButton>
        ) : null}
        {event.jam && canViewRecordings ? (
          <TabButton
            active={tab === 'recordings'}
            onClick={() => setTab('recordings')}
          >
            {t('events.tabs.recordings', { defaultValue: 'Recordings' })}
          </TabButton>
        ) : null}
      </nav>

      {tab === 'description' && event.content ? (
        <OpenpeepsMarkdown source={event.content} mentions={post.mentions} />
      ) : null}

      {tab === 'replies' ? (
        <>
          <ReplyBox post={post} />
          {contextQuery.isLoading ? (
            <div className="text-muted-foreground py-4 text-sm">
              <LoadingSpinner />
            </div>
          ) : (
            descendentThreads.map((thread) => (
              <ThreadedFeed key={thread.id} thread={thread} isDescendants />
            ))
          )}
        </>
      ) : null}

      {tab === 'rsvps' ? (
        rsvps.length ? (
          rsvps.map((rsvp) => (
            <div key={rsvp.profile.id} className="flex items-center gap-2">
              <div className="min-w-0 flex-1">
                <ProfileCard
                  profile={rsvp.profile}
                  action={
                    profile && profile.id !== rsvp.profile.id ? (
                      <PopupMenu>
                        {profile.following?.some(
                          (f) => f.id === rsvp.profile.id,
                        ) ? (
                          <PopupMenuButton
                            title={t('profile.actions.message', {
                              defaultValue: 'Message',
                            })}
                            text={t('profile.actions.message', {
                              defaultValue: 'Message',
                            })}
                            action={() =>
                              openCreateConversation({
                                profiles: [rsvp.profile],
                                skipProfileSelection: true,
                              })
                            }
                          />
                        ) : null}
                        <FollowUnfollowButton profile={rsvp.profile} popup />
                      </PopupMenu>
                    ) : undefined
                  }
                />
              </div>
              {canManageRsvps && rsvp.profile.id !== post.profile.id ? (
                rsvp.response === 'removed' ? (
                  <Button
                    variant="outline"
                    action={() =>
                      rsvpManage(
                        {
                          response: 'yes',
                          recurrenceId: occurrenceId,
                        },
                        { id: post.id, profileId: rsvp.profile.id },
                      )
                    }
                  >
                    {t('events.rsvp.restoreAttendee', {
                      defaultValue: 'Restore',
                    })}
                  </Button>
                ) : (
                  <Button
                    variant="outline"
                    action={() =>
                      rsvpManage(
                        {
                          response: 'removed',
                          recurrenceId: occurrenceId,
                        },
                        { id: post.id, profileId: rsvp.profile.id },
                      )
                    }
                  >
                    {t('events.rsvp.removeAttendee', {
                      defaultValue: 'Remove',
                    })}
                  </Button>
                )
              ) : null}
            </div>
          ))
        ) : (
          <p className="text-muted-foreground py-4 text-sm">
            {t('events.noRsvps', { defaultValue: 'No RSVPs yet.' })}
          </p>
        )
      ) : null}

      {tab === 'attendees' && showJamAttendeesTab ? (
        jamAttendeesQuery.data?.length ? (
          jamAttendeesQuery.data.map((attendee) => (
            <ProfileFromId
              key={attendee.id}
              profileId={attendee.profileId}
              action={<UpdatingDate date={attendee.createdAt} />}
            />
          ))
        ) : (
          <p className="text-muted-foreground py-4 text-sm">
            {t('events.noAttendees', { defaultValue: 'No attendees yet.' })}
          </p>
        )
      ) : null}

      {tab === 'recordings' && event.jam && canViewRecordings ? (
        recordingsQuery.isLoading ? (
          <div className="text-muted-foreground py-4 text-sm">
            <LoadingSpinner />
          </div>
        ) : recordingsQuery.data?.length ? (
          recordingsQuery.data.map((recording) => (
            <JamRecordingItem
              key={recording.id}
              post={post}
              recording={recording}
              canManage={canViewRecordings}
            />
          ))
        ) : (
          <p className="text-muted-foreground py-4 text-sm">
            {t('events.noRecordings', { defaultValue: 'No recordings yet.' })}
          </p>
        )
      ) : null}

      <div className="h-[40vh]" />
    </article>
  );
}

function JamRecordingItem({
  post,
  recording,
  canManage,
}: {
  post: PublicPost;
  recording: JamRecording;
  canManage: boolean;
}) {
  const t = useT();
  const { success, error: toastError } = useToast();
  const { openpeepsApi } = useOpenpeeps();
  const [confirmOpen, setConfirmOpen] = useState(false);
  const publishReply = openpeepsApi.publishRecordingReplyAction({
    id: post.id,
    recordingId: recording.id,
  });
  const deleteRecording = openpeepsApi.deleteRecordingAction({
    id: post.id,
    recordingId: recording.id,
  });

  const handleDelete = async () => {
    try {
      await deleteRecording();
      setConfirmOpen(false);
      success(
        t('events.deleteRecordingSuccess', {
          defaultValue: 'Recording deleted',
        }),
      );
    } catch {
      toastError(
        t('events.deleteRecordingError', {
          defaultValue: 'Failed to delete recording',
        }),
      );
    }
  };

  return (
    <div className="flex flex-col gap-2 py-4">
      <UpdatingDate date={recording.createdAt} />
      {recording.status === 'completed' && recording.attachment ? (
        <>
          <VideoPlayer
            attachment={recording.attachment}
            autoPlay={false}
            muted={false}
            className="aspect-video w-full rounded-md"
          />
          <a
            href={recording.attachment.url}
            download={recording.attachment.filename}
            className="text-primary inline-flex items-center gap-1 self-start text-sm hover:underline"
          >
            <Download className="h-4 w-4" />
            {t('events.downloadRecording', {
              defaultValue: 'Download recording',
            })}
          </a>
        </>
      ) : (
        <p className="text-muted-foreground text-sm">
          {recording.status === 'active'
            ? t('events.recordingInProgress', {
                defaultValue: 'Recording in progress…',
              })
            : t('events.recordingProcessing', {
                defaultValue: 'Processing recording…',
              })}
        </p>
      )}
      <div className="flex flex-wrap items-center gap-2">
        {canManage &&
        recording.status === 'completed' &&
        recording.attachment ? (
          recording.replyPostId ? (
            <p className="text-muted-foreground text-sm">
              {t('events.recordingReplyPosted', {
                defaultValue: 'Posted to discussion',
              })}
            </p>
          ) : (
            <Button
              variant="outline"
              className="self-start"
              action={async () => {
                try {
                  await publishReply();
                  success(
                    t('events.postRecordingReplySuccess', {
                      defaultValue: 'Recording posted to discussion',
                    }),
                  );
                } catch {
                  toastError(
                    t('events.postRecordingReplyError', {
                      defaultValue: 'Failed to post recording to discussion',
                    }),
                  );
                }
              }}
            >
              {t('events.postRecordingReply', {
                defaultValue: 'Post to discussion',
              })}
            </Button>
          )
        ) : null}
        {canManage &&
        recording.status !== 'active' &&
        recording.status !== 'requested' ? (
          <>
            <Button
              variant="outline"
              className="self-start"
              action={() => setConfirmOpen(true)}
            >
              <Trash2 className="mr-1 h-4 w-4" />
              {t('events.deleteRecording', {
                defaultValue: 'Delete recording',
              })}
            </Button>
            <Dialog
              open={confirmOpen}
              onOpenChange={(next) => !next && setConfirmOpen(false)}
            >
              <DialogContent className="max-w-sm">
                <DialogHeader>
                  <DialogTitle>
                    {t('events.deleteRecording', {
                      defaultValue: 'Delete recording',
                    })}
                  </DialogTitle>
                </DialogHeader>
                <p className="text-sm">
                  {t('events.deleteRecordingConfirm', {
                    defaultValue: 'Delete this recording permanently?',
                  })}
                </p>
                <DialogActions
                  cancelLabel={t('posts.deleteModal.cancel', {
                    defaultValue: 'Cancel',
                  })}
                  onCancel={() => setConfirmOpen(false)}
                  actionLabel={t('posts.deleteModal.delete', {
                    defaultValue: 'Delete',
                  })}
                  onAction={handleDelete}
                  actionVariant="destructive"
                />
              </DialogContent>
            </Dialog>
          </>
        ) : null}
      </div>
    </div>
  );
}

function TabButton({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`px-4 py-2 text-sm ${active ? 'border-primary border-b-2 font-semibold' : 'text-muted-foreground hover:text-foreground'}`}
    >
      {children}
    </button>
  );
}

// platform/svelte/src/lib/components/core/post/types/event/FullEvent.svelte
<script lang="ts">
	import { getPostContext, jamAttendanceStore, me } from '$lib/api';
	import { OpenpeepsMarkdown } from '$lib/components/core/markdown';
	import {
		buildThreads,
		calculateEffectiveRsvps,
		groupName,
		profileName
	} from '@openpeeps/common/lib';
	import type { PublicPost, Event, PublicProfile } from '@openpeeps/common/types';
	import { Button, getModalManager, Loader, PopupMenu, PopupMenuButton, UpdatingDate } from '@openpeeps/ui';
	import { Tab, TabGroup } from '@skeletonlabs/skeleton';
	import { Share } from 'lucide-svelte';
	import { ThreadedFeed } from '../..';
	import ReplyBox from '../../ReplyBox.svelte';
	import EventLocation from '../../pieces/EventLocation.svelte';
	import ShareMenu from '../../pieces/ShareMenu.svelte';
	import EventMenu from '../../pieces/EventMenu.svelte';
	import EventRsvpButton from './EventRsvpButton.svelte';
	import { Avatar, FollowUnfollowButton, ProfileCard, ProfileFromId } from '$lib/components/core/profile';
	import { goto } from '$app/navigation';
	import { CreateNewConversation } from '$lib/components/core/conversations';
	import { i18nContext } from '$lib/components/i18n';
	import { AccessDeniedLoader } from '$lib/components/layout';
	import { page } from '$app/state';
	import { postViewCounter } from '$lib/utils';

	interface Props {
		post: PublicPost;
	}

	let { post }: Props = $props();
	const modalManager = getModalManager();
	const { t } = i18nContext();
	const event = $derived(post.data as Event);
	const isEventModerator = $derived(event.moderators?.find((mId) => mId === $me.id));
	const myEvent = $derived(post.profile?.id === $me?.id);
	const iAmModerator = $derived(event.moderators?.includes($me?.id));
	const group = $derived(post.group ? post.group : undefined);
	const rsvps = $derived(calculateEffectiveRsvps(post));

	const jamAttendeesQuery = jamAttendanceStore(post.id);
	let tabSet = $state(post.data?.content ? 'description' : 'replies');

	let postContextQuery = getPostContext(post.id);

	let descendentThreads = $derived(
		($postContextQuery.data && buildThreads($postContextQuery.data.descendants)) || []
	);

	let eventScope = $derived.by(() => {
		if (post?.visibility === 'public') {
			return t('events.public');
		}
		if (post?.groupId && post?.visibility === 'group') {
			return t('events.group');
		}
		if (post?.visibility === 'direct') {
			return t('events.private');
		}
		return t('events.community');
	});
</script>

<div class="flex w-full flex-col gap-2 p-3" use:postViewCounter={post.id}>
	<span class="mb-3 aspect-video w-full overflow-hidden rounded">
		<img
			src={event.image || '/img/event-default.png'}
			class="h-full w-full object-cover"
			alt="image for {event.name}"
		/>
	</span>

	<div class="flex items-center justify-between">
		<div class="">
			<div class="flex gap-x-4">
				<span class="bg-surface-200 mb-3 rounded-lg px-3 py-1">
					{eventScope}
				</span>
				<!-- <span class="bg-surface-200 mb-3 rounded-lg px-3 py-1">
					{(event?.maxAttendees || 0) - (attendees?.length || 0)} slots left
				</span> -->
			</div>
			{#if post?.groupId}
				<Button class="text-muted-foreground anchor" action={() => goto(`/groups/@${post.group?.handle}`)}
					>{groupName(group)}</Button
				>
			{/if}
		</div>
		<div class="flex items-center gap-x-2">
			<ShareMenu {post} variant="variant-ringed-primary">
				{#snippet menuButton()}
					<Share class="size-4" />
				{/snippet}
			</ShareMenu>
			{#if $me?.id === post.profile.id}
				<EventMenu {post} variant="variant-ringed-primary" class="size-10 p-0" />
			{/if}
		</div>
	</div>

	<h1 class="h2">{event.name}</h1>
	<div class="mt-2 flex items-center gap-x-2">
		<div>
			<Avatar profile={post?.profile as PublicProfile} size={2} />
		</div>
		<div>
			{t('events.hostedBy', {profileName: `${profileName(post.profile)}${myEvent ? ' · You' : ''}`})}
		</div>
	</div>
	{#if event?.start}
		<div class="mt-4 flex gap-x-4">
			<div class="border-foreground/20 rounded-md border-[0.5px] px-4 py-1">
				<p class="text-center">
					{new Date(event?.start || '').toLocaleString(undefined, {
						month: 'short'
					})}
				</p>
				<p class="text-center">{new Date(event?.start || '').getDate()}</p>
			</div>
			<div>
				<span class="opacity-50">{t('events.startDate')}</span>
				<p class="">
					{new Date(event?.start || '').toLocaleDateString(undefined, {
						weekday: 'long',
						month: 'long',
						day: 'numeric',
						year: 'numeric'
					})}
				</p>
				<p class="text-muted-foreground mt-2">
					{new Date(event?.start || '').toLocaleTimeString(undefined, {
						hour: '2-digit',
						minute: '2-digit',
						timeZoneName: event?.start ? undefined : 'short'
					})}
				</p>
			</div>
		</div>
	{/if}
	{#if event?.end}
		<div class="mt-4 flex gap-x-4">
			<div class="border-foreground/20 rounded-md border-[0.5px] px-4 py-1">
				<p class="text-center">
					{new Date(event?.start || '').toLocaleString(undefined, {
						month: 'short'
					})}
				</p>
				<p class="text-center">{new Date(event?.start || '').getDate()}</p>
			</div>
			<div>
				<span class="opacity-50">{t('events.endDate')}</span>
				<p class="">
					{new Date(event?.end || '').toLocaleDateString(undefined, {
						weekday: 'long',
						month: 'long',
						day: 'numeric',
						year: 'numeric'
					})}
				</p>
				<p class="text-muted-foreground mt-2">
					{event?.end &&
						new Date(event?.end || '').toLocaleTimeString(undefined, {
							hour: '2-digit',
							minute: '2-digit',
							timeZoneName: event?.end ? undefined : 'short'
						})}
				</p>
			</div>
		</div>
	{/if}
	<EventLocation {post} preview={false} />
	<EventRsvpButton {post} />
	{#if event.jam}
		{#if myEvent || isEventModerator}
			<Button
				variant="variant-filled-primary"
				action={`${page.url.origin}/events/${post.id}/jam`}
				class="w-full">{t('events.jam.start')}
			</Button>
		{/if}
	{/if}
	<TabGroup>
		{#if post.data?.content}
			<Tab bind:group={tabSet} name="description" value="description"
				>{t('events.tabs.description')}</Tab
			>
		{/if}
		<Tab bind:group={tabSet} name="replies" value="replies">{t('events.tabs.discussion')}</Tab>
		<Tab bind:group={tabSet} name="rsvps" value="rsvps">{t('events.tabs.rsvps')}</Tab>
		{#if event.jam && (myEvent || iAmModerator) && $jamAttendeesQuery.isSuccess}
			<Tab bind:group={tabSet} name="attendees" value="attendees"
				>{t('events.tabs.jamAttendees')}</Tab
			>
		{/if}
		{#snippet panel()}
			{#if tabSet === 'description'}
				<div>
					<OpenpeepsMarkdown source={event.content} />
				</div>
			{:else if tabSet === 'replies'}
				<ReplyBox {post} />
				<AccessDeniedLoader queries={[$postContextQuery]}>
					{#each descendentThreads as thread (thread.id)}
						<ThreadedFeed {thread} />
					{/each}
				</AccessDeniedLoader>
			{:else if tabSet === 'rsvps'}
				{#each rsvps as rsvp (rsvp.createdAt)}
					<ProfileCard profile={rsvp.profile} avatarSize={2}>
						{#snippet action()}
							<PopupMenu>
								{#if $me?.following?.find((f) => f.id === rsvp.profile.id)}
									<PopupMenuButton
										action={() =>
											modalManager.show(CreateNewConversation, {
												profiles: [rsvp.profile],
												skipProfileSelection: true
											})}
										title={t('profile.actions.message')}
										text={t('profile.actions.message')}
									/>
								{/if}
								<FollowUnfollowButton profile={rsvp.profile} btnType={'popup'} />
							</PopupMenu>
						{/snippet}
					</ProfileCard>
				{:else}
					<p class="text-muted-foreground">{t('events.noRsvps')}</p>
				{/each}
			{:else if tabSet === 'attendees'}
				<AccessDeniedLoader queries={[$jamAttendeesQuery]}>
					{#if $jamAttendeesQuery?.data}
						{#each $jamAttendeesQuery.data as attendee (attendee.id)}
							<ProfileFromId profileId={attendee.profileId} avatarSize={2} >
								{#snippet action()}
									<UpdatingDate date={attendee.createdAt} />
								{/snippet}
							</ProfileFromId>
						{:else}
							<p class="text-muted-foreground">{t('events.noAttendees')}</p>
						{/each}
					{/if}
				</AccessDeniedLoader>
			{/if}
		{/snippet}
	</TabGroup>
</div>
