// platform/react-native/src/components/custom/post/pieces/ProfileEventRelationship.tsx
import { View } from 'react-native';
import React from 'react';
import { calculateEffectiveRsvps, Event, PublicPost } from '@openpeeps/common';
import { useOpenpeeps } from '@openpeeps/react';
import { ThemedText } from '~/components/ui/themed-text';
import { useTranslation } from 'react-i18next';

interface ProfileEventRelationshipProps {
  post: PublicPost;
}


export const ProfileEventRelationship: React.FC<
  ProfileEventRelationshipProps
> = ({ post }) => {
  const event = post.data as Event;
  const { t } = useTranslation();
  const { currentProfile } = useOpenpeeps();
  const myEvent = post?.profile?.id === currentProfile?.id;
  const isModerator = event?.moderators?.find(
    profileId => profileId === currentProfile?.id,
  );
  const myRsvp =
    post &&
    calculateEffectiveRsvps(post).find(
      r => r.profile.id === currentProfile?.id,
    );

  const relationshipText = (() => {
    if (myEvent) {
      return t('events.profileRelationship.owner');
    } else if (isModerator) {
      return t('groups.roles.moderator');
    } else if (myRsvp?.response === 'yes') {
      return t('events.profileRelationship.attending');
    } else if (myRsvp?.response === 'tentative') {
      return t('events.profileRelationship.tentative');
    }
    return null;
  })();


  if (relationshipText) {
    return (
      <View className="bg-foreground px-2 py-1 rounded-2xl">
        <ThemedText className="text-background text-center text-sm">
          {relationshipText}
        </ThemedText>
      </View>
    );
  } else {
    return null;
  }
};

// platform/svelte/src/lib/components/core/post/types/event/ProfileEventRelationship.svelte
<script lang="ts">
	// @ts-nocheck
	import type { Event, PublicPost } from '@openpeeps/common/types';
	import { i18nContext } from '$lib/components/i18n';
	import { getCurrentProfile } from '$lib/auth';
	import { calculateEffectiveRsvps } from '@openpeeps/common';
	const { t } = i18nContext();

	interface Props {
		post: PublicPost;
	}

	const { post }: Props = $props();
	const event = $derived(post.data as Event);
	const me = getCurrentProfile();
	const myEvent = $derived(post.profile?.id === me?.id);
	const iAmModerator = $derived(event.moderators?.includes(me?.id));
	const myRsvp = $derived(calculateEffectiveRsvps(post).find((rsvp) => me?.id === rsvp.profile.id));
</script>

{#if myEvent}
	<div class="variant-ghost-primary rounded-2xl px-2">
		<span class="text-background text-center text-sm">
			{t('events.profileRelationship.owner')}
		</span>
	</div>
{:else if iAmModerator}
	<div class="variant-ghost-primary rounded-2xl px-2">
		<span class="text-center text-sm">
			{t('events.profileRelationship.moderator')}
		</span>
	</div>
{:else if myRsvp?.response === 'yes'}
	<div class="variant-ghost-tertiary rounded-2xl px-2">
		<span class="text-foreground text-center text-sm">
			{t('events.profileRelationship.attending')}
		</span>
	</div>
{:else if myRsvp?.response === 'tentative'}
	<div class="variant-ghost-surface rounded-2xl px-2">
		<span class="text-foreground text-center text-sm">
			{t('events.profileRelationship.tentative')}
		</span>
	</div>
{/if}
