// platform/react/src/components/post/types/event/ProfileEventRelationship.tsx
import type { Event, PublicPost } from '@openpeeps/common/types';
import { calculateEffectiveRsvps } from '@openpeeps/common/lib';
import { useT } from '../../../../i18n';
import { useCurrentProfile } from '../../../layout/IdentityContext';

export interface ProfileEventRelationshipProps {
  post: PublicPost;
}

export function ProfileEventRelationship({
  post,
}: ProfileEventRelationshipProps) {
  const t = useT();
  const me = useCurrentProfile();
  const event = post.data as Event;
  const myEvent = post.profile?.id === me?.id;
  const iAmModerator = !!event.moderators?.includes(me?.id ?? '');
  const myRsvp = calculateEffectiveRsvps(post).find(
    (rsvp) => me?.id === rsvp.profile.id,
  );

  if (myEvent) {
    return (
      <div className="variant-ghost-primary rounded-2xl px-2">
        <span className="text-background text-center text-sm">
          {t('events.profileRelationship.owner', { defaultValue: 'Owner' })}
        </span>
      </div>
    );
  }

  if (iAmModerator) {
    return (
      <div className="variant-ghost-primary rounded-2xl px-2">
        <span className="text-center text-sm">
          {t('events.profileRelationship.moderator', {
            defaultValue: 'Moderator',
          })}
        </span>
      </div>
    );
  }

  if (myRsvp?.response === 'yes') {
    return (
      <div className="variant-ghost-tertiary rounded-2xl px-2">
        <span className="text-foreground text-center text-sm">
          {t('events.profileRelationship.attending', {
            defaultValue: 'Attending',
          })}
        </span>
      </div>
    );
  }

  if (myRsvp?.response === 'tentative') {
    return (
      <div className="variant-ghost-surface rounded-2xl px-2">
        <span className="text-foreground text-center text-sm">
          {t('events.profileRelationship.tentative', {
            defaultValue: 'Tentative',
          })}
        </span>
      </div>
    );
  }

  return null;
}

// platform/svelte/src/lib/components/core/post/types/event/ProfileEventRelationship.svelte
<script lang="ts">
	// @ts-nocheck
	import type { Event, PublicPost } from '@openpeeps/common/types';
	import { i18nContext } from '$lib/components/i18n';
	import { getCurrentProfile } from '$lib/auth';
	import { calculateEffectiveRsvps } from '@openpeeps/common';
	const { t } = i18nContext();

	interface Props {
		post: PublicPost;
	}

	const { post }: Props = $props();
	const event = $derived(post.data as Event);
	const me = getCurrentProfile();
	const myEvent = $derived(post.profile?.id === me?.id);
	const iAmModerator = $derived(event.moderators?.includes(me?.id));
	const myRsvp = $derived(calculateEffectiveRsvps(post).find((rsvp) => me?.id === rsvp.profile.id));
</script>

{#if myEvent}
	<div class="variant-ghost-primary rounded-2xl px-2">
		<span class="text-background text-center text-sm">
			{t('events.profileRelationship.owner')}
		</span>
	</div>
{:else if iAmModerator}
	<div class="variant-ghost-primary rounded-2xl px-2">
		<span class="text-center text-sm">
			{t('events.profileRelationship.moderator')}
		</span>
	</div>
{:else if myRsvp?.response === 'yes'}
	<div class="variant-ghost-tertiary rounded-2xl px-2">
		<span class="text-foreground text-center text-sm">
			{t('events.profileRelationship.attending')}
		</span>
	</div>
{:else if myRsvp?.response === 'tentative'}
	<div class="variant-ghost-surface rounded-2xl px-2">
		<span class="text-foreground text-center text-sm">
			{t('events.profileRelationship.tentative')}
		</span>
	</div>
{/if}
