// platform/svelte/src/lib/components/core/preview-link/local/PostPreview.svelte
<script lang="ts">
	import { getPostStore } from '$lib/api';
	import { Loader } from '@openpeeps/ui';
	import FeedPostContent from '../../post/pieces/FeedPostContent.svelte';
	import AccessDenied from '../AccessDenied.svelte';

	interface Props {
		path: string;
	}

	let { path }: Props = $props();

	const postQuery = getPostStore(path.substring(7));

	const post = $derived($postQuery.data);
</script>

<Loader queries={[$postQuery]}>
	{#if post}
		<FeedPostContent {post} />
	{/if}
	{#snippet error()}
		<AccessDenied queries={[$postQuery]} />
	{/snippet}
</Loader>

// platform/react/src/components/preview-link/local/PostPreview.tsx
import { FeedPostContent } from '../../post/FeedPostContent';
import { PostInfoHeader } from '../../post/pieces/PostInfoHeader';
import { useOpenpeeps } from '../../../contexts/openpeeps';
import { LoadingSpinner } from '@openpeepshq/react-ui';

export interface PostPreviewProps {
  path: string;
}

export function PostPreview({ path }: PostPreviewProps) {
  const postId = path.substring(7);
  const { openpeepsApi } = useOpenpeeps();
  const postQuery = openpeepsApi.usePost(postId);

  if (postQuery.isLoading) {
    return (
      <div className="text-muted-foreground text-sm">
        <LoadingSpinner />
      </div>
    );
  }

  if (!postQuery.data) return null;

  return (
    <>
      <PostInfoHeader post={postQuery.data} />
      <FeedPostContent post={postQuery.data} />
    </>
  );
}
