// libraries/react-ui/src/components/loaders/Loader.tsx
import * as React from 'react';
import { cn } from '@/lib/utils';
import { LoadingIcon } from './LoadingIcon';
import { WaitForQueries } from './WaitForQueries';
import type { PartialQueryObserverResult } from '@/types';

export interface LoaderProps {
  fullScreen?: boolean;
  loadingMessage?: string;
  errorMessage?: string;
  className?: string;
  queries?: PartialQueryObserverResult<unknown>[];
  promises?: Promise<unknown>[];
  ignoreErrors?: boolean;
  children?: React.ReactNode;
  loading?: React.ReactNode;
  error?: React.ReactNode;
}

export function Loader({
  fullScreen = false,
  loadingMessage = '',
  errorMessage = 'An error occurred.',
  className,
  queries,
  promises,
  ignoreErrors = false,
  children,
  loading,
  error,
}: LoaderProps) {
  const overlayClass = cn(
    'z-30 flex w-full flex-col items-center justify-center bg-background/80 p-10',
    fullScreen && 'fixed left-0 top-0 h-full',
    className,
  );

  return (
    <WaitForQueries
      queries={queries}
      promises={promises}
      ignoreErrors={ignoreErrors}
      success={children}
      loading={
        <div className={overlayClass}>
          {loading ?? (
            <>
              <LoadingIcon />
              {loadingMessage && <p className="mt-3">{loadingMessage}</p>}
            </>
          )}
        </div>
      }
      error={
        <div className={overlayClass}>{error ?? <p>{errorMessage}</p>}</div>
      }
    />
  );
}

// libraries/ui/src/lib/loaders/Loader.svelte
<script lang="ts">
	import { LoadingIcon, WaitForQueries } from '.';
	import type { QueryObserverResult } from '@tanstack/svelte-query';

	interface Props {
		fullScreen?: boolean;
		loadingMessage?: string;
		errorMessage?: string;
		classes?: string;
		queries?: QueryObserverResult<unknown, unknown>[];
		promises?: Promise<unknown>[];
		ignoreErrors?: boolean;
		children?: import('svelte').Snippet;
		loading?: import('svelte').Snippet;
		error?: import('svelte').Snippet;
	}

	let {
		fullScreen = false,
		loadingMessage = '',
		errorMessage = 'An error occurred.',
		classes = '',
		queries,
		promises,
		ignoreErrors = false,
		children,
		loading: loadingLocal,
		error: errorLocal
	}: Props = $props();

	const backgroundClass =
		'flex flex-col items-center justify-center w-full z-30 bg-surface-50/80 p-10 ' +
		(fullScreen ? 'h-full fixed left-0 top-0 ' : '') +
		classes;
</script>

<WaitForQueries {queries} {promises} {ignoreErrors}>
	{#snippet success()}
		{@render children?.()}
	{/snippet}
	{#snippet loading()}
		<div class={backgroundClass}>
			{#if loadingLocal}
				{@render loadingLocal()}
			{:else}
				<LoadingIcon />
				<p class="mt-3">{loadingMessage}</p>
			{/if}
		</div>
	{/snippet}
	{#snippet error()}
		<div class={backgroundClass}>
			{#if errorLocal}
				{@render errorLocal()}
			{:else}
				<p>{errorMessage}</p>
			{/if}
		</div>
	{/snippet}
</WaitForQueries>
