// platform/react/src/components/post/FeedPostContent.tsx
import type { PublicPost } from '@openpeeps/common/types';

import { FeedArticle } from './types/Article';
import { FeedEvent } from './types/Event';
import { FeedNote } from './types/Note';
import { FeedPoll } from './types/Poll';

export interface FeedPostContentProps {
  post: PublicPost;
}

export function FeedPostContent({ post }: FeedPostContentProps) {
  if (post.deletedAt) {
    return (
      <div className="text-sm text-gray-500">This post has been deleted.</div>
    );
  }

  switch (post.type) {
    case 'note':
      return <FeedNote post={post} />;
    case 'question':
      return <FeedPoll post={post} />;
    case 'event':
      return <FeedEvent post={post} />;
    case 'article':
      return <FeedArticle post={post} />;
    default:
      return null;
  }
}

// platform/svelte/src/lib/components/core/post/pieces/FeedPostContent.svelte
<script lang="ts">
  import type { PublicPost } from '@openpeeps/common/types';
  import FeedPoll from '../types/poll/FeedPoll.svelte';
  import FeedNote from '../types/note/FeedNote.svelte';
  import FeedEvent from '../types/event/FeedEvent.svelte';
  import FeedArticle from '../types/article/FeedArticle.svelte';

  interface Props {
    post: PublicPost;
  }

  let { post }: Props = $props();
</script>

{#if post.deletedAt}
  <div class="text-sm text-gray-500">This post has been deleted.</div>
{:else if post.type === 'note'}
  <FeedNote {post} />
{:else if post.type === 'question'}
  <FeedPoll {post} />
{:else if post.type === 'event'}
  <FeedEvent {post} />
{:else if post.type === 'article'}
  <FeedArticle {post} />
{/if}
