// platform/react-native/src/components/custom/post/pieces/FeedPostContent.tsx
import React from 'react';
import type { PublicPost } from '@openpeeps/common/types';
import { FeedNote } from '../types/note/FeedNote';
import { FeedPoll } from '../types/poll/FeedPoll';
import { FeedEvent } from '../types/event/FeedEvent';
import { FeedArticle } from '../types/article/FeedArticle';
import { View } from 'react-native';
import { ThemedText } from '../../../ui/themed-text';

interface FeedPostContentProps {
  post: PublicPost;
}


export const FeedPostContent = ({ post }: FeedPostContentProps) => {
  if (post.deletedAt) {
    return <View className="text-sm text-gray-500">This post has been deleted.</View>;
  }
  if (post.type === 'note') {
    return <FeedNote {...{ post }} />;
  }
  if (post.type === 'question') {
    return <FeedPoll {...{ post }} />;
  }
  if (post.type === 'event') {
    return <FeedEvent {...{ post }} />;
  }
  if (post.type === 'article') {
    return <FeedArticle {...{ post }} />;
  }
  return <View><ThemedText className="text-red-500">This post type is not supported.</ThemedText></View>;
};

// platform/svelte/src/lib/components/core/post/pieces/FeedPostContent.svelte
<script lang="ts">
  import type { PublicPost } from '@openpeeps/common/types';
  import FeedPoll from '../types/poll/FeedPoll.svelte';
  import FeedNote from '../types/note/FeedNote.svelte';
  import FeedEvent from '../types/event/FeedEvent.svelte';
  import FeedArticle from '../types/article/FeedArticle.svelte';

  interface Props {
    post: PublicPost;
  }

  let { post }: Props = $props();
</script>

{#if post.deletedAt}
  <div class="text-sm text-gray-500">This post has been deleted.</div>
{:else if post.type === 'note'}
  <FeedNote {post} />
{:else if post.type === 'question'}
  <FeedPoll {post} />
{:else if post.type === 'event'}
  <FeedEvent {post} />
{:else if post.type === 'article'}
  <FeedArticle {post} />
{/if}
