// platform/react/src/components/post/pieces/PostMenu.tsx
import { useMemo, useState } from 'react';
import {
  BookmarkMinus,
  BookmarkPlus,
  FlagIcon,
  Pencil,
  Pin,
  Repeat2,
  ThumbsUp,
  Trash,
} from 'lucide-react';
import type { PublicPost } from '@openpeepshq/common/types';
import {
  checkGroupCapabilities,
  checkPostCapabilities,
  checkRoleCapabilities,
} from '@openpeepshq/common/lib';
import {
  PopupMenu,
  PopupMenuButton,
  PopupSeparator,
} from '@openpeepshq/react-ui';
import { useOpenpeeps } from '../../../contexts/openpeeps';
import { useT } from '../../../i18n';
import { useAuthData, useCurrentProfile } from '../../layout/IdentityContext';
import { useCapabilities, useServerInfo } from '../../server-data';
import { ReportProfileOrPostModal } from '../../profile/ReportProfileOrPostModal';
import { DeletePostModal } from './modals/DeletePostModal';
import { ReactionsModal } from './modals/ReactionsModal';
import { RepostModal } from './modals/RepostModal';
import { useEditPostModal } from '../post-form/EditPostModalContext';

export interface PostMenuProps {
  post: PublicPost;
  deleteCallback?: () => void;
}

export function PostMenu({ post, deleteCallback }: PostMenuProps) {
  const t = useT();
  const me = useCurrentProfile();
  const authData = useAuthData();
  const capabilities = useCapabilities();
  const serverInfo = useServerInfo();
  const { openpeepsApi } = useOpenpeeps();
  const { openEditPost } = useEditPostModal();

  const [modal, setModal] = useState<
    'reactions' | 'reposts' | 'delete' | 'reportPost' | 'reportProfile' | null
  >(null);

  const bookmarkedIdsQuery = openpeepsApi.useCurrentProfileBookmarkedIds();
  const followProfile = openpeepsApi.followProfileAction({ id: post.profile.id });
  const unfollowProfile = openpeepsApi.unfollowProfileAction({
    id: post.profile.id,
  });
  const bookmarkPost = openpeepsApi.bookmarkPostAction({ id: post.id });
  const unbookmarkPost = openpeepsApi.unbookmarkPostAction({ id: post.id });
  const updateGroup = openpeepsApi.updateGroupAction({
    id: post.group?.id ?? '',
  });
  const pinGloballyMutation = openpeepsApi.admin.pinPostGloballyAction();

  const postProfile = post.profile;
  const isFollowing = me?.following?.some((f) => f.id === postProfile.id);
  const isBookmarked = bookmarkedIdsQuery.data?.includes(post.id) ?? false;
  const pinnedGlobally =
    serverInfo.communityConfig?.content?.pinnedPost === post.id;
  const pinnedInGroup = post.group?.pinnedPostId === post.id;

  const canPinToGroup = useMemo(
    () =>
      !!post.group &&
      checkGroupCapabilities(authData, ['core-groups-pin'], post.group).success,
    [authData, post.group],
  );

  const canPinGlobally = useMemo(
    () =>
      ['public', 'local'].includes(post.visibility) &&
      !!me &&
      checkRoleCapabilities(me.roles ?? [], ['core-config-update']).success,
    [me, post.visibility],
  );

  const canDeletePost = useMemo(
    () =>
      checkPostCapabilities(
        authData,
        ['core-posts-delete'],
        post,
        capabilities,
      ).success,
    [authData, post, capabilities],
  );

  const canReportPost = useMemo(
    () =>
      !!me &&
      checkRoleCapabilities(me.roles ?? [], ['core-reports-create']).success,
    [me],
  );

  const isPostOwner = postProfile?.id === me?.id;

  if (!me) return null;

  const handleEditPost = () => {
    if (post.data?.type === 'event') {
      window.location.assign(`/events/${post.id}/edit`);
      return;
    }
    if (post.data?.type === 'article') {
      window.location.assign(`/articles/${post.id}/edit`);
      return;
    }
    openEditPost(post);
  };

  return (
    <>
      <PopupMenu
        className="hover:bg-surface-200 h-max rounded-full p-2"
        title={t('posts.menu.title', { defaultValue: 'Post menu' })}
      >
        {postProfile.id !== me.id ? (
          isFollowing ? (
            <PopupMenuButton
              title={t('profile.actions.unfollow', { defaultValue: 'Unfollow' })}
              text={t('profile.actions.unfollow', { defaultValue: 'Unfollow' })}
              action={() => unfollowProfile(undefined)}
            />
          ) : (
            <PopupMenuButton
              title={t('profile.actions.follow', { defaultValue: 'Follow' })}
              text={t('profile.actions.follow', { defaultValue: 'Follow' })}
              action={() => followProfile({ reblogs: true, notify: true })}
            />
          )
        ) : null}
        <PopupMenuButton
          title={t('posts.menu.reposts', { defaultValue: 'Reposts' })}
          text={t('posts.menu.reposts', { defaultValue: 'Reposts' })}
          icon={Repeat2}
          action={() => setModal('reposts')}
        />
        <PopupMenuButton
          title={t('posts.menu.reactions', { defaultValue: 'Reactions' })}
          text={t('posts.menu.reactions', { defaultValue: 'Reactions' })}
          icon={ThumbsUp}
          action={() => setModal('reactions')}
        />
        {isBookmarked ? (
          <PopupMenuButton
            title={t('posts.unbookmark.title', { defaultValue: 'Remove bookmark' })}
            text={t('posts.unbookmark.title', { defaultValue: 'Remove bookmark' })}
            icon={BookmarkMinus}
            action={async () => {
              await unbookmarkPost(undefined);
            }}
          />
        ) : (
          <PopupMenuButton
            title={t('posts.bookmark.title', { defaultValue: 'Bookmark' })}
            text={t('posts.bookmark.title', { defaultValue: 'Bookmark' })}
            icon={BookmarkPlus}
            action={async () => {
              await bookmarkPost(undefined);
            }}
          />
        )}
        {canPinGlobally ? (
          <PopupMenuButton
            title={
              pinnedGlobally
                ? t('posts.unpinGlobally.title', { defaultValue: 'Unpin globally' })
                : t('posts.pinGlobally.title', { defaultValue: 'Pin globally' })
            }
            text={
              pinnedGlobally
                ? t('posts.unpinGlobally.title', { defaultValue: 'Unpin globally' })
                : t('posts.pinGlobally.title', { defaultValue: 'Pin globally' })
            }
            icon={Pin}
            action={() =>
              pinGloballyMutation({ postId: pinnedGlobally ? '' : post.id })
            }
          />
        ) : null}
        {canPinToGroup && post.group ? (
          pinnedInGroup ? (
            <PopupMenuButton
              title={t('posts.unpinInGroup.title', { defaultValue: 'Unpin in group' })}
              text={t('posts.unpinInGroup.title', { defaultValue: 'Unpin in group' })}
              icon={Pin}
              action={() =>
                updateGroup({ ...post.group!, pinnedPostId: '' })
              }
            />
          ) : (
            <PopupMenuButton
              title={t('posts.pinInGroup.title', { defaultValue: 'Pin in group' })}
              text={t('posts.pinInGroup.title', { defaultValue: 'Pin in group' })}
              icon={Pin}
              action={() =>
                updateGroup({ ...post.group!, pinnedPostId: post.id })
              }
            />
          )
        ) : null}
        {isPostOwner ? (
          <>
            <PopupSeparator />
            <PopupMenuButton
              title={t('common.actions.edit', { defaultValue: 'Edit' })}
              text={t('common.actions.edit', { defaultValue: 'Edit' })}
              icon={Pencil}
              action={handleEditPost}
            />
          </>
        ) : null}
        {canDeletePost ? (
          <PopupMenuButton
            title={t('common.actions.delete', { defaultValue: 'Delete' })}
            text={t('common.actions.delete', { defaultValue: 'Delete' })}
            icon={Trash}
            danger
            action={() => setModal('delete')}
          />
        ) : null}
        {canReportPost ? (
          <>
            <PopupMenuButton
              title={t('common.actions.reportPost', { defaultValue: 'Report post' })}
              text={t('common.actions.reportPost', { defaultValue: 'Report post' })}
              icon={FlagIcon}
              danger
              action={() => setModal('reportPost')}
            />
            <PopupMenuButton
              title={t('common.actions.reportProfile', {
                defaultValue: 'Report @{{handle}}',
                handle: post.profile.handle,
              })}
              text={t('common.actions.reportProfile', {
                defaultValue: 'Report @{{handle}}',
                handle: post.profile.handle,
              })}
              icon={FlagIcon}
              danger
              action={() => setModal('reportProfile')}
            />
          </>
        ) : null}
      </PopupMenu>

      <ReactionsModal
        reactions={post.reactions ?? []}
        open={modal === 'reactions'}
        onClose={() => setModal(null)}
      />
      <RepostModal
        post={post}
        open={modal === 'reposts'}
        onClose={() => setModal(null)}
      />
      <DeletePostModal
        post={post}
        open={modal === 'delete'}
        onClose={() => setModal(null)}
        deleteCallback={deleteCallback}
      />
      <ReportProfileOrPostModal
        reportType="post"
        post={post}
        open={modal === 'reportPost'}
        onClose={() => setModal(null)}
      />
      <ReportProfileOrPostModal
        reportType="profile"
        profile={post.profile}
        open={modal === 'reportProfile'}
        onClose={() => setModal(null)}
      />
    </>
  );
}

// platform/svelte/src/lib/components/core/post/pieces/PostMenu.svelte
<script lang="ts">
  import {
    followProfileMutation,
    unFollowProfileMutation,
    updateGroupMutation,
    bookmarkPostMutation,
    unbookmarkPostMutation,
  } from '$lib/api';
  import type { PublicPost, PublicProfile } from '@openpeeps/common/types';
  import {
    Pencil,
    Pin,
    Repeat,
    ThumbsUp,
    Trash,
    FlagIcon,
    BookmarkPlus,
    BookmarkMinus,
  } from 'lucide-svelte';
  import { pinGlobally } from '$lib/api';
  import { toaster } from '$lib/utils';
  import { goto } from '$app/navigation';
  import { serverInfoStore } from '$lib/api';
  import {
    checkGroupCapabilities,
    checkPostCapabilities,
    checkRoleCapabilities,
  } from '@openpeeps/common/lib';
  import {
    PopupMenu,
    PopupMenuButton,
    PopupSeparator,
    getModalManager,
  } from '@openpeeps/ui';
  import {
    EditPostModal,
    ReactionsModal,
    DeletePostModal,
    RepostModal,
  } from '$lib/components/core/post';
  import { getServerDataContext } from '$lib/components/serverData';
  import { i18nContext } from '$lib/components/i18n';
  import { ReportProfileOrPostModal } from '$lib/components/core/profile';
  import { getCurrentProfile } from '$lib/auth';
  import { updatePostStore } from '../post-form/stores';
  import { currentProfileBookmarkedIds } from '$lib/api';

  const me = getCurrentProfile();

  const { capabilities } = getServerDataContext();

  const { t } = i18nContext();

  const modalManager = getModalManager();
  const toast = toaster();
  const serverInfo = serverInfoStore();
  const bookmarkedIdsStore = currentProfileBookmarkedIds();

  interface Props {
    post: PublicPost;
    deleteCallback?: () => void;
  }

  let { post, deleteCallback = () => {} }: Props = $props();

  let postProfile: PublicProfile = $derived(post.profile);
  let postId = post.id;

  const updateGroup = updateGroupMutation({ id: post.group?.id ?? '' });

  let canPinToGroup = $derived(
    post.group &&
      checkGroupCapabilities(['core-groups-pin'], me, post.group).success,
  );

  let pinnedGlobally: boolean = $derived(
    $serverInfo.data?.communityConfig?.content?.pinnedPost === post.id,
  );
  let pinnedInGroup: boolean = $derived(post.group?.pinnedPostId === post.id);

  let canPinGlobally: boolean = $derived(
    ['public', 'local'].includes(post.visibility) &&
      me &&
      checkRoleCapabilities(['core-config-update'], me?.roles).success,
  );
  let canDeletePost: boolean = $derived(
    checkPostCapabilities(['core-posts-delete'], me, post, capabilities)
      .success,
  );
  let isPostOwner: boolean = $derived(postProfile?.id === me?.id);
  let canReportPost: boolean = $derived(
    checkRoleCapabilities(['core-reports-create'], me?.roles).success,
  );
  let isBookmarked: boolean = $derived(
    $bookmarkedIdsStore.data?.includes(post.id) ?? false,
  );

  const pinGloballyMutation = pinGlobally();
  const followProfile = followProfileMutation({ id: post.profile.id });
  const unfollowProfile = unFollowProfileMutation({
    id: post.profile.id,
  });
  const bookmarkPost = bookmarkPostMutation({ id: post.id });
  const unbookmarkPost = unbookmarkPostMutation({ id: post.id });

  const handlePinGlobally = async () => {
    const response = await pinGloballyMutation({
      postId: pinnedGlobally ? '' : postId,
    });
    if (response.success) {
      toast({
        message: pinnedGlobally
          ? t('posts.unpinGlobally.success')
          : t('posts.pinGlobally.success'),
        type: 'success',
      });
    }
  };

  const handlePinInGroup = async () =>
    post.group &&
    updateGroup({ ...post.group, pinnedPostId: post.id })
      .then(() =>
        toast({
          message: t('posts.pinInGroup.success'),
          type: 'success',
        }),
      )
      .catch(() =>
        toast({
          message: t('posts.pinInGroup.error'),
          type: 'error',
          autohide: false,
        }),
      );

  const handleUnpinInGroup = async () =>
    post.group &&
    updateGroup({ ...post.group, pinnedPostId: '' })
      .then(() =>
        toast({
          message: t('posts.unpinInGroup.success'),
          type: 'success',
        }),
      )
      .catch(() =>
        toast({
          message: t('posts.unpinInGroup.error'),
          type: 'error',
          autohide: false,
        }),
      );

  const handleFollow = async () => {
    const response = await followProfile({
      reblogs: true,
      notify: true,
    });
    toast({
      message: response.success
        ? t('profile.follow.success')
        : t('profile.follow.error'),
      type: 'success',
      action: {
        label: 'View Profile',
        response: () => {
          goto(`/@${post.profile.handle}`, {
            invalidateAll: true,
          });
        },
      },
    });
  };
  const handleUnfollow = async () => {
    const response = await unfollowProfile();
    toast({
      message: response.success
        ? t('profile.unfollow.success')
        : t('profile.unfollow.error'),
      type: 'success',
    });
  };

  const handleEditPost = () => {
    if (post.data?.type === 'event') {
      goto(`/events/${post.id}/edit`);
    } else if (post.data?.type === 'article') {
      goto(`/articles/${post.id}/edit`);
    } else {
      updatePostStore.set(post);
      modalManager.show(EditPostModal);
    }
  };
</script>

{#if me}
  <PopupMenu
    class="hover:bg-surface-200 h-max rounded-full"
    menuId="post-menu-{post.id}"
  >
    {#if postProfile?.id !== me?.id}
      {#if me?.following.map((f) => f.id).includes(postProfile?.id)}
        <PopupMenuButton
          title={t('profile.actions.unfollow')}
          action={handleUnfollow}
          text={t('profile.actions.unfollow')}
          loadingText="loading..."
        />
      {:else}
        <PopupMenuButton
          title={t('profile.actions.follow')}
          action={handleFollow}
          text={t('profile.actions.follow')}
          loadingText="loading..."
        />
      {/if}
    {/if}
    <PopupMenuButton
      title="Reposts"
      action={() => modalManager.show(RepostModal, { post })}
      icon={Repeat}
      text="Reposts"
    />
    <PopupMenuButton
      title="Reactions"
      action={() =>
        modalManager.show(ReactionsModal, { reactions: post.reactions })}
      icon={ThumbsUp}
      text="Reactions"
    />
    {#if isBookmarked}
      <PopupMenuButton
        title={t('posts.unbookmark.title')}
        action={async () => {
          await unbookmarkPost();
          toast({
            message: t('posts.unbookmark.success'),
            type: 'success',
          });
        }}
        icon={BookmarkMinus}
        text={t('posts.unbookmark.title')}
      />
    {:else}
      <PopupMenuButton
        title={t('posts.bookmark.title')}
        action={async () => {
          await bookmarkPost();
          toast({
            message: t('posts.bookmark.success'),
            type: 'success',
          });
        }}
        icon={BookmarkPlus}
        text={t('posts.bookmark.title')}
      />
    {/if}
    {#if canPinGlobally}
      <PopupMenuButton
        title={pinnedGlobally ? t('posts.unpinGlobally.title'): t('posts.pinGlobally.title')}
        action={handlePinGlobally}
        icon={Pin}
        text={pinnedGlobally ? t('posts.unpinGlobally.title'): t('posts.pinGlobally.title')}
      />
    {/if}
    {#if canPinToGroup}
      {#if pinnedInGroup}
        <PopupMenuButton
          title={t('posts.unpinInGroup.title')}
          action={handleUnpinInGroup}
          icon={Pin}
          text={t('posts.unpinInGroup.title')}
        />
      {:else}
        <PopupMenuButton
          title={t('posts.pinInGroup.title')}
          action={handlePinInGroup}
          icon={Pin}
          text={t('posts.pinInGroup.title')}
        />
      {/if}
    {/if}
    {#if isPostOwner}
      <PopupSeparator />
      <PopupMenuButton
        title={t('common.actions.edit')}
        action={handleEditPost}
        icon={Pencil}
        text={t('common.actions.edit')}
      />
    {/if}
    {#if canDeletePost}
      <PopupMenuButton
        title={t('common.actions.delete')}
        action={() =>
          modalManager.show(DeletePostModal, { post, deleteCallback })}
        icon={Trash}
        text={t('common.actions.delete')}
        danger
      />
    {/if}
    {#if canReportPost}
      <PopupMenuButton
        title={t('common.actions.reportPost')}
        action={() =>
          modalManager.show(ReportProfileOrPostModal, {
            post: post,
            reportType: 'post',
          })}
        icon={FlagIcon}
        text={t('common.actions.reportPost')}
        danger
      />
      <PopupMenuButton
        title={t('common.actions.reportProfile', {
          handle: post.profile.handle,
        })}
        action={() =>
          modalManager.show(ReportProfileOrPostModal, {
            profile: post.profile,
            reportType: 'profile',
          })}
        icon={FlagIcon}
        text={t('common.actions.reportProfile', {
          handle: post.profile.handle,
        })}
        danger
      />
    {/if}
  </PopupMenu>
{/if}
