// platform/react-native/src/components/custom/post/pieces/PostMenu.tsx
import { View, Pressable, Share } from 'react-native';
import React, { useCallback, useEffect, useRef } from 'react';
import {
  EllipsisIcon,
  PencilIcon,
  LinkIcon,
  Trash2Icon,
  FlagIcon,
  UserXIcon,
  UsersPlusIcon,
  PinIcon,
  BookmarkPlusIcon,
  BookmarkMinusIcon,
} from '~/components/icons';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu';
import { ThemedText } from '~/components/ui/themed-text';
import Clipboard from '@react-native-clipboard/clipboard';
import Toast from 'react-native-toast-message';
import { BASE_URL } from '~/lib/constants';
import { checkGroupCapabilities, checkRoleCapabilities, PublicPost } from '@openpeeps/common';
import { truncateText } from '~/lib/utils';
import { useOpenpeeps } from '@openpeeps/react';
import { BottomSheetModal } from '@gorhom/bottom-sheet';
import { DeletePostSheeConfirmationSheet } from '~/components/custom/modals/post';
import { useNavigation } from '@react-navigation/native';
import { MainStackParamList } from '~/components/navigation/types';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useTranslation } from 'react-i18next';
import { ReportProfileOrPostSheet } from '../../common/report-profile-or-post-sheet';
import { UploadIcon } from '~/components/icons';
interface PostMenuProps {
  post: PublicPost;
}
export const PostMenu = ({ post }: PostMenuProps) => {
  const { t } = useTranslation();
  const { openpeepsApi, queryClient } = useOpenpeeps();
  const { data: currentProfile, refetch: refetchCurrentProfile } =
    openpeepsApi.useCurrentProfile();
  const deleteMessageModalRef = useRef<BottomSheetModal>(null);
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();
  const reportProfileModalRef = useRef<BottomSheetModal>(null);
  const reportPostModalRef = useRef<BottomSheetModal>(null);
  const [isFollowing, setIsFollowing] = React.useState(false);
  const { data: serverInfo } = openpeepsApi.useServerInfo();
  const canPinToGroup = post.group &&
    checkGroupCapabilities(['core-groups-pin'], currentProfile, post.group).success
  const pinnedInGroup: boolean = post.group?.pinnedPostId === post.id
  const canPinGlobally: boolean = ['public', 'local'].includes(post.visibility) &&
      currentProfile &&
      checkRoleCapabilities(['core-config-update'], currentProfile?.roles).success || false
  const pinnedGlobally: boolean = 
    serverInfo?.communityConfig?.content?.pinnedPost === post.id
  const {data: bookmarkedIdsStore, refetch: refetchBookmarkedIds} = openpeepsApi.useCurrentProfileBookmarkedIds();

  const isBookmarked = bookmarkedIdsStore?.includes(post.id);

  const bookmarkPost = openpeepsApi.bookmarkPostAction({id: post.id});
  const unbookmarkPost = openpeepsApi.unbookmarkPostAction({id: post.id});

  const deletePost = openpeepsApi.deletePostAction({
    id: post.id,
  });

  const updateGroup = openpeepsApi.updateGroupAction({ id: post.group?.id as string });
  const pinGloballyMutation = openpeepsApi.admin.pinPostGloballyAction();

  const followProfile = openpeepsApi.followProfileAction({ id: post.profile.id });
  const unfollowProfile = openpeepsApi.unfollowProfileAction({
    id: post.profile.id,
  });

  const handleDeletePostModalPress = useCallback(() => {
    deleteMessageModalRef.current?.present();
  }, []);

  const handleReportProfileModalPress = useCallback(() => {
    reportProfileModalRef.current?.present();
  }, []);

  const handleReportPostModalPress = useCallback(() => {
    reportPostModalRef.current?.present();
  }, []);

  const handleDelete = async () => {
    void deletePost().then((res: unknown) => {
      if (res) {
        Toast.show({
          type: 'success',
          text1: t('posts.delete.success'),
        });
      } else {
        Toast.show({
          type: 'error',
          text1: t('posts.delete.error'),
        });
      }
    });
  };

  const handleFollow = async () => {
    const response = await followProfile({
      reblogs: true,
      notify: true,
    });
    await refetchCurrentProfile();
    Toast.show({
      type: response.success ? 'success' : 'error',
      text1: response.success
        ? t('profile.follow.followedSuccess')
        : t('profile.follow.error'),
    });
    await queryClient.invalidateQueries();
  };

  const handleUnfollow = async () => {
    const response = await unfollowProfile();
    await refetchCurrentProfile();
    Toast.show({
      type: response.success ? 'success' : 'error',
      text1: response.success
        ? t('profile.follow.unfollowedSuccess')
        : t('profile.follow.error'),
    });
    await queryClient.invalidateQueries();
  };

  const handlePinInGroup = async () =>
    post.group &&
    updateGroup({ ...post.group, pinnedPostId: post.id })
      .then(() =>
        Toast.show({
          type:  'success' ,
          text1: t('posts.pinInGroup.success'),
      }))
      .catch(() =>
        Toast.show({
          type:  'error' ,
          text1: t('posts.pinInGroup.error'),
          autoHide: false
    })
  );

  const handleUnpinInGroup = async () =>
    post.group &&
    updateGroup({ ...post.group, pinnedPostId: '' })
      .then(() =>
        Toast.show({
          type:  'success' ,
          text1: t('posts.unpinInGroup.success'),
      }))
      .catch(() =>
        Toast.show({
          type:  'error' ,
          text1: t('posts.create.error'),
          autoHide: false
    })
  );

  const handlePinGlobally = async () => {
    const response = await pinGloballyMutation({
      postId: pinnedGlobally ? '' : post.id,
    });
    if (response.success) {
        Toast.show({
          type:  'success' ,
          text1: pinnedGlobally
          ? t('posts.unpinGlobally.success')
          : t('posts.pinGlobally.success'),
      })
    }
  };

  useEffect(() => {
    const isCurrentProfileFollowing = currentProfile?.following
      .map((p) => p.id)
      .includes(post.profile.id);

    setIsFollowing(isCurrentProfileFollowing || false);
    refetchBookmarkedIds()
  }, [currentProfile, post]);

  return (
    <View key={post.id}>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Pressable className="mr-2 p-2">
            <EllipsisIcon className="text-foreground" />
          </Pressable>
        </DropdownMenuTrigger>
        <DropdownMenuContent className="mt-1 ">
          <DropdownMenuGroup className="mr-4">
            <DropdownMenuItem
              onPress={() => {
                try {
                  Clipboard.setString(`${BASE_URL}/post/${post.id}`);
                  Toast.show({
                    type: 'success',
                    text1: t('posts.copyPostLink.success'),
                    text2: t('posts.copyPostLink.successMessage'),
                  });
                } catch (e) {
                  Toast.show({
                    type: 'error',
                    text1: t('posts.copyPostLink.error'),
                    text2: t('posts.copyPostLink.errorMessage'),
                  });
                }
              }}
              className=" flex-row gap-x-2 items-center">
              <LinkIcon size={16} className="text-foreground" />
              <ThemedText>{t('posts.copyPostLink.submit')}</ThemedText>
            </DropdownMenuItem>

            <DropdownMenuItem
              onPress={() => {
                Share.share({
                  message: t('posts.actions.shareMessage'),
                  url: `${BASE_URL}/post/${post.id}`,
                });
              }}
              className=" flex-row gap-x-2 items-center">
              <UploadIcon size={16} className="text-foreground" />
              <ThemedText>{t('posts.actions.shareMessage')}</ThemedText>
            </DropdownMenuItem>

            {currentProfile?.id === post.profile.id && !post.repost && (
              <>
                <DropdownMenuItem
                  onPress={() => {
                    navigation.navigate('EditPost', {
                      id: post.id,
                    });
                  }}
                  className=" flex-row gap-x-2 items-center">
                  <PencilIcon size={16} className="text-foreground" />
                  <ThemedText>{t('common.actions.edit')}</ThemedText>
                </DropdownMenuItem>
              </>
            )}
            {/* <DropdownMenuItem className=" flex-row gap-x-2 items-center">
              <ClockIcon size={16} className="text-foreground" />
              <ThemedText>Edit History</ThemedText>
            </DropdownMenuItem> */}
            {currentProfile?.id !== post.profile.id && (
              <>
                {isFollowing ? (
                  <DropdownMenuItem
                    onPress={handleUnfollow}
                    className=" flex-row gap-x-2 items-center">
                    <UserXIcon size={16} className="text-foreground" />
                    <ThemedText>
                      {t('profile.actions.unfollow', {
                        name: truncateText(
                          post?.profile?.displayName ||
                          `@${post?.profile?.handle}`,
                          5,
                        ),
                      })}
                    </ThemedText>
                  </DropdownMenuItem>
                ) : (
                  <DropdownMenuItem
                    onPress={handleFollow}
                    className=" flex-row gap-x-2 items-center">
                    <UsersPlusIcon size={16} className="text-foreground" />
                    <ThemedText>
                      {t('profile.actions.follow', {
                        name: truncateText(
                          post?.profile?.displayName ||
                          `@${post?.profile?.handle}`,
                          5,
                        ),
                      })}
                    </ThemedText>
                  </DropdownMenuItem>
                )}
              </>
            )}
            {currentProfile?.id === post.profile.id && (
              <DropdownMenuItem
                onPress={handleDeletePostModalPress}
                className=" flex-row gap-x-2 items-center text-destructive">
                <Trash2Icon size={16} className="text-destructive" />
                <ThemedText className="text-destructive">
                  {t('common.actions.delete')}
                </ThemedText>
              </DropdownMenuItem>
            )}
            {currentProfile?.id !== post.profile.id && (
              <>
                <DropdownMenuItem
                  onPress={handleReportPostModalPress}
                  className=" flex-row gap-x-2 items-center text-destructive">
                  <FlagIcon size={16} className="text-destructive" />
                  <ThemedText className="text-destructive">
                    {t('common.actions.reportPost')}
                  </ThemedText>
                </DropdownMenuItem>
                <DropdownMenuItem
                  onPress={handleReportProfileModalPress}
                  className=" flex-row gap-x-2 items-center text-destructive">
                  <FlagIcon size={16} className="text-destructive" />
                  <ThemedText className="text-destructive">
                    {t('common.actions.reportProfile', {
                      handle: post.profile.handle,
                    })}
                  </ThemedText>
                </DropdownMenuItem>
              </>
            )}
            {canPinGlobally && (
              <DropdownMenuItem
                onPress={handlePinGlobally}
                className=" flex-row gap-x-2 items-center text-destructive">
                <PinIcon size={16} className="text-destructive" />
                <ThemedText className="text-destructive">
                  {pinnedGlobally ? t('posts.unpinGlobally.title'): t('posts.pinGlobally.title')}
                </ThemedText>
              </DropdownMenuItem>
            )}
            {canPinToGroup && (
              <>
                {pinnedInGroup ? (
                  <DropdownMenuItem
                    onPress={handleUnpinInGroup}
                    className=" flex-row gap-x-2 items-center">
                    <PinIcon size={16} className="text-foreground" />
                    <ThemedText>
                      {t('posts.unpinInGroup.title')}
                    </ThemedText>
                  </DropdownMenuItem>
                ) : (
                  <DropdownMenuItem
                    onPress={handlePinInGroup}
                    className=" flex-row gap-x-2 items-center">
                    <PinIcon size={16} className="text-foreground" />
                    <ThemedText>
                      {t('posts.pinInGroup.title')}
                    </ThemedText>
                  </DropdownMenuItem>
                )}
              </>
            )}
            {isBookmarked ? (
              <DropdownMenuItem
                onPress={async () => {
                  await unbookmarkPost().then(()=> refetchBookmarkedIds())
                  Toast.show({
                    type: 'success',
                    text1: t('posts.unbookmark.success'),
                  });
                }}
                className=" flex-row gap-x-2 items-center">
                <BookmarkMinusIcon size={16} className="text-foreground" />
                <ThemedText>{t('posts.unbookmark.title')}</ThemedText>
              </DropdownMenuItem>
            ) : (
              <DropdownMenuItem
                onPress={async () => {
                  await bookmarkPost().then(()=> refetchBookmarkedIds())
                  Toast.show({
                    type: 'success',
                    text1: t('posts.bookmark.success'),
                  });
                }}
                className=" flex-row gap-x-2 items-center">
                <BookmarkPlusIcon size={16} className="text-foreground" />
                <ThemedText>{t('posts.bookmark.title')}</ThemedText>
              </DropdownMenuItem>
            )}
          </DropdownMenuGroup>
        </DropdownMenuContent>
      </DropdownMenu>
      <DeletePostSheeConfirmationSheet
        ref={deleteMessageModalRef}
        onDelete={handleDelete}
        post={post}
      />
      <ReportProfileOrPostSheet
        ref={reportProfileModalRef}
        profile={post.profile}
        reportType="profile"
      />
      <ReportProfileOrPostSheet
        ref={reportPostModalRef}
        post={post}
        reportType="post"
      />
    </View>
  );
};

// platform/svelte/src/lib/components/core/post/pieces/PostMenu.svelte
<script lang="ts">
  import {
    followProfileMutation,
    unFollowProfileMutation,
    updateGroupMutation,
    bookmarkPostMutation,
    unbookmarkPostMutation,
  } from '$lib/api';
  import type { PublicPost, PublicProfile } from '@openpeeps/common/types';
  import {
    Pencil,
    Pin,
    Repeat,
    ThumbsUp,
    Trash,
    FlagIcon,
    BookmarkPlus,
    BookmarkMinus,
  } from 'lucide-svelte';
  import { pinGlobally } from '$lib/api';
  import { toaster } from '$lib/utils';
  import { goto } from '$app/navigation';
  import { serverInfoStore } from '$lib/api';
  import {
    checkGroupCapabilities,
    checkPostCapabilities,
    checkRoleCapabilities,
  } from '@openpeeps/common/lib';
  import {
    PopupMenu,
    PopupMenuButton,
    PopupSeparator,
    getModalManager,
  } from '@openpeeps/ui';
  import {
    EditPostModal,
    ReactionsModal,
    DeletePostModal,
    RepostModal,
  } from '$lib/components/core/post';
  import { getServerDataContext } from '$lib/components/serverData';
  import { i18nContext } from '$lib/components/i18n';
  import { ReportProfileOrPostModal } from '$lib/components/core/profile';
  import { getCurrentProfile } from '$lib/auth';
  import { updatePostStore } from '../post-form/stores';
  import { currentProfileBookmarkedIds } from '$lib/api';

  const me = getCurrentProfile();

  const { capabilities } = getServerDataContext();

  const { t } = i18nContext();

  const modalManager = getModalManager();
  const toast = toaster();
  const serverInfo = serverInfoStore();
  const bookmarkedIdsStore = currentProfileBookmarkedIds();

  interface Props {
    post: PublicPost;
    deleteCallback?: () => void;
  }

  let { post, deleteCallback = () => {} }: Props = $props();

  let postProfile: PublicProfile = $derived(post.profile);
  let postId = post.id;

  const updateGroup = updateGroupMutation({ id: post.group?.id ?? '' });

  let canPinToGroup = $derived(
    post.group &&
      checkGroupCapabilities(['core-groups-pin'], me, post.group).success,
  );

  let pinnedGlobally: boolean = $derived(
    $serverInfo.data?.communityConfig?.content?.pinnedPost === post.id,
  );
  let pinnedInGroup: boolean = $derived(post.group?.pinnedPostId === post.id);

  let canPinGlobally: boolean = $derived(
    ['public', 'local'].includes(post.visibility) &&
      me &&
      checkRoleCapabilities(['core-config-update'], me?.roles).success,
  );
  let canDeletePost: boolean = $derived(
    checkPostCapabilities(['core-posts-delete'], me, post, capabilities)
      .success,
  );
  let isPostOwner: boolean = $derived(postProfile?.id === me?.id);
  let canReportPost: boolean = $derived(
    checkRoleCapabilities(['core-reports-create'], me?.roles).success,
  );
  let isBookmarked: boolean = $derived(
    $bookmarkedIdsStore.data?.includes(post.id) ?? false,
  );

  const pinGloballyMutation = pinGlobally();
  const followProfile = followProfileMutation({ id: post.profile.id });
  const unfollowProfile = unFollowProfileMutation({
    id: post.profile.id,
  });
  const bookmarkPost = bookmarkPostMutation({ id: post.id });
  const unbookmarkPost = unbookmarkPostMutation({ id: post.id });

  const handlePinGlobally = async () => {
    const response = await pinGloballyMutation({
      postId: pinnedGlobally ? '' : postId,
    });
    if (response.success) {
      toast({
        message: pinnedGlobally
          ? t('posts.unpinGlobally.success')
          : t('posts.pinGlobally.success'),
        type: 'success',
      });
    }
  };

  const handlePinInGroup = async () =>
    post.group &&
    updateGroup({ ...post.group, pinnedPostId: post.id })
      .then(() =>
        toast({
          message: t('posts.pinInGroup.success'),
          type: 'success',
        }),
      )
      .catch(() =>
        toast({
          message: t('posts.pinInGroup.error'),
          type: 'error',
          autohide: false,
        }),
      );

  const handleUnpinInGroup = async () =>
    post.group &&
    updateGroup({ ...post.group, pinnedPostId: '' })
      .then(() =>
        toast({
          message: t('posts.unpinInGroup.success'),
          type: 'success',
        }),
      )
      .catch(() =>
        toast({
          message: t('posts.unpinInGroup.error'),
          type: 'error',
          autohide: false,
        }),
      );

  const handleFollow = async () => {
    const response = await followProfile({
      reblogs: true,
      notify: true,
    });
    toast({
      message: response.success
        ? t('profile.follow.success')
        : t('profile.follow.error'),
      type: 'success',
      action: {
        label: 'View Profile',
        response: () => {
          goto(`/@${post.profile.handle}`, {
            invalidateAll: true,
          });
        },
      },
    });
  };
  const handleUnfollow = async () => {
    const response = await unfollowProfile();
    toast({
      message: response.success
        ? t('profile.unfollow.success')
        : t('profile.unfollow.error'),
      type: 'success',
    });
  };

  const handleEditPost = () => {
    if (post.data?.type === 'event') {
      goto(`/events/${post.id}/edit`);
    } else if (post.data?.type === 'article') {
      goto(`/articles/${post.id}/edit`);
    } else {
      updatePostStore.set(post);
      modalManager.show(EditPostModal);
    }
  };
</script>

{#if me}
  <PopupMenu
    class="hover:bg-surface-200 h-max rounded-full"
    menuId="post-menu-{post.id}"
  >
    {#if postProfile?.id !== me?.id}
      {#if me?.following.map((f) => f.id).includes(postProfile?.id)}
        <PopupMenuButton
          title={t('profile.actions.unfollow')}
          action={handleUnfollow}
          text={t('profile.actions.unfollow')}
          loadingText="loading..."
        />
      {:else}
        <PopupMenuButton
          title={t('profile.actions.follow')}
          action={handleFollow}
          text={t('profile.actions.follow')}
          loadingText="loading..."
        />
      {/if}
    {/if}
    <PopupMenuButton
      title="Reposts"
      action={() => modalManager.show(RepostModal, { post })}
      icon={Repeat}
      text="Reposts"
    />
    <PopupMenuButton
      title="Reactions"
      action={() =>
        modalManager.show(ReactionsModal, { reactions: post.reactions })}
      icon={ThumbsUp}
      text="Reactions"
    />
    {#if isBookmarked}
      <PopupMenuButton
        title={t('posts.unbookmark.title')}
        action={async () => {
          await unbookmarkPost();
          toast({
            message: t('posts.unbookmark.success'),
            type: 'success',
          });
        }}
        icon={BookmarkMinus}
        text={t('posts.unbookmark.title')}
      />
    {:else}
      <PopupMenuButton
        title={t('posts.bookmark.title')}
        action={async () => {
          await bookmarkPost();
          toast({
            message: t('posts.bookmark.success'),
            type: 'success',
          });
        }}
        icon={BookmarkPlus}
        text={t('posts.bookmark.title')}
      />
    {/if}
    {#if canPinGlobally}
      <PopupMenuButton
        title={pinnedGlobally ? t('posts.unpinGlobally.title'): t('posts.pinGlobally.title')}
        action={handlePinGlobally}
        icon={Pin}
        text={pinnedGlobally ? t('posts.unpinGlobally.title'): t('posts.pinGlobally.title')}
      />
    {/if}
    {#if canPinToGroup}
      {#if pinnedInGroup}
        <PopupMenuButton
          title={t('posts.unpinInGroup.title')}
          action={handleUnpinInGroup}
          icon={Pin}
          text={t('posts.unpinInGroup.title')}
        />
      {:else}
        <PopupMenuButton
          title={t('posts.pinInGroup.title')}
          action={handlePinInGroup}
          icon={Pin}
          text={t('posts.pinInGroup.title')}
        />
      {/if}
    {/if}
    {#if isPostOwner}
      <PopupSeparator />
      <PopupMenuButton
        title={t('common.actions.edit')}
        action={handleEditPost}
        icon={Pencil}
        text={t('common.actions.edit')}
      />
    {/if}
    {#if canDeletePost}
      <PopupMenuButton
        title={t('common.actions.delete')}
        action={() =>
          modalManager.show(DeletePostModal, { post, deleteCallback })}
        icon={Trash}
        text={t('common.actions.delete')}
        danger
      />
    {/if}
    {#if canReportPost}
      <PopupMenuButton
        title={t('common.actions.reportPost')}
        action={() =>
          modalManager.show(ReportProfileOrPostModal, {
            post: post,
            reportType: 'post',
          })}
        icon={FlagIcon}
        text={t('common.actions.reportPost')}
        danger
      />
      <PopupMenuButton
        title={t('common.actions.reportProfile', {
          handle: post.profile.handle,
        })}
        action={() =>
          modalManager.show(ReportProfileOrPostModal, {
            profile: post.profile,
            reportType: 'profile',
          })}
        icon={FlagIcon}
        text={t('common.actions.reportProfile', {
          handle: post.profile.handle,
        })}
        danger
      />
    {/if}
  </PopupMenu>
{/if}
