// platform/react/src/components/post/pieces/PostInfoHeader.tsx
import type { PublicPost, PublicReplyPost } from '@openpeeps/common/types';
import { Avatar } from '../../profile';
import { UpdatingDate } from '@openpeeps/react-ui';
import { PostMenu } from './PostMenu';

export interface PostInfoHeaderProps {
  post: PublicPost | PublicReplyPost;
  showMenu?: boolean;
  deleteCallback?: () => void;
}

export function PostInfoHeader({
  post,
  showMenu = false,
  deleteCallback,
}: PostInfoHeaderProps) {
  const { profile } = post;
  return (
    <div className="flex justify-between py-2">
      <div className="flex w-fit space-x-2">
        <a href={`/@${profile.handle}`}>
          <Avatar profile={profile} size={3} />
        </a>
        <div className="flex flex-col flex-wrap">
          <a
            href={`/@${profile.handle}`}
            className="text-sm font-semibold hover:underline"
          >
            {profile.displayName || `@${profile.handle}`}
          </a>
          <span className="text-xs text-muted-foreground">
            @{profile.handle}
          </span>
          <span className="text-xs font-extralight">
            <UpdatingDate date={post.createdAt} />
          </span>
        </div>
      </div>
      {showMenu && 'id' in post ? (
        <PostMenu post={post as PublicPost} deleteCallback={deleteCallback} />
      ) : null}
    </div>
  );
}

// platform/svelte/src/lib/components/core/post/pieces/PostInfoHeader.svelte
<script lang="ts">
	import type { PublicPost } from '@openpeeps/common/types';
	import { Avatar } from '../../profile';
	import PostMenu from './PostMenu.svelte';
	import DisplayUserNameBlock from '$lib/components/core/profile/DisplayUserNameBlock.svelte';
	import { UpdatingDate } from '@openpeeps/ui';

	interface Props {
		post: PublicPost;
		showMenu: boolean;
		deleteCallback?: () => void;
	}

	let { post, showMenu, deleteCallback = () => undefined }: Props = $props();
</script>

<div class="flex justify-between py-5">
	<div class="flex w-fit space-x-2">
		<a href={`/@${post.profile.handle}`}>
			<Avatar profile={post?.profile} size={4} />
		</a>
		<div class="flex flex-col flex-wrap">
			<DisplayUserNameBlock profile={post.profile} />
			<span class="text-sm font-extralight">
				<UpdatingDate date={post.createdAt} />
			</span>
		</div>
	</div>
	{#if showMenu}
		<PostMenu {post} {deleteCallback} />
	{/if}
</div>
