// platform/web/src/pages/auth/ResetPassword.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, Input, Label, Toast } from '@openpeeps/react-ui';
import { useT, useOpenpeeps } from '@openpeeps/react';
import { AuthLayout } from '@openpeeps/react/components';

import { performResetPassword } from '../../lib/auth';

export function ResetPassword() {
  const t = useT();
  const navigate = useNavigate();
  const { client } = useOpenpeeps();

  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [token, setToken] = useState('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // SvelteKit version reads `location.hash.substring(7)` (`#token=...`).
    setToken(window.location.hash.replace(/^#token=/, ''));
  }, []);

  const handleSubmit = async () => {
    setError(null);
    try {
      await performResetPassword(client, { password }, token);
      navigate('/auth/login');
    } catch (err) {
      setError((err as Error).message);
    }
  };

  return (
    <AuthLayout navigate={navigate}>
      <form
        className="text-token flex h-fit flex-col gap-6"
        onSubmit={(e) => {
          e.preventDefault();
          void handleSubmit();
        }}
      >
        <h2 className="text-xl">
          {t('auth.resetPassword.title', { defaultValue: 'Reset Password' })}
        </h2>

        <Label title={t('auth.newPassword', { defaultValue: 'New Password' })}>
          <Input
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            type="password"
          />
        </Label>

        <Label
          title={t('common.confirmPassword', {
            defaultValue: 'Confirm Password',
          })}
        >
          <Input
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            required
            type="password"
          />
        </Label>

        {error && (
          <Toast variant="error" onDismiss={() => setError(null)}>
            {error}
          </Toast>
        )}

        <Button
          title={t('auth.resetPassword.submit', { defaultValue: 'Reset' })}
          disabled={confirmPassword !== password || password.length === 0}
          variant="variant-filled-primary"
          action={handleSubmit}
          className="w-full"
        >
          {t('auth.resetPassword.submit', { defaultValue: 'Reset' })}
        </Button>
      </form>
    </AuthLayout>
  );
}

// platform/app/src/routes/auth/reset-password/+page.svelte
<script lang="ts">
  import { resetPassword } from '@openpeeps/svelte/api';
  import { goto } from '$app/navigation';
  import { FormOld, LabelOld, Input } from '@openpeeps/ui';
  import { Button } from '@openpeeps/ui';
  import { onMount } from 'svelte';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';

  getPageHeaderStore().set({ title: 'Reset Password' });

  let password = $state('');
  let confirmPassword = $state('');

  let token: string = '';

  const error = $state({
    type: '',
    message: '',
  });

  const handleSubmit = () =>
    resetPassword({ password }, token)
      .then(() => goto('/auth/login'))
      .catch((e) => (error.message = e.message));

  onMount(() => {
    token = location.hash.substring(7);
  });
</script>

<FormOld
  {handleSubmit}
  className="text-token h-fit space-y-6"
  error={error.type === 'general' ? error.message : ''}
>
  <h2 class="text-xl">Reset Password</h2>

  <LabelOld
    title="New Password"
    message={error.type === 'password' ? error.message : ''}
  >
    <Input
      bind:value={password}
      error={error.type === 'password'}
      required
      type="password"
    />
  </LabelOld>

  <LabelOld
    title="Confirm Password"
    message={error.type === 'password' ? error.message : ''}
  >
    <Input
      bind:value={confirmPassword}
      error={error.type === 'password'}
      required
      type="password"
    />
  </LabelOld>

  <Button
    title="Reset Password"
    disabled={confirmPassword !== password}
    variant="variant-filled-primary"
    action={handleSubmit}
    class="w-full"
  >
    Submit
  </Button>
</FormOld>
