// platform/svelte/src/lib/components/core/post/types/event/CardEvent.svelte
<script lang="ts">
  import { Button, Timespan } from '@openpeeps/ui';
  import type { Event, PublicPost } from '@openpeeps/common/types';
  import { page } from '$app/state';
  import ParticipantsCard from '../../pieces/ParticipantsCard.svelte';
  import { jamStateStore } from '$lib/api';
  import { getCurrentProfile } from '$lib/auth';
  import { getJamUrl } from '@openpeeps/common/lib';
  import EventLocation from '../../pieces/EventLocation.svelte';
  import { i18nContext } from '$lib/components/i18n';
  import ProfileEventRelationship from './ProfileEventRelationship.svelte';
  import { AccessDeniedLoader } from '$lib/components/layout';
  import { postViewCounter } from '$lib/utils';

  const { t } = i18nContext();

  interface Props {
    post: PublicPost;
  }

  const me = getCurrentProfile();

  const { post }: Props = $props();
  const event = $derived(post.data as Event);
  const jam = $derived(event?.jam);

  const jamLink = getJamUrl(post.id, page.url.origin);

  const jamStateQuery = $derived(jam ? jamStateStore(post.id) : undefined);
</script>

<div class="hover:bg-surface-100 overflow-hidden rounded-md px-2 pt-2" use:postViewCounter={post.id}>
  <a href="{page.url.origin}/posts/{post.id}" class="flex flex-col gap-2">
    <span class="aspect-video w-full overflow-hidden rounded-md">
      <img
        src={event.image || '/img/event-default.png'}
        alt={event?.name || event?.content}
        class="h-full w-full object-cover"
      />
    </span>
    <span class="flex flex-col gap-1">
      <div class="truncate text-sm">
        <Timespan {...event} />
      </div>
      <h3 class="truncate font-semibold">{event?.name || event?.content}</h3>
      <div class="flex flex-col gap-1">
        <div class="flex flex-row gap-x-2">
          <EventLocation {post} truncate={true} />
          <ProfileEventRelationship {post} />
        </div>
        {#if jam && me}
          {@const jamState = $jamStateQuery?.data}
          {@const attendeesLength = jamState?.participants.length ?? 0}
          <AccessDeniedLoader queries={[$jamStateQuery!]}>
            <span
              class="flex items-center justify-start {attendeesLength > 1
                ? 'gap-5'
                : 'gap-2'} 
						text-surface-600 text-xs {attendeesLength > 0 ? '-mt-4' : ''}"
            >
              {#if jamState?.active}
                <span class="-ml-5 w-12">
                  <ParticipantsCard {jamState} />
                </span>
                <span>
                  {attendeesLength}
                  {attendeesLength === 1 ? 'attendee' : 'attendees'}
                </span>
                <span>
                  <Button
                    action={jamLink}
                    variant="variant-filled-primary"
                    compact
                  >
                    {t('jam.join.submit')}
                  </Button>
                </span>
              {:else if jam.moderators.includes(me.id)}
                <span>
                  <Button action={jamLink} variant="variant-filled-primary">
                    {t('jam.start.submit')}
                  </Button>
                </span>
              {/if}
            </span>
          </AccessDeniedLoader>
        {/if}
      </div>
    </span>
  </a>
</div>

// platform/react/src/components/post/types/event/CardEvent.tsx
import type { Event, PublicPost } from '@openpeeps/common/types';
import { getJamUrl, truncateText } from '@openpeeps/common/lib';
import { Button } from '@openpeeps/react-ui';
import { useOpenpeeps } from '../../../../contexts/openpeeps';
import { useT } from '../../../../i18n';
import { useCurrentProfile } from '../../../layout/IdentityContext';
import { usePostViewRef } from '../../../../lib/postViewCounter';
import { EventLocation } from '../../pieces/EventLocation';
import { ParticipantsCard } from '../../pieces/ParticipantsCard';
import { ProfileEventRelationship } from './ProfileEventRelationship';

export interface CardEventProps {
  post: PublicPost;
}

function formatEventTimespan(event: Event) {
  if (!event.start) return '';
  const start = new Date(event.start);
  const end = event.end ? new Date(event.end) : undefined;
  const datePart = start.toLocaleDateString(undefined, {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  });
  const timePart = start.toLocaleTimeString(undefined, {
    hour: '2-digit',
    minute: '2-digit',
  });
  if (end) {
    return `${datePart} · ${timePart} – ${end.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}`;
  }
  return `${datePart} · ${timePart}`;
}

export function CardEvent({ post }: CardEventProps) {
  const t = useT();
  const me = useCurrentProfile();
  const postViewRef = usePostViewRef(post.id);
  const { openpeepsApi } = useOpenpeeps();
  const event = post.data as Event;
  const jam = event.jam;
  const jamStateQuery = openpeepsApi.useJamState(post.id);
  const jamState = jam ? jamStateQuery.data : undefined;
  const attendeesLength = jamState?.participants.length ?? 0;

  const jamLink = getJamUrl(
    post.id,
    typeof window !== 'undefined' ? window.location.origin : undefined,
  );

  const postLink = `/posts/${post.id}`;

  return (
    <div
      ref={postViewRef}
      className="hover:bg-surface-100 mb-6 w-full overflow-hidden rounded-lg border"
    >
      <a href={postLink} className="block">
        <div className="aspect-video w-full overflow-hidden">
          <img
            src={event.image || '/img/event-default.png'}
            alt={event.name ? `image for ${event.name}` : 'Event'}
            className="h-full w-full object-cover"
          />
        </div>
      </a>
      <div className="grid gap-y-4 p-4">
        <a href={postLink} className="block text-inherit no-underline">
          <p className="text-muted-foreground text-sm">
            {formatEventTimespan(event)}
          </p>
          <h3 className="text-xl font-semibold">
            {truncateText(event.name, 100) || '-'}
          </h3>
        </a>
        <div className="flex flex-wrap gap-x-2 gap-y-1">
          <EventLocation post={post} truncate />
          <ProfileEventRelationship post={post} />
        </div>
        {jam && me ? (
          jamState?.active ? (
            <div className="text-surface-600 flex items-center justify-start gap-2 text-xs">
              <span className="w-12">
                <ParticipantsCard jamState={jamState} />
              </span>
              <span>
                {attendeesLength}{' '}
                {attendeesLength === 1
                  ? t('events.jam.attendee', { defaultValue: 'attendee' })
                  : t('events.jam.attendees', { defaultValue: 'attendees' })}
              </span>
              <Button action={jamLink} variant="variant-filled-primary" compact>
                {t('jam.join.submit', { defaultValue: 'Join Jam' })}
              </Button>
            </div>
          ) : jam.moderators.includes(me.id) ? (
            <div>
              <Button action={jamLink} variant="variant-filled-primary">
                {t('jam.start.submit', { defaultValue: 'Start Jam' })}
              </Button>
            </div>
          ) : null
        ) : null}
      </div>
    </div>
  );
}
