// platform/react/src/components/post/feed/events/EventsFeed.tsx
import { useEffect, useMemo, useRef } from 'react';
import { Rss } from 'lucide-react';
import type { PublicPost, SuccessFailureResponse } from '@openpeeps/common/types';
import type {
  InfiniteData,
  UseInfiniteQueryResult,
} from '@tanstack/react-query';
import { useT } from '../../../../i18n';
import { CardEvent } from '../../types/event/CardEvent';
import { LoadingSpinner } from '@openpeeps/react-ui';

export type EventsFeedQuery = UseInfiniteQueryResult<
  InfiniteData<PublicPost[], unknown>,
  SuccessFailureResponse
>;

export interface EventsFeedProps {
  query: EventsFeedQuery;
}

export function EventsFeed({ query }: EventsFeedProps) {
  const t = useT();
  const sentinelRef = useRef<HTMLDivElement | null>(null);

  const posts = useMemo(() => {
    const flat = (query.data?.pages ?? []).flat();
    const seen = new Set<string>();
    return flat.filter((p) => {
      if (seen.has(p.id)) return false;
      seen.add(p.id);
      return true;
    });
  }, [query.data]);

  useEffect(() => {
    const el = sentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver((entries) => {
      const entry = entries[0];
      if (!entry) return;
      if (
        entry.isIntersecting &&
        query.hasNextPage &&
        !query.isFetchingNextPage
      ) {
        void query.fetchNextPage();
      }
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, [query]);

  if (query.isLoading) {
    return (
      <div className="flex h-32 items-center justify-center text-sm text-muted-foreground">
        <LoadingSpinner />
        </div>
    );
  }

  if (posts.length === 0) {
    return (
      <div className="flex h-96 w-full flex-col items-center justify-center gap-y-4">
        <Rss className="text-surface-300 size-20" />
        <p className="text-xl">
          {t('feed.empty', { defaultValue: 'No events yet.' })}
        </p>
      </div>
    );
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2">
      {posts.map((post) => (
        <CardEvent key={post.id} post={post} />
      ))}
      <div ref={sentinelRef} aria-hidden="true" className="col-span-full h-8" />
      {query.isFetchingNextPage ? (
        <div className="col-span-full flex justify-center py-4 text-sm text-muted-foreground">
          <LoadingSpinner />
        </div>
      ) : null}
    </div>
  );
}

// platform/svelte/src/lib/components/core/post/feed/events/EventsFeed.svelte
<script lang="ts">
	import type { PublicPost } from '@openpeeps/common/types';
	import type { CreateInfiniteQueryResult, InfiniteData } from '@tanstack/svelte-query';
	import { Calendar, PhoneOff } from 'lucide-svelte';
	import { InfiniteScrollContainer } from '@openpeeps/ui';
	import { CardEvent } from '../..';
	import { i18nContext } from '@openpeeps/svelte/components';
	const { t } = i18nContext();

	interface Props {
		query: CreateInfiniteQueryResult<InfiniteData<PublicPost[], unknown>>;
		type?: 'event' | 'jam';
	}

	let { query, type = 'event' }: Props = $props();
</script>

<InfiniteScrollContainer {query} uniqueBy={(post) => post.id}>
	{#snippet children({ list })}
		<div class="grid grid-cols-1 gap-2 md:grid-cols-2 md:gap-4">
			{#each list as post (post.id)}
				<CardEvent {post} />
			{/each}
		</div>
	{/snippet}
	{#snippet empty()}
		<div class="flex h-72 w-full flex-col items-center justify-center gap-y-6">
			{#if type === 'jam'}
				<PhoneOff size={60} />
			{:else}
				<Calendar size={60} />
			{/if}
			<p>{t('events.feed.empty', { type })}</p>
		</div>
	{/snippet}
</InfiniteScrollContainer>
