// platform/svelte/src/lib/components/core/post/pieces/ParticipantsCard.svelte
<script lang="ts">
	import type { JamState } from '@openpeeps/common/types';
	import AvatarFromId from '../../profile/AvatarFromId.svelte';

	interface Props {
		jamState: JamState;
		size?: number;
	}

	let { jamState, size = 1.5 }: Props = $props();
</script>

<div class="flex w-full justify-between gap-4 p-5">
	<div class="flex items-center">
		{#if jamState.participants.length > 2}
			{#each jamState.participants.slice(0, 2) as participant (participant)}
				<AvatarFromId containerClass="-mr-2" id={participant} borderless={true} {size} />
			{/each}
		{:else}
			{#each jamState.participants as participant (participant)}
				<AvatarFromId containerClass="-mr-2" id={participant} borderless={true} {size} />
			{/each}
		{/if}
	</div>
</div>

// platform/rn-components/src/components/post/pieces/ParticipantsCard.tsx
import { View } from 'react-native';
import React from 'react';
import type { JamState } from '@openpeepshq/common/types';
import { ProfileFromId } from '../../profile/ProfileFromId';

interface ParticipantsCardProps {
  jamState: JamState;
}

export const ParticipantsCard: React.FC<ParticipantsCardProps> = ({
  jamState,
}) => {
  return (
    <View className="flex w-full justify-between gap-4 p-5">
      <View className="flex items-center">
        {jamState.participants.length > 2 ? (
          <>
            {jamState.participants.slice(0, 2).map((participant) => (
              <>
                <ProfileFromId id={participant} />
              </>
            ))}
          </>
        ) : (
          <>
            {jamState.participants.map((participant) => (
              <>
                <ProfileFromId id={participant} />
              </>
            ))}
          </>
        )}
      </View>
    </View>
  );
};
