// platform/svelte/src/lib/components/core/post/pieces/PostInfoHeader.svelte
<script lang="ts">
	import type { PublicPost } from '@openpeeps/common/types';
	import { Avatar } from '../../profile';
	import PostMenu from './PostMenu.svelte';
	import DisplayUserNameBlock from '$lib/components/core/profile/DisplayUserNameBlock.svelte';
	import { UpdatingDate } from '@openpeeps/ui';

	interface Props {
		post: PublicPost;
		showMenu: boolean;
		deleteCallback?: () => void;
	}

	let { post, showMenu, deleteCallback = () => undefined }: Props = $props();
</script>

<div class="flex justify-between py-5">
	<div class="flex w-fit space-x-2">
		<a href={`/@${post.profile.handle}`}>
			<Avatar profile={post?.profile} size={4} />
		</a>
		<div class="flex flex-col flex-wrap">
			<DisplayUserNameBlock profile={post.profile} />
			<span class="text-sm font-extralight">
				<UpdatingDate date={post.createdAt} />
			</span>
		</div>
	</div>
	{#if showMenu}
		<PostMenu {post} {deleteCallback} />
	{/if}
</div>

// platform/rn-components/src/components/post/pieces/PostInfoHeader.tsx
import React from 'react';
import { TouchableOpacity } from 'react-native';
import { UpdatingDate } from '../../custom/date/updating-date';
import { PostMenu } from './PostMenu';
import { type PublicPost } from '@openpeepshq/common';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { MainStackParamList } from '~/components/navigation/types';
import { ProfileAvatar } from '../../profile/Avatar';
import { ProfileHandle, ProfileName } from '../../profile/ProfilePieces';
import { ThemedView } from '~/components/ui/themed-view';

interface PostHeaderProps {
  post: PublicPost;
  showMenu?: boolean;
  deleteCallback?: () => void;
}

export const PostInfoHeader = ({
  post,
  showMenu = true,
  deleteCallback,
}: PostHeaderProps) => {
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  return (
    <ThemedView className="flex-row mt-3 mb-5 px-5 justify-between items-center">
      <ThemedView className="flex-row gap-3">
        <TouchableOpacity
          onPress={() =>
            navigation.navigate('Profile', {
              handle: post.profile.handle as string,
            })
          }
        >
          <ProfileAvatar profile={post.profile} className="size-14" />
        </TouchableOpacity>
        <ThemedView>
          <ProfileName profile={[post.profile]} />
          <ProfileHandle profile={[post.profile]} />
          <UpdatingDate date={post.createdAt as string} />
        </ThemedView>
      </ThemedView>
      {showMenu && <PostMenu post={post} deleteCallback={deleteCallback} />}
    </ThemedView>
  );
};
