// platform/rn-components/src/components/groups/GroupFeed.tsx
import React from 'react';
import type { GroupWithMeta } from '@openpeepshq/common/types';
import { useFeedListParams, useOpenpeeps } from '@openpeepshq/react';
import { Feed } from '~/components/post/Feed';

export interface GroupFeedProps {
  group: GroupWithMeta;
}

export const GroupFeed = ({ group }: GroupFeedProps) => {
  const { openpeepsApi } = useOpenpeeps();
  const query = openpeepsApi.usePostsByGroup(
    group.id,
    useFeedListParams({ limit: 15 })
  );

  return (
    <Feed
      query={query}
      inGroup
      pinnedPostId={group.pinnedPostId}
      isPostFeed={false}
    />
  );
};

// platform/svelte/src/lib/components/core/groups/GroupFeed.svelte
<script lang="ts">
  import type { GroupWithMeta } from '@openpeeps/common/types';
  import { Feed } from '$lib/components/core/post';
  import { infiniteGroupFeedStore } from '$lib/api';
  import { getCurrentProfile } from '$lib/auth';
  import { NewNoteButton } from '$lib/components/navigation';

  const currentProfile = getCurrentProfile();

  interface Props {
    group: GroupWithMeta;
  }

  let { group }: Props = $props();

  let query = infiniteGroupFeedStore(group.id, { limit: 15 });
</script>

<NewNoteButton visibility="group" {currentProfile} {group} />
<Feed {query} inGroup pinnedPostId={group.pinnedPostId} />
