// platform/svelte/src/lib/components/core/notification/NotificationWrapper.svelte
<script lang="ts">
	import { Avatar } from '$lib/components/core/profile';
	import type { Profile, ProfileStats } from '@openpeeps/common/types';
	import { User, Users, Dot } from 'lucide-svelte';
	import type { Snippet } from 'svelte';

	interface Props {
		profile: Profile & { profileStats: ProfileStats };
		seen?: boolean;
		isGroup?: string;
		showProfile?: boolean;
		children: Snippet;
	}

	let { profile, isGroup, seen = true, showProfile = true, children }: Props = $props();
</script>

<div class="w-full items-start gap-3 overflow-hidden border-b px-4 py-5 hover:bg-surface-300">
	<div class="flex justify-end">
		{#if !seen}
			<Dot class="h-3 w-3" />
		{/if}
	</div>
	{#if showProfile}
		<div class="flex-shrink-0">
			<div class="flex items-center gap-4 px-6">
				{#if isGroup}
					<Users class="h-8 w-8 text-surface-500" />
				{:else}
					<User class="h-8 w-8 text-surface-500" />
				{/if}
				<a href={`/@${profile?.handle}`}>
					<Avatar {profile} size={4} />
				</a>
			</div>
		</div>
	{/if}

	<div class="flex flex-1 flex-col">
		<div class="flex w-full items-start justify-between">
			<div class="flex-1">
				{@render children()}
			</div>
		</div>
	</div>
</div>

// platform/react/src/components/notifications/NotificationWrapper.tsx
import type { ReactNode } from 'react';
import { Dot, User, Users } from 'lucide-react';
import type { PublicProfile } from '@openpeeps/common/types';
import { Avatar } from '../profile';

export interface NotificationWrapperProps {
  profile: PublicProfile;
  seen?: boolean;
  isGroup?: boolean;
  showProfile?: boolean;
  children: ReactNode;
}

export function NotificationWrapper({
  profile,
  seen = true,
  isGroup = false,
  showProfile = true,
  children,
}: NotificationWrapperProps) {
  return (
    <div className="hover:bg-surface-300 w-full items-start gap-3 overflow-hidden border-b px-4 py-5">
      <div className="flex justify-end">{!seen ? <Dot className="h-3 w-3" /> : null}</div>
      {showProfile ? (
        <div className="flex items-center gap-4 px-6">
          {isGroup ? (
            <Users className="text-surface-500 h-8 w-8" />
          ) : (
            <User className="text-surface-500 h-8 w-8" />
          )}
          <a href={`/@${profile.handle}`}>
            <Avatar profile={profile} size={3.5} />
          </a>
        </div>
      ) : null}
      <div className="flex flex-1 flex-col">{children}</div>
    </div>
  );
}
