// platform/rn-components/src/components/conversations/MessageInThread.tsx
import React from 'react';
import { View } from 'react-native';
import { useTranslation } from 'react-i18next';
import type { PublicPost, PublicProfile } from '@openpeepshq/common/types';
import { profileName } from '@openpeepshq/common';
import { isUnreadPostForViewer, useCurrentProfile } from '@openpeepshq/react';
import { UpdatingDate } from '~/components/custom/date/updating-date';
import { ProfileAvatar } from '~/components/profile/Avatar';
import { ThemedText } from '~/components/ui/themed-text';
import { usePostViewRef } from '~/hooks/use-post-view-ref';
import { ConversationMessageBubble } from './ConversationMessageBubble';

const inAudience = (post: PublicPost, profile: PublicProfile) =>
  !!post.audience?.some((p) => p.id === profile.id);

const audienceDiff = (
  previous: PublicPost | undefined,
  message: PublicPost
) => {
  const before = previous?.audience ?? [];
  const after = message.audience ?? [];
  return {
    added: after.filter((p) => !before.some((b) => b.id === p.id)),
    removed: before.filter((p) => !after.some((a) => a.id === p.id)),
  };
};

const AvatarRow = ({ profiles }: { profiles: PublicProfile[] }) => (
  <View className="flex-row -space-x-2">
    {profiles.map((p) => (
      <ProfileAvatar key={p.id} profile={p} className="size-10" />
    ))}
  </View>
);

export interface MessageInThreadProps {
  previous: PublicPost | undefined;
  message: PublicPost;
  multipleParticipants?: boolean;
  conversationRootId?: string;
}

export const MessageInThread = ({
  previous,
  message,
  multipleParticipants = true,
  conversationRootId,
}: MessageInThreadProps) => {
  const { t } = useTranslation();
  const me = useCurrentProfile();
  const isUnread = isUnreadPostForViewer(message, me?.id);
  const postViewRef = usePostViewRef(message.id, {
    conversationRootId,
    adjustUnread: isUnread,
  });
  const { added, removed } = audienceDiff(previous, message);
  // The author leaving their own conversation is shown via the "left" label
  // below, so exclude them from the "removedBy" avatars to avoid redundancy.
  const removedOthers = removed.filter((p) => p.id !== message.profile.id);
  const name = profileName(message.profile);
  const isMe = message.profile.id === me?.id;

  return (
    <>
      {!previous ? (
        <ThemedText className="mt-2 w-full text-center text-sm">
          {message.inReplyToId
            ? t('conversations.messageInThread.addedBy', { name })
            : t('conversations.messageInThread.startedBy', { name })}
        </ThemedText>
      ) : null}

      {previous &&
      inAudience(previous, message.profile) &&
      !inAudience(message, message.profile) ? (
        <View className="flex-row items-center gap-2">
          <ProfileAvatar profile={message.profile} className="size-10" />
          <ThemedText>
            {t('conversations.messageInThread.left', { name })}
          </ThemedText>
        </View>
      ) : null}

      {previous && added.length > 0 ? (
        <View className="flex-row items-center gap-2">
          <AvatarRow profiles={added} />
          <ThemedText>
            {t('conversations.messageInThread.addedBy', { name })}
          </ThemedText>
        </View>
      ) : null}

      {removedOthers.length > 0 ? (
        <View className="flex-row items-center gap-2">
          <AvatarRow profiles={removedOthers} />
          <ThemedText>
            {t('conversations.messageInThread.removedBy', { name })}
          </ThemedText>
        </View>
      ) : null}

      <View ref={postViewRef} className="flex-row">
        {!isMe && multipleParticipants ? (
          <View className="mr-2 mt-6">
            <ProfileAvatar profile={message.profile} className="size-10" />
          </View>
        ) : null}
        <View className="min-w-0 flex-1">
          <ConversationMessageBubble message={message} unread={isUnread} />
        </View>
      </View>

      <View
        className={`mt-2 w-full flex-row text-sm ${
          isMe ? 'justify-end' : 'justify-start'
        }`}
      >
        {multipleParticipants && !isMe ? (
          <ThemedText className="text-sm">{name} · </ThemedText>
        ) : null}
        <UpdatingDate date={message.createdAt} />
      </View>
    </>
  );
};

// platform/svelte/src/lib/components/core/conversations/MessageInThread.svelte
<script lang="ts">
	import type { PublicPost } from '@openpeeps/common/types';
	import { me } from '$lib/api';
	import { inAudience, audienceDiff } from './helpers';
	import { Avatar } from '../profile';
	import { profileName } from '@openpeeps/common/lib';
	import { ParticipantsCard } from '$lib/components';
	import { Message } from '.';
	import { UpdatingDate } from '@openpeeps/ui';
	import { i18nContext } from '$lib/components/i18n';
	import { postViewCounter } from '$lib/utils';

	const { t } = i18nContext();

	interface Props {
		previous: PublicPost | undefined;
		message: PublicPost;
		multipleParticipants?: boolean;
	}

	let { previous, message, multipleParticipants = true }: Props = $props();

	const participantChanges = audienceDiff(previous, message);
</script>

{#if !previous}
	{#if !message.inReplyToId}
		<div class="mt-2 w-full text-center text-sm">
			{t('conversations.messageInThread.startedBy', { name: profileName(message.profile) })}
		</div>
	{:else}
		<div class="mt-2 w-full text-center text-sm">
			{t('conversations.messageInThread.addedBy', { name: profileName(message.profile) })}
		</div>
	{/if}
{/if}

{#if previous && inAudience(previous, message.profile) && !inAudience(message, message.profile)}
	<div>
		<Avatar
			profile={message.profile}
			borderless
			containerClass="inline-block"
			size={2.5}
			navigate
		/>
		{t('conversations.messageInThread.left', { name: profileName(message.profile) })}
	</div>
{/if}

{#if previous && participantChanges.added.length}
	<div>
		<ParticipantsCard participants={participantChanges.added} navigate />
		{t('conversations.messageInThread.addedBy', { name: profileName(message.profile) })}
	</div>
{/if}

{#if participantChanges.removed.length}
	<div>
		<ParticipantsCard participants={participantChanges.removed} navigate />
		{t('conversations.messageInThread.removedBy', { name: profileName(message.profile) })}
	</div>
{/if}

<div class="flex" use:postViewCounter={message.id}>
	{#if message.profile.id !== $me?.id && multipleParticipants}
		<Avatar containerClass="mt-6 mr-2" profile={message.profile} navigate />
	{/if}
	<Message {message} />
</div>

<div
	class="mt-2 w-full text-sm
{message.profile.id === $me?.id ? 'text-right' : 'text-left'}
"
>
	{#if multipleParticipants && message.profile.id !== $me?.id}
		{profileName(message.profile)} &middot;
	{/if}
	<UpdatingDate date={message.createdAt} />
</div>
