// platform/web/src/pages/admin/components/RestoreTestBackupModal.tsx
import { useState } from 'react';
import { useT, useOpenpeeps } from '@openpeeps/react';
import {
  Button,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@openpeeps/react-ui';

export interface RestoreTestBackupModalProps {
  onClose: () => void;
}

export function RestoreTestBackupModal({
  onClose,
}: RestoreTestBackupModalProps) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const restoreBackup = openpeepsApi.admin.restoreBackupAction();
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async () => {
    setError(null);
    setSubmitting(true);
    try {
      const name = 'test-backup.zip';
      const response = await fetch(`/template/${name}`);
      const blob = await response.blob();
      const file = new File([blob], name, { type: 'application/zip' });
      await restoreBackup(file);
      onClose();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>
            {t('admin.backups.testRestore.title', {
              defaultValue: 'Restore test data',
            })}
          </DialogTitle>
        </DialogHeader>
        <p className="px-1 text-sm">
          {t('admin.backups.testRestore.confirm', {
            defaultValue:
              'This will restore sample test data into the community. Are you sure?',
          })}
        </p>
        {error ? (
          <p className="border-error/40 text-error rounded-md border p-2 text-sm">
            {error}
          </p>
        ) : null}
        <DialogFooter>
          <Button variant="variant-ringed-primary" action={onClose}>
            {t('admin.backups.testRestore.cancel', { defaultValue: 'Cancel' })}
          </Button>
          <Button
            variant="variant-filled-primary"
            action={submit}
            disabled={submitting}
          >
            {t('admin.backups.testRestore.continue', {
              defaultValue: 'Continue',
            })}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// platform/svelte/src/lib/components/core/backups/RestoreTestBackupModal.svelte
<script lang="ts">
	import { getModalStore, getToastStore } from '@skeletonlabs/skeleton';
	import { toast } from '$lib/utils/toast';
	import { Button } from '@openpeeps/ui';
	import { restoreBackupMutation } from '$lib/api';
	import { ModalFooter, ModalHeader, ModalWrapper } from '@openpeeps/ui';
	import { i18nContext } from '$lib/components/i18n';

	const { t } = i18nContext();
	const restoreBackup = restoreBackupMutation();

	const toastStore = getToastStore();
	const modalStore = getModalStore();

	const handleRestoreBackup = async () => {
		const name = 'test-backup.zip';
		const response = await fetch(`/template/${name}`);
		const blob = await response.blob();
		const file = new File([blob], name, { type: 'application/zip' });

		await restoreBackup(file)
			.then(() => {
				toastStore.trigger(
					toast({
						message: t('admin.backups.testRestore.restoreSuccess'),
						background: 'variant-filled-success'
					})
				);
			})
			.catch(() => {
				toastStore.trigger(
					toast({
						message: t('admin.backups.testRestore.restoreError'),
						background: 'variant-filled-error'
					})
				);
			})
			.finally(() => {
				modalStore.close();
			});
	};
</script>

{#if $modalStore[0]}
	<ModalWrapper>
		<ModalHeader title={t('admin.backups.testRestore.title')} />
		<article class="flex flex-col p-4">
			<div class="mt-4 w-full">{t('admin.backups.testRestore.confirm')}</div>
		</article>
		<ModalFooter>
			<div class="flex w-full justify-between">
				<Button title={t('admin.backups.testRestore.cancel')} variant="variant-ghost-primary" action={modalStore.close}
					>{t('admin.backups.testRestore.cancel')}</Button
				>
				<Button title={t('admin.backups.testRestore.continue')} variant="variant-filled-primary" action={handleRestoreBackup}>
					{t('admin.backups.testRestore.continue')}
				</Button>
			</div>
		</ModalFooter>
	</ModalWrapper>
{/if}
