// platform/web/src/pages/admin/components/RestoreBackupModal.tsx
import { useState } from 'react';
import { useT, useOpenpeeps } from '@openpeeps/react';
import {
  Button,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@openpeeps/react-ui';

export interface RestoreBackupModalProps {
  onClose: () => void;
}

export function RestoreBackupModal({ onClose }: RestoreBackupModalProps) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const restoreBackup = openpeepsApi.admin.restoreBackupAction();
  const [file, setFile] = useState<File | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async () => {
    if (!file) {
      setError(
        t('admin.backups.restore.selectFile', { defaultValue: 'Select File' }),
      );
      return;
    }
    setError(null);
    setSubmitting(true);
    try {
      await restoreBackup(file);
      onClose();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>
            {t('admin.backups.restore.title', {
              defaultValue: 'Restore backup',
            })}
          </DialogTitle>
        </DialogHeader>
        <div className="px-1">
          <input
            type="file"
            accept=".zip"
            className="w-full rounded-md border p-2 text-sm"
            onChange={(e) => setFile(e.target.files?.item(0) ?? null)}
          />
        </div>
        {error ? (
          <p className="border-error/40 text-error rounded-md border p-2 text-sm">
            {error}
          </p>
        ) : null}
        <DialogFooter>
          <Button variant="variant-ringed-primary" action={onClose}>
            {t('admin.backups.restore.cancel', { defaultValue: 'Cancel' })}
          </Button>
          <Button
            variant="variant-filled-primary"
            action={submit}
            disabled={!file || submitting}
          >
            {t('admin.backups.restore.confirm', { defaultValue: 'Confirm' })}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// platform/svelte/src/lib/components/core/backups/RestoreBackupModal.svelte
<script lang="ts">
  import { getModalStore, getToastStore } from '@skeletonlabs/skeleton';
  import { toast } from '$lib/utils/toast';
  import { Button } from '@openpeeps/ui';
  import { restoreBackupMutation } from '$lib/api';
  import { ModalFooter, ModalHeader, ModalWrapper } from '@openpeeps/ui';
  import { i18nContext } from '@openpeeps/svelte/components/i18n';

  const restoreBackup = restoreBackupMutation();

  let zipFile: FileList | null = $state(null);
  // ------------ STORES --------------
  const toastStore = getToastStore();
  const modalStore = getModalStore();
  const { t } = i18nContext();

  // ------------ MUTATIONS ---------------

  const handleRestoreBackup = async () => {
    if (!zipFile) {
      toastStore.trigger(
        toast({
          message: t('admin.backups.restore.selectFile'),
          background: 'variant-filled-error',
        }),
      );
      return;
    }

    await restoreBackup(zipFile.item(0) as File)
      .then(() => {
        toastStore.trigger(
          toast({
            message: t('admin.backups.restore.success'),
            background: 'variant-filled-success',
          }),
        );
      })
      .catch(() => {
        toastStore.trigger(
          toast({
            message: t('admin.backups.restore.error'),
            background: 'variant-filled-error',
          }),
        );
      })
      .finally(() => {
        modalStore.close();
      });
  };
</script>

{#if $modalStore[0]}
  <ModalWrapper>
    <ModalHeader title={t('admin.backups.restore.title')} />

    <article class="flex flex-col p-4">
      <div class="mt-4 w-full">
        <input
          type="file"
          accept=".zip"
          class="w-full border border-neutral-500 py-4"
          bind:files={zipFile}
        />
      </div>
    </article>
    <ModalFooter>
      <div class="flex gap-x-2">
        <Button
          title={t('admin.backups.restore.cancel')}
          variant="variant-filled-primary"
          action={modalStore.close}>{t('admin.backups.restore.cancel')}</Button
        >
        <Button
          title={t('admin.backups.restore.confirm')}
          variant="variant-filled-primary"
          disabled={!zipFile}
          action={handleRestoreBackup}
        >
          {t('admin.backups.restore.confirm')}
        </Button>
      </div>
    </ModalFooter>
  </ModalWrapper>
{/if}
