// platform/server/src/emails/notifications/repost/Email.tsx
import {
  Button,
  Container,
  Img,
  Section,
  Text,
} from '@react-email/components';
import type {
  EmailGlobals,
  PublicPost,
  PublicProfile,
} from '@openpeeps/common/types';
import {
  getProfileAvatar,
  profileName,
  truncateText,
} from '@openpeeps/common/lib';

import { BaseEmailLayout } from '../../BaseEmailLayout';
import { emailStyles } from '../../styles';

interface Locals {
  senderProfile: PublicProfile;
  recipientProfile: PublicProfile;
  post: PublicPost;
}

export const RepostEmail = ({
  globals,
  locals,
}: {
  globals: EmailGlobals;
  locals: Locals;
}) => {
  const { t } = globals.i18nContext;

  return (
    <BaseEmailLayout
      globals={globals}
      previewText={t('emails.reaction.body', {
        profileName: profileName(locals.senderProfile),
      })}
      showGreeting
      recipientProfile={locals.recipientProfile}
    >
      <Text style={emailStyles.heading}>
        {t('emails.reaction.body', {
          profileName: profileName(locals.senderProfile),
        })}
      </Text>
      {locals.post?.data?.content && (
        <Container style={emailStyles.infoContainer}>
          <Img
            src={getProfileAvatar(
              locals.senderProfile,
              globals.communityConfig,
            )}
            alt={profileName(locals.recipientProfile) || ''}
            style={emailStyles.avatar}
            width="50"
            height="50"
          />
          <Container style={emailStyles.messageCard}>
            <Container>
              <Text style={emailStyles.username}>
                {profileName(locals.recipientProfile)}
              </Text>
              <Text style={emailStyles.handle}>
                @{locals.recipientProfile.handle}
              </Text>
            </Container>
            <Text>{truncateText(locals.post.data.content, 100)}</Text>
          </Container>
        </Container>
      )}
      <Section style={emailStyles.ctaContainer}>
        <Button
          href={`${globals.serverData.rootUrl}/posts/${locals.post.id}`}
          style={emailStyles.button}
        >
          {t('emails.repost.cta')}
        </Button>
      </Section>
    </BaseEmailLayout>
  );
};

// platform/svelte/src/lib/components/notifications/defaultNotifications/reply/Email.svelte
<script lang="ts">
	import type { EmailGlobals, PublicPost, PublicProfile } from '@openpeeps/common/types';
	import { Button, Container, Img, Link, Section, Text } from '@openpeeps/svelte5-email';
	import BaseEmailLayout from '../../../layout/BaseEmailLayout.svelte';
	import { emailStyles } from '$lib/components/styles';
	import { getProfileAvatar, profileName, truncateText } from '@openpeeps/common/lib';

	interface Props {
		globals: EmailGlobals;
		locals: {
			senderProfile: PublicProfile;
			post: PublicPost;
			recipientProfile: PublicProfile;
			data: {
				replyPost: PublicPost;
			};
		};
	}

	let { globals, locals }: Props = $props();
	const { t } = globals.i18nContext;
</script>

<BaseEmailLayout
	{globals}
	previewText={t('emails.reply.body', {
		profileName: profileName(locals.senderProfile)
	})}
	showLogo={true}
	showGreeting={true}
	showAppLinks={true}
	showFooter={true}
>
	<Text style={emailStyles.heading}>
		{t('emails.reply.body', {
			profileName: profileName(locals.senderProfile)
		})}</Text
	>
	{#if locals.post?.data?.content}
		<Container style={emailStyles.infoContainer}>
			<Img
				src={getProfileAvatar(locals.senderProfile, globals.communityConfig)}
				alt={profileName(locals.senderProfile) || ''}
				style={emailStyles.avatar}
				width="50"
				height="50"
			/>
			<Container style={emailStyles.messageCard}>
				<Container>
					<Text style={emailStyles.username}>{profileName(locals.senderProfile)}</Text>
					<Text style={emailStyles.handle}>@{locals.senderProfile.handle}</Text>
				</Container>
				<Text>
					{truncateText(locals.data.replyPost.data.content, 30)}
				</Text>
			</Container>
		</Container>
	{/if}
	<Section style={emailStyles.ctaContainer}>
		<Button
			href="{globals.serverData.rootUrl}/posts/{locals.data.replyPost.id}"
			style={emailStyles.button}
		>
			{t('emails.reply.cta')}
		</Button>
	</Section>
</BaseEmailLayout>
