// libraries/react-ui/src/components/date/StopWatch.tsx
import * as React from 'react';
import { stopWatchFormatter } from './formatter';

export interface StopWatchProps {
  start: string | Date | number;
  formatter?: (duration: number) => string;
  intervalMs?: number;
}

export function StopWatch({
  start,
  formatter = stopWatchFormatter,
  intervalMs = 1000,
}: StopWatchProps) {
  const [text, setText] = React.useState(() =>
    formatter(Date.now() - new Date(start).getTime()),
  );

  React.useEffect(() => {
    setText(formatter(Date.now() - new Date(start).getTime()));
    const handle = setInterval(() => {
      setText(formatter(Date.now() - new Date(start).getTime()));
    }, intervalMs);
    return () => clearInterval(handle);
  }, [start, formatter, intervalMs]);

  return <>{text}</>;
}

// libraries/ui/src/lib/date/StopWatch.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { stopWatchFormatter } from './formatter';

  interface Props {
    start: string | Date | number;
    formatter?: (duration: number) => string;
  }

  let { start, formatter = stopWatchFormatter }: Props = $props();

  let formattedTimespan = $state(
    formatter(Date.now() - new Date(start).getTime()),
  );

  onMount(() => {
    setInterval(() => {
      formattedTimespan = formatter(Date.now() - new Date(start).getTime());
    }, 1000);
  });
</script>

{formattedTimespan}
