// platform/react-native/src/components/custom/date/updating-date.tsx
import React, {useEffect} from 'react';
import {dateFormatter} from './formatter';
import {ThemedText} from '../../ui/themed-text';

interface UpdatingDateProps {
  date: string | Date | number;
  formatter?: (date: string | Date | number) => string;
}

export const UpdatingDate = ({
  date,
  formatter = dateFormatter,
}: UpdatingDateProps) => {
  const [formattedDate, setFormattedDate] = React.useState(formatter(date));

  useEffect(() => {
    const interval = setInterval(() => {
      setFormattedDate(formatter(date));
    }, 60000);
    return () => clearInterval(interval);
  }, [date, formatter]);

  return <ThemedText className="">{formattedDate}</ThemedText>;
};

// libraries/ui/src/lib/date/UpdatingDate.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { dateFormatter } from './formatter';

	interface Props {
		date: string | Date | number;
		formatter?: (date: string | Date) => string;
	}

	let { date, formatter = dateFormatter }: Props = $props();

	let formattedDate = $state(formatter(date as string));

	onMount(() => {
		setInterval(() => {
			formattedDate = formatter(date as string);
		}, 60000);
	});
</script>

{formattedDate}
