// platform/web/src/pages/feeds/Bookmarks.tsx
import { useT, useOpenpeeps, useSetPageHeader } from '@openpeeps/react';
import { Feed } from '@openpeeps/react/components';

export function FeedsBookmarks() {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();

  const query = openpeepsApi.useBookmarkedPosts({ limit: 15 });

  useSetPageHeader(t('navigation.bookmarks', { defaultValue: 'Bookmarks' }));

  return (
    <div className="space-y-4 p-4">
      <Feed query={query} />
    </div>
  );
}

// platform/app/src/routes/(protected)/(private)/feeds/bookmarks/+page.svelte
<script lang="ts">
  import { Feed } from '@openpeeps/svelte/components';
  import { infiniteBookmarkedPostsStore } from '@openpeeps/svelte/api';
  import { i18nContext } from '@openpeeps/svelte/components';
  import { setPageHeader } from '@openpeeps/svelte/stores';
  const { t } = i18nContext();

  const query = infiniteBookmarkedPostsStore({ limit: 15 });
  setPageHeader({ title: t('navigation.bookmarks') });
</script>

<Feed {query} />
