// platform/svelte/src/lib/components/core/configuration/server-configuration/ConfigurationTree.svelte
<script lang="ts">
  import { z, ZodObject, type ZodRawShape } from 'zod';
  import { getToastStore, TreeView } from '@skeletonlabs/skeleton';
  import { ConfigurationCategory } from '..';
  import { updateConfigMutation, testPaymentMutation } from '$lib/api';
  import { Button } from '@openpeeps/ui';
  import {
    diffConfigTrees,
    equal,
  } from '$lib/components/core/configuration/helpers';
  import { toast } from '$lib/utils/toast';
  import { hasValue } from '@openpeeps/common';
  import { i18nContext } from '$lib/components/i18n';

  interface Props {
    schema: ZodObject<ZodRawShape>;
    config: z.infer<typeof schema>;
    defaults: z.infer<typeof schema>;
    namespace: string;
    name: string;
    onUpdate?: () => void;
  }

  let {
    schema,
    config,
    defaults,
    namespace,
    name,
    onUpdate = () => {},
  }: Props = $props();

  const updateConfig = updateConfigMutation({ namespace, name });
  const testPayment = testPaymentMutation();

  const toastStore = getToastStore();

  let value: z.infer<typeof schema> | undefined = $state();

  const { t } = i18nContext();

  const handleSubmit = async () => {
    const data = diffConfigTrees(config, value!);
    const paidMembership = data?.payments?.stripe?.paidMembership?.enabled;
    const enabled =
      paidMembership === undefined &&
      config?.payments?.stripe?.paidMembership?.enabled;
    if (hasValue(data?.payments?.stripe) && enabled) {
      const { success, key } = await testPayment({
        ...data.payments.stripe,
        paidMembership: {
          ...config.payments.stripe.paidMembership,
          ...data.payments.stripe.paidMembership,
          enabled,
        },
      });
      if (!success) {
        toastStore.trigger(
          toast({
            message: t(key!),
            background: 'variant-filled-error',
            autohide: true,
          }),
        );
        return;
      }
    }
    await updateConfig({
      config: data,
    });
    onUpdate();
  };
</script>

<div class="mb-20 h-full">
  <TreeView indent="ml-4" open>
    <ConfigurationCategory bind:value {schema} {config} {defaults} />
  </TreeView>

  <span class="mt-4 flex justify-end">
    <Button
      title={t('common.submit')}
      disabled={equal(config, value!)}
      action={handleSubmit}
      variant="variant-filled-primary"
    >
      {t('common.submit')}
    </Button>
  </span>
</div>

// platform/react/src/components/configuration/ConfigurationTree.tsx
import { useEffect, useMemo, useState } from 'react';
import { ZodObject, type ZodRawShape } from 'zod';
import { Button } from '@openpeeps/react-ui';
import { useT } from '../../i18n';
import type { ConfigTree } from '@openpeeps/common/types';
import { diffConfigTrees, equal } from '../../lib/configuration/helpers';
import { ConfigurationCategory } from './ConfigurationCategory';

export interface ConfigurationTreeProps {
  schema: ZodObject<ZodRawShape>;
  config: Record<string, unknown>;
  defaults: Record<string, unknown>;
  onSave: (patch: Record<string, unknown>) => Promise<void>;
}

export function ConfigurationTree({
  schema,
  config,
  defaults,
  onSave,
}: ConfigurationTreeProps) {
  const t = useT();
  const [value, setValue] = useState<Record<string, unknown>>(() =>
    structuredClone(config),
  );

  useEffect(() => {
    setValue(structuredClone(config));
  }, [config]);

  const unchanged = useMemo(
    () => equal(config as ConfigTree, value as ConfigTree),
    [config, value],
  );

  const handleSubmit = async () => {
    const data = diffConfigTrees(config as ConfigTree, value as ConfigTree);
    await onSave(data);
  };

  return (
    <div className="mb-20 h-full">
      <ConfigurationCategory
        schema={schema}
        config={config}
        defaults={defaults}
        value={value}
        onChange={setValue}
        collapsible={false}
      />
      <div className="mt-4 flex justify-end">
        <Button
          title={t('common.submit', { defaultValue: 'Submit' })}
          variant="variant-filled-primary"
          disabled={unchanged}
          action={handleSubmit}
        >
          {t('common.submit', { defaultValue: 'Submit' })}
        </Button>
      </div>
    </div>
  );
}
