// platform/react/src/components/registry/ErrorComponent.tsx
import { Ban } from 'lucide-react';

export interface ErrorComponentProps {
  componentKey: string;
  registry: Map<string, unknown>;
  showError?: boolean;
}

export function ErrorComponent({
  componentKey,
  showError = true,
}: ErrorComponentProps) {
  if (!showError) return null;
  return (
    <div className="border-error bg-error/10 text-error flex w-full items-start gap-3 rounded border p-4">
      <div>
        <Ban />
      </div>
      <div>
        <h3 className="text-lg font-bold">Component not found</h3>
        <p className="w-full text-wrap">
          Component "{componentKey}" not found in registry
        </p>
      </div>
    </div>
  );
}

// platform/svelte/src/lib/components/registry/ErrorComponent.svelte
<script lang="ts">
	import { Ban } from 'lucide-svelte';
	import type { Component } from 'svelte';
	interface Props {
		key: string;
		registry: Map<string, Component<any>>;
		showError?: boolean;
	}

	let { key, registry, showError = true }: Props = $props();
</script>

{#if showError}
	<div class="alert variant-filled-error w-full">
		<!-- Icon -->
		<div><Ban /></div>
		<!-- Message -->
		<div class="alert-message">
			<h3 class="h3">Component not found</h3>
			<p class="w-full text-wrap">Component "{key}" not found in registry</p>
		</div>
	</div>
{/if}
