// libraries/ui/src/lib/popup-menu/PopupMenuButton.svelte
<script lang="ts">
	import { Loader } from 'lucide-svelte';
	import type { Snippet } from 'svelte';
	import type { IconType } from '$lib';
	import { preventDefault, stopPropagation } from '$lib';

	interface Props {
		action: string | (() => Promise<unknown> | unknown);
		text?: string;
		loadingText?: string;
		icon?: IconType;
		danger?: boolean;
		compact?: boolean;
		title?: string;
		textSnippet?: Snippet;
	}
	let {
		action,
		text = '',
		loadingText = '',
		icon: Icon = undefined,
		danger = false,
		compact = false,
		title = '',
		textSnippet = undefined
	}: Props = $props();

	let isLoading = $state(false);

	const buttonClass =
		'w-full flex p-2 hover:bg-surface-hover-token rounded items-center gap-x-2 text-left';
</script>

{#snippet content()}
	{#if isLoading}
		<Loader size={16} class="flex-0" />
		{#if !compact}
			<span>{loadingText || text}</span>
		{/if}
	{:else}
		{#if Icon}
			<Icon size={16} class="flex-shrink-0" />
		{/if}
		{#if !compact}
			{#if textSnippet}
				{@render textSnippet()}
			{:else}
				<span class="text-left">{text}</span>
			{/if}
		{/if}
	{/if}
{/snippet}

{#if typeof action === 'string'}
	<a
		{title}
		href={action}
		class={buttonClass}
		onclick={stopPropagation(() => {
			isLoading = true;
		})}
	>
		{@render content()}
	</a>
{:else}
	<button
		{title}
		class:text-error-600={danger}
		class:justify-center={compact}
		class={buttonClass}
		onclick={stopPropagation(
			preventDefault(async () => {
				isLoading = true;
				await action();
				isLoading = false;
			})
		)}
		disabled={isLoading}
	>
		{@render content()}
	</button>
{/if}

// libraries/react-ui/src/components/popup-menu/PopupMenuButton.tsx
import * as React from 'react';
import { Loader } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { ButtonAction, IconType } from '@/types';

export interface PopupMenuButtonProps {
  action: ButtonAction;
  text?: string;
  loadingText?: string;
  icon?: IconType;
  danger?: boolean;
  compact?: boolean;
  title?: string;
  textSlot?: React.ReactNode;
}

const baseClass =
  'flex w-full items-center gap-x-2 rounded-button p-2 text-left transition-colors hover:bg-surface disabled:opacity-60';

export function PopupMenuButton({
  action,
  text = '',
  loadingText = '',
  icon: Icon,
  danger = false,
  compact = false,
  title = '',
  textSlot,
}: PopupMenuButtonProps) {
  const [isLoading, setIsLoading] = React.useState(false);

  const content = isLoading ? (
    <>
      <Loader size={16} className="shrink-0" />
      {!compact && <span>{loadingText || text}</span>}
    </>
  ) : (
    <>
      {Icon && <Icon size={16} className="shrink-0" />}
      {!compact && (textSlot ?? <span className="text-left">{text}</span>)}
    </>
  );

  if (typeof action === 'string') {
    return (
      <a
        title={title}
        href={action}
        className={cn(
          baseClass,
          danger && 'text-error',
          compact && 'justify-center',
        )}
        onClick={(e) => {
          e.stopPropagation();
          setIsLoading(true);
        }}
      >
        {content}
      </a>
    );
  }

  return (
    <button
      type="button"
      title={title}
      disabled={isLoading}
      className={cn(
        baseClass,
        danger && 'text-error',
        compact && 'justify-center',
      )}
      onClick={async (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsLoading(true);
        try {
          await action();
        } finally {
          setIsLoading(false);
        }
      }}
    >
      {content}
    </button>
  );
}
