// platform/svelte/src/lib/components/core/profile/ProfileCard.svelte
<script lang="ts">
	import type { PublicProfile } from '@openpeeps/common/types';
	import FollowUnfollowButton from './FollowUnfollowButton.svelte';
	import { Avatar } from '.';
	import { profileName } from '@openpeeps/common/lib';

	interface Props {
		profile: PublicProfile;
		avatarSize?: number;
		showAction?: boolean;
		noPadding?: boolean;
		badges?: import('svelte').Snippet;
		action?: import('svelte').Snippet;
	}

	let {
		profile,
		avatarSize = 3.5,
		showAction = true,
		noPadding = false,
		badges,
		action
	}: Props = $props();
</script>

<div class="flex justify-between {noPadding ? '' : 'p-4'} w-full">
	<a href={`/@${profile.handle}`} class="flex items-center gap-x-2">
		<Avatar {profile} borderless size={avatarSize} />
		<div class="text-left">
			<h3 class="flex gap-2 text-lg font-semibold {avatarSize < 2 ? 'text-sm' : 'text-lg'}">
				<span>{profileName(profile)}</span>
				{@render badges?.()}
			</h3>
			<h3 class={avatarSize < 2 ? 'text-xs' : 'text-sm'}>@{profile.handle}</h3>
		</div>
	</a>
	{#if showAction}
		{#if action}{@render action()}{:else}
			<FollowUnfollowButton {profile} />
		{/if}
	{/if}
</div>

// platform/react/src/components/profile/ProfileCard.tsx
import type { PublicProfile } from '@openpeeps/common/types';
import { Avatar } from './Avatar';
import { FollowUnfollowButton } from './FollowUnfollowButton';

export interface ProfileCardProps {
  profile: PublicProfile;
  /**
   * When provided, the card acts as a selection control: clicking it calls
   * `onSelect` instead of navigating to the profile page. Used in selection
   * contexts such as starting a new conversation.
   */
  onSelect?: (profile: PublicProfile) => void;
  showAction?: boolean;
}

/**
 * Compact card listing one profile (used by search results / member lists).
 * Translation of `core/profile/ProfileCard.svelte`, including the
 * Follow/Unfollow action button.
 */
export function ProfileCard({ profile, onSelect, showAction = true }: ProfileCardProps) {
  const details = (
    <>
      <Avatar profile={profile} size={3} />
      <div className="flex min-w-0 flex-col">
        <span className="truncate text-sm font-semibold">
          {profile.displayName || `@${profile.handle}`}
        </span>
        <span className="truncate text-xs text-muted-foreground">
          @{profile.handle}
        </span>
        {profile.bio && (
          <span className="mt-1 line-clamp-2 text-sm text-muted-foreground">
            {profile.bio}
          </span>
        )}
      </div>
    </>
  );

  return (
    <div className="flex items-center justify-between gap-3 border-b p-4 hover:bg-surface-100">
      {onSelect ? (
        <button
          type="button"
          onClick={() => onSelect(profile)}
          className="flex min-w-0 flex-1 items-center gap-3 text-left"
        >
          {details}
        </button>
      ) : (
        <a
          href={`/@${profile.handle}`}
          className="flex min-w-0 flex-1 items-center gap-3"
        >
          {details}
        </a>
      )}
      {showAction && (
        <div className="flex-shrink-0">
          <FollowUnfollowButton profile={profile} compact />
        </div>
      )}
    </div>
  );
}
