// platform/react/src/pages/groups/New.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { GroupData, PublicProfile } from '@openpeepshq/common/types';
import { groupCapabilityTemplates } from '@openpeepshq/common/lib';
import { useT, useOpenpeeps, useSetPageHeader } from '../../index';
import {
  GroupForm,
  ProfilesInput,
  useCurrentProfile,
  useServerInfo,
} from '../../components';
import { Button, Label, Toast } from '@openpeepshq/react-ui';

export function NewGroup() {
  const t = useT();
  const navigate = useNavigate();
  const { openpeepsApi } = useOpenpeeps();
  const createGroup = openpeepsApi.createGroupAction();
  const { publicContent } = useServerInfo();
  const me = useCurrentProfile();
  const [members, setMembers] = useState<PublicProfile[]>([]);

  useSetPageHeader(
    t('groups.new.title', { defaultValue: 'Create group' }),
    undefined,
    'groups-create-page-title',
  );

  const [groupData, setGroupData] = useState<GroupData>(() => ({
    displayName: '',
    handle: '',
    description: '',
    rules: '',
    capabilities: publicContent
      ? groupCapabilityTemplates.defaultGroup.capabilities
      : groupCapabilityTemplates.defaultGroupClosedCommunity.capabilities,
  }));
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async () => {
    setError(null);
    let data = groupData;
    if (data.handle.length === 0) {
      if (!data.displayName) {
        setError(
          t('handle.validation.error', {
            defaultValue: 'A handle or display name is required',
          }),
        );
        return;
      }
      data = {
        ...data,
        handle: data
          .displayName!.toLowerCase()
          .replaceAll(' ', '_')
          .replace(/[^a-zA-Z0-9_]/g, '')
          .trim()
          .slice(0, 16),
      };
    }
    setSubmitting(true);
    try {
      const group = (await createGroup({
        ...data,
        members,
      })) as { handle: string };
      navigate(`/groups/@${group.handle}`);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="space-y-4 p-4 pb-12">
      <GroupForm groupData={groupData} onChange={setGroupData} />

      <div className="space-y-2 px-1">
        <Label htmlFor="group-members">
          {t('groups.form.members', { defaultValue: 'Members' })}
        </Label>
        <ProfilesInput
          value={members}
          onChange={setMembers}
          banlist={me ? [me] : []}
          placeholder={t('groups.form.membersPlaceholder', {
            defaultValue: 'Add members to this group',
          })}
        />
      </div>

      {error && (
        <Toast
          variant="error"
          testId="groups-duplicate-handle-error"
          onDismiss={() => setError(null)}
        >
          {error}
        </Toast>
      )}

      <Button
        title="Create group"
        variant="default"
        action={submit}
        disabled={submitting}
        data-testid="groups-create-submit"
      >
        {submitting
          ? t('common.submitting', { defaultValue: 'Creating…' })
          : t('common.submit', { defaultValue: 'Create group' })}
      </Button>
    </div>
  );
}

// platform/app/src/routes/(protected)/(conditionally-public)/groups/new/+page.svelte
<script lang="ts">
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { ProfileSelector } from '@openpeeps/svelte/components';
  import { type GroupData, type PublicProfile } from '@openpeeps/common/types';
  import { CreateGroupButton } from '@openpeeps/svelte/components';
  import { Label } from '@openpeeps/ui';
  import { GroupForm } from '@openpeeps/svelte/components';
  import { presetProps } from '@openpeeps/svelte/utils';
  import { createGroupMutation } from '@openpeeps/svelte/api';
  import { goto } from '$app/navigation';
  import type { Component } from 'svelte';
  import { toaster } from '@openpeeps/svelte/utils';
  import { i18nContext } from '@openpeeps/svelte/components';
  import { groupCapabilityTemplates } from '@openpeeps/common/lib';
  import { getServerInfo } from '@openpeeps/svelte/server';
  import { getCurrentProfile } from '@openpeeps/svelte/auth';

  const { t } = i18nContext();
  const toast = toaster();
  const me = getCurrentProfile();

  const { publicContent } = getServerInfo();

  const createGroup = createGroupMutation();

  let selectedMembersProfiles: PublicProfile[] = $state([]);

  let groupData: GroupData = $state({
    displayName: '',
    handle: '',
    description: '',
    rules: '',
    capabilities: publicContent
      ? groupCapabilityTemplates.defaultGroup.capabilities
      : groupCapabilityTemplates.defaultGroupClosedCommunity.capabilities,
  });

  const handleSubmit = async () => {
    if (groupData.handle.length === 0) {
      if (!groupData.displayName) {
        toast({ message: t('handle.validation.error'), type: 'error' });
        return;
      }
      groupData.handle = groupData.displayName
        .toLowerCase()
        .replaceAll(' ', '_')
        .replace(/[^a-zA-Z0-9_]/g, '')
        .trim()
        .slice(0, 16);
    }

    createGroup({
      ...groupData,
      members: selectedMembersProfiles,
    })
      .then((g) => goto(`/groups/@${g.handle}`))
      .catch((e) => toast({ message: t(e.message), type: 'error' }));
  };

  getPageHeaderStore().set({
    title: 'Create group',
    actions: presetProps(
      CreateGroupButton as Component<Record<string, unknown>>,
      { handleSubmit },
    ),
  });
</script>

<div class="pb-12">
  <GroupForm bind:groupData />
  <Label title="Members" classes="px-4 mt-4">
    <ProfileSelector bind:selectedProfiles={selectedMembersProfiles} profilesToExclude={[me]} />
  </Label>
</div>
