// platform/rn-components/src/components/notifications/types/JamSpeaker.tsx
import { View } from 'react-native';
import React from 'react';
import { ThemedText } from '~/components/ui/themed-text';
import { NotificationWrapper } from '../NotificationWrapper';
import { PublicNotification } from '@openpeepshq/common';
import { profileName } from '~/lib/utils';
import { UpdatingDate } from '../../custom/date/updating-date';
import { JamCard } from '../../jams/JamCard';
import { useTranslation } from 'react-i18next';

interface NotificationTypeProps {
  notification: PublicNotification;
}

export const JamSpeaker: React.FC<NotificationTypeProps> = ({
  notification,
}) => {
  const profile = notification.senderProfile!;
  const { t } = useTranslation();

  return (
    <NotificationWrapper profile={profile} seen={notification.seen}>
      <View className="w-full">
        <View className="flex w-full items-center justify-between">
          <View className="mb-2 flex flex-row items-center gap-2 font-semibold flex-wrap">
            <ThemedText>
              {t('notification.jamSpeaker.text', {
                profileName: profileName(profile),
              })}{' '}
            </ThemedText>
            <UpdatingDate date={notification.createdAt} />
          </View>
        </View>
        <JamCard jamPost={notification.post!} />
      </View>
    </NotificationWrapper>
  );
};

// platform/svelte/src/lib/components/core/notification/types/JamSpeaker.svelte
<script lang="ts">
	import type { ExpandedNotification } from '@openpeeps/common/types';
	import { profileName } from '@openpeeps/common/lib';
	import { UpdatingDate } from '@openpeeps/ui';
	import NotificationWrapper from '../NotificationWrapper.svelte';
	import CardEvent from '../../post/types/event/CardEvent.svelte';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		notification: ExpandedNotification;
	}

	let { notification }: Props = $props();
	const { t } = i18nContext();

	const profile = notification.senderProfile!;
</script>

<NotificationWrapper {profile} seen={notification.seen}>
	<div class="w-full px-4">
		<div class="flex w-full items-center justify-between">
			<p class="mb-2 flex items-center gap-2 text-sm font-semibold">
				{t('notification.jamSpeaker.text', {
					profileName: profileName(profile)
				})}{' '}
				<UpdatingDate date={notification.createdAt} />
			</p>
		</div>
		<CardEvent post={notification.post!} />
	</div>
</NotificationWrapper>
