// platform/react-native/src/components/custom/notification/types/jam-started.tsx
import { View } from 'react-native';
import React from 'react';
import { ThemedText } from '~/components/ui/themed-text';
import { NotificationWrapper } from '../NotificationWrapper';
import { PublicNotification } from '@openpeeps/common';
import { profileName } from '~/lib/utils';
import { UpdatingDate } from '../../date/updating-date';
import { JamCard } from '../../jam/jam-card';
import { useTranslation } from 'react-i18next';

interface NotificationTypeProps {
  notification: PublicNotification;
}
export const JamStarted: React.FC<NotificationTypeProps> = ({ notification }) => {
  const profile = notification.senderProfile!;
  const { t } = useTranslation();

  return (
    <NotificationWrapper profile={profile} seen={notification.seen}>
      <View className="w-full">
        <View className="mb-2 flex flex-row items-center gap-2 font-semibold text-wrap flex-wrap">
          <ThemedText>
            {t('notification.jamStarted.text', {
              profileName: profileName(profile),
            })}{' '}
          </ThemedText>
          <UpdatingDate date={notification.createdAt} />
        </View>
        {notification.post?.type === 'event' && (
          <JamCard
            jamPost={notification.post!} />
        )}
      </View>
    </NotificationWrapper>
  );
};

// platform/svelte/src/lib/components/core/notification/types/JamStarted.svelte
<script lang="ts">
	import type { ExpandedNotification } from '@openpeeps/common/types';
	import { liveJamsListStore } from '$lib/api';
	import { profileName } from '@openpeeps/common/lib';
	import { UpdatingDate } from '@openpeeps/ui';
	import NotificationWrapper from '../NotificationWrapper.svelte';
	import CardEvent from '../../post/types/event/CardEvent.svelte';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		notification: ExpandedNotification;
	}

	let { notification }: Props = $props();
	const { t } = i18nContext();

	const profile = notification.senderProfile!;
</script>

<NotificationWrapper {profile} seen={notification.seen}>
	<div class="w-full px-4">
		<div class="flex w-full items-center justify-between">
			<p class="flex items-center gap-2 text-sm font-semibold">
				{t('notification.jamStarted.text', {
					profileName: profileName(profile)
				})}{' '}
				<UpdatingDate date={notification.createdAt} />
			</p>
		</div>
		<CardEvent post={notification.post!} />
	</div>
</NotificationWrapper>
