// platform/rn-components/src/components/notifications/types/NewGroupPost.tsx
import React from 'react';
import { Pressable } from 'react-native';
import { PublicNotification } from '@openpeepshq/common';
import { NotificationWrapper } from '../NotificationWrapper';
import { MainStackParamList } from '~/components/navigation/types';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useNavigation } from '@react-navigation/native';
import { FeedPost } from '../../post/FeedPost';

interface NotificationTypeProps {
  notification: PublicNotification;
}
export const NewGroupPost: React.FC<NotificationTypeProps> = ({
  notification,
}) => {
  const profile = notification.senderProfile!;
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  const { post } = notification;

  if (!post) {
    return null;
  }

  return (
    <NotificationWrapper
      profile={profile}
      group={notification.group || post.group}
      seen={notification.seen}
      showProfile={true}
    >
      <Pressable
        onPress={() => navigation.navigate('Post', { id: post.id })}
        className="w-full flex"
      >
        <FeedPost post={post} showReplyTo={false} showMenu={false} />
      </Pressable>
    </NotificationWrapper>
  );
};

// platform/svelte/src/lib/components/core/notification/types/NewGroupPost.svelte
<script lang="ts">
	import { FeedPost } from '$lib/components/core/post';
	import { Users } from 'lucide-svelte';
	import type { ExpandedNotification } from '@openpeeps/common/types';
	import { groupName } from '@openpeeps/common/lib';
	import NotificationWrapper from '../NotificationWrapper.svelte';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		notification: ExpandedNotification;
	}

	let { notification }: Props = $props();

	const { t } = i18nContext();

	const post = notification.post!;
	const profile = notification.senderProfile!;
	const group = post.group!;
</script>

<NotificationWrapper {profile} seen={notification.seen} showProfile={false}>
	<a class="w-full px-4" href="/posts/{post.id}">
		<div class="flex w-full items-center justify-between">
			<p class="mb-2 flex items-center gap-2 text-sm font-semibold">
				<Users size={16} />
				{t('notification.newGroupPost.text', {
					groupName: groupName(group)
				})}
			</p>
		</div>

		{#if post}
			<FeedPost {post} inGroup />
		{/if}
	</a>
</NotificationWrapper>
