// platform/rn-components/src/components/custom/notification/types/new-group-invitation.tsx
import { Pressable, View } from 'react-native';
import React from 'react';
import { ThemedText } from '~/components/ui/themed-text';
import { NotificationWrapper } from '../NotificationWrapper';
import { PublicNotification, GroupWithMeta } from '@openpeepshq/common';
import { UsersIcon } from '~/components/icons';
import { UpdatingDate } from '../../date/updating-date';
import { useTranslation } from 'react-i18next';
import { ProfileAvatar } from '../../profile/profile-avatar';
import { MainStackParamList } from '~/components/navigation/types';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useNavigation } from '@react-navigation/native';
interface NotificationTypeProps {
  notification: PublicNotification;
}

export const NewGroupInvitation: React.FC<NotificationTypeProps> = ({
  notification,
}) => {
  const profile = notification.senderProfile!;
  const group = notification.group as GroupWithMeta;
  const { t } = useTranslation();
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  return (
    <NotificationWrapper
      profile={profile}
      seen={notification.seen}
      showProfile={false}>
      <View className="w-full">
        <View className="w-full flex items-center gap-x-4 flex-wrap">
          <UsersIcon className="text-muted-foreground h-8 w-8" />
          <ProfileAvatar profile={profile} className="size-16" />
        </View>
        <View className="mt-2">
          <ThemedText>{t('notification.newGroupInvitation.text')}</ThemedText>
          <Pressable
            onPress={() =>
              navigation.navigate('Group', { handle: group.handle })
            }>
            <ThemedText className="font-bold">{group.displayName}</ThemedText>
          </Pressable>
          <View className="ml-2 text-wrap">
            <UpdatingDate date={notification.createdAt} />
          </View>
        </View>
      </View>
    </NotificationWrapper>
  );
};

// platform/svelte/src/lib/components/core/notification/types/NewGroupInvitation.svelte
<script lang="ts">
	import type { ExpandedNotification, GroupWithMeta } from '@openpeeps/common/types';
	import { profileName } from '@openpeeps/common/lib';
	import { UpdatingDate } from '@openpeeps/ui';
	import { Users } from 'lucide-svelte';
	import GroupAvatar from '../../groups/GroupAvatar.svelte';
	import NotificationWrapper from '../NotificationWrapper.svelte';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		notification: ExpandedNotification;
	}

	let { notification }: Props = $props();
	const { t } = i18nContext();

	const profile = notification.senderProfile!;
	const group = notification.group as GroupWithMeta;
</script>

<NotificationWrapper {profile} seen={notification.seen} showProfile={false}>
	<div class="w-full px-4">
		<div class="flex items-center gap-x-4">
			<Users class="h-8 w-8 text-surface-500" />
			<GroupAvatar {group} size={4} />
		</div>
		<span class="py-2">
			{t('notification.newGroupInvitation.text')}{' '}
			<strong>
				<a href={`/groups/@${group.handle}`}>{group.displayName}</a>
			</strong>
			<span class="ml-2">
				<UpdatingDate date={notification.createdAt} />
			</span>
		</span>
	</div>
</NotificationWrapper>
