// platform/rn-components/src/components/profile/AvatarWithName.tsx
import React from 'react';
import { View } from 'react-native';
import type { PublicProfile } from '@openpeepshq/common';
import { ThemedText } from '../ui/themed-text';
import { ProfileAvatar } from './Avatar';

export interface AvatarWithNameProps {
  profile?: PublicProfile;
}

export const AvatarWithName = ({ profile }: AvatarWithNameProps) => (
  <View className="flex-row items-center gap-2">
    {profile ? <ProfileAvatar profile={profile} className="size-8" /> : null}
    <ThemedText className="text-sm">
      {profile?.displayName || profile?.handle}
    </ThemedText>
  </View>
);

// platform/svelte/src/lib/components/core/profile/AvatarWithName.svelte
<script lang="ts">
	import type { PublicProfile } from '@openpeeps/common/types';
	import { Avatar } from '.';

	interface Props {
		profile: PublicProfile;
	}

	let { profile }: Props = $props();
</script>

<div class="flex items-center gap-2 text-sm">
	<Avatar {profile} size={1.5} borderless />
	{profile.displayName || profile.handle}
</div>
