// platform/react-native/src/components/custom/profile/profile-card.tsx
import { View, TouchableWithoutFeedback, Pressable } from 'react-native';
import React from 'react';
import { Profile } from '@openpeeps/common';
import { XIcon } from '../../icons';
import { ThemedText } from '../../ui/themed-text';
import { truncateText } from '../../../lib/utils';
import { useNavigation } from '@react-navigation/native';
import { MainStackParamList } from '../../navigation/types';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { ProfileAvatar } from './profile-avatar';

interface ProfileCardProps {
  profile: Profile;
  hasAction?: boolean;
  actionType?: 'follow' | 'message' | 'unfollow' | 'link' | 'select';
  handleSelectProfile?: () => void;
  rightComponent?: React.ReactNode;
}
export const ProfileCard = ({
  actionType = 'link',
  handleSelectProfile,
  profile,
  rightComponent,
}: ProfileCardProps) => {
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  const handleGoToProfile = () => {
    navigation.navigate('Profile', {
      handle: profile.handle,
    });
  };

  return (
    <View className="flex flex-row justify-between w-full px-4 mb-8">
      <TouchableWithoutFeedback
        onPress={() => {
          if (actionType === 'select' && handleSelectProfile) {
            handleSelectProfile();
          }
          if (actionType !== 'select') {
            handleGoToProfile();
          }
        }}>
        <View className="flex flex-row items-center gap-x-2">
          <ProfileAvatar profile={profile} className="size-16"/>
          <View className="">
            <ThemedText className="text-lg font-semibold">
              {truncateText(profile.displayName, 18) || profile.handle}
            </ThemedText>
            <ThemedText className="">@{profile.handle}</ThemedText>
          </View>
        </View>
      </TouchableWithoutFeedback>
      {rightComponent}
    </View>
  );
};

interface MiniProfileCardProps {
  profile: Profile;
  onPress?: (profile: Profile) => void;
  showAction?: boolean;
}

export const MiniProfileCard = ({
  profile,
  onPress,
  showAction = true,
}: MiniProfileCardProps) => {

  return (
    <View className="flex flex-row gap-x-2 items-center px-2 py-2 border rounded-md border-gray-600">
      <ProfileAvatar profile={profile} className="size-8" />
      <ThemedText>
        {truncateText(profile.displayName, 10) || `@${profile.handle}`}
      </ThemedText>
      {showAction && (
        <Pressable onPress={() => onPress && onPress(profile)}>
          <XIcon size={16} className="text-foreground" />
        </Pressable>
      )}
    </View>
  );
};

// platform/svelte/src/lib/components/core/profile/ProfileCard.svelte
<script lang="ts">
	import type { PublicProfile } from '@openpeeps/common/types';
	import FollowUnfollowButton from './FollowUnfollowButton.svelte';
	import { Avatar } from '.';
	import { profileName } from '@openpeeps/common/lib';

	interface Props {
		profile: PublicProfile;
		avatarSize?: number;
		showAction?: boolean;
		noPadding?: boolean;
		badges?: import('svelte').Snippet;
		action?: import('svelte').Snippet;
	}

	let {
		profile,
		avatarSize = 3.5,
		showAction = true,
		noPadding = false,
		badges,
		action
	}: Props = $props();
</script>

<div class="flex justify-between {noPadding ? '' : 'p-4'} w-full">
	<a href={`/@${profile.handle}`} class="flex items-center gap-x-2">
		<Avatar {profile} borderless size={avatarSize} />
		<div class="text-left">
			<h3 class="flex gap-2 text-lg font-semibold {avatarSize < 2 ? 'text-sm' : 'text-lg'}">
				<span>{profileName(profile)}</span>
				{@render badges?.()}
			</h3>
			<h3 class={avatarSize < 2 ? 'text-xs' : 'text-sm'}>@{profile.handle}</h3>
		</div>
	</a>
	{#if showAction}
		{#if action}{@render action()}{:else}
			<FollowUnfollowButton {profile} />
		{/if}
	{/if}
</div>
