// platform/rn-components/src/components/profile/ProfileWithActionCard.tsx
import React, { type ReactNode } from 'react';
import { View } from 'react-native';
import type { PublicProfile } from '@openpeepshq/common';
import { ThemedText } from '../ui/themed-text';
import { ProfileAvatar } from './Avatar';
import { ProfileLink } from './ProfileLink';
import { FollowUnfollowButton } from './FollowUnfollowButton';

export interface ProfileWithActionCardProps {
  profile: PublicProfile;
  leading?: ReactNode;
}

export const ProfileWithActionCard = ({
  profile,
  leading,
}: ProfileWithActionCardProps) => (
  <View className="mb-4 w-full flex-row items-center justify-between">
    <View className="flex-row items-center gap-2">
      {leading}
      <ProfileLink profile={profile} className="flex-row items-center gap-2">
        <ProfileAvatar profile={profile} />
        <View>
          <ThemedText className="font-bold">
            {profile.displayName || profile.handle}
          </ThemedText>
          <ThemedText className="text-sm text-muted-foreground">
            @{profile.handle}
          </ThemedText>
        </View>
      </ProfileLink>
    </View>
    <FollowUnfollowButton profile={profile} compact />
  </View>
);

// platform/svelte/src/lib/components/core/profile/ProfileWithActionCard.svelte
<script lang="ts">
	import type { PublicProfile } from '@openpeeps/common/types';
	import FollowUnfollowButton from './FollowUnfollowButton.svelte';
	import { Avatar } from '.';
	import { profileName } from '@openpeeps/common/lib';
	import { me } from '$lib/api';

	interface Props {
		profile: PublicProfile;
	}

	let { profile }: Props = $props();
</script>

<div class="flex w-full justify-between border-b p-4">
	<div class="flex items-center gap-x-2">
		<a href={`/@${profile.handle}`}>
			<Avatar {profile} />
		</a>
		<div class="">
			<a href={`/@${profile.handle}`} class="[&>h3]:underline-offset-2 [&>h3]:hover:underline">
				<h3 class="text-lg font-semibold">
					{profileName(profile)}
				</h3>
				<h3 class=" text-sm">@{profile.handle}</h3>
			</a>
		</div>
	</div>
	{#if $me}
		<FollowUnfollowButton {profile} />
	{/if}
</div>
