// platform/react/src/components/configuration/ConfigurationValueEditor.tsx
import { useEffect, useMemo, useState } from 'react';
import { z, type ZodType } from 'zod';
import { Input, Textarea } from '@openpeeps/react-ui';
import { useT } from '../../i18n';
import { unwrap } from '../../lib/configuration/helpers';

export interface ConfigurationValueEditorProps {
  schema: ZodType;
  config: unknown;
  defaults: unknown;
  path: (string | number)[];
  value?: unknown;
  onChange: (value: unknown) => void;
  disabled?: boolean;
}

export function ConfigurationValueEditor({
  schema,
  config,
  defaults,
  path,
  value: valueProp,
  onChange,
  disabled: disabledProp,
}: ConfigurationValueEditorProps) {
  const t = useT();
  const unwrappedSchema = useMemo(() => unwrap(schema), [schema]);
  const disabled = disabledProp ?? schema.description === 'fixed';
  const [value, setValue] = useState(valueProp ?? config);

  useEffect(() => {
    setValue(valueProp ?? config);
  }, [valueProp, config]);

  const setAndNotify = (next: unknown) => {
    setValue(next);
    onChange(next);
  };

  const dirty = value !== config;
  const label = t(String(path.at(-1)), {
    defaultValue: String(path.at(-1)),
  });
  const password = schema.description === 'password';
  const longText = schema.description === 'longText';

  if (unwrappedSchema instanceof z.ZodString) {
    if (longText) {
      return (
        <div className="my-2 pl-4">
          <label className="label flex flex-col gap-1">
            <span className={dirty ? 'font-bold' : ''}>{label}</span>
            <Textarea
              value={String(value ?? '')}
              placeholder={String(defaults ?? '')}
              disabled={disabled}
              onChange={(e) => setAndNotify(e.target.value)}
            />
          </label>
        </div>
      );
    }
    return (
      <div className="my-2 pl-4">
        <label className="label flex flex-col gap-1">
          <span className={dirty ? 'font-bold' : ''}>{label}</span>
          <Input
            type={password ? 'password' : 'text'}
            value={String(value ?? '')}
            placeholder={String(defaults ?? '')}
            disabled={disabled}
            onChange={(e) => setAndNotify(e.target.value)}
          />
        </label>
      </div>
    );
  }

  if (unwrappedSchema instanceof z.ZodNumber) {
    return (
      <div className="my-2 pl-4">
        <label className="label flex flex-col gap-1">
          <span className={dirty ? 'font-bold' : ''}>{label}</span>
          <Input
            type="number"
            value={value === undefined || value === null ? '' : String(value)}
            placeholder={String(defaults ?? '')}
            disabled={disabled}
            onChange={(e) =>
              setAndNotify(e.target.value === '' ? undefined : Number(e.target.value))
            }
          />
        </label>
      </div>
    );
  }

  if (unwrappedSchema instanceof z.ZodBoolean) {
    return (
      <div className="my-2 pl-4">
        <label className="flex items-center gap-2">
          <input
            type="checkbox"
            className="checkbox"
            checked={Boolean(value)}
            disabled={disabled}
            onChange={(e) => setAndNotify(e.target.checked)}
          />
          <span className={dirty ? 'font-bold' : ''}>{label}</span>
        </label>
      </div>
    );
  }

  if (unwrappedSchema instanceof z.ZodEnum) {
    const options =
      unwrappedSchema.options ??
      (unwrappedSchema._def?.entries
        ? Object.keys(unwrappedSchema._def.entries)
        : []);
    return (
      <div className="my-2 pl-4">
        <p className={dirty ? 'font-bold' : ''}>{label}</p>
        {(options as string[]).map((option) => (
          <label key={option} className="flex items-center gap-2">
            <input
              type="radio"
              className="radio"
              name={path.join('-')}
              value={option}
              checked={value === option}
              disabled={disabled}
              onChange={() => setAndNotify(option)}
            />
            <span>{option}</span>
          </label>
        ))}
      </div>
    );
  }

  return null;
}

// platform/svelte/src/lib/components/core/configuration/server-configuration/ConfigurationValueEditor.svelte
<script lang="ts">
	// @ts-nocheck
	import { z, ZodType } from 'zod';
	import { unwrap } from '$lib/components/core/configuration/helpers';
	import { i18nContext } from '$lib/components/i18n';

	const { t } = i18nContext();

	interface Props {
		schema: ZodType;
		config: z.infer<ZodType>;
		defaults: z.infer<ZodType>;
		path: (string | number)[];
		value?: z.infer<ZodType>;
		unwrappedSchema?: unknown;
		disabled?: boolean;
	}

	let {
		schema,
		config,
		defaults,
		path,
		value = $bindable(),
		unwrappedSchema = unwrap(schema),
		disabled = schema.description === 'fixed'
	}: Props = $props();

	value = config;

	const password = schema.description === 'password';
	const longText = schema.description === 'longText';

	let dirty = $derived(value !== config);
</script>

<div class="my-2 pl-4">
	{#if unwrappedSchema instanceof z.ZodString}
		<label class="label">
			<span class:font-bold={dirty}>{t(String(path.slice(-1)[0]))}</span>
			{#if longText}
				<textarea bind:value class="input rounded" placeholder={defaults} {disabled}>
					{value}
				</textarea>
			{:else}
				<input
					type={password ? 'password' : 'text'}
					bind:value
					class="input rounded"
					placeholder={defaults}
					{disabled}
				/>
			{/if}
		</label>
	{:else if unwrappedSchema instanceof z.ZodNumber}
		<label class="label">
			<span class:font-bold={dirty}>{t(String(path.slice(-1)[0]))}</span>
			<input bind:value type="number" class="input rounded" placeholder={defaults} {disabled} />
		</label>
	{:else if unwrappedSchema instanceof z.ZodBoolean}
		<label class="flex items-center space-x-2">
			<input bind:checked={value} class="checkbox" type="checkbox" {disabled} />
			<span class:font-bold={dirty}>{t(String(path.slice(-1)[0]))}</span>
		</label>
	{:else if unwrappedSchema instanceof z.ZodEnum}
		<p class:font-bold={dirty}>{t(String(path.slice(-1)[0]))}</p>
		{#each (unwrappedSchema.options ?? (unwrappedSchema._def?.entries ? Object.keys(unwrappedSchema._def.entries) : [])) as option}
			<label class="flex items-center space-x-2">
				<input
					bind:group={value}
					class="radio"
					type="radio"
					name={path.join('-')}
					value={option}
					{disabled}
				/>
				<span>{option}</span>
			</label>
		{/each}
	{/if}
</div>
