// platform/react/src/components/configuration/ConfigurationCategory.tsx
import { useEffect, useMemo, useState } from 'react';
import { ZodObject, type ZodRawShape, ZodArray, type ZodType } from 'zod';
import type { ConfigTree } from '@openpeeps/common/types';
import { capitalizeFirstLetter } from '@openpeeps/common';
import { ExpandableBox } from '@openpeeps/react-ui';
import { useT } from '../../i18n';
import {
  diffConfigTrees,
  equal,
  isFieldHidden,
  unwrap,
} from '../../lib/configuration/helpers';
import { ConfigurationList } from './ConfigurationList';
import { ConfigurationValueEditor } from './ConfigurationValueEditor';

export interface ConfigurationCategoryProps {
  schema: ZodObject<ZodRawShape>;
  config: Record<string, unknown>;
  defaults: Record<string, unknown>;
  path?: (string | number)[];
  value?: Record<string, unknown>;
  onChange: (value: Record<string, unknown>) => void;
  disabled?: boolean;
  collapsible?: boolean;
}

export function ConfigurationCategory({
  schema,
  config,
  defaults,
  path = [],
  value: valueProp,
  onChange,
  disabled: disabledProp,
  collapsible = true,
}: ConfigurationCategoryProps) {
  const t = useT();
  const disabled = disabledProp ?? schema.description === 'fixed';
  const [value, setValue] = useState<Record<string, unknown>>(
    () => structuredClone(valueProp ?? config),
  );

  useEffect(() => {
    setValue(structuredClone(valueProp ?? config));
  }, [valueProp, config]);

  const setAndNotify = (next: Record<string, unknown>) => {
    setValue(next);
    onChange(next);
  };

  const dirty = !equal(config as ConfigTree, value as ConfigTree);
  const dirtyPaths = useMemo(() => {
    const diff = diffConfigTrees(config as ConfigTree, value as ConfigTree) as Record<
      string,
      unknown
    >;
    return Object.keys(diff).flatMap((key) => [...path.map(String), key]);
  }, [config, value, path]);

  const pathName = path.at(-1);
  const fields = Object.entries(schema.shape).map(([key, def]) => ({
    key,
    def: def as ZodType,
    path: [...path, key],
  }));

  const updateField = (key: string, fieldValue: unknown) => {
    setAndNotify({ ...value, [key]: fieldValue });
  };

  const hasKey = (key: string) => dirtyPaths.includes(key);

  if (fields.length === 0) return null;

  const body = (
    <>
      {fields.map((field) => {
        if (isFieldHidden(field.def)) return null;
        const fieldSchema = unwrap(field.def);
        if (isFieldHidden(fieldSchema)) return null;

        const title = (
          <p
            className={
              !collapsible
                ? dirty && hasKey(String(field.key))
                  ? 'font-bold'
                  : ''
                : dirty && hasKey(String(field.key))
                  ? 'font-bold'
                  : ''
            }
          >
            {capitalizeFirstLetter(String(field.key))}
          </p>
        );

        if (fieldSchema instanceof ZodObject) {
          const nested = (
            <ConfigurationCategory
              schema={fieldSchema}
              path={field.path}
              config={(config[field.key] ?? {}) as Record<string, unknown>}
              defaults={(defaults[field.key] ?? {}) as Record<string, unknown>}
              value={(value[field.key] ?? {}) as Record<string, unknown>}
              onChange={(v) => updateField(String(field.key), v)}
              collapsible={false}
              disabled={disabled}
            />
          );
          return collapsible ? (
            <ExpandableBox key={String(field.key)} title={title} initialOpen={false}>
              {nested}
            </ExpandableBox>
          ) : (
            <div key={String(field.key)}>{title}{nested}</div>
          );
        }

        if (fieldSchema instanceof ZodArray) {
          return (
            <ConfigurationList
              key={String(field.key)}
              schema={fieldSchema as ZodArray<ZodType>}
              path={field.path}
              config={(config[field.key] ?? []) as unknown[]}
              value={(value[field.key] ?? []) as unknown[]}
              onChange={(v) => updateField(String(field.key), v)}
              disabled={disabled}
            />
          );
        }

        return (
          <ConfigurationValueEditor
            key={String(field.key)}
            schema={field.def}
            path={field.path.map(String)}
            config={config[field.key]}
            defaults={defaults[field.key]}
            value={value[field.key]}
            onChange={(v) => updateField(String(field.key), v)}
            disabled={disabled}
          />
        );
      })}
    </>
  );

  return (
    <div className={collapsible ? 'mt-4 pl-4' : ''}>
      {collapsible && (
        <p className={dirty ? 'font-bold' : ''}>
          {pathName || t('configuration.title', { defaultValue: 'Configuration' })}
        </p>
      )}
      {body}
    </div>
  );
}

// platform/svelte/src/lib/components/core/configuration/server-configuration/ConfigurationCategory.svelte
<script lang="ts">
  import { z, ZodObject, type ZodRawShape } from 'zod';
  import {
    ConfigurationList,
    ConfigurationValueEditor,
    ConfigurationCategory,
  } from '..';
  import {
    diffConfigTrees,
    equal,
    unwrap,
  } from '$lib/components/core/configuration/helpers';
  import { i18nContext } from '$lib/components/i18n';
  import { ExpandableBox } from '@openpeeps/ui';
  import { capitalizeFirstLetter } from '@openpeeps/common';

  const { t } = i18nContext();

  type Shape = z.infer<typeof schema>;
  type Key = keyof Shape;
  type Value = Shape[keyof Shape];

  const fieldInfo = (entry: [Key, Value]) => {
    const key = entry[0];
    const def = entry[1];
    return { key, def, path: [...path, key] };
  };

  interface Props {
    schema: ZodObject<ZodRawShape>;
    config: Shape;
    defaults: Shape;
    path?: (string | number)[];
    value?: Shape;
    disabled?: boolean;
    collapsible?: boolean;
  }

  let {
    schema,
    config,
    defaults,
    path = [],
    value = $bindable(),
    collapsible = true,
    disabled = schema.description === 'fixed' ? true : undefined,
  }: Props = $props();

  value = structuredClone(config);

  let dirty = $derived(!equal(config, value));
  let dirtyProps = $derived(
    Object.entries(diffConfigTrees(config, value)).map(fieldInfo),
  );
  let dirtyPaths = $derived(dirtyProps.map((p) => p.path).flat());

  const pathName = path.slice(-1)[0];
  let dirtyField = $derived(
    dirtyPaths?.find((p) => p === pathName) !== undefined,
  );

  const fields = Object.entries(schema.shape).map(fieldInfo);

  const hasKey = (v: string | number) => dirtyPaths.includes(v?.toString());
</script>

{#if fields.length > 0}
  <div class={collapsible ? 'mt-4 pl-4' : ''}>
    {#if collapsible}
      <p class:font-bold={dirty}>
        {pathName || t('configuration.title')}
      </p>
    {/if}
    {#each fields as field}
      {@const fieldSchema = unwrap(field.def)}
      {#if fieldSchema.description !== 'fixed'}
        {#if fieldSchema instanceof z.ZodObject}
          <ExpandableBox initialOpen={false}>
            {#snippet title()}
              <p
                class:font-bold={!collapsible
                  ? dirtyField && hasKey(field.key)
                  : dirty && hasKey(field.key)}
              >
                {capitalizeFirstLetter(field.key?.toString())}
              </p>
            {/snippet}
            <ConfigurationCategory
              bind:value={value[field.key]}
              schema={fieldSchema}
              path={field.path}
              config={config[field.key]}
              defaults={defaults[field.key]}
              collapsible={false}
              {disabled}
            ></ConfigurationCategory>
          </ExpandableBox>
        {:else if fieldSchema instanceof z.ZodArray}
          <ConfigurationList
            bind:value={value[field.key]}
            schema={fieldSchema}
            path={field.path}
            config={config[field.key]}
            {disabled}
          ></ConfigurationList>
        {:else}
          <ConfigurationValueEditor
            bind:value={value[field.key]}
            schema={field.def}
            path={field.path.map(String)}
            config={config[field.key]}
            defaults={defaults[field.key]}
            {disabled}
          ></ConfigurationValueEditor>
        {/if}
      {/if}
    {/each}
  </div>
{/if}
