// platform/react/src/components/navigation/ContentHeader.tsx
import { ChevronLeft } from 'lucide-react';
import { capitalizeFirstLetter } from '@openpeeps/common/lib';
import { usePageHeader } from '../../stores';
import { useT } from '../../i18n';
import { useRouter } from '../../contexts/router';

export function ContentHeader() {
  const pageHeader = usePageHeader();
  const t = useT();
  const router = useRouter();

  const titleString =
    typeof pageHeader?.title === 'string'
      ? pageHeader.title
      : capitalizeFirstLetter(
          router.pathname.split('/').filter(Boolean).pop() ?? '',
        );

  const titleNode =
    pageHeader?.title && typeof pageHeader.title !== 'string'
      ? pageHeader.title
      : null;

  return (
    <div className="bg-card sticky top-0 z-10 flex h-16 w-full items-center justify-between border-b p-4">
      <div className="flex items-center gap-2">
        <button
          type="button"
          title={t('navigation.back')}
          onClick={() => router.back()}
        >
          <ChevronLeft />
        </button>
        {titleNode ?? <h5 className="text-xl font-semibold">{titleString}</h5>}
      </div>
      {pageHeader?.actions && (
        <div className="flex items-center gap-2">{pageHeader.actions}</div>
      )}
    </div>
  );
}

// platform/svelte/src/lib/components/navigation/ContentHeader.svelte
<script lang="ts">
  import { ChevronLeft } from 'lucide-svelte';
  import { getPageHeaderStore } from '$lib/stores';
  import { page } from '$app/state';
  import { capitalizeFirstLetter } from '@openpeeps/common/lib';
  import { i18nContext } from '$lib/components/i18n';

  const pageHeader = getPageHeaderStore();
  const { t } = i18nContext();

  const title = $derived(
    typeof $pageHeader?.title === 'string'
      ? $pageHeader.title
      : capitalizeFirstLetter(page.url.pathname.split('/').reverse()[0]),
  );
  const Title = $derived(
    $pageHeader?.title && typeof $pageHeader.title !== 'string'
      ? $pageHeader.title
      : undefined,
  );

  const Actions = $derived($pageHeader?.actions);
</script>

<div
  class="bg-surface-50 sticky top-0 z-10 flex h-16 w-full items-center justify-between border-b p-4"
>
  <div class="flex items-center gap-2">
    <button title={t('navigation.back')} onclick={() => window.history.back()}>
      <ChevronLeft />
    </button>
    {#if Title}
      <Title />
    {:else}
      <h5 class="h5">{title}</h5>
    {/if}
  </div>
  {#if Actions}
    <div class="flex items-center gap-2">
      <Actions />
    </div>
  {/if}
</div>
