// platform/svelte/src/lib/components/core/post/feed/chronological/PinnedPost.svelte
<script lang="ts">
	import FeedPost from './FeedPost.svelte';
	import { getPostStore } from '$lib/api';
	import { Pin } from 'lucide-svelte';
	import { WaitForQueries } from '@openpeeps/ui';

	interface Props {
		pinnedPostId: string;
		inGroup?: boolean;
	}

	let { pinnedPostId, inGroup = false }: Props = $props();

	const postStore = getPostStore(pinnedPostId);
</script>

<WaitForQueries queries={[$postStore]}>
	{#if $postStore.data}
		<a
			href="/posts/{$postStore.data?.repost ? $postStore.data?.repost?.id : $postStore.data?.id}"
			class="bg-surface-300"
		>
			<div class="px-5 pt-3 text-sm">
				<Pin class="mr-1 inline-block size-4" />
				Pinned post
			</div>
			<FeedPost post={$postStore.data} inGroup />
		</a>
	{/if}
</WaitForQueries>

// platform/react/src/components/post/PinnedPost.tsx
import { Pin } from 'lucide-react';
import { useOpenpeeps } from '../../contexts/openpeeps';
import { useT } from '../../i18n';
import { FeedPost } from './FeedPost';

export interface PinnedPostProps {
  pinnedPostId: string;
  inGroup?: boolean;
}

export function PinnedPost({ pinnedPostId, inGroup = false }: PinnedPostProps) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const postQuery = openpeepsApi.usePost(pinnedPostId);
  const post = postQuery.data;

  if (postQuery.isLoading || !post) return null;

  const href = `/posts/${post.repost ? post.repost.id : post.id}`;

  return (
    <a href={href} className="bg-surface-100 block">
      <div className="px-5 pt-3 text-sm">
        <Pin className="mr-1 inline-block size-4" />
        {t('feed.pinned', { defaultValue: 'Pinned post' })}
      </div>
      <FeedPost post={post} inGroup={inGroup} />
    </a>
  );
}
