// platform/svelte/src/lib/components/core/post/VideoPlayOverlay.svelte
<script lang="ts">
	import { CirclePlay } from 'lucide-svelte';

	interface Props {
		video: boolean;
	}

	const { video }: Props = $props();
</script>

{#if video}
	<div class="absolute inset-0 flex items-center justify-center">
		<div class="flex h-12 w-12 items-center justify-center rounded-full bg-black/60 text-white">
			<CirclePlay />
		</div>
	</div>
{/if}

// platform/react/src/components/post/VideoPlayOverlay.tsx
import { CirclePlay } from 'lucide-react';

export interface VideoPlayOverlayProps {
  video: boolean;
}

/** Mirrors Svelte `VideoPlayOverlay.svelte` — play affordance on video thumbnails. */
export const VideoPlayOverlay = ({ video }: VideoPlayOverlayProps) => {
  if (!video) return null;

  return (
    <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
      <div className="flex size-12 items-center justify-center rounded-full bg-black/60 text-white">
        <CirclePlay className="size-8" />
      </div>
    </div>
  );
};
