// platform/svelte/src/lib/components/core/post/pieces/EventLocation.svelte
<script lang="ts">
	import type { Event, PublicPost } from '@openpeeps/common/types';
	import { Link } from '@openpeeps/ui';
	import { ExternalLink, LinkIcon, MapPin, PhoneCall } from 'lucide-svelte';
	import { getJamUrl, truncateText } from '@openpeeps/common/lib';
	import { page } from '$app/state';
	interface Props {
		post: PublicPost;
		preview?: boolean;
		truncate?: boolean;
	}
	let { post, preview = true, truncate = false }: Props = $props();
	const event = $derived(post.data as Event);

	const jamLink = `${page.url.origin}/events/${post.id}/jam`;
</script>

{#if preview}
	<div class="flex items-center gap-1">
		{#if event.physicalLocation}
			<MapPin class="h-4 w-4" />
			{truncate ? truncateText(event.physicalLocation.text) : event.physicalLocation.text}
		{:else if event.jam}
			<PhoneCall class="h-4 w-4" />
			<Link action={getJamUrl(post.id, page.url.origin)} newTab>Jam Event</Link>
		{:else if event.url}
			<LinkIcon class="h-4 w-4" />
			<Link action={event.url} newTab>
				<span class="flex items-center gap-1">
					Online
					<ExternalLink class="h-4 w-4" />
				</span>
			</Link>
		{/if}
	</div>
{:else}
	<div class="mt-4 flex gap-x-4">
		<div
			class="border-foreground/20 flex items-center justify-center rounded-md border-[0.5px] px-4 py-1"
		>
			{#if event?.physicalLocation}
				<MapPin class="text-muted-foreground my-3" size={24} />
			{:else if event?.jam}
				<PhoneCall class="text-muted-foreground my-3" size={24} />
			{:else if event?.url}
				<LinkIcon class="text-muted-foreground my-3" size={24} />
			{/if}
		</div>
		<div>
			{#if event?.physicalLocation}
				<div>
					<p class="">
						{truncate
							? truncateText(event.physicalLocation.text)
							: event.physicalLocation.text || 'Physical Location'}
					</p>
				</div>
			{:else if event?.jam}
				<div>
					<p class="">Jam Event</p>
					<a href={jamLink} target="_blank" rel="noopener noreferrer" class="anchor mt-2"
						>{truncateText(jamLink, 30)}</a
					>
				</div>
			{:else if event?.url}
				<div>
					<p class="">External Event</p>
					<a href={event.url} target="_blank" rel="noopener noreferrer" class="anchor mt-2"
						>{truncateText(event?.url, 40)}</a
					>
				</div>
			{/if}
		</div>
	</div>
{/if}

// platform/react/src/components/post/pieces/EventLocation.tsx
import { ExternalLink, Link as LinkIcon, MapPin, PhoneCall } from 'lucide-react';
import type { Event, PublicPost } from '@openpeeps/common/types';
import { getJamUrl, truncateText } from '@openpeeps/common/lib';

export interface EventLocationProps {
  post: PublicPost;
  preview?: boolean;
  truncate?: boolean;
}

export function EventLocation({
  post,
  preview = true,
  truncate = false,
}: EventLocationProps) {
  if (post.data?.type !== 'event') return null;
  const event = post.data as Event;
  const origin = typeof window !== 'undefined' ? window.location.origin : '';
  const jamLink = getJamUrl(post.id, origin);

  if (preview) {
    return (
      <div className="flex items-center gap-1 text-sm">
        {event.physicalLocation ? (
          <>
            <MapPin className="h-4 w-4 shrink-0" />
            <span>
              {truncate
                ? truncateText(event.physicalLocation.text)
                : event.physicalLocation.text}
            </span>
          </>
        ) : event.jam ? (
          <>
            <PhoneCall className="h-4 w-4 shrink-0" />
            <a href={jamLink} target="_blank" rel="noreferrer" className="text-primary hover:underline">
              Jam Event
            </a>
          </>
        ) : event.url ? (
          <>
            <LinkIcon className="h-4 w-4 shrink-0" />
            <a
              href={event.url}
              target="_blank"
              rel="noreferrer"
              className="text-primary inline-flex items-center gap-1 hover:underline"
            >
              Online
              <ExternalLink className="h-4 w-4" />
            </a>
          </>
        ) : null}
      </div>
    );
  }

  return (
    <div className="mt-4 flex gap-x-4">
      <div className="border-foreground/20 flex items-center justify-center rounded-md border px-4 py-1">
        {event.physicalLocation ? (
          <MapPin className="text-muted-foreground my-3" size={24} />
        ) : event.jam ? (
          <PhoneCall className="text-muted-foreground my-3" size={24} />
        ) : event.url ? (
          <LinkIcon className="text-muted-foreground my-3" size={24} />
        ) : null}
      </div>
      <div>
        {event.physicalLocation ? (
          <p>{truncate ? truncateText(event.physicalLocation.text) : event.physicalLocation.text}</p>
        ) : event.jam ? (
          <>
            <p>Jam Event</p>
            <a href={jamLink} target="_blank" rel="noreferrer" className="text-primary mt-2 block text-sm">
              {truncateText(jamLink, 30)}
            </a>
          </>
        ) : event.url ? (
          <>
            <p>External Event</p>
            <a href={event.url} target="_blank" rel="noreferrer" className="text-primary mt-2 block text-sm">
              {truncateText(event.url, 40)}
            </a>
          </>
        ) : null}
      </div>
    </div>
  );
}
