// platform/svelte/src/lib/components/core/post/pieces/EventMenu.svelte
<script lang="ts">
	import { me } from '$lib/api';
	import type { PublicPost } from '@openpeeps/common/types';
	import { CopyPlusIcon, Pencil, Trash } from 'lucide-svelte';
	import { getModalManager, PopupMenu, PopupMenuButton, type Variant } from '@openpeeps/ui';
	import type { Snippet } from 'svelte';
	import { i18nContext } from '$lib/components/i18n';
	import { goto } from '$app/navigation';
	import { getNewPostStores } from '$lib/stores';
	import { DeletePostModal, getServerDataContext } from '$lib/components';
	import { checkPostCapabilities } from '@openpeeps/common';

	const { t } = i18nContext();
	interface Props {
		post: PublicPost;
		menuButton?: Snippet;
		variant?: Variant;
		class?: string;
	}
	const newPostStores = getNewPostStores();
	const modalManager = getModalManager();

	let { post, menuButton, variant, class: additionalClasses }: Props = $props();

	const { capabilities } = getServerDataContext();

	let canDeletePost: boolean = $derived(
    checkPostCapabilities(['core-posts-delete'], $me, post, capabilities)
      .success,
  );

	const deleteCallback = () => {
		history.back();
	};
</script>

<PopupMenu menuId="event-menu-{post.id}" {menuButton} {variant} class={additionalClasses}>
	{#if $me?.id === post.profile.id}
		<PopupMenuButton
			title={t('common.actions.edit')}
			action="/events/{post.id}/edit"
			text={t('common.actions.edit')}
			icon={Pencil}
		/>
    	{#if canDeletePost}
			<PopupMenuButton
				title={t('common.actions.delete')}
				text={t('common.actions.delete')}
				action={() =>
				modalManager.show(DeletePostModal, { post, deleteCallback })}
				icon={Trash}
				danger
				/>
		{/if}
		<PopupMenuButton
			title={t('common.actions.duplicate')}
			action={async () => {
				newPostStores.event = {
					data:{
						...post.data,
						content : post.data.content,
					},
					mentions: post.mentions,
					visibility:post.visibility,
					audience: post.audience,
					groupId: post.groupId,
					type:"event"
					
				}
				await goto("/events/new")
			}}
			text={t('common.actions.duplicate')}
			icon={CopyPlusIcon}
		/>
	{/if}
</PopupMenu>

// platform/react/src/components/post/pieces/EventMenu.tsx
import { useMemo, useState } from 'react';
import { CopyPlus, Pencil, Trash } from 'lucide-react';
import type { Event, PublicPost } from '@openpeeps/common/types';
import { checkPostCapabilities } from '@openpeeps/common/lib';
import { PopupMenu, PopupMenuButton } from '@openpeeps/react-ui';
import { useNavigate } from '../../../contexts/router';
import { useT } from '../../../i18n';
import { getNewPostStores } from '../../../stores';
import { useAuthData, useCurrentProfile } from '../../layout/IdentityContext';
import { useCapabilities } from '../../server-data';
import { DeletePostModal } from './modals/DeletePostModal';

export interface EventMenuProps {
  post: PublicPost;
  menuButton?: React.ReactNode;
}

export function EventMenu({ post, menuButton }: EventMenuProps) {
  const t = useT();
  const navigate = useNavigate();
  const me = useCurrentProfile();
  const authData = useAuthData();
  const capabilities = useCapabilities();
  const [showDelete, setShowDelete] = useState(false);

  const canDeletePost = useMemo(
    () =>
      checkPostCapabilities(authData, ['core-posts-delete'], post, capabilities)
        .success,
    [authData, post, capabilities],
  );

  if (me?.id !== post.profile.id) return null;

  const duplicate = () => {
    getNewPostStores().event = {
      type: 'event',
      visibility: post.visibility,
      data: { ...(post.data as Event) },
      audience: post.audience,
      groupId: post.groupId,
      mentions: post.mentions,
    };
    navigate('/events/new');
  };

  return (
    <>
      <PopupMenu
        menuButton={menuButton}
        title={t('events.menu.title', { defaultValue: 'Event options' })}
      >
        <PopupMenuButton
          title={t('common.actions.edit', { defaultValue: 'Edit' })}
          text={t('common.actions.edit', { defaultValue: 'Edit' })}
          icon={Pencil}
          action={`/events/${post.id}/edit`}
        />
        {canDeletePost ? (
          <PopupMenuButton
            title={t('common.actions.delete', { defaultValue: 'Delete' })}
            text={t('common.actions.delete', { defaultValue: 'Delete' })}
            icon={Trash}
            danger
            action={() => setShowDelete(true)}
          />
        ) : null}
        <PopupMenuButton
          title={t('common.actions.duplicate', { defaultValue: 'Duplicate' })}
          text={t('common.actions.duplicate', { defaultValue: 'Duplicate' })}
          icon={CopyPlus}
          action={duplicate}
        />
      </PopupMenu>

      <DeletePostModal
        post={post}
        open={showDelete}
        onClose={() => setShowDelete(false)}
        deleteCallback={() => window.history.back()}
      />
    </>
  );
}
