// platform/svelte/src/lib/components/core/post/pieces/PollContent.svelte
<script lang="ts">
	import { Avatar } from '../../profile';
	import { Button } from '@openpeeps/ui';
	import type { PublicPost } from '@openpeeps/common/types';
	import { formatDistanceToNow, isPast } from 'date-fns';
	import { votePollMutation } from '$lib/api';
	import { toast } from '$lib/utils/toast';
	import { getToastStore, ProgressBar } from '@skeletonlabs/skeleton';
	import { preventDefault, stopPropagation } from '@openpeeps/ui';
	import { checkPostCapabilities, collectVotes, groupName, hasValue } from '@openpeeps/common/lib';
	import { getServerDataContext } from '$lib/components/serverData';
	import { getCurrentAuthData, getCurrentProfile } from '$lib/auth';
	import { i18nContext } from '$lib/components/i18n';
  import { goto } from '$app/navigation';

	interface Props {
		post: PublicPost;
	}

	let { post }: Props = $props();
	const me = getCurrentProfile();
	const authData = getCurrentAuthData();

	const { capabilities } = getServerDataContext();
	const { t } = i18nContext();

	const toastStore = getToastStore();
	const votePoll = votePollMutation({ id: post.id });

	const { votes, voteCounts } = $derived(collectVotes(post));

	let hasPollEnded: boolean = $derived(
		!!(post?.data?.type === 'question' && post.data.expiresAt && isPast(post.data.expiresAt))
	);
	let hasVoted: boolean = $derived(
		!!(me && !!((votes.find((v) => v?.profile?.id === me?.id)?.selection?.length ?? 0) > 0))
	);
	let canVote: boolean = $derived(!!(me && !hasPollEnded && !hasVoted));

	let selectedPollOption: number | undefined = $state();
	let selectedPollOptions: number[] | undefined = $state();

	const handleVote = async () => {
		if (post.data?.type !== 'question') {
			return;
		}
		const hasCapabilities = checkPostCapabilities(
			authData,
			['core-posts-vote'],
			post,
			capabilities,
		);

		if (!hasCapabilities.success) {
			toastStore.trigger(
				toast({
					message: post?.group
						? t('posts.vote.lackPermission', {
								groupName: groupName(post.group),
							})
						: t('posts.vote.lackPermissionNoGroup'),
					action: post?.group
						? {
						label: t('groups.goto'),
						response() {
							if(post?.group){
							goto(`/group/@${post.group.handle}`)
							}
						},
					} : undefined,
					background: 'variant-filled-error'
				})
			);
			return;
		}

		const selection = (
			post?.data.multiple
				? selectedPollOptions
				: hasValue(selectedPollOption)
					? [selectedPollOption]
					: undefined
		) as number[];

		if (selection && selection.length > 0) {
			await votePoll({ selection });
			toastStore.trigger(
				toast({
					message: t('posts.vote.successToast'),
					background: 'variant-filled-success'
				})
			);
		} else {
			toastStore.trigger(
				toast({
					message: t('posts.vote.selectOption'),
					background: 'variant-filled-error'
				})
			);
		}
	};
	const handleClearVote = async () => {
		if (post.data?.type !== 'question') {
			return;
		}
		let selection: number[] = [];
		await votePoll({ selection });
		toastStore.trigger(
			toast({
				message: t('posts.vote.cleared'),
				background: 'variant-filled-success'
			})
		);
	};
</script>

{#if post?.data?.type === 'question'}
	<div class="rounded-md p-4">
		{#each post?.data?.options as option, i (i)}
			<div class="mt-4 flex items-center gap-x-2 rounded-md px-4 py-2" role="none">
				{#if canVote}
					{#if post?.data?.multiple}
						<input
							type="checkbox"
							class="h-4 w-4"
							bind:group={selectedPollOptions}
							onclick={stopPropagation()}
							value={i}
						/>
					{:else}
						<input
							type="radio"
							class="h-4 w-4"
							bind:group={selectedPollOption}
							onclick={stopPropagation()}
							value={i}
						/>
					{/if}
				{/if}
				<div class="w-full">
					<div class="flex justify-between align-middle">
						<span style="line-height: 2.5rem; vertical-align: middle">{option.content}</span>
						<span class="flex align-middle">
							{#if post?.data.votersVisible}
								{#each votes
									.filter((v) => v.selection.includes(i))
									.slice(0, 2) as vote (vote.profile.id)}
									<span class="-ml-4 inline-block">
										<Avatar borderless profile={vote.profile} size={2.5} />
									</span>
								{/each}
							{/if}
							<span style="line-height: 2.5rem; vertical-align: middle">
								{voteCounts[i] ?? 0}
							</span>
						</span>
					</div>
					<ProgressBar
						meter="rounded bg-primary-500"
						value={voteCounts[i] ?? 0}
						max={votes.length || 1}
					/>
				</div>
			</div>
		{/each}

		{#if canVote}
			<Button title={t('posts.poll.vote')} variant="variant-ringed-surface" class="mt-4" action={handleVote}>
				{t('posts.form.poll.submit')}
			</Button>
		{/if}
		<div class="mt-4 flex items-center gap-x-3 text-sm">
			<p>
				{t('posts.vote.votesCount', { count: votes.length || 0 })}
			</p>
			{#if post?.data.expiresAt}
				<p>
					{#if hasPollEnded}
						{t('posts.poll.ended')}
					{:else}
						{formatDistanceToNow(post?.data.expiresAt)} {t('posts.poll.timeLeft')}
					{/if}
				</p>
			{/if}
			{#if hasVoted && !hasPollEnded}
				<button
					title={t('posts.poll.undoVoteTitle')}
					class="text-primary-500 mt-[-2px] text-base font-semibold"
					onclick={stopPropagation(preventDefault(handleClearVote))}>{t('posts.poll.undo')}</button
				>
			{/if}
		</div>
	</div>
{/if}

// platform/react/src/components/post/pieces/PollContent.tsx
import { useState, type KeyboardEvent, type MouseEvent } from 'react';
import { collectVotes, hasValue, type PublicPost } from '@openpeeps/common';
import { checkPostCapabilities, groupName } from '@openpeeps/common/lib';

const isPast = (date: Date | string) => new Date(date).getTime() < Date.now();

const formatDistanceToNow = (date: Date | string) => {
  const target = new Date(date).getTime();
  const seconds = Math.round((target - Date.now()) / 1000);
  const abs = Math.abs(seconds);
  const rtf = new Intl.RelativeTimeFormat(undefined, { numeric: 'auto' });
  if (abs < 60) return rtf.format(seconds, 'second');
  if (abs < 3600) return rtf.format(Math.round(seconds / 60), 'minute');
  if (abs < 86400) return rtf.format(Math.round(seconds / 3600), 'hour');
  return rtf.format(Math.round(seconds / 86400), 'day');
};
import { useOpenpeeps } from '../../../contexts/openpeeps';
import { useT } from '../../../i18n';
import { useAuthData, useCurrentProfile } from '../../layout/IdentityContext';
import { useToast } from '../../layout/ToastProvider';
import { useCapabilities } from '../../server-data';
import { Avatar } from '../../profile';
import { Button } from '@openpeeps/react-ui';

export interface PollContentProps {
  post: PublicPost;
}

export function PollContent({ post }: PollContentProps) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const currentProfile = useCurrentProfile();
  const authData = useAuthData();
  const capabilities = useCapabilities();
  const { success, error } = useToast();
  const votePoll = openpeepsApi.voteOnPostAction({ id: post.id });

  const [selectedPollOption, setSelectedPollOption] = useState<number>();
  const [selectedPollOptions, setSelectedPollOptions] = useState<number[]>([]);

  if (post.data?.type !== 'question') return null;

  const pollData = post.data;
  const { votes, voteCounts } = collectVotes(post);
  const hasPollEnded = !!(pollData.expiresAt && isPast(pollData.expiresAt));
  const hasVoted = !!(
    currentProfile &&
    (votes.find((v) => v?.profile?.id === currentProfile.id)?.selection
      ?.length ?? 0) > 0
  );
  const canVote = !!(currentProfile && !hasPollEnded && !hasVoted);
  const totalVotes = votes.length || 1;

  const handleVote = async () => {
    const hasCapabilities = checkPostCapabilities(
      authData,
      ['core-posts-vote'],
      post,
      capabilities,
    );

    if (!hasCapabilities.success) {
      error(
        post.group
          ? t('posts.vote.lackPermission', {
              defaultValue: 'You need to be a member of {{groupName}} to vote.',
              groupName: groupName(post.group),
            })
          : t('posts.vote.lackPermissionNoGroup', {
              defaultValue: 'You do not have permission to vote on this poll.',
            }),
      );
      return;
    }

    const selection = (
      pollData.multiple
        ? selectedPollOptions
        : hasValue(selectedPollOption)
          ? [selectedPollOption]
          : undefined
    ) as number[] | undefined;

    if (!selection?.length) {
      error(
        t('posts.vote.selectOption', {
          defaultValue: 'Please select an option to vote.',
        }),
      );
      return;
    }
    try {
      await votePoll({ selection });
      success(
        t('posts.vote.successToast', {
          defaultValue: 'Your vote was counted.',
        }),
      );
    } catch {
      error(
        t('posts.vote.error', {
          defaultValue: 'Could not update your vote. Please try again.',
        }),
      );
    }
  };

  const handleClearVote = async () => {
    try {
      await votePoll({ selection: [] });
      success(
        t('posts.vote.cleared', { defaultValue: 'Your vote was cleared.' }),
      );
    } catch {
      error(
        t('posts.vote.error', {
          defaultValue: 'Could not update your vote. Please try again.',
        }),
      );
    }
  };

  const stopFeedNavigation = (e: MouseEvent | KeyboardEvent) => {
    e.preventDefault();
    e.stopPropagation();
  };

  return (
    <div
      className="bg-surface-100 rounded-lg px-4 py-4"
      onClick={stopFeedNavigation}
      onKeyDown={stopFeedNavigation}
      role="presentation"
    >
      <div className="space-y-4">
        {pollData.options.map((option, index) => (
          <div
            key={`${option.content}-${index}`}
            className="flex items-center gap-2 py-2"
          >
            {canVote ? (
              pollData.multiple ? (
                <input
                  type="checkbox"
                  checked={selectedPollOptions.includes(index)}
                  onChange={() =>
                    setSelectedPollOptions((prev) =>
                      prev.includes(index)
                        ? prev.filter((i) => i !== index)
                        : [...prev, index],
                    )
                  }
                />
              ) : (
                <input
                  type="radio"
                  name={`poll-${post.id}`}
                  checked={selectedPollOption === index}
                  onChange={() => setSelectedPollOption(index)}
                />
              )
            ) : null}
            <div className="flex-1">
              <div className="flex items-center justify-between gap-2">
                <span className="text-base">{option.content}</span>
                <div className="flex items-center gap-2">
                  {pollData.votersVisible ? (
                    <div className="flex -space-x-2">
                      {votes
                        .filter((v) => v.selection.includes(index))
                        .slice(0, 2)
                        .map((vote) => (
                          <Avatar
                            key={vote.profile.id}
                            profile={vote.profile}
                            size={1.5}
                          />
                        ))}
                    </div>
                  ) : null}
                  <span>{voteCounts?.[index] ?? 0}</span>
                </div>
              </div>
              <div className="bg-surface-300 mt-2 h-2 overflow-hidden rounded-full">
                <div
                  className="bg-primary h-full rounded-full transition-all"
                  style={{
                    width: `${((voteCounts[index] ?? 0) / totalVotes) * 100}%`,
                  }}
                />
              </div>
            </div>
          </div>
        ))}
      </div>

      {canVote ? (
        <Button
          variant="variant-filled-primary"
          className="mt-4"
          title={t('posts.poll.vote', { defaultValue: 'Vote' })}
          action={handleVote}
        >
          {t('posts.form.poll.submit', { defaultValue: 'Vote' })}
        </Button>
      ) : null}

      <div className="text-muted-foreground mt-4 flex flex-wrap items-center gap-3 text-sm">
        <span>
          {votes.length || 0} {t('posts.vote.count', { defaultValue: 'votes' })}
        </span>
        {pollData.expiresAt ? (
          <span>
            {hasPollEnded
              ? t('posts.poll.ended', { defaultValue: 'Poll ended' })
              : `${formatDistanceToNow(pollData.expiresAt)} ${t('posts.poll.timeLeft', { defaultValue: 'left' })}`}
          </span>
        ) : null}
        {hasVoted && !hasPollEnded ? (
          <Button
            variant="variant-ghost-primary"
            className="h-auto min-h-0 px-0 font-semibold"
            title={t('posts.poll.undoVoteTitle', {
              defaultValue: 'Undo your vote',
            })}
            action={handleClearVote}
          >
            {t('posts.poll.undoVote', { defaultValue: 'Undo vote' })}
          </Button>
        ) : null}
      </div>
    </div>
  );
}
