// platform/svelte/src/lib/components/core/post/pieces/PostActions.svelte
<script lang="ts">
	import type { PublicPost } from '@openpeeps/common/types';
	import ReplyButton from './actions/ReplyButton.svelte';
	import RepostButton from './actions/RepostButton.svelte';
	import ReactionButton from './actions/ReactionButton.svelte';
	import { me } from '$lib/api';
	import { preventDefault, stopPropagation } from '@openpeeps/ui';

	interface Props {
		post: PublicPost;
		compact?: boolean;
	}

	let { post, compact = false }: Props = $props();
</script>

{#if $me}
	<div
		class="mx-auto grid w-full grid-cols-3 items-center p-2 {compact ? '' : 'border-t'}"
		onclick={stopPropagation(preventDefault(() => {}))}
		onkeydown={stopPropagation(preventDefault(() => {}))}
		role="none"
	>
		<div class="hover:bg-surface-200 justify-self-start p-2">
			<ReplyButton {post} {compact} />
		</div>
		<div class="hover:bg-surface-200 justify-self-center p-2">
			<RepostButton {post} {compact} />
		</div>
		<div class="hover:bg-surface-200 justify-self-end p-2">
			<ReactionButton {post} {compact} />
		</div>
		<!-- <ShareButton {post} {compact} /> -->
	</div>
{/if}

// platform/react/src/components/post/pieces/PostActions.tsx
import { Reply, Repeat2, ThumbsUp } from 'lucide-react';
import type { PublicPost } from '@openpeepshq/common/types';
import { Button } from '@openpeepshq/react-ui';
import { useT } from '../../../i18n';
import { useFeedPostActions } from '../../../hooks/posts/useFeedPostActions';
import { postReactionStats } from '../helpers';

export interface PostActionsProps {
  post: PublicPost;
  compact?: boolean;
}

export function PostActions({ post, compact = false }: PostActionsProps) {
  const t = useT();
  const {
    me,
    myRepost,
    iReacted,
    disabledForGroup,
    reply,
    toggleRepost,
    toggleReaction,
  } = useFeedPostActions(post);

  if (!me) return null;

  const actionClass =
    'hover:bg-surface rounded-button flex gap-2 p-2 text-sm disabled:opacity-60';

  const replyLabel = t('posts.footer.reply', { defaultValue: 'Reply' });
  const repostLabel = t('posts.footer.repost', { defaultValue: 'Repost' });
  const likeLabel = t('posts.footer.like', { defaultValue: 'Like' });

  return (
    <div
      className="mx-auto grid w-full grid-cols-3 items-center p-2"
      onClick={(e) => {
        e.preventDefault();
        e.stopPropagation();
      }}
      onKeyDown={(e) => e.stopPropagation()}
      role="presentation"
    >
      <Button
        variant="unstyled"
        className={`${actionClass} justify-self-start`}
        title={t('posts.actions.reply', { defaultValue: 'Reply' })}
        action={reply}
        disabled={disabledForGroup}
      >
        <Reply className="h-4 w-4" />
        {compact ? post.replyCount || null : replyLabel}
      </Button>
      <Button
        variant="unstyled"
        className={`${actionClass} justify-self-center ${myRepost ? 'text-primary' : ''}`}
        title={t('posts.actions.repost', { defaultValue: 'Repost' })}
        action={toggleRepost}
        disabled={disabledForGroup}
        spinnerOnlyOnLoading
        data-testid="posts-repost-button"
      >
        <Repeat2 className="h-4 w-4" />
        {compact ? post.repostCount || null : repostLabel}
      </Button>
      <Button
        variant="unstyled"
        className={`${actionClass} justify-self-end ${iReacted ? 'text-primary' : ''}`}
        title={t('posts.actions.react', { defaultValue: 'React' })}
        action={toggleReaction}
        disabled={disabledForGroup}
        spinnerOnlyOnLoading
      >
        <ThumbsUp className="h-4 w-4" />
        {compact
          ? post.reactions?.length
            ? ` · ${postReactionStats(post)}`
            : null
          : likeLabel}
      </Button>
    </div>
  );
}
