// platform/svelte/src/lib/components/core/jams/pieces/JamChatMessage.svelte
<script lang="ts">
  import { truncateText, type JamEvent } from '@openpeeps/common';
  import { UpdatingDate } from '@openpeeps/ui';
  import { OpenpeepsMarkdown } from '../../markdown';
  import { Avatar } from '../../profile';
  import { profileStore } from '$lib/api';
  import { AccessDeniedLoader } from '$lib/components/layout';

  interface JamChatMessageProps {
    message: JamEvent;
  }

  const attendance = ['join', 'leave', 'start', 'close'];

  const attendanceMap = {
    join: 'joined',
    leave: 'left',
    start: 'started',
    close: 'closed',
  };

  let { message }: JamChatMessageProps = $props();

  let profileQuery = profileStore(message.profileId);
</script>

<AccessDeniedLoader queries={[$profileQuery]}>
  {#if $profileQuery.isSuccess}
    {#if message.type === 'message'}
      <div class="flex items-center justify-between">
        <div class="grid w-full grid-cols-5 gap-x-1">
          <div class="col-span-1 flex w-full justify-center">
            <Avatar profile={$profileQuery?.data} borderless size={2} />
          </div>
          <div class="col-span-4 w-full">
            <div class="flex w-full gap-x-1">
              <h4 class="hidden md:flex">
                {truncateText(
                  $profileQuery?.data?.displayName ||
                    `@${$profileQuery?.data?.handle}`,
                  20,
                )}
              </h4>
              <h4 class="flex md:hidden">
                {truncateText(
                  $profileQuery?.data?.displayName ||
                    `@${$profileQuery?.data?.handle}`,
                  10,
                )}
              </h4>
              <p class="break-words text-sm text-neutral-500">
                <UpdatingDate date={message?.createdAt} />
              </p>
            </div>
            <OpenpeepsMarkdown source={message.content} newTab />
          </div>
        </div>
      </div>
    {:else if attendance.includes(message.type)}
      <div class="flex items-center justify-center">
        <span class="text-center text-sm text-neutral-500">
          {$profileQuery?.data?.displayName ||
            `@${$profileQuery?.data?.handle}`}{' '}
          {attendanceMap[message.type as keyof typeof attendanceMap]} the jam
          <UpdatingDate date={message?.createdAt} />
        </span>
      </div>
    {/if}
  {/if}
</AccessDeniedLoader>

// platform/react/src/components/jams/JamChatMessage.tsx
import { truncateText, type JamEvent } from '@openpeeps/common';
import { useOpenpeeps } from '../../contexts/openpeeps';
import { OpenpeepsMarkdown } from '../markdown/OpenpeepsMarkdown';
import { Avatar } from '../profile/Avatar';
import { UpdatingDate } from '@openpeeps/react-ui';

const attendance = ['join', 'leave', 'start', 'close'] as const;

const attendanceMap = {
  join: 'joined',
  leave: 'left',
  start: 'started',
  close: 'closed',
} as const;

export interface JamChatMessageProps {
  message: JamEvent;
}

export function JamChatMessage({ message }: JamChatMessageProps) {
  const { openpeepsApi } = useOpenpeeps();
  const profileQuery = openpeepsApi.useProfile(message.profileId || 'unknown');
  const profile = profileQuery.data;

  if (!message.profileId) {
    return null;
  }

  if (profileQuery.isLoading) {
    return null;
  }

  if (!profile) {
    return null;
  }

  if (message.type === 'message') {
    return (
      <div className="flex items-center justify-between">
        <div className="grid w-full grid-cols-5 gap-x-1">
          <div className="col-span-1 flex w-full justify-center">
            <Avatar profile={profile} borderless size={2} />
          </div>
          <div className="col-span-4 w-full">
            <div className="flex w-full gap-x-1">
              <h4 className="hidden md:flex">
                {truncateText(profile.displayName || `@${profile.handle}`, 20)}
              </h4>
              <h4 className="flex md:hidden">
                {truncateText(profile.displayName || `@${profile.handle}`, 10)}
              </h4>
              <p className="break-words text-sm text-neutral-500">
                <UpdatingDate date={message.createdAt} />
              </p>
            </div>
            <OpenpeepsMarkdown
              source={message.content ?? ''}
              linkPreviewMode="none"
            />
          </div>
        </div>
      </div>
    );
  }

  if (attendance.includes(message.type as (typeof attendance)[number])) {
    const label =
      attendanceMap[message.type as keyof typeof attendanceMap] ?? message.type;
    return (
      <div className="flex items-center justify-center">
        <span className="text-center text-sm text-neutral-500">
          {profile.displayName || `@${profile.handle}`} {label} the jam{' '}
          <UpdatingDate date={message.createdAt} />
        </span>
      </div>
    );
  }

  return null;
}
