// platform/react-native/src/components/custom/post/types/article/FeedArticle.tsx
import React from 'react';
import type { Article, PublicPost } from '@openpeeps/common/types';
import { Image, View } from 'react-native';
import { ThemedText } from '~/components/ui/themed-text';
import { OpenPeepsMarkdown } from '~/components/custom/markdown';
import { useMemo } from 'react';
import { firstNWords } from '@openpeeps/common';
import { Button } from '~/components/ui/button';
import { ArrowRightIcon } from 'lucide-react-native';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { MainStackParamList } from '~/components/navigation/types';
import { useTranslation } from 'react-i18next';
import { CachedImage } from '~/components/custom/common';

interface Props {
    post: PublicPost;
}

export const FeedArticle = ({ post }: Props) => {

    const article = useMemo(() => post.data as Article, [post]);

    const previewContent = useMemo(() => firstNWords(article.content, 50), [article.content]);
    const navigation = useNavigation<NativeStackNavigationProp<MainStackParamList>>();
    const { t } = useTranslation();

    return (<View className="flex flex-col gap-2">
        {article.image && (
            <CachedImage
                url={article.image}
                className="w-full h-72"
                resizeMode="cover" 
            />
        )}
        <ThemedText className="text-xl font-bold">{article.title}</ThemedText>
        <OpenPeepsMarkdown
            source={previewContent}
            linkPreviewMode="none"
        />
        <View className="w-full flex flex-row justify-end">
            <Button
                onPress={() => navigation.navigate('Post', { id: post.id })}
                className="flex flex-row gap-2 w-48"
            >
                <ThemedText>{t('posts.article.readMore')}</ThemedText>
                <ArrowRightIcon className="w-4 h-4" />
            </Button>
        </View>
    </View>);
};

// platform/svelte/src/lib/components/core/post/types/article/FeedArticle.svelte
<script lang="ts">
  import { ArrowRight } from 'lucide-svelte';
  import { firstNWords } from '@openpeeps/common';
  import type { Article, PublicPost } from '@openpeeps/common/types';
  import { i18nContext } from '$lib/components/i18n';
  import { Button } from '@openpeeps/ui';
  import { OpenpeepsMarkdown } from '$lib/components/core/markdown';

  const { t } = i18nContext();
  interface Props {
    post: PublicPost;
  }

  let { post }: Props = $props();
  let article = $derived(post.data as Article);

  const previewContent = $derived(firstNWords(article.content, 50));
  const showReadMore = $derived(
    article.content && previewContent.length < article.content.length,
  );
</script>

<div class="flex w-full flex-col gap-2">
  {#if article.image}
    <img
      src={article.image}
      class="w-full object-cover"
      alt="image for {article.title}"
    />
  {/if}
  <div class="prose allpeep-markdown">
    <h3 class="h3">{article.title}</h3>
  </div>
  <div>
    <OpenpeepsMarkdown
      source="{previewContent}{showReadMore ? '...' : ''}"
      linkPreviewMode="none"
    />
  </div>
  {#if showReadMore}
    <div class="flex justify-end">
      <Button action="/posts/{post.id}" class="text-primary-500">
        {t('posts.article.readMore')}
        <ArrowRight class="inline-block size-4" />
      </Button>
    </div>
  {/if}
</div>
