// platform/react/src/components/preview-link/LocalPreviewLink.tsx
import { isGroupPath, isJamPath, isPostPath } from './helpers';
import { GroupPreview } from './local/GroupPreview';
import { PostPreview } from './local/PostPreview';
import { JamPreview } from './local/JamPreview';

export interface LocalPreviewLinkProps {
  url: string;
}

export function LocalPreviewLink({ url }: LocalPreviewLinkProps) {
  const path = new URL(url).pathname;
  const isPost = isPostPath(path);
  const isJam = isJamPath(path);
  const isGroup = isGroupPath(path);

  return (
    <a
      href={url}
      className="hover:bg-muted mb-2 block w-full min-w-0 max-w-full overflow-hidden rounded-md border p-3 no-underline"
      onClick={(e) => e.stopPropagation()}
    >
      {isPost ? <PostPreview path={path} /> : null}
      {isGroup ? <GroupPreview path={path} /> : null}
      {isJam ? <JamPreview path={path} /> : null}
    </a>
  );
}

// platform/svelte/src/lib/components/core/preview-link/LocalPreviewLink.svelte
<script lang="ts">
  import { isJamPath, isPostPath, isGroupPath } from './helpers';
  import PostPreview from './local/PostPreview.svelte';
  import JamPreview from './local/JamPreview.svelte';
  import GroupPreview from './local/GroupPreview.svelte';
  import { Button } from '@openpeeps/ui';
  interface Props {
    url: string;
  }

  let { url }: Props = $props();

  const path = new URL(url).pathname;

  const isPost = isPostPath(path);
  const isJam = isJamPath(path);
  const isGroup = isGroupPath(path);
</script>

<Button action={url}>
  <div class="card w-full p-3">
    {#if isPost}
      <PostPreview {path} />
    {:else if isGroup}
      <GroupPreview {path} />
    {:else if isJam}
      <JamPreview {path} />
    {/if}
  </div>
</Button>
