// platform/app/src/routes/(protected)/(private)/settings/+page.svelte
<script lang="ts">
  import { ConfigMenuButton } from '@openpeeps/svelte/components';
  import { getCurrentIdentity } from '@openpeeps/svelte/auth';
  import { getServerInfo } from '@openpeeps/svelte/server';
  import { isOwnerProfile } from '@openpeeps/common';

  const { profile } = getCurrentIdentity();
  const { payments } = getServerInfo();
  const stripeMembershipEnabled = $derived(
    payments?.stripe.paidMembership.enabled && !isOwnerProfile(profile),
  );
</script>

<div class="p-4">
  <ConfigMenuButton
    translationPrefix="settings.publicProfile"
    action="/settings/public-profile"
  />
  <ConfigMenuButton
    translationPrefix="settings.account"
    action="/settings/account"
  />
  <ConfigMenuButton
    translationPrefix="settings.notifications"
    action="/settings/notifications"
  />
  <ConfigMenuButton
    translationPrefix="settings.theme"
    action="/settings/theme"
  />
  <ConfigMenuButton
    translationPrefix="settings.language"
    action="/settings/language"
  />
  <ConfigMenuButton
    translationPrefix="settings.accessTokens"
    action="/settings/access-tokens"
  />
  {#if stripeMembershipEnabled}
    <ConfigMenuButton
      translationPrefix="settings.billing"
      action="/settings/billing"
    />
  {/if}
</div>

// platform/react/src/pages/settings/Index.tsx
import { isOwnerProfile } from '@openpeepshq/common';
import { useSetPageHeader } from '../../index';
import {
  ConfigMenuButton,
  useCurrentProfile,
  useServerInfo,
} from '../../components';

export function Settings() {
  const profile = useCurrentProfile();
  const serverInfo = useServerInfo();

  useSetPageHeader('Settings', undefined, 'settings-page-heading');

  const stripeMembershipEnabled =
    !!serverInfo.payments?.stripe?.paidMembership?.enabled &&
    !(profile && isOwnerProfile(profile));

  return (
    <div className="p-4">
      <ConfigMenuButton
        translationPrefix="settings.publicProfile"
        action="/settings/public-profile"
        testId="settings-link-public-profile"
      />
      <ConfigMenuButton
        translationPrefix="settings.account"
        action="/settings/account"
        testId="settings-link-account"
      />
      <ConfigMenuButton
        translationPrefix="settings.notifications"
        action="/settings/notifications"
        testId="settings-link-notifications"
      />
      <ConfigMenuButton
        translationPrefix="settings.accessTokens"
        action="/settings/access-tokens"
      />
      <ConfigMenuButton
        translationPrefix="settings.theme"
        action="/settings/theme"
        testId="settings-link-theme"
      />
      <ConfigMenuButton
        translationPrefix="settings.language"
        action="/settings/language"
      />
      {stripeMembershipEnabled && (
        <ConfigMenuButton
          translationPrefix="settings.billing"
          action="/settings/billing"
          testId="settings-link-billing"
        />
      )}
    </div>
  );
}
