// platform/app/src/routes/(protected)/(private)/settings/language/+page.svelte
<script lang="ts">
  import { i18nContext, getServerDataContext } from '@openpeeps/svelte/components';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import {
    currentProfileSettingsStore,
    updateProfileSettingsMutation,
  } from '@openpeeps/svelte/api';
  import { Button } from '@openpeeps/ui';
  import { getToastStore } from '@skeletonlabs/skeleton';
  import { toast } from '@openpeeps/svelte';
  import { getCurrentProfile } from '@openpeeps/svelte/auth';
  import { sleep } from '@openpeeps/common';

  const pageHeaderStore = getPageHeaderStore();
  let profileSettingsQuery = currentProfileSettingsStore();
  const currentProfile = getCurrentProfile();

  const updateSettings = updateProfileSettingsMutation();
  const toastStore = getToastStore();
  const { t } = i18nContext();

  const { serverInfo } = getServerDataContext();
  const communityDefaultLanguage = serverInfo?.communityConfig?.settings?.defaultLanguage ?? 'en';

  const AVAILABLE_LANGUAGES = [
    { code: 'en', name: 'English' },
    { code: 'de', name: 'Deutsch' },
  ];

  let language = $state<string>(communityDefaultLanguage);

  const handleSubmit = () =>
    updateSettings({
      id: currentProfile.id,
      language,
    })
      .then(() => {
        localStorage.setItem('openpeeps-language', language);
        toastStore.trigger(
          toast({
            message: t('settings.language.updateSuccess'),
            background: 'variant-filled-success',
          }),
        );
      })
      .then(() => sleep(5))
      .then(() => window.location.reload());

  $effect(() => {
    if ($profileSettingsQuery.data) {
      language = $profileSettingsQuery.data.language ?? communityDefaultLanguage;
    }
  });

  $effect(() => {
    pageHeaderStore.set({
      title: t('settings.language.title'),
    });
  });
</script>

<div class="flex flex-col gap-4 p-3">
  <div class="border p-4">
    <h4 class="my-4 text-lg font-semibold">
      {t('settings.language.title')}
    </h4>
    <span>{t('settings.language.languageDescription')}</span>
    <div class="flex-wrap items-center gap-x-4 gap-y-2 mt-4">
      {#each AVAILABLE_LANGUAGES as lang}
        <div>
          <input
            type="radio"
            class="h-4 w-4"
            bind:group={language}
            value={lang.code}
          />
          <span>
            {lang.name}
            {#if lang.code === communityDefaultLanguage}
              <span class="text-sm opacity-60">{t('settings.language.default')}</span>
            {/if}
          </span>
        </div>
      {/each}
    </div>
  </div>
  <Button variant="variant-ghost-primary" action={handleSubmit}>{t('common.form.save')}</Button>
</div>

// platform/react/src/pages/settings/Language.tsx
import { useEffect, useState } from 'react';
import { useT, useOpenpeeps } from '../../index';
import { useCurrentProfile, useServerInfo } from '../../components';
import { Button, Toast } from '@openpeepshq/react-ui';

const AVAILABLE_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'de', name: 'Deutsch' },
] as const;

export function LanguageSettings() {
  const t = useT();
  const profile = useCurrentProfile();
  const serverInfo = useServerInfo();
  const { openpeepsApi } = useOpenpeeps();
  const settingsQuery = openpeepsApi.useCurrentProfileSettings();
  const updateSettings = openpeepsApi.updateCurrentProfileSettingsAction();

  const communityDefaultLanguage =
    serverInfo.communityConfig?.settings?.defaultLanguage ?? 'en';

  const [language, setLanguage] = useState(communityDefaultLanguage);
  const [saving, setSaving] = useState(false);
  const [status, setStatus] = useState<{
    type: 'success' | 'error';
    message: string;
  } | null>(null);

  useEffect(() => {
    if (settingsQuery.data?.language) {
      setLanguage(settingsQuery.data.language);
    }
  }, [settingsQuery.data?.language]);

  if (!profile) return null;

  const save = async () => {
    setStatus(null);
    setSaving(true);
    try {
      await updateSettings({ id: profile.id, language });
      localStorage.setItem('openpeeps-language', language);
      setStatus({
        type: 'success',
        message: t('settings.language.updateSuccess', {
          defaultValue: 'Language updated. Reloading…',
        }),
      });
      window.setTimeout(() => window.location.reload(), 500);
    } catch (err) {
      setStatus({ type: 'error', message: (err as Error).message });
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="flex flex-col gap-4 p-3">
      <div className="border p-4">
        <h4 className="my-4 text-lg font-semibold">
          {t('settings.language.title', { defaultValue: 'Language' })}
        </h4>
        <span>
          {t('settings.language.languageDescription', {
            defaultValue: 'Choose your preferred language.',
          })}
        </span>
        <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2">
          {AVAILABLE_LANGUAGES.map((lang) => (
            <label key={lang.code} className="flex items-center gap-2">
              <input
                type="radio"
                className="h-4 w-4"
                checked={language === lang.code}
                onChange={() => setLanguage(lang.code)}
              />
              <span>
                {lang.name}
                {lang.code === communityDefaultLanguage ? (
                  <span className="ml-1 text-sm opacity-60">
                    {t('settings.language.default', {
                      defaultValue: '(community default)',
                    })}
                  </span>
                ) : null}
              </span>
            </label>
          ))}
        </div>
      </div>
      {status ? (
        <Toast variant={status.type} onDismiss={() => setStatus(null)}>
          {status.message}
        </Toast>
      ) : null}
      <Button variant="default" action={save} disabled={saving}>
        {t('common.form.save', { defaultValue: 'Save' })}
      </Button>
    </div>
  );
}
