// platform/svelte/src/lib/components/core/post/pieces/PollContent.svelte
<script lang="ts">
	import { Avatar } from '../../profile';
	import { Button } from '@openpeeps/ui';
	import type { PublicPost } from '@openpeeps/common/types';
	import { formatDistanceToNow, isPast } from 'date-fns';
	import { votePollMutation } from '$lib/api';
	import { toast } from '$lib/utils/toast';
	import { getToastStore, ProgressBar } from '@skeletonlabs/skeleton';
	import { preventDefault, stopPropagation } from '@openpeeps/ui';
	import { checkPostCapabilities, collectVotes, groupName, hasValue } from '@openpeeps/common/lib';
	import { getServerDataContext } from '$lib/components/serverData';
	import { getCurrentProfile } from '$lib/auth';
	import { i18nContext } from '$lib/components/i18n';
  import { goto } from '$app/navigation';

	interface Props {
		post: PublicPost;
	}

	let { post }: Props = $props();
	const me = getCurrentProfile();

	const { capabilities } = getServerDataContext();
	const { t } = i18nContext();

	const toastStore = getToastStore();
	const votePoll = votePollMutation({ id: post.id });

	const { votes, voteCounts } = $derived(collectVotes(post));

	let hasPollEnded: boolean = $derived(
		!!(post?.data?.type === 'question' && post.data.expiresAt && isPast(post.data.expiresAt))
	);
	let hasVoted: boolean = $derived(
		!!(me && !!((votes.find((v) => v?.profile?.id === me?.id)?.selection?.length ?? 0) > 0))
	);
	let canVote: boolean = $derived(!!(me && !hasPollEnded && !hasVoted));

	let selectedPollOption: number | undefined = $state();
	let selectedPollOptions: number[] | undefined = $state();

	const handleVote = async () => {
		if (post.data?.type !== 'question') {
			return;
		}
		const hasCapabilities = checkPostCapabilities(['core-posts-vote'], me, post, capabilities)

		if (!hasCapabilities.success) {
			toastStore.trigger(
				toast({
					message: post?.group
						? t('posts.vote.lackPermission', {
								groupName: groupName(post.group),
							})
						: t('posts.vote.lackPermissionNoGroup'),
					action: post?.group
						? {
						label: t('groups.goto'),
						response() {
							if(post?.group){
							goto(`/group/@${post.group.handle}`)
							}
						},
					} : undefined,
					background: 'variant-filled-error'
				})
			);
			return;
		}

		const selection = (
			post?.data.multiple
				? selectedPollOptions
				: hasValue(selectedPollOption)
					? [selectedPollOption]
					: undefined
		) as number[];

		if (selection && selection.length > 0) {
			await votePoll({ selection });
			toastStore.trigger(
				toast({
					message: t('posts.vote.successToast'),
					background: 'variant-filled-success'
				})
			);
		} else {
			toastStore.trigger(
				toast({
					message: t('posts.vote.selectOption'),
					background: 'variant-filled-error'
				})
			);
		}
	};
	const handleClearVote = async () => {
		if (post.data?.type !== 'question') {
			return;
		}
		let selection: number[] = [];
		await votePoll({ selection });
		toastStore.trigger(
			toast({
				message: t('posts.vote.cleared'),
				background: 'variant-filled-success'
			})
		);
	};
</script>

{#if post?.data?.type === 'question'}
	<div class="rounded-md p-4">
		{#each post?.data?.options as option, i (i)}
			<div class="mt-4 flex items-center gap-x-2 rounded-md px-4 py-2" role="none">
				{#if canVote}
					{#if post?.data?.multiple}
						<input
							type="checkbox"
							class="h-4 w-4"
							bind:group={selectedPollOptions}
							onclick={stopPropagation()}
							value={i}
						/>
					{:else}
						<input
							type="radio"
							class="h-4 w-4"
							bind:group={selectedPollOption}
							onclick={stopPropagation()}
							value={i}
						/>
					{/if}
				{/if}
				<div class="w-full">
					<div class="flex justify-between align-middle">
						<span style="line-height: 2.5rem; vertical-align: middle">{option.content}</span>
						<span class="flex align-middle">
							{#if post?.data.votersVisible}
								{#each votes
									.filter((v) => v.selection.includes(i))
									.slice(0, 2) as vote (vote.profile.id)}
									<span class="-ml-4 inline-block">
										<Avatar borderless profile={vote.profile} size={2.5} />
									</span>
								{/each}
							{/if}
							<span style="line-height: 2.5rem; vertical-align: middle">
								{voteCounts[i] ?? 0}
							</span>
						</span>
					</div>
					<ProgressBar
						meter="rounded bg-primary-500"
						value={voteCounts[i] ?? 0}
						max={votes.length || 1}
					/>
				</div>
			</div>
		{/each}

		{#if canVote}
			<Button title={t('posts.poll.vote')} variant="variant-ringed-surface" class="mt-4" action={handleVote}>
				{t('posts.form.poll.submit')}
			</Button>
		{/if}
		<div class="mt-4 flex items-center gap-x-3 text-sm">
			<p>
				{t('posts.vote.votesCount', { count: votes.length || 0 })}
			</p>
			{#if post?.data.expiresAt}
				<p>
					{#if hasPollEnded}
						{t('posts.poll.ended')}
					{:else}
						{formatDistanceToNow(post?.data.expiresAt)} {t('posts.poll.timeLeft')}
					{/if}
				</p>
			{/if}
			{#if hasVoted && !hasPollEnded}
				<button
					title={t('posts.poll.undoVoteTitle')}
					class="text-primary-500 mt-[-2px] text-base font-semibold"
					onclick={stopPropagation(preventDefault(handleClearVote))}>{t('posts.poll.undo')}</button
				>
			{/if}
		</div>
	</div>
{/if}

// platform/rn-components/src/components/custom/post/pieces/PollContent.tsx
import React, { useState } from 'react';
import { View, TouchableOpacity } from 'react-native';
import { ThemedText as Text } from '~/components/ui/themed-text';
import { hasValue, type PublicPost } from '@openpeepshq/common';
import { collectVotes } from '@openpeepshq/common';
import { formatDistanceToNow, isPast } from 'date-fns';
import { useOpenpeeps } from '@openpeepshq/react';
import Toast from 'react-native-toast-message';
import { Button } from '~/components/ui/button';
import { Checkbox } from '~/components/ui/checkbox';
import { useTranslation } from 'react-i18next';
import { ProfileAvatar } from '~/components/custom/profile/profile-avatar';

interface Props {
  post: PublicPost;
}

export const PollContent = ({ post }: Props) => {
  const { t } = useTranslation();
  const [selectedPollOption, setSelectedPollOption] = useState<number>();
  const [selectedPollOptions, setSelectedPollOptions] = useState<number[]>([]);

  const { openpeepsApi, currentProfile } = useOpenpeeps();

  const { votes, voteCounts } = collectVotes(post);

  const votePoll = openpeepsApi.voteOnPostAction({ id: post!.id });

  let hasPollEnded: boolean = !!(
    post?.data?.type === 'question' &&
    post.data.expiresAt &&
    isPast(post.data.expiresAt)
  );

  let hasVoted: boolean = !!(
    currentProfile &&
    (votes.find((v) => v?.profile?.id === currentProfile.id)?.selection
      ?.length ?? 0) > 0
  );

  let canVote: boolean = !!(currentProfile && !hasPollEnded && !hasVoted);

  const handleVote = async () => {
    if (post?.data?.type !== 'question') {
      return;
    }

    const selection = (
      post?.data.multiple
        ? selectedPollOptions
        : hasValue(selectedPollOption)
          ? [selectedPollOption]
          : undefined
    ) as number[];
    if (selection && selection.length > 0) {
      try {
        await votePoll({
          selection,
        });
        Toast.show({
          type: 'success',
          text1: t('posts.vote.success'),
        });
      } catch (error) {
        Toast.show({
          type: 'error',
          text1: t('posts.vote.error'),
          text2:
            error instanceof Error ? error.message : t('common.errors.error'),
        });
      }
    } else {
      Toast.show({
        type: 'error',
        text1: t('posts.poll.selectOption'),
      });
    }
  };

  const handleClearVote = async () => {
    if (post?.data?.type !== 'question') {
      return;
    }

    try {
      await votePoll({
        selection: [],
      });
      Toast.show({
        type: 'success',
        text1: t('posts.poll.undoVote'),
      });
    } catch (error) {
      Toast.show({
        type: 'error',
        text1: t('posts.vote.error'),
        text2:
          error instanceof Error ? error.message : t('common.errors.error'),
      });
    }
  };

  return (
    <View className="bg-surface rounded-lg px-4 py-4">
      <View className="gap-4">
        {post?.data?.type === 'question' &&
          post.data.options.map((option, index) => {
            const voteCount = voteCounts[index] ?? 0;
            const votePercent = (voteCount / (votes.length || 1)) * 100;

            return (
              <View
                key={`${option.content}-${index}`}
                className="flex-row items-center gap-2 py-2"
              >
                {canVote && (
                  <>
                    {post?.data?.type === 'question' && post.data.multiple ? (
                      <Checkbox
                        checked={selectedPollOptions.includes(index)}
                        onCheckedChange={() => {
                          setSelectedPollOptions((prev) => {
                            if (prev.includes(index)) {
                              return prev.filter((i) => i !== index);
                            }
                            return [...prev, index];
                          });
                        }}
                      />
                    ) : (
                      <TouchableOpacity
                        onPress={() => setSelectedPollOption(index)}
                        className="flex-row items-center gap-2"
                      >
                        <View className="h-5 w-5 rounded-full border border-muted-foreground justify-center items-center">
                          {selectedPollOption === index && (
                            <View className="h-3 w-3 rounded-full bg-primary" />
                          )}
                        </View>
                      </TouchableOpacity>
                    )}
                  </>
                )}
                <View className="flex-1">
                  <View className="flex-row items-center justify-between gap-2">
                    <Text className="flex-1 text-base">{option.content}</Text>
                    <View className="flex-row items-center gap-2">
                      {post?.data?.type === 'question' &&
                        post.data.votersVisible && (
                          <View className="flex-row">
                            {votes
                              .filter((v) => v.selection.includes(index))
                              .slice(0, 2)
                              .map((vote) => (
                                <View
                                  key={`${vote.profile.displayName}-${vote.profile.id}`}
                                  className="-ml-4"
                                >
                                  <ProfileAvatar
                                    profile={vote.profile}
                                    className="size-6"
                                  />
                                </View>
                              ))}
                          </View>
                        )}
                      <Text>{voteCount}</Text>
                    </View>
                  </View>
                  <View className="bg-border mt-2 h-2 overflow-hidden rounded-full">
                    <View
                      className="bg-primary h-full rounded-full"
                      style={{
                        width: votePercent === 0 ? 8 : `${votePercent}%`,
                      }}
                    />
                  </View>
                </View>
              </View>
            );
          })}
      </View>

      {canVote && (
        <Button variant="outline" className="mt-4 w-32" onPress={handleVote}>
          <Text>{t('posts.form.poll.submit')}</Text>
        </Button>
      )}

      <View className="mt-4 flex-row items-center gap-3">
        <Text className="text-sm text-muted-foreground">
          {`${votes.length || 0} ${t('posts.vote.count')}`}
        </Text>
        {post?.data?.type === 'question' && post.data.expiresAt && (
          <Text className="text-sm text-muted-foreground">
            {hasPollEnded
              ? t('posts.poll.ended')
              : `${formatDistanceToNow(post.data.expiresAt)} ${t(
                  'posts.poll.timeLeft'
                )}`}
          </Text>
        )}
        {hasVoted && !hasPollEnded && (
          <TouchableOpacity onPress={handleClearVote}>
            <Text className="text-primary font-semibold">
              {t('posts.poll.undoVote')}
            </Text>
          </TouchableOpacity>
        )}
      </View>
    </View>
  );
};
