// platform/app/src/routes/(protected)/(private)/admin/diagnostics/+page.svelte
<script lang="ts">
  import { ConfigMenuButton } from '@openpeeps/svelte/components';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { i18nContext } from '@openpeeps/svelte/components/i18n';

  const { t } = i18nContext();

  getPageHeaderStore().set({
    title: t('diagnostics.title'),
  });
</script>

<div class="p-4">
  <ConfigMenuButton
    translationPrefix="diagnostics.email"
    action="/admin/diagnostics/email"
  ></ConfigMenuButton>
  <ConfigMenuButton
    translationPrefix="diagnostics.logs"
    action="/admin/diagnostics/logs"
  ></ConfigMenuButton>
</div>

// platform/react/src/pages/admin/Diagnostics.tsx
import { useT, useSetPageHeader } from '../../index';
import { ConfigMenuButton } from '../../components';

export function AdminDiagnostics() {
  const t = useT();

  useSetPageHeader(t('diagnostics.title', { defaultValue: 'Diagnostics' }));

  return (
    <div className="p-4">
      <ConfigMenuButton
        translationPrefix="diagnostics.email"
        action="/admin/diagnostics/email"
      />
      <ConfigMenuButton
        translationPrefix="diagnostics.logs"
        action="/admin/diagnostics/logs"
      />
      <ConfigMenuButton
        translationPrefix="diagnostics.performance"
        action="/admin/diagnostics/performance"
      />
    </div>
  );
}
