// platform/app/src/routes/(protected)/(private)/admin/invites/+page.svelte
<script lang="ts">
  import {
    getModalStore,
    type ModalComponent,
    type ModalSettings,
  } from '@skeletonlabs/skeleton';
  import { page } from '$app/state';
  import {
    SearchAndFilterBar,
    Badge,
    Table,
    UpdatingDate,
  } from '@openpeeps/ui';
  import {
    SortModal,
    FilterModal,
    InvitesTablePopup,
    InviteLinksHeaderActions,
    AccessDeniedLoader,
  } from '@openpeeps/svelte/components';
  import { type ColumnDefinition } from '@openpeeps/ui';
  import { getInvitesListStore } from '@openpeeps/svelte/api';
  import type { InviteLinkWithMeta } from '@openpeeps/common/types';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { inviteLinkMatchesQuery } from '@openpeeps/common/lib';
  import { i18nContext } from '@openpeeps/svelte/components/i18n';

  const { t } = i18nContext();

  const inviteListQuery = getInvitesListStore();

  const modalStore = getModalStore();

  const pageHeaderStore = getPageHeaderStore();

  const sortComponent: ModalComponent = { ref: SortModal };
  const filterComponent: ModalComponent = { ref: FilterModal };

  let tabSet: number = $state(0);
  let search = $state('');

  export const sortModal: ModalSettings = {
    type: 'component',
    component: sortComponent,
  };

  export const filterModal: ModalSettings = {
    type: 'component',
    component: filterComponent,
  };

  const inviteListColumns: ColumnDefinition<InviteLinkWithMeta>[] = [
    {
      type: 'property',
      header: t('admin.invites.linkColumn'),
      id: 'slug',
    },
    {
      id: 'creator',
      type: 'text',
      header: t('admin.invites.createdByColumn'),
      render: (inviteLink) => '@' + inviteLink.profile.handle,
    },
    {
      id: 'groups',
      type: 'text',
      header: t('admin.invites.groupsColumn'),
      render: (inviteLink) =>
        inviteLink.groups
          .map((group) => group.displayName || '@' + group.handle)
          .join(', ') || '—',
    },
    {
      id: 'dateCreated',
      header: t('admin.invites.expirationDateColumn'),
      type: 'component',
      render: (inviteLink) => ({
        component: UpdatingDate,
        props: { date: inviteLink.expiresAt },
      }),
    },
    {
      id: 'uses',
      header: t('admin.invites.usesColumn'),
      type: 'text',
      render: (invite) => `${invite.redemptions.length}/${invite.maxUses}`,
    },
    {
      id: 'status',
      header: t('admin.invites.statusColumn'),
      type: 'component',
      render: (invite) => {
        const active = invite.active && new Date(invite.expiresAt) > new Date();
        return {
          component: Badge,
          props: {
            status: active ? 'active' : 'inactive',
            variant: active ? 'variant-filled-success' : 'variant-filled-error',
          },
        };
      },
    },
    {
      id: 'action',
      type: 'component',
      header: ' ',
      render: (inviteLink) => ({
        component: InvitesTablePopup,
        props: {
          inviteLink,
        },
      }),
    },
  ];

  $effect(() => {
    if (page.url.hash.includes('link')) {
      tabSet = 1;
      pageHeaderStore.set({
        title: t('admin.invites.title'),
        actions: InviteLinksHeaderActions,
      });
    } else {
      tabSet = 0;
      pageHeaderStore.set({ title: t('admin.invites.title') });
    }
  });
</script>

<div class="relative">
  <div
    class="z-10 w-full border-b flex justify-between items-center px-5 py-2 sticky top-14"
  >
    <h4>{t('admin.invites.linkHeading')}</h4>
    <InviteLinksHeaderActions />
  </div>
  <div class="relative">
    <AccessDeniedLoader queries={[$inviteListQuery]}>
      {#snippet error()}
        <div>
          <div class="w-full flex justify-center items-center p-4">
            <h2 class="text-lg text-error-500">
              Error: {$inviteListQuery?.error?.message}
            </h2>
          </div>
        </div>
      {/snippet}
      {#if $inviteListQuery?.data?.length === 0}
        <div class="w-full flex justify-center items-center p-4">
          <h2 class="text-lg">{t('admin.invites.noInvitesFound')}</h2>
        </div>
      {:else}
        <div class="relative">
          <SearchAndFilterBar
            className="sticky top-28"
            bind:search
            placeholder={t('admin.invites.searchPlaceholder')}
            handleOnSortButtonClicked={() => modalStore.trigger(sortModal)}
            handleOnFilterButtonClicked={() => modalStore.trigger(filterModal)}
          />

          <Table
            data={$inviteListQuery.data}
            columnDefinitions={inviteListColumns}
            filter={(row) => !search || inviteLinkMatchesQuery(row, search)}
          />
        </div>
      {/if}
    </AccessDeniedLoader>
  </div>
</div>

// platform/react/src/pages/admin/Invites.tsx
import { useMemo, useState } from 'react';
import { CheckCheck, Copy, MoreVertical, Users, X } from 'lucide-react';
import { inviteLinkMatchesQuery } from '@openpeepshq/common/lib';
import type { InviteLinkWithMeta } from '@openpeepshq/common/types';
import { useT, useOpenpeeps, useSetPageHeader } from '../../index';
import { Avatar } from '../../components';
import { UpdatingDate } from '@openpeepshq/react-ui';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  Input,
  PopupMenu,
  PopupMenuButton,
} from '@openpeepshq/react-ui';
import { AdminInviteActions } from './components/AdminInviteActions';
import { inviteUrl } from './components/InviteWithLinkModal';

export function AdminInvites() {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const invitesQuery = openpeepsApi.admin.useInvitesList();
  const [search, setSearch] = useState('');

  const headerActions = useMemo(() => <AdminInviteActions />, []);

  useSetPageHeader(
    t('admin.invites.title', { defaultValue: 'Invites' }),
    headerActions,
  );

  const invites = (invitesQuery.data ?? []) as InviteLinkWithMeta[];
  const filtered = search
    ? invites.filter((i) => inviteLinkMatchesQuery(i, search))
    : invites;

  return (
    <div className="p-4">
      <div className="mb-4">
        <Input
          placeholder={t('admin.invites.searchPlaceholder', {
            defaultValue: 'Search by name or email',
          })}
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      {filtered.length === 0 ? (
        <div className="flex w-full items-center justify-center p-4">
          <h2 className="text-lg">
            {t('admin.invites.noInvitesFound', {
              defaultValue: 'No invites found',
            })}
          </h2>
        </div>
      ) : (
        <div className="rounded-md border">
          <table className="w-full text-sm">
            <thead className="bg-surface">
              <tr>
                <th className="p-2 text-left">
                  {t('admin.invites.linkColumn', { defaultValue: 'Link' })}
                </th>
                <th className="p-2 text-left">
                  {t('admin.invites.createdByColumn', {
                    defaultValue: 'Created by',
                  })}
                </th>
                <th className="p-2 text-left">
                  {t('admin.invites.groupsColumn', { defaultValue: 'Groups' })}
                </th>
                <th className="p-2 text-left">
                  {t('admin.invites.expirationDateColumn', {
                    defaultValue: 'Expires',
                  })}
                </th>
                <th className="p-2 text-left">
                  {t('admin.invites.usesColumn', { defaultValue: 'Uses' })}
                </th>
                <th className="p-2 text-left">
                  {t('admin.invites.statusColumn', { defaultValue: 'Status' })}
                </th>
                <th className="p-2"></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((invite) => {
                const active =
                  invite.active && new Date(invite.expiresAt) > new Date();
                return (
                  <tr key={invite.id} className="border-t">
                    <td className="p-2 font-mono text-xs">{invite.slug}</td>
                    <td className="p-2">@{invite.profile.handle}</td>
                    <td className="p-2 text-xs">
                      {invite.groups
                        .map((g) => g.displayName || `@${g.handle}`)
                        .join(', ') || '—'}
                    </td>
                    <td className="p-2 text-xs">
                      <UpdatingDate date={invite.expiresAt} />
                    </td>
                    <td className="p-2 text-xs">
                      {invite.redemptions.length}/{invite.maxUses}
                    </td>
                    <td className="p-2 text-xs">
                      <span
                        className={`rounded px-2 py-0.5 ${active ? 'bg-success/20 text-success' : 'bg-error/20 text-error'}`}
                      >
                        {active
                          ? t('admin.invites.statusActive', {
                              defaultValue: 'Active',
                            })
                          : t('admin.invites.statusInactive', {
                              defaultValue: 'Inactive',
                            })}
                      </span>
                    </td>
                    <td className="p-2 text-right">
                      <InvitesTablePopup invite={invite} />
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function InvitesTablePopup({ invite }: { invite: InviteLinkWithMeta }) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const activate = openpeepsApi.admin.activateInviteAction();
  const deactivate = openpeepsApi.admin.deactivateInviteAction();
  const [showInvited, setShowInvited] = useState(false);

  const active = invite.active && new Date(invite.expiresAt) > new Date();
  const expired = new Date(invite.expiresAt) <= new Date();

  return (
    <>
      <PopupMenu placement="bottom-end" width="w-56" icon={MoreVertical}>
        <PopupMenuButton
          icon={Users}
          title={t('admin.invites.seeInvitedAccounts', {
            defaultValue: 'See invited accounts',
          })}
          text={t('admin.invites.seeInvitedAccounts', {
            defaultValue: 'See invited accounts',
          })}
          action={() => setShowInvited(true)}
        />
        {active ? (
          <>
            <PopupMenuButton
              icon={Copy}
              title={t('admin.invites.copyLink', {
                defaultValue: 'Copy link',
              })}
              text={t('admin.invites.copyLink', { defaultValue: 'Copy link' })}
              action={() =>
                void navigator.clipboard.writeText(inviteUrl(invite.slug))
              }
            />
            <PopupMenuButton
              icon={X}
              title={t('admin.invites.deactivate', {
                defaultValue: 'Deactivate',
              })}
              text={t('admin.invites.deactivate', {
                defaultValue: 'Deactivate',
              })}
              action={() => deactivate({ id: invite.id })}
            />
          </>
        ) : !expired ? (
          <PopupMenuButton
            icon={CheckCheck}
            title={t('admin.invites.activate', { defaultValue: 'Activate' })}
            text={t('admin.invites.activate', { defaultValue: 'Activate' })}
            action={() => activate({ id: invite.id })}
          />
        ) : null}
      </PopupMenu>

      {showInvited ? (
        <ListOfInvitedMembers
          invite={invite}
          onClose={() => setShowInvited(false)}
        />
      ) : null}
    </>
  );
}

function ListOfInvitedMembers({
  invite,
  onClose,
}: {
  invite: InviteLinkWithMeta;
  onClose: () => void;
}) {
  const t = useT();

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>
            {t('admin.invites.invitedMembers', {
              defaultValue: 'Invited members',
            })}
          </DialogTitle>
        </DialogHeader>
        <div className="max-h-[50vh] space-y-2 overflow-y-auto px-1">
          {invite.redemptions.length === 0 ? (
            <p className="text-muted-foreground text-sm">
              {t('admin.invites.noJoinedAccounts', {
                defaultValue: 'No accounts have joined with this link yet.',
              })}
            </p>
          ) : (
            invite.redemptions.map((profile) => (
              <a
                key={profile.id}
                href={`/@${profile.handle}`}
                className="hover:bg-surface flex items-center gap-2 rounded-md p-2"
              >
                <Avatar profile={profile} size={2} />
                <span>{profile.displayName || `@${profile.handle}`}</span>
              </a>
            ))
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
