// platform/web/src/pages/About.tsx
import { Link as RouterLink, useNavigate } from 'react-router-dom';
import { Link } from '@openpeeps/react-ui';
import { useT } from '@openpeeps/react';
import {
  AuthLayout,
  useCurrentProfile,
  useServerInfo,
} from '@openpeeps/react/components';

import { Markdown } from '../lib/Markdown';

export function About() {
  const t = useT();
  const navigate = useNavigate();
  const serverInfo = useServerInfo();
  const currentProfile = useCurrentProfile();

  const communityName = serverInfo.communityConfig?.info?.name ?? 'AllPeep';
  const aboutPage =
    serverInfo.communityConfig?.content?.aboutPage ??
    'This is a community hosted on AllPeep.';

  return (
    <AuthLayout noRedirect navigate={navigate}>
      <h1 className="h1 pb-4 font-bold">
        {t('about.welcomeTo', {
          defaultValue: `Welcome to ${communityName}`,
          name: communityName,
        })}
      </h1>

      <Markdown source={aboutPage} />

      {!currentProfile && (
        <div className="flex justify-between px-2 pt-4">
          {serverInfo.communityConfig?.settings?.openRegistrations && (
            <span>
              Don't have an account?{' '}
              <Link action="/auth/register" className="text-sm">
                Sign Up
              </Link>
            </span>
          )}
          {serverInfo.publicContent && (
            <span>
              <RouterLink to="/feeds/local" className="op-anchor text-sm">
                See community feed
              </RouterLink>
            </span>
          )}
        </div>
      )}
    </AuthLayout>
  );
}

// platform/app/src/routes/about/+page.svelte
<script lang="ts">
  import { getCurrentProfile } from '@openpeeps/svelte/auth';
  import {
    OpenpeepsMarkdown,
    AuthLayout,
    getServerDataContext,
  } from '@openpeeps/svelte/components';
  import { Link } from '@openpeeps/ui';

  let { serverInfo } = getServerDataContext();
  const currentProfile = getCurrentProfile();

</script>

<AuthLayout noRedirect>
  <h1 class="h1 pb-4 font-bold">
    Welcome to {serverInfo?.communityConfig.info.name}
  </h1>

  <OpenpeepsMarkdown
    source={serverInfo?.communityConfig.content?.aboutPage ||
      'This is a community hosted on AllPeep.'}
  />
  {#if !currentProfile}
    <div class="flex justify-between px-2">
      {#if serverInfo.communityConfig.settings.openRegistrations}
        <span>
          Don't have an account?
          <Link action="/auth/register" class="text-sm">Sign Up</Link>
        </span>
      {/if}
      <span>
        {#if serverInfo.publicContent}
          <Link action="/feeds/local" class="text-sm">See community feed</Link>
        {/if}
      </span>
    </div>
  {/if}
</AuthLayout>
