// platform/react-native/src/components/custom/post/feed/chronological/FeedPost.tsx
import { type PublicPost } from '@openpeeps/common';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { MainStackParamList } from '~/components/navigation/types';
import {
    PostHeader,
    PostActions,
    FeedPostContent,
    PostReactionHeader,
} from '../../pieces';
import React from 'react';
import { ThreadPost } from '../threaded/ThreadPost';
import { ThemedView } from '~/components/ui/themed-view';

interface FeedPostProps {
    post: PublicPost;
    accessible?: boolean;
    hideReply?: boolean;
    previewMode?: boolean;
    showMenu?: boolean;
    inGroup?: boolean;
    refetch?: () => void;
    showReplyTo?: boolean;
    showReactionHeader?: boolean;
}

export const FeedPost = ({
    post,
    hideReply,
    previewMode = false,
    showMenu = true,
    inGroup = false,
    showReplyTo = false,
    showReactionHeader = true,
}: FeedPostProps) => {
    const navigation =
        useNavigation<NativeStackNavigationProp<MainStackParamList>>();

    const displayedPost = post.repost || post;

    if (!post) { return null; }

    const handlePostPress = () => {
        navigation.navigate('Post', {
            id: displayedPost.id,
        });
    };

    if (!displayedPost?.profile) {
        return <></>;
    }

    return (
        <ThemedView className="py-5 border-b border-border">
            {showReactionHeader && (

                <PostReactionHeader
                    post={post}
                    inGroup={inGroup}
                    hideReply={hideReply}
                    previewMode={previewMode}
                />
            )}
            {post.replyTo && showReplyTo ? (
                <ThreadPost
                    post={post.replyTo as PublicPost}
                    isParent={true}
                    isChild={false}
                    noActions={true}
                    noMenu={true}
                />
            ) : null}

            <PostHeader
                post={displayedPost}
                showMenu={!post.repost && !post.inReplyToId && !previewMode && showMenu}
            />

            <ThemedView className="px-5">
                <FeedPostContent post={displayedPost} />
            </ThemedView>
            <PostActions
                post={displayedPost}
                previewMode={previewMode}
                onPostPress={handlePostPress}
            />
        </ThemedView>
    );
};

// platform/svelte/src/lib/components/core/post/feed/chronological/FeedPost.svelte
<script lang="ts">
  import type { PublicPost } from '@openpeeps/common/types';
  import PostReactionHeader from '$lib/components/core/post/pieces/PostReactionHeader.svelte';
  import PostInfoHeader from '$lib/components/core/post/pieces/PostInfoHeader.svelte';
  import FeedPostStats from '$lib/components/core/post/pieces/FullPostStats.svelte';
  import FeedPostActions from '$lib/components/core/post/pieces/PostActions.svelte';
  import FeedPostContent from '$lib/components/core/post/pieces/FeedPostContent.svelte';
  import ThreadPost from '../threaded/ThreadPost.svelte';
  import type { Snippet } from 'svelte';

  interface Props {
    post: PublicPost;
    deleteCallback?: () => void;
    noReactionHeader?: boolean;
    inGroup?: boolean;
    showReplyTo?: boolean;
    content?: Snippet;
  }

  let {
    post,
    deleteCallback = () => undefined,
    noReactionHeader = false,
    inGroup = false,
    showReplyTo = false,
    content = undefined,
  }: Props = $props();

  const hasReactionHeader =
    !noReactionHeader &&
    (!!post.repost || !!post.inReplyToId || (!!post.groupId && !inGroup));

  let displayedPost: PublicPost = $derived(post?.repost || post);
  let hasStats: boolean = $derived(
    !!(
      displayedPost?.repostCount ||
      displayedPost?.reactions.length ||
      displayedPost?.replyCount
    ),
  );
</script>

<div class="border-b p-4">
  {#if hasReactionHeader}
    <PostReactionHeader {post} {deleteCallback} {inGroup} />
  {/if}
  {#if displayedPost.replyTo && showReplyTo}
    <a href="/posts/{displayedPost.replyTo.id}">
      <ThreadPost
        post={displayedPost.replyTo as PublicPost}
        isParent
        noActions
        noMenu
      />
    </a>
  {/if}
  <div>
    <PostInfoHeader
      post={displayedPost}
      showMenu={!hasReactionHeader}
      {deleteCallback}
    />
    <div class="pb-2">
      {#if content}
        {@render content()}
      {:else}
        <FeedPostContent post={displayedPost} />
      {/if}
    </div>
    {#if hasStats}
      <FeedPostStats post={displayedPost} />
    {/if}
  </div>
  <FeedPostActions post={displayedPost} />
</div>
