// platform/react/src/components/post/FeedPost.tsx
import type { ReactNode, RefObject } from 'react';
import type { PublicPost } from '@openpeeps/common/types';
import { usePostViewRef } from '../../lib/postViewCounter';

import { FeedPostContent } from './FeedPostContent';
import { PostInfoHeader } from './pieces/PostInfoHeader';
import { PostReactionHeader } from './pieces/PostReactionHeader';
import { FeedPostStats } from './pieces/FeedPostStats';
import { PostActions } from './pieces/PostActions';
import { ThreadPost } from './feed/threaded/ThreadPost';

export interface FeedPostProps {
  post: PublicPost;
  deleteCallback?: () => void;
  noReactionHeader?: boolean;
  inGroup?: boolean;
  showReplyTo?: boolean;
  /** Optional override for the body (used when threading). */
  content?: ReactNode;
}

/**
 * Single post card for the chronological feed. Mirrors `FeedPost.svelte`:
 * shows a small reaction/reply/group banner, the author header, the body,
 * stats and actions. The body component dispatches on `post.type`.
 */
export function FeedPost({
  post,
  deleteCallback,
  noReactionHeader = false,
  inGroup = false,
  showReplyTo = false,
  content,
}: FeedPostProps) {
  const postViewRef = usePostViewRef(post.id) as RefObject<HTMLDivElement>;
  const hasReactionHeader =
    !noReactionHeader &&
    (!!post.repost || !!post.inReplyToId || (!!post.groupId && !inGroup));

  const displayedPost: PublicPost = post.repost ?? post;
  const hasStats = !!(
    displayedPost?.repostCount ||
    displayedPost?.reactions?.length ||
    displayedPost?.replyCount
  );

  return (
    <div ref={postViewRef} className="border-b p-4">
      {hasReactionHeader && (
        <PostReactionHeader post={post} inGroup={inGroup} />
      )}

      {displayedPost.replyTo && showReplyTo && (
        <a href={`/posts/${displayedPost.replyTo.id}`}>
          <ThreadPost
            post={displayedPost.replyTo as PublicPost}
            isParent
            noActions
            noMenu
          />
        </a>
      )}

      <div>
        <PostInfoHeader
          post={displayedPost}
          showMenu={!hasReactionHeader}
          deleteCallback={deleteCallback}
        />
        <div className="min-w-0 pb-2">
          {content ?? <FeedPostContent post={displayedPost} />}
        </div>
        {hasStats && <FeedPostStats post={displayedPost} />}
      </div>

      <PostActions post={displayedPost} />
    </div>
  );
}

// platform/svelte/src/lib/components/core/post/feed/chronological/FeedPost.svelte
<script lang="ts">
  import type { PublicPost } from '@openpeeps/common/types';
  import PostReactionHeader from '$lib/components/core/post/pieces/PostReactionHeader.svelte';
  import PostInfoHeader from '$lib/components/core/post/pieces/PostInfoHeader.svelte';
  import FeedPostStats from '$lib/components/core/post/pieces/FullPostStats.svelte';
  import FeedPostActions from '$lib/components/core/post/pieces/PostActions.svelte';
  import FeedPostContent from '$lib/components/core/post/pieces/FeedPostContent.svelte';
  import ThreadPost from '../threaded/ThreadPost.svelte';
  import type { Snippet } from 'svelte';
  import { postViewCounter } from '$lib/utils';

  interface Props {
    post: PublicPost;
    deleteCallback?: () => void;
    noReactionHeader?: boolean;
    inGroup?: boolean;
    showReplyTo?: boolean;
    content?: Snippet;
  }

  let {
    post,
    deleteCallback = () => undefined,
    noReactionHeader = false,
    inGroup = false,
    showReplyTo = false,
    content = undefined,
  }: Props = $props();

  const hasReactionHeader =
    !noReactionHeader &&
    (!!post.repost || !!post.inReplyToId || (!!post.groupId && !inGroup));

  let displayedPost: PublicPost = $derived(post?.repost || post);
  let hasStats: boolean = $derived(
    !!(
      displayedPost?.repostCount ||
      displayedPost?.reactions.length ||
      displayedPost?.replyCount
    ),
  );
</script>

<div class="border-b p-4" use:postViewCounter={post.id}>
  {#if hasReactionHeader}
    <PostReactionHeader {post} {deleteCallback} {inGroup} />
  {/if}
  {#if displayedPost.replyTo && showReplyTo}
    <a href="/posts/{displayedPost.replyTo.id}">
      <ThreadPost
        post={displayedPost.replyTo as PublicPost}
        isParent
        noActions
        noMenu
      />
    </a>
  {/if}
  <div>
    <PostInfoHeader
      post={displayedPost}
      showMenu={!hasReactionHeader}
      {deleteCallback}
    />
    <div class="pb-2">
      {#if content}
        {@render content()}
      {:else}
        <FeedPostContent post={displayedPost} />
      {/if}
    </div>
    {#if hasStats}
      <FeedPostStats post={displayedPost} />
    {/if}
  </div>
  <FeedPostActions post={displayedPost} />
</div>
