// platform/rn-components/src/components/jams/JamChatMessage.tsx
import React, { useMemo } from 'react';
import { View } from 'react-native';
import {
  truncateText,
  type JamEvent,
  type PublicProfile,
} from '@openpeepshq/common';
import { useOpenpeeps } from '@openpeepshq/react';
import { UpdatingDate } from '~/components/custom/date/updating-date';
import { OpenpeepsMarkdown } from '~/components/markdown';
import { ThemedText } from '~/components/ui/themed-text';
import { ProfileAvatar } from '../profile/Avatar';

const attendance = ['join', 'leave', 'start', 'close'] as const;

const attendanceMap = {
  join: 'joined',
  leave: 'left',
  start: 'started',
  close: 'closed',
} as const;

export interface JamChatMessageProps {
  message: JamEvent;
  mentionProfiles?: PublicProfile[];
}

export const JamChatMessage = ({
  message,
  mentionProfiles = [],
}: JamChatMessageProps) => {
  const { openpeepsApi } = useOpenpeeps();
  const profileQuery = openpeepsApi.useProfile(message.profileId || 'unknown');
  const profile = profileQuery.data;
  const mentions = useMemo(() => {
    const items = mentionProfiles.map((item) => ({ profile: item }));
    if (!profile) return items;
    if (items.some((item) => item.profile.id === profile.id)) return items;
    return [{ profile }, ...items];
  }, [mentionProfiles, profile]);

  if (!message.profileId || profileQuery.isLoading || !profile) {
    return null;
  }

  const name = profile.displayName || `@${profile.handle}`;

  if (message.type === 'message') {
    return (
      <View className="w-full flex-row gap-x-1">
        <View className="w-1/5 items-center">
          <ProfileAvatar profile={profile} className="size-8" />
        </View>
        <View className="w-4/5">
          <View className="w-full flex-row items-center gap-x-1">
            <ThemedText className="font-semibold">
              {truncateText(name, 10)}
            </ThemedText>
            <ThemedText className="text-sm text-muted-foreground">
              <UpdatingDate date={message.createdAt} />
            </ThemedText>
          </View>
          <OpenpeepsMarkdown
            source={message.content ?? ''}
            mentions={mentions}
            linkPreviewMode="none"
          />
        </View>
      </View>
    );
  }

  if (attendance.includes(message.type as (typeof attendance)[number])) {
    const label =
      attendanceMap[message.type as keyof typeof attendanceMap] ?? message.type;
    return (
      <View className="items-center justify-center">
        <ThemedText className="text-center text-sm text-muted-foreground">
          {name} {label} the jam <UpdatingDate date={message.createdAt} />
        </ThemedText>
      </View>
    );
  }

  return null;
};

// platform/svelte/src/lib/components/core/jams/pieces/JamChatMessage.svelte
<script lang="ts">
  import { truncateText, type JamEvent } from '@openpeeps/common';
  import { UpdatingDate } from '@openpeeps/ui';
  import { OpenpeepsMarkdown } from '../../markdown';
  import { Avatar } from '../../profile';
  import { profileStore } from '$lib/api';
  import { AccessDeniedLoader } from '$lib/components/layout';

  interface JamChatMessageProps {
    message: JamEvent;
  }

  const attendance = ['join', 'leave', 'start', 'close'];

  const attendanceMap = {
    join: 'joined',
    leave: 'left',
    start: 'started',
    close: 'closed',
  };

  let { message }: JamChatMessageProps = $props();

  let profileQuery = profileStore(message.profileId);
</script>

<AccessDeniedLoader queries={[$profileQuery]}>
  {#if $profileQuery.isSuccess}
    {#if message.type === 'message'}
      <div class="flex items-center justify-between">
        <div class="grid w-full grid-cols-5 gap-x-1">
          <div class="col-span-1 flex w-full justify-center">
            <Avatar profile={$profileQuery?.data} borderless size={2} />
          </div>
          <div class="col-span-4 w-full">
            <div class="flex w-full gap-x-1">
              <h4 class="hidden md:flex">
                {truncateText(
                  $profileQuery?.data?.displayName ||
                    `@${$profileQuery?.data?.handle}`,
                  20,
                )}
              </h4>
              <h4 class="flex md:hidden">
                {truncateText(
                  $profileQuery?.data?.displayName ||
                    `@${$profileQuery?.data?.handle}`,
                  10,
                )}
              </h4>
              <p class="break-words text-sm text-neutral-500">
                <UpdatingDate date={message?.createdAt} />
              </p>
            </div>
            <OpenpeepsMarkdown source={message.content} newTab />
          </div>
        </div>
      </div>
    {:else if attendance.includes(message.type)}
      <div class="flex items-center justify-center">
        <span class="text-center text-sm text-neutral-500">
          {$profileQuery?.data?.displayName ||
            `@${$profileQuery?.data?.handle}`}{' '}
          {attendanceMap[message.type as keyof typeof attendanceMap]} the jam
          <UpdatingDate date={message?.createdAt} />
        </span>
      </div>
    {/if}
  {/if}
</AccessDeniedLoader>
