// libraries/react-ui/src/components/infinite-scrolling/InfiniteScrollContainer.tsx
import * as React from 'react';
import { Loader } from '../loaders/Loader';
import { getUniqueBy } from '../../lib/utils';
import { ScrollObserver, type InfiniteQueryLike } from './ScrollObserver';

export interface InfiniteScrollContainerQueryResult<D> extends InfiniteQueryLike {
  data?: { pages?: D[][] };
  isPending: boolean;
  isSuccess: boolean;
}

export interface InfiniteScrollContainerProps<D> {
  query: InfiniteScrollContainerQueryResult<D>;
  children: (ctx: { list: D[] }) => React.ReactNode;
  empty?: React.ReactNode;
  uniqueBy: (item: D) => string;
  scrollTop?: boolean;
  additionalItems?: D[];
}

export function InfiniteScrollContainer<D>({
  query,
  children,
  empty,
  uniqueBy,
  scrollTop = false,
  additionalItems = [],
}: InfiniteScrollContainerProps<D>) {
  const list = React.useMemo(
    () =>
      getUniqueBy(
        [...((query.data?.pages ?? []).flat() as D[]), ...additionalItems],
        uniqueBy,
      ),
    [query.data, additionalItems, uniqueBy],
  );

  if (!query) return null;

  return (
    <Loader
      queries={[
        {
          isPending: query.isPending,
          isSuccess: query.isSuccess,
          data: query.data,
        },
      ]}
    >
      {list.length ? (
        <>
          {scrollTop && <ScrollObserver query={query} />}
          {children({ list })}
          {!scrollTop && <ScrollObserver query={query} />}
        </>
      ) : (
        empty
      )}
    </Loader>
  );
}

// libraries/ui/src/lib/infinite-scrolling/InfiniteScrollContainer.svelte
<script lang="ts" generics="D">
  import type {
    CreateInfiniteQueryResult,
    InfiniteData,
  } from '@tanstack/svelte-query';
  import { Loader } from '$lib';
  import type { Snippet } from 'svelte';
  import { getUniqueBy } from '$lib/utils';
  import ScrollObserver from './ScrollObserver.svelte';
  interface Props {
    query: CreateInfiniteQueryResult<InfiniteData<D[], unknown>, unknown>;
    children: Snippet<[{ list: D[] }]>;
    empty?: Snippet;
    uniqueBy: (item: D) => string;
    scrollTop?: boolean;
    additionalItems?: D[];
  }

  let {
    query,
    children,
    empty,
    uniqueBy,
    scrollTop = false,
    additionalItems = [],
  }: Props = $props();

  let list = $derived(
    getUniqueBy(
      [...($query?.data?.pages?.flat() || []), ...additionalItems],
      uniqueBy,
    ),
  );
</script>

{#if $query}
  <Loader queries={[$query]}>
    {#if list.length}
      {#if scrollTop}
        <ScrollObserver {query} />
      {/if}
      {@render children({ list })}

      {#if !scrollTop}
        <ScrollObserver {query} />
      {/if}
    {:else}
      {@render empty?.()}
    {/if}
  </Loader>
{/if}
