// platform/react-native/src/components/custom/post/feed/threaded/ThreadPost.tsx
import React from 'react';
import { PublicPost } from '@openpeeps/common';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Pressable } from 'react-native';
import { ProfileHandle, ProfileName } from '~/components/custom/common';
import { UpdatingDate } from '~/components/custom/date';
import { ProfileAvatar } from '~/components/custom/profile';
import { MainStackParamList } from '~/components/navigation/types';
import { FeedPostContent, PostActions, PostMenu } from '../../pieces';
import { ThemedView } from '~/components/ui/themed-view';

interface ThreadPostProps {
    post: PublicPost;
    isParent?: boolean;
    isChild?: boolean;
    noActions?: boolean;
    noMenu?: boolean;
}


export const ThreadPost: React.FC<ThreadPostProps> = ({
    post,
    isParent = false,
    isChild = false,
    noActions = false,
    noMenu = false,
}: ThreadPostProps) => {
    const navigation =
        useNavigation<NativeStackNavigationProp<MainStackParamList>>();

    return (
        <ThemedView className="relative flex-row py-5 px-4 gap-3">
            {/* Vertical line from top */}
            {isChild && (
                <ThemedView
                    className="absolute bg-input"
                    style={{
                        width: 1,
                        left: 39,
                        top: 0,
                        height: 32,
                    }}
                />
            )}

            {/* Vertical line to bottom */}
            {isParent && (
                <ThemedView
                    className="absolute bg-input w-1 h-full"
                    style={{
                        width: 1,
                        left: 39,
                        top: 32,
                        bottom: 0,
                    }}
                />
            )}

            <Pressable
                onPress={() =>
                    navigation.navigate('Profile', { handle: post.profile.handle })
                }>
                <ProfileAvatar profile={post.profile} className="size-14" />
            </Pressable>

            <ThemedView className="flex-1 gap-2 mb-2">
                <ThemedView className="flex-row justify-between items-start">
                    <ThemedView>
                        <ProfileName profile={[post.profile]} />
                        <ProfileHandle profile={[post.profile]} />
                        <UpdatingDate date={post.createdAt as string} />
                    </ThemedView>
                    {!noMenu && <PostMenu post={post} />}
                </ThemedView>

                <FeedPostContent post={post} />

                {!noActions && <PostActions post={post} />}
            </ThemedView>
        </ThemedView>
    );
};

// platform/svelte/src/lib/components/core/post/feed/threaded/ThreadPost.svelte
<script lang="ts">
  import type { PublicPost } from '@openpeeps/common/types';
  import { Avatar } from '$lib/components/core/profile';
  import DisplayUserNameBlock from '$lib/components/core/profile/DisplayUserNameBlock.svelte';
  import PostMenu from '../../pieces/PostMenu.svelte';
  import FeedPostContent from '../../pieces/FeedPostContent.svelte';
  import PostActions from '../../pieces/PostActions.svelte';
  import { UpdatingDate } from '@openpeeps/ui';

  interface Props {
    post: PublicPost;
    isParent?: boolean;
    isChild?: boolean;
    noActions?: boolean;
    noMenu?: boolean;
  }

  let {
    post,
    isParent = false,
    isChild = false,
    noActions = false,
    noMenu = false,
  }: Props = $props();
</script>

<div class="flex flex-row gap-2 p-2">
  <div class="relative w-12 justify-items-stretch">
    <Avatar profile={post.profile} borderless size={3} />
    {#if isParent}
      <div class="bg-surface-300 absolute left-6 h-full w-[1px]"></div>
    {/if}
  </div>
  <div class="w-32 grow">
    <div class="bg-surface-100 rounded-xl p-2">
      <div class="mb-2 flex flex-row items-start justify-between">
        <div class="flex flex-col flex-wrap">
          <DisplayUserNameBlock profile={post.profile} />
        </div>
        <div class="flex flex-row gap-2">
          <span class="text-sm font-extralight">
            <UpdatingDate date={post.createdAt} />
          </span>
          {#if !noMenu}
            <PostMenu {post} />
          {/if}
        </div>
      </div>
      <FeedPostContent {post} />
    </div>
    {#if !noActions}
      <PostActions {post} compact={true} />
    {/if}
  </div>
</div>
