// platform/rn-components/src/components/custom/post/feed/threaded/ThreadedFeed.tsx
import React, { useMemo } from 'react';
import { ThemedView } from '~/components/ui/themed-view';
import { MainStackParamList } from '~/components/navigation/types';
import { Thread } from '@openpeepshq/common';
import { Pressable } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { collectPath, lastLongestPathSelector } from '~/lib/post';
import { ThreadPost } from './ThreadPost';

type ThreadedFeedProps = {
    thread: Thread;
    pathSelector?: (thread: Thread) => Thread;
    isAncestors?: boolean;
};

export const ThreadedFeed: React.FC<ThreadedFeedProps> = ({
    thread,
    pathSelector = lastLongestPathSelector,
    isAncestors = false,
}: ThreadedFeedProps) => {
    const navigation =
        useNavigation<NativeStackNavigationProp<MainStackParamList>>();

    const postList = useMemo(() =>
        collectPath(pathSelector(thread)), [thread, pathSelector]);

    return (
        <ThemedView className="w-full" style={{ flexGrow: 1 }}>
            {postList.map((post, index) => (
                <Pressable className="w-full" key={post.id} onPress={() => navigation.navigate('Post', { id: post.id })}>
                    <ThreadPost
                        post={post}
                        isParent={index !== postList.length - 1 || isAncestors}
                        isChild={index !== 0}
                    />
                </Pressable>)
            )}
        </ThemedView>
    );
};

// platform/svelte/src/lib/components/core/post/feed/threaded/ThreadedFeed.svelte
<script lang="ts">
  import type { PublicPost, Thread } from '@openpeeps/common/types';
  import { dateSorter } from '@openpeeps/common/lib';
  import ThreadPost from '$lib/components/core/post/feed/threaded/ThreadPost.svelte';
  import { Button } from '@openpeeps/ui';

  const lastLongestPathSelector = (
    thread: Thread,
  ): Thread & { depth: number } => {
    const candidates = thread.children.map((t) => lastLongestPathSelector(t));

    const maxDepth = Math.max(0, ...candidates.map((c) => c.depth));

    const selectedChild = candidates
      .filter((c) => c.depth === maxDepth)
      .sort(dateSorter())
      .reverse()[0];

    return {
      ...thread,
      children: selectedChild ? [selectedChild] : [],
      depth: maxDepth + 1,
    };
  };

  const collectPath = (
    thread: Thread,
    currentPath: PublicPost[] = [],
  ): PublicPost[] => {
    if (thread) {
      return [...currentPath, thread, ...collectPath(thread.children[0])];
    } else {
      return currentPath;
    }
  };

  interface Props {
    thread: Thread;
    pathSelector?: (thread: Thread) => Thread;
  }

  let { thread, pathSelector = lastLongestPathSelector }: Props = $props();

  let postList: PublicPost[] = $derived(collectPath(pathSelector(thread)));
</script>

<div>
  {#each postList as post, index (post.id)}
    <Button action="/posts/{post.id}">
      <ThreadPost
        {post}
        isChild={index > 0}
        isParent={index < postList.length - 1}
      />
    </Button>
  {/each}
</div>
