// platform/react-native/src/components/custom/post/pieces/gallery/GalleryDocument.tsx
import React from 'react';
import { DownloadIcon } from '~/components/icons';
import type { MediaAttachmentData } from '@openpeeps/common';
import { Button } from '~/components/ui/button';
import { DocumentAttachment } from '../DocumentAttachment';
import { useTranslation } from 'react-i18next';
import { ThemedText } from '~/components/ui/themed-text';
import { ThemedView } from '~/components/ui/themed-view';
import { downloadDocument } from '~/lib/downloadFile';

interface GalleryDocumentProps {
    attachment: MediaAttachmentData;
}

export const GalleryDocument = ({ attachment }: GalleryDocumentProps) => {
    const { t } = useTranslation();
    return (
        <ThemedView className="flex size-full items-center justify-center p-4">
            <DocumentAttachment attachment={attachment} />
            <Button
                className="absolute bottom-4 right-4"
                onPress={() => {
                    downloadDocument(attachment.url);
                }}
            >
                <ThemedView className="bg-primary flex-row items-center gap-2">
                    <DownloadIcon className="size-4" />
                    <ThemedText className="text-sm">{t('common.actions.download')}</ThemedText>
                </ThemedView>
            </Button>
        </ThemedView >);
};

// platform/svelte/src/lib/components/core/post/pieces/gallery/GalleryDocument.svelte
<script lang="ts">
  import { Download } from 'lucide-svelte';
  import type { MediaAttachmentData } from '@openpeeps/common';
  import { Button } from '@openpeeps/ui';
  import { downloadFile } from '$lib/utils';
  import DocumentAttachment from '../DocumentAttachment.svelte';
  import { i18nContext } from '$lib/components/i18n';

  const { t } = i18nContext();

  interface Props {
    attachment: MediaAttachmentData;
  }

  let { attachment }: Props = $props();
</script>

<div class="flex size-full items-center justify-center p-4">
  <div class="md:w-128 relative flex h-96 w-full flex-col">
    <DocumentAttachment {attachment} />
    <Button
      class="absolute bottom-4 right-4"
      variant="variant-filled-primary"
      action={() => downloadFile(attachment.url, attachment.filename)}
    >
      <Download class="size-4" />
      <span class="text-sm">{t('common.actions.download')}</span>
    </Button>
  </div>
</div>
