// platform/react/src/components/groups/ChangeGroupRolesModal.tsx
import { useState } from 'react';
import type {
  GroupMember,
  GroupRelationship,
  GroupWithMeta,
} from '@openpeeps/common/types';
import { defaultGroupRoles } from '@openpeeps/common/types';
import {
  Button,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Label,
} from '@openpeeps/react-ui';
import { useOpenpeeps } from '../../contexts/openpeeps';
import { useT } from '../../i18n';

export interface ChangeGroupRolesModalProps {
  group: GroupWithMeta;
  member: GroupMember;
  onClose: () => void;
}

export function ChangeGroupRolesModal({
  group,
  member,
  onClose,
}: ChangeGroupRolesModalProps) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const setMemberRoles = openpeepsApi.setGroupMemberRolesAction({
    id: group.id,
    memberId: member.profile.id,
  });

  const [roles, setRoles] = useState<Set<GroupRelationship>>(
    () => new Set(member.roles ?? []),
  );
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const toggleRole = (role: GroupRelationship, checked: boolean) => {
    setRoles((prev) => {
      const next = new Set(prev);
      if (checked) next.add(role);
      else next.delete(role);
      return next;
    });
  };

  const submit = async () => {
    setError(null);
    setSubmitting(true);
    try {
      await setMemberRoles({ roles: [...roles] });
      onClose();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>
            {t('groups.changeRoles.title', { defaultValue: 'Change roles' })}
          </DialogTitle>
        </DialogHeader>
        <p className="px-1 text-sm">
          {t('groups.changeRoles.description', {
            defaultValue: 'Update roles for @{{handle}}',
            handle: member.profile.handle,
          })}
        </p>
        <div className="space-y-3 px-1">
          {defaultGroupRoles.map((role) => (
            <div key={role} className="flex items-center justify-between gap-4">
              <Label htmlFor={`role-${role}`} classes="text-base font-medium">
                {t(`groups.roles.${role}`, { defaultValue: role })}
              </Label>
              <input
                id={`role-${role}`}
                type="checkbox"
                checked={roles.has(role)}
                onChange={(e) => toggleRole(role, e.target.checked)}
                className="size-4"
              />
            </div>
          ))}
        </div>
        {error ? (
          <p className="border-error/40 text-error rounded-md border p-2 text-sm">
            {error}
          </p>
        ) : null}
        <DialogFooter>
          <Button variant="variant-ringed-primary" action={onClose}>
            {t('common.cancel', { defaultValue: 'Cancel' })}
          </Button>
          <Button
            variant="variant-filled-primary"
            action={submit}
            disabled={submitting}
          >
            {t('groups.changeRoles.confirm', { defaultValue: 'Save roles' })}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// platform/svelte/src/lib/components/core/groups/pieces/modals/ChangeGroupRolesModal.svelte
<script lang="ts">
	import { setMemberRolesMutation } from '$lib/api';
	import { getModalManager, ModalFooter, ModalHeader, ModalWrapper, Button } from '@openpeeps/ui';
	import { toast } from '$lib/utils/toast';
	import {
		defaultGroupRoles,
		type GroupMember,
		type GroupRelationship,
		type GroupWithMeta
	} from '@openpeeps/common/types';
	import { getToastStore, SlideToggle } from '@skeletonlabs/skeleton';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		group: GroupWithMeta;
		member: GroupMember;
	}

	const { t } = i18nContext();
	let { group, member }: Props = $props();
	const modalManager = getModalManager();
	const toastStore = getToastStore();

	const setMemberRoles = setMemberRolesMutation({ id: group.id, memberId: member.profile.id });

	const allRoles = defaultGroupRoles;

	const rolesSet = $state(new Set(member.roles));
	const roles = $derived([...rolesSet]);

	const doSetMemberRoles = async () => {
		setMemberRoles({ roles })
			.then(() => {
				toastStore.trigger(
					toast({
						message: t('groups.changeRoles.successMessage')
					})
				);
				modalManager.close();
			})
			.catch(() => {
				toastStore.trigger(
					toast({
						message: t('groups.changeRoles.errorMessage')
					})
				);
			});
	};

	const setRoleStatus = (role: GroupRelationship, status: boolean) => {
		if (status) {
			rolesSet.add(role);
		} else {
			rolesSet.delete(role);
		}
	};
</script>

<ModalWrapper>
	<ModalHeader title={t('groups.changeRoles.title')} />
	<div class="p-4">
		{t('groups.changeRoles.description', {
			handle: member.profile.handle
		})}
	</div>
	<div class="p-4">
		{#each allRoles as role}
			<div class="flex items-center justify-between">
				<div>
					<p class="text-lg font-medium">{t(`groups.roles.${role}`)}</p>
				</div>

				<SlideToggle
					name="slide"
					checked={rolesSet.has(role)}
					on:change={(e) => setRoleStatus(role, (e.target as HTMLInputElement).checked)}
					background="bg-surface-300"
					active="bg-primary-500"
				/>
			</div>
		{/each}
	</div>
	<ModalFooter extraClassNames="flex justify-end w-full">
		<Button title={t('common.cancel')} variant="variant-ringed-primary" action={modalManager.close}>
			{t('common.cancel')}
		</Button>
		<Button
			title={t('groups.changeRoles.confirm')}
			variant="variant-filled-error"
			action={doSetMemberRoles}>{t('groups.changeRoles.confirm')}</Button
		>
	</ModalFooter>
</ModalWrapper>
