// platform/react/src/components/groups/ConfirmMemberRemovalModal.tsx
import { useState } from 'react';
import type { GroupWithMeta, PublicProfile } from '@openpeeps/common/types';
import {
  Button,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@openpeeps/react-ui';
import { useOpenpeeps } from '../../contexts/openpeeps';
import { useT } from '../../i18n';

export interface ConfirmMemberRemovalModalProps {
  group: GroupWithMeta;
  profile: PublicProfile;
  onClose: () => void;
}

export function ConfirmMemberRemovalModal({
  group,
  profile,
  onClose,
}: ConfirmMemberRemovalModalProps) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const removeMember = openpeepsApi.removeGroupMemberAction({
    id: group.id,
    memberId: profile.id,
  });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async () => {
    setError(null);
    setSubmitting(true);
    try {
      await removeMember();
      onClose();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>
            {t('groups.removeMember.title', { defaultValue: 'Remove member' })}
          </DialogTitle>
        </DialogHeader>
        <p className="px-1 text-sm">
          {t('groups.removeMember.description', {
            defaultValue: 'Remove @{{handle}} from this group?',
            handle: profile.handle,
          })}
        </p>
        {error ? (
          <p className="border-error/40 text-error rounded-md border p-2 text-sm">
            {error}
          </p>
        ) : null}
        <DialogFooter>
          <Button variant="variant-ringed-primary" action={onClose}>
            {t('common.cancel', { defaultValue: 'Cancel' })}
          </Button>
          <Button
            variant="variant-filled-error"
            action={submit}
            disabled={submitting}
          >
            {t('groups.removeMember.confirm', { defaultValue: 'Remove' })}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// platform/svelte/src/lib/components/core/groups/pieces/modals/ConfirmMemberRemovalModal.svelte
<script lang="ts">
	import { removeMemberMutation } from '$lib/api';
	import { getModalManager, ModalFooter, ModalHeader, ModalWrapper, Button } from '@openpeeps/ui';
	import { toast } from '$lib/utils/toast';
	import type { GroupWithMeta, PublicProfile } from '@openpeeps/common/types';
	import { getToastStore } from '@skeletonlabs/skeleton';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		group: GroupWithMeta;
		profile: PublicProfile;
	}

	const { t } = i18nContext();
	let { group, profile }: Props = $props();
	const modalManager = getModalManager();
	const toastStore = getToastStore();

	const removeMember = removeMemberMutation({ id: group.id, memberId: profile.id });

	const doRemoveMember = async () => {
		removeMember()
			.then(() => {
				toastStore.trigger(
					toast({
						message: t('groups.removeMember.successMessage')
					})
				);
				modalManager.close();
			})
			.catch(() => {
				toastStore.trigger(
					toast({
						message: t('groups.removeMember.errorMessage')
					})
				);
			});
	};
</script>

<ModalWrapper>
	<ModalHeader title={t('groups.removeMember.title')} />
	<div class="p-4">
		{(t('groups.removeMember.description'),
		{
			handle: profile.handle
		})}
	</div>
	<ModalFooter extraClassNames="flex justify-end w-full">
		<Button title="Cancel" variant="variant-ringed-primary" action={modalManager.close}
			>Cancel</Button
		>
		<Button
			title={t('groups.removeMember.confirm')}
			variant="variant-filled-error"
			action={doRemoveMember}
		>
			{t('groups.removeMember.confirm')}
		</Button>
	</ModalFooter>
</ModalWrapper>
