// platform/react/src/components/groups/DeleteGroupModal.tsx
import { useState } from 'react';
import type { GroupWithMeta } from '@openpeeps/common/types';
import { groupName } from '@openpeeps/common/lib';
import {
  Button,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@openpeeps/react-ui';
import { useRouter } from '../../contexts/router';
import { useOpenpeeps } from '../../contexts/openpeeps';
import { useT } from '../../i18n';

export interface DeleteGroupModalProps {
  group: GroupWithMeta;
  onClose: () => void;
}

export function DeleteGroupModal({ group, onClose }: DeleteGroupModalProps) {
  const t = useT();
  const router = useRouter();
  const { openpeepsApi } = useOpenpeeps();
  const deleteGroup = openpeepsApi.deleteGroupAction({ id: group.id });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async () => {
    setError(null);
    setSubmitting(true);
    try {
      await deleteGroup();
      onClose();
      router.back();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>
            {t('groups.delete.title', { defaultValue: 'Delete group' })}
          </DialogTitle>
        </DialogHeader>
        <p className="px-1 text-sm">
          {t('groups.delete.description', {
            defaultValue: 'Delete {{groupName}} permanently?',
            groupName: groupName(group),
          })}
        </p>
        {error ? (
          <p className="border-error/40 text-error rounded-md border p-2 text-sm">
            {error}
          </p>
        ) : null}
        <DialogFooter>
          <Button variant="variant-ringed-surface" action={onClose}>
            {t('groups.delete.cancel', { defaultValue: 'Cancel' })}
          </Button>
          <Button
            variant="variant-filled-error"
            action={submit}
            disabled={submitting}
          >
            {t('groups.delete.deleteButton', { defaultValue: 'Delete' })}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// platform/svelte/src/lib/components/core/groups/pieces/modals/DeleteGroupModal.svelte
<script lang="ts">
	import { getToastStore } from '@skeletonlabs/skeleton';
	import { Button } from '@openpeeps/ui';
	import { deleteGroupMutation } from '$lib/api';
	import { toast } from '$lib/utils/toast';
	import { getModalManager, ModalFooter, ModalHeader, ModalWrapper } from '@openpeeps/ui';
	import type { GroupWithMeta } from '@openpeeps/common/types';
	import { groupName } from '@openpeeps/common/lib';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		group: GroupWithMeta;
		callback?: ()=>void
	}

	let { group , callback}: Props = $props();
	const { t } = i18nContext();
	const modalManager = getModalManager();
	const toastStore = getToastStore();

	const deleteGroup = deleteGroupMutation({
		id: group.id
	});

	const handleDeletePost = async () => {
		await deleteGroup()
			.then(() => {
				toastStore.trigger(
					toast({
						message: t('groups.delete.successMessage'),
						background: 'variant-filled-success'
					})
				);
				callback?.()
				modalManager.close();
			})
			.catch(() => {
				toastStore.trigger(
					toast({
						message: t('groups.delete.toastError'),
						background: 'variant-filled-error'
					})
				);
			});
	};
</script>

<ModalWrapper extraClassNames="max-w-sm">
	<ModalHeader title={t('groups.delete.title')} />
	<article class=" overflow-h-scroll m-4 max-h-[65vh] pb-3">
		<p class="my-4">
			{t('groups.delete.description', {
				groupName: groupName(group)
			})}
		</p>
	</article>
	<ModalFooter>
		<Button
			title={t('groups.delete.confirm')}
			action={handleDeletePost}
			variant="variant-filled-error"
			mutations={[$deleteGroup]}
		>
			{t('groups.delete.deleteButton')}
		</Button>
		<Button
			title={t('groups.delete.cancel')}
			action={() => modalManager.close()}
			variant="variant-ringed-surface">{t('groups.delete.cancel')}</Button
		>
	</ModalFooter>
</ModalWrapper>
