// libraries/react-ui/src/components/modal/ModalWrapper.tsx
import * as React from 'react';
import { cn } from '@/lib/utils';

export interface ModalWrapperProps {
  className?: string;
  width?: string;
  children?: React.ReactNode;
}

export function ModalWrapper({
  className,
  width = 'w-[95vw] max-w-2xl',
  children,
}: ModalWrapperProps) {
  return (
    <div
      className={cn(
        'op-card max-h-[90vh] overflow-y-auto bg-surface shadow-xl',
        width,
        className,
      )}
    >
      {children}
    </div>
  );
}

// libraries/ui/src/lib/modal/ModalWrapper.svelte
<script lang="ts">
	interface Props {
		extraClassNames?: string;
		width?: string;
		children?: import('svelte').Snippet;
	}

	let { extraClassNames = '', width = 'w-modal', children }: Props = $props();
</script>

<div class="card bg-surface-50 max-h-[90vh] overflow-y-auto shadow-xl {extraClassNames} {width}">
	{@render children?.()}
</div>
