// libraries/ui/src/lib/modal/ModalFooter.svelte
<script lang="ts">
	interface Props {
		extraClassNames?: string;
		children?: import('svelte').Snippet;
	}

	let { extraClassNames = '', children }: Props = $props();
</script>

<footer
	class="modal-footer sticky bottom-0 flex items-center justify-between border-t-[1px] border-surface-300 bg-surface-50 px-4 py-2 {extraClassNames}"
>
	{@render children?.()}
</footer>

// libraries/react-ui/src/components/modal/ModalFooter.tsx
import * as React from 'react';
import { cn } from '@/lib/utils';

export interface ModalFooterProps {
  className?: string;
  children?: React.ReactNode;
}

export function ModalFooter({ className, children }: ModalFooterProps) {
  return (
    <footer
      className={cn(
        'bg-surface sticky bottom-0 flex items-center justify-between border-t px-4 py-2',
        className,
      )}
    >
      {children}
    </footer>
  );
}
