// platform/svelte/src/lib/components/navigation/HeaderMobile.svelte
<script lang="ts">
	import { MessageSquareText } from 'lucide-svelte';
	import { getServerInfo } from '$lib/server';
	import { currentProfileSettingsStore, currentProfileStore } from '$lib/api';
	import { Avatar } from '$lib/components/core/profile';
	import { goto } from '$app/navigation';
	import { Drawer, getDrawerStore, type DrawerSettings } from '@skeletonlabs/skeleton';
	import SideBar from './SideBar.svelte';
	import { i18nContext } from '$lib/components/i18n';
	import { getTheme } from '@openpeeps/common';

	let profileSettingsQuery = currentProfileSettingsStore()
	let profileSettings = $profileSettingsQuery.data
	const logoSmall = getTheme(getServerInfo().communityConfig, profileSettings).logoSmall;
	const profileQuery = currentProfileStore();
	const drawerStore = getDrawerStore();
	const { t } = i18nContext();

	const drawerSettings: DrawerSettings = {
		width: 'w-[380px]',
		rounded: 'rounded-none'
	};
</script>

<Drawer>
	<SideBar />
</Drawer>

<div class="bg-background sticky top-0 z-10 flex px-4 py-2 md:hidden">
	<div class="flex w-full items-center justify-between">
		<button
			title={t('navigation.profile')}
			class=""
			onclick={() => drawerStore.open(drawerSettings)}
		>
			<Avatar profile={$profileQuery.data} size={2.5} borderless />
		</button>
		<div class="">
			<a href="/">
				<img src={logoSmall} alt="logo" class="h-6 px-4" />
			</a>
		</div>
		<button title={t('navigation.messages')} onclick={() => goto('/conversations')}>
			<MessageSquareText />
		</button>
	</div>
</div>

// platform/react/src/components/navigation/HeaderMobile.tsx
import { useState } from 'react';
import { MessageSquareText, Menu } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogPortal,
  DialogOverlay,
  DialogTrigger,
} from '@openpeeps/react-ui';
import { getTheme } from '@openpeeps/common';
import { useServerInfo } from '../server-data';
import { useCurrentProfileSettings } from '../layout/IdentityContext';
import { useRouter } from '../../contexts/router';
import { useT } from '../../i18n';
import { SideBar } from './SideBar';

export interface HeaderMobileProps {
  /** Render slot to draw the avatar trigger (defaults to a generic icon). */
  avatar?: React.ReactNode;
}

export function HeaderMobile({ avatar }: HeaderMobileProps = {}) {
  const serverInfo = useServerInfo();
  const profileSettings = useCurrentProfileSettings();
  const router = useRouter();
  const t = useT();
  const [open, setOpen] = useState(false);

  const logoSmall = getTheme(
    serverInfo.communityConfig,
    profileSettings,
  ).logoSmall;

  return (
    <div className="bg-background sticky top-0 z-10 flex px-4 py-2 md:hidden">
      <div className="flex w-full items-center justify-between">
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <button type="button" title={t('navigation.profile')}>
              {avatar ?? <Menu />}
            </button>
          </DialogTrigger>
          <DialogPortal>
            <DialogOverlay />
            <DialogContent
              showCloseButton={false}
              className="left-0 top-0 h-screen w-[380px] translate-x-0 translate-y-0 rounded-none border-r p-0"
            >
              <SideBar onClose={() => setOpen(false)} />
            </DialogContent>
          </DialogPortal>
        </Dialog>

        <div>
          {logoSmall && (
            <a href="/">
              <img src={logoSmall} alt="logo" className="h-6 px-4" />
            </a>
          )}
        </div>

        <button
          type="button"
          title={t('navigation.messages')}
          onClick={() => router.navigate('/conversations')}
        >
          <MessageSquareText />
        </button>
      </div>
    </div>
  );
}
