// platform/svelte/src/lib/components/navigation/MobileMenuItem.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import type { IconType } from '@openpeeps/ui';

	interface Props {
		action: string | (() => unknown);
		icon: IconType;
		title?: string;
	}

	let { action, icon, title = '' }: Props = $props();

	let active: boolean = $derived(typeof action === 'string' && location.pathname === action);
</script>

<button
	{title}
	onclick={() => {
		if (typeof action === 'function') {
			action();
		} else {
			goto(action);
		}
	}}
>
	<span
		class="flex items-center gap-x-2"
		class:text-base-200={!active}
		class:text-primary-500={active}
		class:font-bold={active}
	>
		<svelte:component this={icon} class="mr-1 h-5 w-5" strokeWidth={active ? 3 : 2} />
	</span>
</button>

// platform/react/src/components/navigation/MobileMenuItem.tsx
import { cn } from '@openpeeps/react-ui';
import type { IconType } from '@openpeeps/react-ui';
import { useRouter } from '../../contexts/router';

export interface MobileMenuItemProps {
  action: string | (() => unknown);
  icon: IconType;
  title?: string;
}

export function MobileMenuItem({
  action,
  icon: Icon,
  title,
}: MobileMenuItemProps) {
  const router = useRouter();
  const active = typeof action === 'string' && router.pathname === action;

  return (
    <button
      type="button"
      title={title}
      onClick={() => {
        if (typeof action === 'function') action();
        else router.navigate(action);
      }}
    >
      <span
        className={cn(
          'flex items-center gap-x-2',
          active ? 'text-primary-500 font-bold' : 'text-foreground/70',
        )}
      >
        <Icon className="mr-1 h-5 w-5" />
      </span>
    </button>
  );
}
