// platform/svelte/src/lib/components/navigation/PageHeaderAction.svelte
<script lang="ts">
	import { Button } from '@openpeeps/ui';

	interface Props {
		title: string;
		action?: () => Promise<void> | void;
	}

	let { title, action }: Props = $props();
</script>

<Button {title} class="h-6 w-fit text-sm" variant="variant-ringed-surface" {action}>
	<span>{title}</span>
</Button>

// platform/react/src/components/navigation/PageHeaderAction.tsx
import { Button } from '@openpeeps/react-ui';

export interface PageHeaderActionProps {
  title: string;
  action?: () => Promise<void> | void;
}

export function PageHeaderAction({ title, action }: PageHeaderActionProps) {
  return (
    <Button
      title={title}
      className="h-6 w-fit text-sm"
      variant="variant-ringed-surface"
      action={
        action
          ? () => Promise.resolve(action()).then(() => undefined)
          : undefined
      }
    >
      <span>{title}</span>
    </Button>
  );
}
