// platform/svelte/src/lib/components/navigation/SideBar.svelte
<script lang="ts">
	import { MainMenu } from '.';
	import { getServerInfo } from '$lib/server';
	import { ProfileMenu } from '.';
	import { X } from 'lucide-svelte';
	import { getDrawerStore } from '@skeletonlabs/skeleton';
	import { currentProfileSettingsStore, me } from '$lib/api';
	import { Link, Button } from '@openpeeps/ui';
	import { i18nContext } from '$lib/components/i18n';
	import { getTheme } from '@openpeeps/common';

	const serverInfo = getServerInfo();
	let profileSettingsQuery = currentProfileSettingsStore()
	let profileSettings = $profileSettingsQuery.data
	const logoSmall = getTheme(serverInfo.communityConfig, profileSettings).logoSmall;
	const {
		communityConfig: {
			info: { name, tagLine }
		}
	} = serverInfo;

	const drawerStore = getDrawerStore();
	const { t } = i18nContext();
</script>

<div class="relative h-screen w-full pt-3 md:h-full">
	<div class="h-[90%] overflow-y-auto">
		<div class="md:items-left flex w-full items-center justify-between px-4">
			<a href="/">
				<img src={logoSmall} alt="logo" class="h-10 object-contain" />
			</a>
			<button
				title={t('common.close')}
				class="flex md:hidden"
				onclick={() => {
					drawerStore.close();
				}}
			>
				<X />
			</button>
		</div>
		{#if $me?.type === 'local'}
			<ProfileMenu />
			<MainMenu />
		{:else}
			<div class="section mt-4">
				<div class="flex h-full flex-col items-center justify-center space-y-4">
					<p class="text-center text-lg font-semibold">{t('navigation.welcome', { name })}</p>
					<p class="px-2 text-center text-sm">{tagLine}</p>
					<Button
						title={t('navigation.joinCommunity')}
						variant="variant-filled-primary"
						action="/auth/register">{t('navigation.joinCommunity')}</Button
					>

					<span class="text-sm">
						{t('navigation.haveAccount')}
						<Link action="/auth/login">{t('navigation.logIn')}</Link>
					</span>
				</div>
			</div>
		{/if}
	</div>
	<div class="bg-surface-50 absolute bottom-3">
		<p class="ml-4 text-center">{t('navigation.poweredBy')}</p>
	</div>
</div>

// platform/react/src/components/navigation/SideBar.tsx
import { X } from 'lucide-react';
import { Button, Link } from '@openpeeps/react-ui';
import { getTheme } from '@openpeeps/common';
import { useServerInfo } from '../server-data';
import {
  useCurrentProfile,
  useCurrentProfileSettings,
} from '../layout/IdentityContext';
import { useT } from '../../i18n';

export interface SideBarProps {
  onClose?: () => void;
  /** Slot for the consumer-supplied main menu (was `<MainMenu />` in Svelte). */
  mainMenu?: React.ReactNode;
  /** Slot for the consumer-supplied profile menu (was `<ProfileMenu />`). */
  profileMenu?: React.ReactNode;
}

/**
 * Translation of @openpeeps/svelte/components/navigation/SideBar.svelte.
 *
 * The Svelte version reached into a sprawling `<MainMenu />` / `<ProfileMenu />`
 * sub-tree (which referenced 30+ feature components). To keep the React port
 * a focused, framework-agnostic shell we expose those as slots, so consumers
 * compose them however their app structures menus.
 */
export function SideBar({ onClose, mainMenu, profileMenu }: SideBarProps = {}) {
  const serverInfo = useServerInfo();
  const profileSettings = useCurrentProfileSettings();
  const profile = useCurrentProfile();
  const t = useT();

  const logoSmall = getTheme(
    serverInfo.communityConfig,
    profileSettings,
  ).logoSmall;
  const { name, tagLine } = serverInfo.communityConfig?.info ?? {};

  return (
    <div className="relative h-screen w-full pt-3 md:h-full">
      <div className="h-[90%] overflow-y-auto">
        <div className="flex w-full items-center justify-between px-4 md:items-start">
          <a href="/">
            {logoSmall && (
              <img src={logoSmall} alt="logo" className="h-10 object-contain" />
            )}
          </a>
          {onClose && (
            <button
              type="button"
              title={t('common.close')}
              className="flex md:hidden"
              onClick={onClose}
            >
              <X />
            </button>
          )}
        </div>

        {profile?.type === 'local' ? (
          <>
            {profileMenu}
            {mainMenu}
          </>
        ) : (
          <div className="mt-4 px-4">
            <div className="flex h-full flex-col items-center justify-center space-y-4">
              {name && (
                <p className="text-center text-lg font-semibold">
                  {t('navigation.welcome', { name })}
                </p>
              )}
              {tagLine && <p className="px-2 text-center text-sm">{tagLine}</p>}
              <Button
                title={t('navigation.joinCommunity')}
                variant="variant-filled-primary"
                action="/auth/register"
              >
                {t('navigation.joinCommunity')}
              </Button>
              <span className="text-sm">
                {t('navigation.haveAccount')}{' '}
                <Link action="/auth/login">{t('navigation.logIn')}</Link>
              </span>
            </div>
          </div>
        )}
      </div>
      <div className="bg-card absolute bottom-3">
        <p className="ml-4 text-center">{t('navigation.poweredBy')}</p>
      </div>
    </div>
  );
}
