// platform/react/src/components/post/pieces/modals/RepostModal.tsx
import type { PublicPost } from '@openpeeps/common/types';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@openpeeps/react-ui';
import { useOpenpeeps } from '../../../../contexts/openpeeps';
import { useT } from '../../../../i18n';
import { ProfileWithActionCard } from '../../../profile/ProfileWithActionCard';

export interface RepostModalProps {
  post: PublicPost;
  open: boolean;
  onClose: () => void;
}

export function RepostModal({ post, open, onClose }: RepostModalProps) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const repostsQuery = openpeepsApi.usePostReposts(post.id);

  return (
    <Dialog open={open} onOpenChange={(next) => !next && onClose()}>
      <DialogContent className="max-h-[80vh] max-w-md overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {t('posts.repostModal.title', { defaultValue: 'Reposters' })}
          </DialogTitle>
        </DialogHeader>
        <article className="pb-3">
          {repostsQuery.isLoading ? (
            <p className="p-5 text-center text-sm text-muted-foreground">
              {t('common.loading', { defaultValue: 'Loading…' })}
            </p>
          ) : repostsQuery.data?.length ? (
            repostsQuery.data.map((repost) => (
              <ProfileWithActionCard
                key={repost.profile.id}
                profile={repost.profile}
              />
            ))
          ) : (
            <p className="p-5 text-center text-sm text-muted-foreground">
              {t('posts.repostModal.empty', {
                defaultValue: 'No reposters yet',
              })}
            </p>
          )}
        </article>
      </DialogContent>
    </Dialog>
  );
}

// platform/svelte/src/lib/components/core/post/pieces/modals/RepostModal.svelte
<script lang="ts">
	import { ProfileWithActionCard } from '$lib/components/core/profile';
	import { ModalHeader, ModalWrapper } from '@openpeeps/ui';
	import type { PublicPost } from '@openpeeps/common/types';
	import { getPostRepostsStore } from '$lib/api';
	import { AccessDeniedLoader } from '$lib/components/layout';
	interface Props {
		post: PublicPost;
	}

	let { post }: Props = $props();
	let reposts = getPostRepostsStore(post);
</script>

<ModalWrapper>
	<ModalHeader title={'Reposters'} />
	<AccessDeniedLoader queries={[$reposts]}>
		<article class=" overflow-h-scroll m-4 max-h-[65vh] pb-3">
			{#if $reposts.data?.length}
				{#each $reposts.data as { profile } (profile.id)}
					<ProfileWithActionCard {profile} />
				{/each}
			{:else}
				<p class="p-5 text-center">No reposters yet</p>
			{/if}
		</article>
	</AccessDeniedLoader>
</ModalWrapper>
