// platform/react/src/components/navigation/breadcrumbs/Breadcrumbs.tsx
import { Fragment } from 'react';
import { useBreadcrumbs } from '../../../stores';
import { CrumbItem } from './Crumb';

export function Breadcrumbs() {
  const breadcrumbs = useBreadcrumbs();
  if (breadcrumbs.length === 0) return null;

  return (
    <ol className="text-muted-foreground mb-3 flex flex-wrap items-center gap-1 px-4 text-sm">
      {breadcrumbs.map((crumb, idx) => (
        <Fragment key={`${crumb.text}-${idx}`}>
          {idx > 0 && (
            <li className="op-crumb-separator" aria-hidden="true">
              ›
            </li>
          )}
          <CrumbItem crumb={crumb} />
        </Fragment>
      ))}
    </ol>
  );
}

// platform/svelte/src/lib/components/navigation/breadcrumbs/Breadcrumbs.svelte
<script lang="ts">
	import { getBreadcrumbsStore } from '$lib/stores';
	import Crumb from './Crumb.svelte';

	const breadcrumbs = getBreadcrumbsStore();
</script>

{#if $breadcrumbs.length > 0}
	<ol class="breadcrumb mb-3">
		{#each $breadcrumbs as crumb, index (index)}
			{#if index > 0}
				<li class="crumb-separator" aria-hidden="true">&rsaquo;</li>
			{/if}
			<Crumb {crumb} />
		{/each}
	</ol>
{/if}
