// platform/svelte/src/lib/components/core/notification/types/Mention.svelte
<script lang="ts">
	import { FeedPost } from '$lib/components/core/post';
	import { AtSign } from 'lucide-svelte';
	import type { ExpandedNotification } from '@openpeeps/common/types';
	import { profileName } from '@openpeeps/common/lib';
	import NotificationWrapper from '../NotificationWrapper.svelte';
	import { i18nContext } from '$lib/components/i18n';

	interface Props {
		notification: ExpandedNotification;
	}

	let { notification }: Props = $props();
	const { t } = i18nContext();

	const profile = notification.senderProfile!;
</script>

<NotificationWrapper {profile} seen={notification.seen} showProfile={false}>
	<a class="w-full px-4 py-2" href="/posts/{notification.post?.id}">
		<div class="flex w-full items-center justify-between">
			<p class="mb-2 flex items-center gap-2 text-sm font-semibold">
				<AtSign size={16} />
				{t('notification.mention.text', {
					profileName: profileName(profile)
				})}
			</p>
		</div>

		{#if notification.post}
			<FeedPost post={notification.post} />
		{/if}
	</a>
</NotificationWrapper>

// platform/rn-components/src/components/notifications/types/Mention.tsx
import React from 'react';
import { Pressable, View } from 'react-native';
import { ThemedText } from '~/components/ui/themed-text';
import { PublicNotification } from '@openpeepshq/common';
import { NotificationWrapper } from '../NotificationWrapper';
import { AtSignIcon } from '~/components/icons';
import { profileName } from '~/lib/utils';
import { useTranslation } from 'react-i18next';
import { MainStackParamList } from '~/components/navigation/types';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useNavigation } from '@react-navigation/native';
import { FeedPost } from '../../post/FeedPost';

interface NotificationTypeProps {
  notification: PublicNotification;
}

export const Mention: React.FC<NotificationTypeProps> = ({ notification }) => {
  const profile = notification.senderProfile!;
  const post = notification.post;
  const { t } = useTranslation();
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  return (
    <NotificationWrapper
      profile={profile}
      seen={notification.seen}
      showProfile={false}
    >
      <Pressable
        onPress={() => post && navigation.navigate('Post', { id: post.id })}
        className="w-full flex"
      >
        <View className="flex w-full items-center justify-between">
          <View className="mb-2 flex flex-row items-center gap-2 font-semibold flex-wrap">
            <AtSignIcon className="h-4 w-4 text-foreground" />
            <ThemedText className="text-foreground">
              {t('notification.mention.text', {
                profileName: profileName(profile),
              })}
            </ThemedText>
          </View>
        </View>
        {post && (
          <FeedPost
            post={post}
            showReplyTo={false}
            showMenu={false}
            noReactionHeader
          />
        )}
      </Pressable>
    </NotificationWrapper>
  );
};
