// platform/svelte/src/lib/components/core/post/post-form/EventForm.svelte
<script lang="ts">
  // @ts-nocheck
  import { Eye } from 'lucide-svelte';
  import {
    postCreationDataSchema,
    type Event,
    type PostCreationData,
    type AudienceSetting,
  } from '@openpeeps/common/types';
  import { Form, FormInput, Input, Label } from '@openpeeps/ui';
  import { FormImageInput } from '../../form';
  import VisibilitySelector from './VisibilitySelector.svelte';
  import { addHours } from 'date-fns';
  import { FormOpenpeepsMarkdownInput } from '../../form';
  import { i18nContext } from '$lib/components/i18n';
  import EventTypeSwitcher from './EventTypeSwitcher.svelte';
  import { getCurrentProfile } from '$lib/auth';
  import {
    EVENT_HEADER_ASPECT_RATIO,
    HEADER_IMAGE_MAX_WIDTH,
  } from '@openpeeps/common/lib';

  const me = getCurrentProfile();

  interface Props {
    postData: PostCreationData;
    isEdit?: boolean;
    onchange?: (data: PostCreationData) => void;
    valid?: boolean;
  }

  let {
    postData = $bindable(),
    isEdit = false,
    onchange,
    valid = $bindable(),
  }: Props = $props();

  let event = $derived(postData.data as Event);
  const { t } = i18nContext();

  const initialEvent = postData.data as Event;

  let showEndDate = $state(initialEvent.end !== undefined);

  let timeZone = $derived(event.timeZone);

  const toggleEndDate = (
    e: globalThis.Event & {
      currentTarget: EventTarget & HTMLInputElement;
    },
  ) => {
    const newShowEndDate = e.currentTarget.checked;
    if (!showEndDate && newShowEndDate) {
      event.end = addHours(event.start, 1).toISOString();
    } else if (!newShowEndDate) {
      event.end = undefined;
    }
    showEndDate = newShowEndDate;
  };

  const setAudience = (audienceSetting?: AudienceSetting) => {
    const isUserInAudience = audienceSetting?.audience?.some(
      (audienceMember) => audienceMember.id === me?.id,
    );
    if (audienceSetting) {
      postData.visibility = audienceSetting.visibility;
      postData.groupId = audienceSetting.groupId;
      postData.audience = isUserInAudience
        ? audienceSetting.audience
        : [...(audienceSetting.audience ?? []), ...(me ? [me] : [])];
    }
  };
</script>

<Form
  bind:data={postData}
  schema={postCreationDataSchema}
  {onchange}
  bind:valid
>
  <FormImageInput
    usage="event-header-image"
    displayType="full"
    aspectRatio={EVENT_HEADER_ASPECT_RATIO}
    maxWidth={HEADER_IMAGE_MAX_WIDTH}
    text={t('events.form.imageDescription')}
    specsText={t('events.form.imageSpecs')}
    showAltInput={false}
    classes={'aspect-video !h-auto'}
    path={['data', 'image']}
  />

  <div class="mt-4 flex flex-col gap-4 px-3">
    <h2 class="text-lg">{t('events.form.title')}</h2>
    <FormInput
      title={t('events.form.name')}
      type="text"
      path={['data', 'name']}
    />

    <p class="text-surface-500 text-sm">{t('events.form.description')}</p>

    <FormOpenpeepsMarkdownInput
      placeholder={t('events.form.descriptionPlaceholder')}
      maxLength={5000}
      path={['data', 'content']}
      inline
    />

    <h2 class="text-lg">{t('events.form.dateAndTimeTitle')}</h2>

    <FormInput
      title={t('events.form.startDate')}
      type="datetime-local"
      path={['data', 'start']}
      {timeZone}
      step={60}
    />

    <Label description={t('events.form.addEndDate')} forCheckbox={true}>
      <Input type="checkbox" checked={showEndDate} oninput={toggleEndDate} />
    </Label>

    {#if showEndDate}
      <FormInput
        title={t('events.form.endDate')}
        type="datetime-local"
        path={['data', 'end']}
        {timeZone}
        step={60}
      />
    {/if}

    <FormInput
      title={t('events.form.timezone')}
      placeholder={t('events.form.timezonePlaceholder')}
      type="select"
      path={['data', 'timeZone']}
      options={Intl.supportedValuesOf('timeZone').map((value) => ({
        value,
        label: value,
      }))}
    />

    <h2 class="text-lg">{t('events.form.location')}</h2>

    <EventTypeSwitcher {isEdit} />

    <h2 class="text-lg">{t('events.form.people')}</h2>

    <FormInput
      title={t('events.form.visibility')}
      description={t('events.form.visibilityNotChangeable')}
      type="mock"
      path={[]}
    >
      {#snippet lead()}
        <Eye size={16} />
      {/snippet}
      <div class="p-0! h-10">
        <VisibilitySelector
          {postData}
          {setAudience}
          showDirect
        />
      </div>
    </FormInput>

    <!-- <FormInput title="Number of attendees" type="number" path={['data', 'maxAttendees']} /> -->
    <FormInput
      description={t('events.form.attendeeListPublic')}
      type="checkbox"
      path={['data', 'attendeeListPublic']}
    />
  </div>
</Form>

// platform/react/src/components/post/post-form/EventForm.tsx
import { useState } from 'react';
import { X } from 'lucide-react';
import type {
  AudienceSetting,
  Event,
  PostCreationData,
} from '@openpeepshq/common/types';
import {
  EVENT_HEADER_ASPECT_RATIO,
  parseEventMaxAttendeesInput,
  withoutEventMaxAttendees,
} from '@openpeepshq/common/lib';
import { Input, Label } from '@openpeepshq/react-ui';
import { useT } from '../../../i18n';
import { useCurrentProfile } from '../../layout/IdentityContext';
import { ImageInput } from '../../form/ImageInput';
import { OpenpeepsMarkdownInput } from './OpenpeepsMarkdownInput';
import { ComposePreviewLinks } from './ComposePreviewLinks';
import { EventTypeSwitcher } from './EventTypeSwitcher';
import { PostAudienceSelector } from './PostAudienceSelector';
import { VisibilitySelector } from './VisibilitySelector';

export interface EventFormProps {
  postData: PostCreationData;
  onChange: (data: PostCreationData) => void;
  isEdit?: boolean;
}

const dateToInputValue = (value: string | undefined) => {
  if (!value) return '';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return '';
  const tz = d.getTimezoneOffset() * 60_000;
  return new Date(d.getTime() - tz).toISOString().slice(0, 16);
};

const toIso = (value: string) => {
  if (!value) return undefined;
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? undefined : d.toISOString();
};

const TIMEZONES =
  typeof Intl !== 'undefined' && 'supportedValuesOf' in Intl
    ? Intl.supportedValuesOf('timeZone')
    : [Intl.DateTimeFormat().resolvedOptions().timeZone];

export function EventForm({
  postData,
  onChange,
  isEdit = false,
}: EventFormProps) {
  const t = useT();
  const me = useCurrentProfile();

  const event = postData.data as Event;
  const [showEndDate, setShowEndDate] = useState(event.end !== undefined);
  const [audienceOpen, setAudienceOpen] = useState(false);

  const patchEvent = (patch: Partial<Event>) => {
    let next: Event = { ...event, ...patch };
    if ('maxAttendees' in patch && patch.maxAttendees === undefined) {
      next = withoutEventMaxAttendees(next);
    }
    onChange({
      ...postData,
      data: next,
    });
  };

  const setAudience = (settings: AudienceSetting) => {
    const audience = settings.audience ?? undefined;
    const includesMe = audience?.some((p) => p.id === me?.id);
    onChange({
      ...postData,
      visibility: settings.visibility,
      groupId: settings.groupId ?? undefined,
      audience:
        settings.visibility === 'direct'
          ? includesMe
            ? audience
            : [...(audience ?? []), ...(me ? [me] : [])]
          : undefined,
    });
  };

  return (
    <div data-testid="events-form-basic-details">
      <ImageInput
        usage="event-header-image"
        url={event.image}
        onChange={(image) => patchEvent({ image })}
        aspectRatio={EVENT_HEADER_ASPECT_RATIO}
        className="aspect-video !h-auto"
        text={t('events.form.imageDescription', {
          defaultValue: 'Upload an image for your event',
        })}
        specsText={t('events.form.imageSpecs', {
          defaultValue:
            'Your image should be at least 800 pixels wide with a 16x9 aspect ratio.',
        })}
        showAltInput={false}
      />

      <div className="mt-4 flex flex-col gap-4 px-3">
        <h2 className="text-lg">
          {t('events.form.title', { defaultValue: 'Basic Details' })}
        </h2>

        <Label
          title={t('events.form.name', { defaultValue: 'Event name' })}
          htmlFor="event-name"
        >
          <Input
            id="event-name"
            value={event.name ?? ''}
            onChange={(e) => patchEvent({ name: e.target.value })}
            data-testid="events-name-input"
          />
        </Label>

        <p className="text-surface-500 text-sm">
          {t('events.form.description', {
            defaultValue: 'Give your event a clear, descriptive name',
          })}
        </p>

        <OpenpeepsMarkdownInput
          rows={6}
          maxLength={5000}
          value={event.content ?? ''}
          onChange={(content) => patchEvent({ content })}
          testId="events-description-input"
          placeholder={t('events.form.descriptionPlaceholder', {
            defaultValue: 'Describe your event',
          })}
        />
        <ComposePreviewLinks content={event.content} />

        <h2 className="text-lg">
          {t('events.form.dateAndTimeTitle', {
            defaultValue: 'Date and Time',
          })}
        </h2>

        <Label
          title={t('events.form.startDate', { defaultValue: 'Start Date' })}
          htmlFor="event-start"
        >
          <Input
            id="event-start"
            type="datetime-local"
            step={60}
            value={dateToInputValue(event.start)}
            onChange={(e) => {
              const start = toIso(e.target.value);
              if (start) patchEvent({ start });
            }}
            data-testid="events-start-input"
          />
        </Label>

        <Label
          description={t('events.form.addEndDate', {
            defaultValue: 'Add end date and time',
          })}
          forCheckbox
        >
          <input
            type="checkbox"
            checked={showEndDate}
            onChange={(e) => {
              const checked = e.target.checked;
              setShowEndDate(checked);
              if (checked && event.start) {
                const end = new Date(event.start);
                end.setHours(end.getHours() + 1);
                patchEvent({ end: end.toISOString() });
              } else {
                patchEvent({ end: undefined });
              }
            }}
          />
        </Label>

        {showEndDate ? (
          <Label
            title={t('events.form.endDate', { defaultValue: 'End Date' })}
            htmlFor="event-end"
          >
            <Input
              id="event-end"
              type="datetime-local"
              step={60}
              value={dateToInputValue(event.end)}
              onChange={(e) => patchEvent({ end: toIso(e.target.value) })}
            />
          </Label>
        ) : null}

        <Label
          title={t('events.form.timezone', { defaultValue: 'Timezone' })}
          htmlFor="event-timezone"
        >
          <select
            id="event-timezone"
            className="bg-background w-full rounded-md border px-3 py-2 text-sm"
            value={event.timeZone ?? TIMEZONES[0]}
            onChange={(e) => patchEvent({ timeZone: e.target.value })}
          >
            {TIMEZONES.map((tz) => (
              <option key={tz} value={tz}>
                {tz}
              </option>
            ))}
          </select>
        </Label>

        <h2 className="text-lg">
          {t('events.form.location', { defaultValue: 'Location' })}
        </h2>

        <EventTypeSwitcher
          event={event}
          isEdit={isEdit}
          onChange={(next) => onChange({ ...postData, data: next })}
        />

        <h2 className="text-lg">
          {t('events.form.people', { defaultValue: 'People' })}
        </h2>

        <Label
          title={t('events.form.visibility', { defaultValue: 'Visibility' })}
          description={t('events.form.visibilityNotChangeable', {
            defaultValue:
              "Note:  The event visibility cannot be changed once the event is published.  Make sure you're adding the right people or group.",
          })}
        >
          <VisibilitySelector
            postData={postData}
            onClick={() => setAudienceOpen(true)}
            disabled={isEdit}
            showDirect
          />
        </Label>

        <Label
          description={t('events.form.attendeeListPublic', {
            defaultValue: 'Let an attendee see others attending this event',
          })}
          forCheckbox
        >
          <input
            type="checkbox"
            checked={event.attendeeListPublic ?? false}
            onChange={(e) =>
              patchEvent({ attendeeListPublic: e.target.checked })
            }
          />
        </Label>

        <Label
          title={t('events.form.maxAttendees', {
            defaultValue: 'Maximum attendees',
          })}
          description={t('events.form.maxAttendeesDescription', {
            defaultValue:
              'Limit how many people can RSVP yes to this event. Leave empty for no limit.',
          })}
        >
          <div className="op-input-group grid grid-cols-[1fr_auto]">
            <Input
              type="number"
              min={1}
              value={event.maxAttendees ?? ''}
              onChange={(e) => {
                patchEvent({
                  maxAttendees: parseEventMaxAttendeesInput(e.target.value),
                });
              }}
            />
            {event.maxAttendees != null ? (
              <button
                type="button"
                className="op-input-group-shim hover:bg-muted/80"
                title={t('events.form.clearMaxAttendees', {
                  defaultValue: 'Remove capacity limit',
                })}
                onClick={() => patchEvent({ maxAttendees: undefined })}
              >
                <X className="size-4" />
              </button>
            ) : null}
          </div>
        </Label>
      </div>

      {!isEdit ? (
        <PostAudienceSelector
          open={audienceOpen}
          onClose={() => setAudienceOpen(false)}
          type="event"
          visibility={postData.visibility}
          groupId={postData.groupId ?? undefined}
          audience={postData.audience ?? []}
          showDirect
          onConfirm={setAudience}
        />
      ) : null}
    </div>
  );
}
