// platform/svelte/src/lib/components/notifications/defaultNotifications/new-profile/Email.svelte
<script lang="ts">
	import type { EmailGlobals, ExpandedNotification } from '@openpeeps/common/types';
	import { Heading, Section, Text, Link, Button } from '@openpeeps/svelte5-email';
	import BaseEmailLayout from '../../../layout/BaseEmailLayout.svelte';
	import { emailStyles } from '$lib/components/styles';
	import { profileName } from '@openpeeps/common/lib';

	interface Props {
		globals: EmailGlobals;
		locals: ExpandedNotification;
	}

	let { globals, locals }: Props = $props();
	const { t } = globals.i18nContext;
</script>

<BaseEmailLayout 
	{globals} 
	previewText={t('emails.newProfile.title', {
		communityName: globals.communityConfig.info.name
	})}
	showLogo={true}
	showGreeting={true}
	showAppLinks={true}
	showFooter={true}
>
	<Heading style={emailStyles.heading}>
		{t('emails.newProfile.title', {
			communityName: globals.communityConfig.info.name
		})}</Heading
	>
	<Section>
		<Text style={emailStyles.paragraph}>
			{t('emails.newProfile.body', {
				profileName: locals.senderProfile ? profileName(locals.senderProfile) : '',
				communityName: globals.communityConfig.info.name
			})}
		</Text>
	</Section>
	<Section style={emailStyles.ctaContainer}>
		<Button href="{globals.serverData.rootUrl}/@{locals.senderProfile?.handle}" 
		style={emailStyles.button}>{t('emails.welcome.cta')}</Button>
	</Section>
</BaseEmailLayout>

// platform/server/src/emails/notifications/groupAdded/Email.tsx
import { Button, Heading, Section, Text } from '@react-email/components';
import type {
  EmailGlobals,
  ExpandedNotification,
} from '@openpeeps/common/types';
import { groupName, profileName } from '@openpeeps/common/lib';

import { BaseEmailLayout } from '../../BaseEmailLayout';
import { emailStyles } from '../../styles';

export const GroupAddedEmail = ({
  globals,
  locals,
}: {
  globals: EmailGlobals;
  locals: ExpandedNotification;
}) => {
  const { t } = globals.i18nContext;
  const senderName = locals.senderProfile
    ? profileName(locals.senderProfile)
    : '';
  const gName = locals.group ? groupName(locals.group) : '';

  return (
    <BaseEmailLayout
      globals={globals}
      previewText={t('emails.groupAdded.title', {
        groupName: gName,
        communityName: globals.communityConfig.info.name,
      })}
      showGreeting
      recipientProfile={locals.recipientProfile}
    >
      <Heading style={emailStyles.heading}>
        {t('emails.groupAdded.title', {
          groupName: gName,
          communityName: globals.communityConfig.info.name,
        })}
      </Heading>
      <Section>
        <Text style={emailStyles.paragraph}>
          {t('emails.groupAdded.body', {
            profileName: senderName,
            groupName: gName,
            communityName: globals.communityConfig.info.name,
          })}
        </Text>
        <Text style={emailStyles.paragraph}>{locals.group?.description}</Text>
      </Section>
      <Section style={emailStyles.ctaContainer}>
        <Button
          href={`${globals.serverData.rootUrl}/groups/@${locals.group?.handle}`}
          style={emailStyles.button}
        >
          {t('emails.groupAdded.cta')}
        </Button>
      </Section>
    </BaseEmailLayout>
  );
};
