// platform/svelte/src/lib/components/core/preview-link/PreviewLink.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { isLocalLink, isValidUrl } from './helpers';
	import LocalPreviewLink from './LocalPreviewLink.svelte';
	import RemotePreviewLink from './RemotePreviewLink.svelte';
	interface Props {
		url?: string;
	}

	let { url = '' }: Props = $props();

	const isValid = $derived(url && isValidUrl(url));

	const isLocal = $derived(isValid && isLocalLink(url, page.url.origin));
</script>

{#if isValid}
	{#if isLocal}
		<LocalPreviewLink {url} />
	{:else}
		<RemotePreviewLink {url} />
	{/if}
{/if}

// platform/react-native/src/components/custom/preview-link/PreviewLink.tsx
import React, { useMemo } from 'react';
import { isLocalLink, isValidUrl } from './helpers';
import { LocalPreviewLink } from './LocalPreviewLink';
import { RemotePreviewLink } from './RemotePreviewLink';
import { BASE_URL } from '../../../lib/constants';

interface PreviewLinkProps {
  url?: string;
}

export const PreviewLink = ({ url = '' }: PreviewLinkProps) => {
  const isValid = useMemo(() => url && isValidUrl(url), [url]);
  const isLocal = useMemo(
    () => isValid && isLocalLink(url, BASE_URL as string),
    [isValid, url],
  );

  if (!isValid) {
    return null;
  }

  return isLocal ? (
    <LocalPreviewLink url={url} />
  ) : (
    <RemotePreviewLink url={url} />
  );
};
