// platform/react/src/components/profile/ProfilePostsAndReplies.tsx
import { useState } from 'react';
import { Users } from 'lucide-react';
import type { PublicProfile } from '@openpeeps/common/types';
import { useOpenpeeps } from '../../contexts/openpeeps';
import { useT } from '../../i18n';
import { useNavigate } from '../../contexts/router';
import { AccessDeniedLoader } from '../layout/AccessDeniedLoader';
import { Feed } from '../post/Feed';
import { GroupCard } from '../groups/GroupCard';

export interface ProfilePostsAndRepliesProps {
  profile: PublicProfile;
}

/**
 * Translation of `profilePage/ProfilePostsAndReplies.svelte` with posts and
 * common-groups tabs.
 */
export function ProfilePostsAndReplies({
  profile,
}: ProfilePostsAndRepliesProps) {
  const t = useT();
  const navigate = useNavigate();
  const { openpeepsApi } = useOpenpeeps();
  const postsQuery = openpeepsApi.usePostsByProfile(profile.id);
  const commonGroupsQuery = openpeepsApi.useCommonGroups(profile.id);
  const [tab, setTab] = useState<'posts' | 'groups'>('posts');

  return (
    <div>
      <div className="border-b flex">
        <button
          type="button"
          className={`flex-1 px-4 py-3 text-sm font-medium ${tab === 'posts' ? 'border-primary border-b-2' : 'text-muted-foreground'}`}
          onClick={() => setTab('posts')}
        >
          {t('profile.posts', { defaultValue: 'Posts' })}
        </button>
        <button
          type="button"
          className={`flex-1 px-4 py-3 text-sm font-medium ${tab === 'groups' ? 'border-primary border-b-2' : 'text-muted-foreground'}`}
          onClick={() => setTab('groups')}
        >
          {t('profile.groups.tabName', { defaultValue: 'Groups' })}
        </button>
      </div>

      {tab === 'posts' ? (
        <Feed query={postsQuery} />
      ) : (
        <AccessDeniedLoader queries={[commonGroupsQuery]}>
          {(commonGroupsQuery.data ?? []).map((group) => (
            <button
              key={group.id}
              type="button"
              title={t('profile.postsAndReplies.openGroupTitle', {
                defaultValue: 'Open group',
              })}
              className="w-full text-left"
              onClick={() => navigate(`/groups/@${group.handle}`)}
            >
              <GroupCard group={group} />
            </button>
          ))}
          {!commonGroupsQuery.data?.length ? (
            <div className="flex h-[60vh] w-full flex-col items-center justify-center gap-y-6">
              <Users size={60} />
              <p>
                {t('profile.groups.noCommonGroups', {
                  defaultValue: 'No groups in common',
                })}
              </p>
            </div>
          ) : null}
        </AccessDeniedLoader>
      )}
    </div>
  );
}

// platform/svelte/src/lib/components/core/profile/profilePage/ProfilePostsAndReplies.svelte
<script lang="ts">
	import { ProfileFeed } from '$lib/components/core/post';
	import { TabGroup, Tab } from '@skeletonlabs/skeleton';
	import type { PublicProfile } from '@openpeeps/common/types';
	import { i18nContext } from '$lib/components/i18n';
	import { goto } from '$app/navigation';
	import { commonGroupsStore } from '@openpeeps/svelte/api';
	import { Loader, preventDefault, stopPropagation } from '@openpeeps/ui';
	import GroupCard from '../../groups/GroupCard.svelte';
	import { Users } from 'lucide-svelte';
  import { AccessDeniedLoader } from '$lib/components/layout';

	const { t } = i18nContext();

	interface Props {
		profile: PublicProfile;
	}

	let { profile }: Props = $props();

	let tabSet: number = $state(0);
	const commonGroupsQuery = commonGroupsStore(profile.id);
</script>

<TabGroup>
	<Tab bind:group={tabSet} name="tab1" value={0}>
		<span class="text-sm">{t('profile.posts')}</span>
	</Tab>
	<Tab bind:group={tabSet} name="tab2" value={1}>
		<span class="text-sm">{t('profile.groups.tabName')}</span>
	</Tab>
	{#snippet panel()}
		{#if tabSet === 0}
			<ProfileFeed {profile} />
		{:else if tabSet === 1}
			<AccessDeniedLoader queries={[$commonGroupsQuery]}>
				{#each $commonGroupsQuery.data || [] as group (group.id)}
					<button
						title={t('profile.postsAndReplies.openGroupTitle')}
						class="w-full"
						onclick={stopPropagation(preventDefault(() => goto(`/groups/@${group.handle}`)))}
					>
						<GroupCard {group} />
					</button>
				{/each}
				{#if !$commonGroupsQuery.data?.length}
					<div class="flex h-[60vh] w-full flex-col items-center justify-center gap-y-6">
						<Users size={60} />
						<p>{t('profile.groups.noCommonGroups')}</p>
					</div>
				{/if}
			</AccessDeniedLoader>
		{/if}
	{/snippet}
</TabGroup>
