// platform/react/src/components/profile/ProfileHeader.tsx
import { MapPin } from 'lucide-react';
import type { PublicProfile } from '@openpeeps/common/types';
import { truncateText } from '@openpeeps/common/lib';

import { useT } from '../../i18n';
import { Avatar } from './Avatar';
import { PostMarkdown } from '../post/Markdown';
import { ProfilePageAction } from './ProfilePageAction';
import { ProfileStats } from './ProfileStats';

export interface ProfileHeaderProps {
  profile: PublicProfile;
  isCurrentProfile?: boolean;
}

/**
 * Translation of `profilePage/ProfileHeader.svelte`. Renders the cover image
 * + avatar + display name + handle + bio + location + custom fields.
 */
export function ProfileHeader({
  profile,
  isCurrentProfile = false,
}: ProfileHeaderProps) {
  const t = useT();
  return (
    <div className="relative">
      <div className="mb-8">
        <div className="bg-surface-200 relative h-44 bg-cover bg-center">
          {profile.header && (
            <img
              src={profile.header}
              alt="banner"
              className="absolute left-0 top-0 h-full w-full object-cover"
            />
          )}
          <Avatar
            profile={profile}
            size={6}
            containerClassName="absolute -bottom-12 left-4"
            borderless
          />
        </div>
        <div className="p-2">
          <h1 className="mt-4 text-base font-semibold">
            {truncateText(profile.displayName || profile.handle, 50)}
          </h1>

          <span className="text-surface-500 my-1 text-sm font-normal">
            @{profile.handle}
          </span>

          <PostMarkdown
            source={profile.bio || t('profile.noBio', { defaultValue: '' })}
          />

          {profile.location?.text && (
            <div className="flex items-center gap-1">
              <span className="input-group-shim">
                <MapPin className="size-3" />
              </span>
              <p>{profile.location.text}</p>
            </div>
          )}

          {(profile.fields ?? []).map((field) => (
            <div key={field.name} className="mt-4 flex items-center gap-2">
              <span className="text-surface-500 text-sm">{field.name}</span>
              <PostMarkdown source={field.value} className="pt-1 text-sm" />
            </div>
          ))}

          <ProfileStats profile={profile} />
          <ProfilePageAction
            profile={profile}
            isCurrentProfile={isCurrentProfile}
          />
        </div>
      </div>
    </div>
  );
}

// platform/svelte/src/lib/components/core/profile/profilePage/ProfileHeader.svelte
<script lang="ts">
	import { Avatar } from '$lib/components/core/profile';
	import { truncateText } from '@openpeeps/common/lib';
	import type { PublicProfile } from '@openpeeps/common/types';
	import OpenpeepsMarkdown from '$lib/components/core/markdown/OpenpeepsMarkdown.svelte';
	import ProfileAction from './ProfilePageAction.svelte';
	import ProfileStats from './ProfileStats.svelte';
	import { i18nContext } from '$lib/components/i18n';
	import { MapPin } from 'lucide-svelte';

	const { t } = i18nContext();

	interface Props {
		profile: PublicProfile;
		isCurrentProfile?: boolean;
	}

	let { profile, isCurrentProfile = false }: Props = $props();
</script>

<div class="relative">
	<div class="mb-8">
		<div class="relative h-44 bg-surface-200 bg-cover bg-center">
			{#if profile?.header}
				<img
					src={profile?.header}
					alt="banner"
					class="absolute left-0 top-0 h-full w-full object-cover"
				/>
			{/if}
			<Avatar {profile} size={6} containerClass="absolute -bottom-12 left-4" borderless={true} />
		</div>
		<ProfileAction {profile} {isCurrentProfile} />
		<div class="p-2">
			<h1 class="mt-4 text-base font-semibold">
				{truncateText(profile?.displayName || profile?.handle, 50)}
			</h1>

			<span class="my-1 text-sm font-normal text-surface-500">
				@{profile?.handle}
			</span>

			<OpenpeepsMarkdown source={profile?.bio || t('profile.noBio')} linkPreviewMode="none" />

			<div class="flex gap-1 items-center">
				<div class="input-group-shim"><MapPin class="size-3" /></div>
				<p>{profile?.location?.text}</p>
			</div>
			<ProfileStats {profile} />

			{#each profile.fields || [] as field}
				<div class="mt-4 flex items-center gap-2">
					<span class="text-sm text-surface-500">{field.name}</span>
					<OpenpeepsMarkdown isInline source={field.value} linkPreviewMode="none" class="pt-3.5" />
				</div>
			{/each}
		</div>
	</div>
</div>
