// platform/rn-components/src/components/post/VideoPlayOverlay.tsx
import React from 'react';
import { View } from 'react-native';
import { PlayIcon } from '~/components/icons';

export interface VideoPlayOverlayProps {
  video: boolean;
}

/** Play affordance on video thumbnails; the parent handles the press. */
export const VideoPlayOverlay = ({ video }: VideoPlayOverlayProps) => {
  if (!video) return null;

  return (
    <View
      pointerEvents="none"
      className="absolute inset-0 items-center justify-center"
    >
      <View className="size-12 items-center justify-center rounded-full bg-black/60">
        <PlayIcon size={32} className="text-white" />
      </View>
    </View>
  );
};

// platform/svelte/src/lib/components/core/post/VideoPlayOverlay.svelte
<script lang="ts">
	import { CirclePlay } from 'lucide-svelte';

	interface Props {
		video: boolean;
	}

	const { video }: Props = $props();
</script>

{#if video}
	<div class="absolute inset-0 flex items-center justify-center">
		<div class="flex h-12 w-12 items-center justify-center rounded-full bg-black/60 text-white">
			<CirclePlay />
		</div>
	</div>
{/if}
