// platform/react-native/src/components/custom/markdown/OpenPeepsMarkdown.tsx
import {
  MentionWithProfile,
} from '@openpeeps/common';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import React, { ReactNode, useMemo } from 'react';
import { Linking, View } from 'react-native';
import Markdown, { MarkdownIt, tokensToAST, stringToTokens } from 'react-native-markdown-display';
import { buildGoto } from '~/components/navigation/helpers';
import { MainStackParamList } from '~/components/navigation/types';
import { BASE_URL } from '~/lib/constants';
import { handleInternalURLNavigation, isLocalLink } from '~/lib/utils';
import { hashtagPlugin, hashtagRenderer } from './extensions/hashtag';
import { mentionPlugin, mentionRenderer } from './extensions/mention';
import { codeBlockRenderer, fenceRenderer } from './extensions/codeBlock';
import { codeInlineRenderer } from './extensions/codeInline';
import { markdownTheme } from './theme';
import { extractLinks, isEmail } from './utils';
import { PreviewLink } from '../preview-link';
import { useOpenPeepsTheme } from '~/theme/OpenPeepsThemeProvider';

interface OpenPeepsMarkdownProps {
  source: string;
  mentions?: MentionWithProfile[];
  linkPreviewMode?: 'prepend' | 'append' | 'inline' | 'none';
}

export const OpenPeepsMarkdown = ({ source, mentions = [], linkPreviewMode = 'none' }: OpenPeepsMarkdownProps) => {
  const { colors } = useOpenPeepsTheme();
  const styles = useMemo(() => markdownTheme(colors), [colors]);

  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  const markdownit = useMemo(() => {
    const md = MarkdownIt({ linkify: true, typographer: true });
    md.use(hashtagPlugin);
    md.use(mentionPlugin(mentions));
    return md;
  }, [mentions]);

  const goto = buildGoto(navigation);

  const handleLinkPress = (url: string) => {
    const isLocal = isLocalLink(url, BASE_URL as string);
    if (url.includes('goto:/') || isLocal) {
      handleInternalURLNavigation(url, goto);
    } else {
      Linking.openURL(url);
    }
  };

  const tokens = useMemo(() => stringToTokens(source, markdownit), [source, markdownit]);
  const links = useMemo(() => tokens.flatMap(extractLinks).filter((link) => !isEmail(link)), [tokens]);
  const ast = useMemo(() => tokensToAST(tokens), [tokens]);

  return (
    <View>
      {linkPreviewMode === 'prepend' && links.length > 0 && (
        <View className="mb-4">
          {links.map((link) => (
            <PreviewLink key={link} url={link} />
          ))}
        </View>
      )}
      <Markdown
        style={styles}
        onLinkPress={url => {
          handleLinkPress(url);
          return false;
        }}
        markdownit={markdownit}
        rules={{
          hashtag: hashtagRenderer(handleLinkPress, colors.primary),
          mention: mentionRenderer(handleLinkPress, colors.primary, mentions),
          code_block: codeBlockRenderer(colors),
          fence: fenceRenderer(colors),
          code_inline: codeInlineRenderer(colors),
        }}>
        {ast as unknown as ReactNode[]}
      </Markdown>
      {linkPreviewMode === 'append' && links.length > 0 && (
        <View className="mt-4">
          {links.map((link) => (
            <PreviewLink key={link} url={link} />
          ))}
        </View>
      )}
    </View>
  );
};

// platform/svelte/src/lib/components/core/markdown/OpenpeepsMarkdown.svelte
<script lang="ts">
  import SvelteMarkdown from '@humanspeak/svelte-markdown';
  import a from './elements/a.svelte';
  import p from './elements/p.svelte';
  import Mention from './elements/Mention.svelte';
  import Hashtag from './elements/Hashtag.svelte';
  import type { Component } from 'svelte';
  import { marked, type TokensList } from 'marked';
  import type { MentionWithProfile } from '@openpeeps/common/types';
  import { PreviewLink } from '$lib/components';
  import hashtag from './extensions/hashtag';
  import mention from './extensions/mention';
  import { emptyTokensList, extractLinks } from './utils';
  import { presetProps } from '$lib/utils';
  import type { Renderers } from './types';
  import { isEmail } from '../preview-link/helpers';

  interface Props {
    source?: string | TokensList;
    mentions?: MentionWithProfile[];
    renderers?: Record<string, Component>;
    linkPreviewMode?: 'prepend' | 'append' | 'inline' | 'none';
    newTab?: boolean | ((link: string) => boolean);
    isInline?: boolean;
    class?: string;
  }

  let {
    source,
    mentions = [],
    renderers = {},
    linkPreviewMode = 'none',
    newTab = false,
    isInline = false,
    class: additionalClass = '',
  }: Props = $props();

  const combinedRenderers = {
    link: newTab ? presetProps(a, { newTab }) : a,
    paragraph: p,
    mention: newTab ? presetProps(Mention, { newTab }) : Mention,
    hashtag: newTab ? presetProps(Hashtag, { newTab }) : Hashtag,
    ...renderers,
  } as unknown as Renderers;

  let tokens: TokensList = $derived(
    Array.isArray(source)
      ? source
      : source
        ? marked
            .use({
              extensions: [mention(mentions), hashtag()],
            })
            .lexer(source)
        : emptyTokensList,
  );
  let links: string[] = $derived(tokens.flatMap(extractLinks));
</script>

<div>
  {#if linkPreviewMode === 'prepend'}
    {#each links as link, index (index)}
      <PreviewLink url={link} />
    {/each}
  {/if}
  <div
    class="allpeep-markdown prose {additionalClass} prose-code:before:content-[''] prose-code:after:content-[''] break-words"
  >
    <SvelteMarkdown {isInline} source={tokens} renderers={combinedRenderers} />
  </div>
  {#if linkPreviewMode === 'append' && tokens.links}
    <div class="mt-4">
      {#each links as link, index (index)}
        {#if !isEmail(link)}
          <PreviewLink url={link} />
        {/if}
      {/each}
    </div>
  {/if}
</div>
