// platform/svelte/src/lib/components/core/groups/AdminGroupCard.svelte
<script lang="ts">
  import type { GroupWithMeta } from '@openpeeps/common/types';
  import { DeleteGroupModal, GroupCard } from '.';
  import { getModalManager, PopupMenu, PopupMenuButton } from '@openpeeps/ui';
  import { i18nContext } from '$lib/components/i18n';
  import { Trash, Users } from 'lucide-svelte';
  import { groupMembersStore } from '$lib/api';
  import { sortGroupMembers } from '@openpeeps/common';
  import ProfileBadge from '../profile/ProfileBadge.svelte';
  import { goto } from '$app/navigation';
  const { t } = i18nContext();
  const modalManager = getModalManager();

  interface Props {
    group: GroupWithMeta;
    deleteCallback?: () => void;
  }

  let { group, deleteCallback }: Props = $props();

  const membersQuery = groupMembersStore(group.id);

  let admins = $derived(
    sortGroupMembers($membersQuery.data || []).filter((m) =>
      m.roles?.includes('admin'),
    ),
  );
</script>

<div class="">
  <GroupCard {group}>
    {#snippet action()}
      <PopupMenu>
        <PopupMenuButton
          title={t('groups.viewMembers')}
          text={t('groups.viewMembers')}
          icon={Users}
          action={() =>
            goto(`/admin/groups/@${group.handle}/members`)
          }
        />
        <PopupMenuButton
          title={t('common.actions.delete') + ' ' + 'group'}
          text={t('common.actions.delete')}
          icon={Trash}
          action={() =>
            modalManager.show(DeleteGroupModal, {
              group,
              callback: deleteCallback,
            })}
        />
      </PopupMenu>
    {/snippet}
  </GroupCard>
  <div class="p-2">
    {#each admins || [] as admin (admin.profile.id)}
      <a href="/@{admin.profile.handle}" target="_blank" class="mr-2">
        <ProfileBadge profile={admin.profile} />
      </a>
    {/each}
  </div>
</div>

// platform/web/src/pages/admin/components/AdminGroupCard.tsx
import { useMemo } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Trash, Users } from 'lucide-react';
import { sortGroupMembers } from '@openpeeps/common/lib';
import type { GroupWithMeta } from '@openpeeps/common/types';
import { useT, useOpenpeeps } from '@openpeeps/react';
import { Avatar, GroupCard } from '@openpeeps/react/components';
import { PopupMenu, PopupMenuButton } from '@openpeeps/react-ui';

export interface AdminGroupCardProps {
  group: GroupWithMeta;
  onDelete: (group: GroupWithMeta) => void;
}

export function AdminGroupCard({ group, onDelete }: AdminGroupCardProps) {
  const t = useT();
  const navigate = useNavigate();
  const { openpeepsApi } = useOpenpeeps();
  const membersQuery = openpeepsApi.useGroupMembers(group.id);

  const admins = useMemo(
    () =>
      sortGroupMembers(membersQuery.data ?? []).filter((m) =>
        m.roles?.includes('admin'),
      ),
    [membersQuery.data],
  );

  return (
    <div className="rounded-md border">
      <div className="flex items-center justify-between gap-2 p-2">
        <GroupCard group={group} showAction={false} />
        <PopupMenu placement="bottom-end" width="w-56">
          <PopupMenuButton
            icon={Users}
            title={t('groups.viewMembers', { defaultValue: 'View members' })}
            text={t('groups.viewMembers', { defaultValue: 'View members' })}
            action={() => navigate(`/admin/groups/@${group.handle}/members`)}
          />
          <PopupMenuButton
            icon={Trash}
            title={t('admin.groups.delete', { defaultValue: 'Delete group' })}
            text={t('common.actions.delete', { defaultValue: 'Delete' })}
            action={() => onDelete(group)}
            danger
          />
        </PopupMenu>
      </div>
      {admins.length > 0 ? (
        <div className="flex flex-wrap gap-2 p-2 pt-0">
          {admins.map((admin) => (
            <Link
              key={admin.profile.id}
              to={`/@${admin.profile.handle}`}
              className="bg-surface-100 hover:bg-surface-200 flex items-center gap-1.5 rounded-full py-0.5 pl-0.5 pr-2 text-xs"
            >
              <Avatar profile={admin.profile} size={1.5} />
              <span>
                {admin.profile.displayName || `@${admin.profile.handle}`}
              </span>
            </Link>
          ))}
        </div>
      ) : null}
    </div>
  );
}
