// platform/svelte/src/lib/components/core/notification/types/Repost.svelte
<script lang="ts">
	import { FeedPost } from '$lib/components/core/post';
	import { Repeat } from 'lucide-svelte';
	import type { ExpandedNotification } from '@openpeeps/common/types';
	import NotificationWrapper from '../NotificationWrapper.svelte';
	import { i18nContext } from '$lib/components/i18n';
	import { profileName } from '@openpeeps/common/lib';

	interface Props {
		notification: ExpandedNotification;
	}

	let { notification }: Props = $props();
	const { t } = i18nContext();

	const profile = notification.senderProfile!;
</script>

<NotificationWrapper {profile} seen={notification.seen} showProfile={false}>
	<a class="w-full px-4 py-2" href="/posts/{notification.post?.id}">
		<div class="flex w-full items-center justify-between">
			<p class="mb-2 flex items-center gap-2 text-sm font-semibold">
				<Repeat size={16} />
				{t('notification.repost.text', {
					profileName: profileName(profile)
				})}{' '}
			</p>
		</div>

		{#if notification.post}
			<FeedPost post={notification.post} />
		{/if}
	</a>
</NotificationWrapper>

// platform/rn-components/src/components/custom/notification/types/repost.tsx
import React from 'react';
import { Pressable, View } from 'react-native';
import { ThemedText } from '~/components/ui/themed-text';
import { PublicNotification } from '@openpeepshq/common';
import { NotificationWrapper } from '../NotificationWrapper';
import { Repeat2Icon } from '~/components/icons';
import { profileName } from '~/lib/utils';
import { useTranslation } from 'react-i18next';
import { MainStackParamList } from '~/components/navigation/types';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useNavigation } from '@react-navigation/native';
import { FeedPost } from '../../post';

interface NotificationTypeProps {
  notification: PublicNotification;
}
export const Repost: React.FC<NotificationTypeProps> = ({ notification }) => {
  const profile = notification.senderProfile!;
  const { t } = useTranslation();
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  return (
    <NotificationWrapper
      profile={profile}
      seen={notification.seen}
      showProfile={false}>
      <Pressable
        onPress={() =>
          navigation.navigate('Post', { id: notification.post?.id as string })
        }
        className="w-full ">
        <View className="flex w-full items-center justify-between">
          <View className="mb-2 flex flex-row items-center gap-2 font-semibold flex-wrap">
            <Repeat2Icon className="h-4 w-4 text-foreground" />
            <ThemedText>
              {t('notification.repost.text', {
                profileName: profileName(profile),
              })}{' '}
            </ThemedText>
          </View>
        </View>
        {notification.post && <FeedPost post={notification.post} />}
      </Pressable>
    </NotificationWrapper>
  );
};
