// platform/web/src/pages/admin/Configuration.tsx
import { useT, useSetPageHeader } from '@openpeeps/react';
import { ConfigMenuButton } from './ConfigMenuButton';

export function AdminConfiguration() {
  const t = useT();

  useSetPageHeader(
    t('configuration.title', { defaultValue: 'Configuration' }),
    undefined,
    'admin-configuration-heading',
  );

  return (
    <div className="p-4">
      <ConfigMenuButton
        translationPrefix="configuration.community"
        action="/admin/configuration/community"
      />
      <ConfigMenuButton
        translationPrefix="configuration.serverSettings"
        action="/admin/configuration/server-settings"
      />
      <ConfigMenuButton
        translationPrefix="configuration.email"
        action="/admin/configuration/email"
      />
      <ConfigMenuButton
        translationPrefix="configuration.i18n"
        action="/admin/configuration/i18n"
      />
    </div>
  );
}

// platform/app/src/routes/(protected)/(private)/admin/configuration/+page.svelte
<script lang="ts">
  import { ConfigMenuButton } from '@openpeeps/svelte/components';
</script>

<div class="p-4">
  <ConfigMenuButton
    translationPrefix="configuration.community"
    action="/admin/configuration/community"
  ></ConfigMenuButton>
  <ConfigMenuButton
    translationPrefix="configuration.serverSettings"
    action="/admin/configuration/server-settings"
  ></ConfigMenuButton>
  <ConfigMenuButton
    translationPrefix="configuration.email"
    action="/admin/configuration/email"
  ></ConfigMenuButton>
  <ConfigMenuButton
    translationPrefix="configuration.i18n"
    action="/admin/configuration/i18n"
  ></ConfigMenuButton>
</div>
