// platform/web/src/pages/admin/Members.tsx
import { useMemo, useState } from 'react';
import { matchesQuery } from '@openpeeps/common/lib';
import { useT, useOpenpeeps, useSetPageHeader } from '@openpeeps/react';
import { Avatar } from '@openpeeps/react/components';
import { Input } from '@openpeeps/react-ui';
import { AdminInviteActions } from './components/AdminInviteActions';
import { ProfileRowActions } from './components/ProfileRowActions';

export function AdminMembers() {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const profilesQuery = openpeepsApi.admin.useProfilesList();
  const [search, setSearch] = useState('');

  const headerActions = useMemo(() => <AdminInviteActions />, []);

  useSetPageHeader(
    t('admin.members.title', { defaultValue: 'Members' }),
    headerActions,
  );

  const filtered = useMemo(() => {
    const profiles = profilesQuery.data ?? [];
    if (!search) return profiles;
    return profiles.filter((p) => matchesQuery(p, search));
  }, [profilesQuery.data, search]);

  return (
    <div className="p-4">
      <div className="mb-4">
        <Input
          placeholder={t('admin.members.searchPlaceholder', {
            defaultValue: 'Search member by name or email',
          })}
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      {filtered.length === 0 ? (
        <div className="flex w-full items-center justify-center p-4">
          <h2 className="text-lg">
            {t('admin.members.noUsersFound', {
              defaultValue: 'No users found',
            })}
          </h2>
        </div>
      ) : (
        <div className="rounded-md border">
          <table className="w-full text-sm">
            <thead className="bg-surface-100">
              <tr>
                <th className="p-2 text-left">
                  {t('admin.members.profileColumn', {
                    defaultValue: 'Profile',
                  })}
                </th>
                <th className="p-2 text-left">
                  {t('admin.members.handleColumn', { defaultValue: 'Handle' })}
                </th>
                <th className="p-2 text-left">
                  {t('admin.members.rolesColumn', { defaultValue: 'Roles' })}
                </th>
                <th className="p-2 text-left">
                  {t('admin.members.createdColumn', {
                    defaultValue: 'Created',
                  })}
                </th>
                <th className="p-2"></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((p) => (
                <tr key={p.id} className="border-t">
                  <td className="p-2">
                    <div className="flex items-center gap-2">
                      <Avatar profile={p} size={2} />
                      <span>{p.displayName || `@${p.handle}`}</span>
                    </div>
                  </td>
                  <td className="text-muted-foreground p-2">@{p.handle}</td>
                  <td className="p-2 text-xs">
                    {(p.roles ?? [])
                      .map((r) => r.displayName || r.key)
                      .join(', ') || '—'}
                  </td>
                  <td className="text-muted-foreground p-2 text-xs">
                    {new Date(p.createdAt).toLocaleDateString()}
                  </td>
                  <td className="p-2 text-right">
                    <ProfileRowActions profile={p} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// platform/app/src/routes/(protected)/(private)/admin/members/+page.svelte
<script lang="ts">
  import {
    ProfileCard,
    ProfileTablePopup,
    MembersHeaderActions,
    AccessDeniedLoader,
  } from '@openpeeps/svelte/components';
import { SearchAndFilterBar, Badges, Table } from '@openpeeps/ui';
  import { type ColumnDefinition } from '@openpeeps/ui';
  import type { ProfileWithMeta } from '@openpeeps/common/types';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { adminProfilesStore } from '@openpeeps/svelte/api';
  import { matchesQuery } from '@openpeeps/common/lib';
  import { i18nContext } from '@openpeeps/svelte/components/i18n';

  const { t } = i18nContext();

  getPageHeaderStore().set({ title: t('admin.members.title'), actions: MembersHeaderActions });
  let search: string = $state('');

  const profilesQuery = adminProfilesStore();

  let allProfiles: ProfileWithMeta[] | undefined = $derived(
    $profilesQuery.data,
  );

  const columnDefinitions: ColumnDefinition<ProfileWithMeta>[] = [
    {
      id: 'profile',
      header: t('admin.members.profileColumn'),
      type: 'component',
      render: (profile) => ({
        component: ProfileCard,
        props: {
          profile,
          showAction: false,
        },
      }),
    },
    {
      id: 'roles',
      header: t('admin.members.rolesColumn'),
      type: 'component',
      render: (profile) => ({
        component: Badges,
        props: {
          data: profile.roles?.map((r) => ({
            status: r.displayName,
          })),
        },
      }),
    },

    {
      id: 'action',
      header: ' ',
      type: 'component',
      render: (profile) => ({
        component: ProfileTablePopup,
        props: {
          profile,
        },
      }),
    },
  ];
</script>

<AccessDeniedLoader queries={[$profilesQuery]}>
  {#if $profilesQuery.data?.length}
    <div class="pt-4">
      <SearchAndFilterBar
        placeholder={t('admin.members.searchPlaceholder')}
        bind:search
      />
      <Table
        data={allProfiles}
        {columnDefinitions}
        filter={(row: ProfileWithMeta) => !search || matchesQuery(row, search)}
      />
    </div>
  {:else}
    <div class="w-full flex justify-center items-center p-4">
      <h2 class="text-lg">{t('admin.members.noUsersFound')}</h2>
    </div>
  {/if}
</AccessDeniedLoader>
