// platform/react/src/components/accounts/SignUpLoginModal.tsx
import {
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@openpeeps/react-ui';
import { useT } from '../../i18n';
import { useRouter } from '../../contexts/router';

export interface SignUpLoginModalProps {
  onClose: () => void;
}

/**
 * Translation of @openpeeps/svelte/components/core/accounts/modals/
 * SignUpLoginModal.svelte. Prompts a guest to sign in before performing an
 * action that requires authentication (e.g. replying to a post).
 */
export function SignUpLoginModal({ onClose }: SignUpLoginModalProps) {
  const t = useT();
  const router = useRouter();

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-md" showCloseButton={false}>
        <DialogHeader>
          <DialogTitle>
            {t('accounts.login.title', { defaultValue: 'Login' })}
          </DialogTitle>
          <DialogDescription>
            {t('accounts.login.description', {
              defaultValue: 'Login to your account',
            })}
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <Button variant="variant-ringed-surface" action={onClose}>
            {t('common.cancel', { defaultValue: 'Cancel' })}
          </Button>
          <Button
            variant="variant-filled-primary"
            action={() => {
              router.navigate('/auth/login');
              onClose();
            }}
          >
            {t('accounts.login.loginButton', { defaultValue: 'Log In' })}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// platform/svelte/src/lib/components/core/accounts/modals/SignUpLoginModal.svelte
<script lang="ts">
	import { Button, getModalManager, ModalFooter, ModalHeader, ModalWrapper } from '@openpeeps/ui';
	import { goto } from '$app/navigation';
	import { i18nContext } from '$lib/components/i18n';

	const { t } = i18nContext();
	const modalManager = getModalManager();
</script>

<ModalWrapper>
	<ModalHeader title={t('accounts.login.title')} />
	<article class="flex flex-col p-4">
		<p class="">{t('accounts.login.description')}</p>
	</article>

	<ModalFooter>
		<Button title={t('common.cancel')} variant="variant-ringed-surface" action={modalManager.close}
			>{t('common.cancel')}</Button
		>
		<Button
			title={t('accounts.login.loginButton')}
			variant="variant-filled-primary"
			action={async () => {
				await goto('/auth/login');
				modalManager.close();
			}}
		>
			{t('accounts.login.loginButton')}
		</Button>
	</ModalFooter>
</ModalWrapper>
