// platform/react/src/pages/auth/Login.tsx
import { useEffect, useState } from 'react';
import { Link as RouterLink } from 'react-router-dom';
import { Eye, EyeOff } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  loginRequestSchema,
  type LoginRequest,
} from '@openpeepshq/common/types';
import {
  Button,
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  Input,
  Link,
  Toast,
} from '@openpeepshq/react-ui';
import {
  useT,
  useOpenpeeps,
  useCredentialsStore,
  useNavigate,
  useSearchParams,
  useHrefOf,
} from '../../index';
import { AuthLayout, useServerInfo, useToast } from '../../components';

import { performLogin } from '../../lib/auth';

export function Login() {
  const t = useT();
  const navigate = useNavigate();
  const searchParams = useSearchParams();
  const href = useHrefOf();
  const { client } = useOpenpeeps();
  const { credentialsStore } = useCredentialsStore();
  const serverInfo = useServerInfo();
  const { success, error: toastError } = useToast();

  const form = useForm<LoginRequest>({
    resolver: zodResolver(loginRequestSchema),
    defaultValues: { email: '', password: '' },
  });
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const redirectUrl =
    searchParams.get('redirect') ?? href({ type: 'feed', feed: 'local' });
  const paymentParam = searchParams.get('payment');

  useEffect(() => {
    if (paymentParam === 'success') {
      success(
        t('payment.success.message', {
          defaultValue: 'Payment received. Redirecting…',
        }),
      );
    } else if (paymentParam === 'cancel') {
      toastError(
        t('payment.cancelled', { defaultValue: 'Checkout was cancelled.' }),
      );
    }
  }, [paymentParam, success, toastError, t]);

  const onSubmit = form.handleSubmit(async (data) => {
    setError(null);
    try {
      const tr = await performLogin(client, credentialsStore, data);
      if (tr.checkoutUrl) {
        window.location.assign(tr.checkoutUrl);
      } else {
        navigate(redirectUrl);
      }
    } catch (err) {
      setError((err as Error).message);
    }
  });

  return (
    <AuthLayout
      redirectTo={redirectUrl}
      navigate={(url) => void navigate(url)}
      hasPayment={!!paymentParam}
    >
      <Form {...form}>
        <form className="flex flex-col gap-3" onSubmit={onSubmit}>
          <h2 className="text-xl" data-testid="auth-login-title">
            {t('auth.login.title', { defaultValue: 'Login' })}
          </h2>
          <p>
            {t('auth.login.welcomeBack', {
              defaultValue:
                'Welcome back, enter details below to log into your community',
            })}
          </p>

          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel>
                  {t('auth.login.email', { defaultValue: 'Email' })}
                </FormLabel>
                <FormControl>
                  <Input
                    {...field}
                    type="email"
                    autoComplete="email"
                    placeholder={t('auth.login.emailPlaceholder', {
                      defaultValue: 'you@email.org',
                    })}
                    data-testid="auth-login-email"
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>
                  {t('auth.login.password', { defaultValue: 'Password' })}
                </FormLabel>
                <FormControl>
                  <div className="relative">
                    <Input
                      {...field}
                      type={showPassword ? 'text' : 'password'}
                      autoComplete="current-password"
                      data-testid="auth-login-password"
                      className="pr-10"
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword((v) => !v)}
                      aria-label={
                        showPassword
                          ? t('auth.login.hidePassword', {
                              defaultValue: 'Hide password',
                            })
                          : t('auth.login.showPassword', {
                              defaultValue: 'Show password',
                            })
                      }
                      className="absolute right-2 top-1/2 -translate-y-1/2"
                    >
                      {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                    </button>
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <span className="px-2">
            <Link
              action={href({ type: 'auth', mode: 'request-reset-password' })}
              className="text-sm"
            >
              {t('auth.login.forgotPassword', {
                defaultValue: 'Forgot Password?',
              })}
            </Link>
          </span>

          {error && (
            <Toast
              variant="error"
              testId="auth-login-error"
              onDismiss={() => setError(null)}
            >
              {error}
            </Toast>
          )}

          <Button
            type="submit"
            variant="default"
            title={t('auth.login.logIn', { defaultValue: 'Log in' })}
            loading={form.formState.isSubmitting}
            data-testid="auth-login-submit"
          >
            {t('auth.login.logIn', { defaultValue: 'Log in' })}
          </Button>
        </form>
      </Form>

      {serverInfo.sso?.oidc && serverInfo.sso.oidc.length > 0 && (
        <div className="mt-4 flex flex-col gap-2">
          {serverInfo.sso.oidc.map((provider) => (
            <Button
              key={provider.id}
              variant="outline"
              action={`/api/openpeeps/core/v1/sso/oidc/${provider.id}/authorize`}
              className="w-full justify-center"
              data-testid={`auth-login-oidc-${provider.id}`}
            >
              {t('auth.login.loginWith', {
                defaultValue: 'Login with {{provider}}',
                provider: provider.name,
              })}
            </Button>
          ))}
        </div>
      )}

      <div className="flex justify-between px-2 pt-4">
        {serverInfo.communityConfig?.settings?.openRegistrations && (
          <span>
            <RouterLink
              to={href({ type: 'about' })}
              className="op-anchor text-sm"
            >
              {t('auth.login.joinCommunity', {
                defaultValue: 'Join Community',
              })}
            </RouterLink>
          </span>
        )}
        {serverInfo.publicContent && (
          <span>
            <RouterLink
              to={href({ type: 'feed', feed: 'local' })}
              className="op-anchor text-sm"
            >
              {t('auth.login.seeCommunityFeed', {
                defaultValue: 'See community feed',
              })}
            </RouterLink>
          </span>
        )}
      </div>
    </AuthLayout>
  );
}

// platform/app/src/routes/auth/login/+page.svelte
<script lang="ts">
  import { getToastStore } from '@skeletonlabs/skeleton';
  import { login } from '@openpeeps/svelte/api';
  import { loginRequestSchema, type LoginRequest } from '@openpeeps/common/types';
  import { Form, FormInput, SubmitButton } from '@openpeeps/ui';
  import { onMount } from 'svelte';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { Link } from '@openpeeps/ui';
  import { toast } from '@openpeeps/svelte/utils';
  import { Eye, EyeOff } from 'lucide-svelte';
  import { getServerInfo } from '@openpeeps/svelte/server';

  const toastStore = getToastStore();

  let data = $state<LoginRequest>({
    email: '',
    password: '',
  });

  let redirectUrl = '';
  getPageHeaderStore().set({
    title: 'Login',
  });

  const handleSubmit = async () => {
    await login(data)
      .then((r) => window.open(r?.checkoutUrl || redirectUrl, '_self'))
      .catch((error: { message: string }) =>
        toastStore.trigger(
          toast({
            message: error.message,
            background: 'variant-filled-error',
          }),
        ),
      );
  };

  onMount(async () => {
    const url = new URL(window.location.href);
    const redirect = url.searchParams.get('redirect');
    if (redirect) {
      redirectUrl = redirect;
    } else {
      redirectUrl = '/feeds/local';
    }
  });

  const serverInfo = getServerInfo();
  let showPassword = $state(false);
</script>

<Form {data} schema={loginRequestSchema}>
  <h2 class="text-xl">Login</h2>

  <p>Welcome back, enter details below to log into your community</p>

  <FormInput path={['email']} placeholder="you@email.org" description="Email" />

  <FormInput
    path={['password']}
    description="Password"
    type={showPassword ? 'text' : 'password'}
  >
    {#snippet tail()}
      <button
        onclick={() => (showPassword = !showPassword)}
        aria-label={showPassword ? 'Hide password' : 'Show password'}
        class="m-0 !p-0"
      >
        {#if showPassword}
          <EyeOff size={20} />
        {:else}
          <Eye size={20} />
        {/if}
      </button>
    {/snippet}
  </FormInput>
  <span class="px-2">
    <Link action="/auth/request-reset-password" class="text-sm">
      Forgot Password?
    </Link>
  </span>
  <SubmitButton action={handleSubmit} title="Log in" disable={false}
    >Log in</SubmitButton
  >
</Form>
<div class="flex justify-between px-2">
  {#if serverInfo.communityConfig.settings.openRegistrations}
    <span>
      <Link action="/about" class="text-sm">Join Community</Link>
    </span>
  {/if}
  <span>
    {#if serverInfo.publicContent}
      <Link action="/feeds/local" class="text-sm">See community feed</Link>
    {/if}
  </span>
</div>
