// platform/web/src/pages/auth/Login.tsx
import { useEffect, useState } from 'react';
import { Link as RouterLink, useNavigate, useSearchParams } from 'react-router-dom';
import { Eye, EyeOff } from 'lucide-react';
import {
  loginRequestSchema,
  type LoginRequest,
} from '@openpeeps/common/types';
import {
  Form,
  FormInput,
  Link,
  SubmitButton,
} from '@openpeeps/react-ui';
import { useT, useOpenpeeps, useCredentialsStore } from '@openpeeps/react';
import { AuthLayout, useServerInfo } from '@openpeeps/react/components';

import { performLogin } from '../../lib/auth';

export function Login() {
  const t = useT();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { client } = useOpenpeeps();
  const { credentialsStore } = useCredentialsStore();
  const serverInfo = useServerInfo();

  const [data] = useState<LoginRequest>(() => ({ email: '', password: '' }));
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const redirectUrl = searchParams.get('redirect') ?? '/feeds/local';

  useEffect(() => {
    setError(null);
  }, [data.email, data.password]);

  const handleSubmit = async () => {
    setError(null);
    try {
      const tr = await performLogin(client, credentialsStore, data);
      if (tr.checkoutUrl) {
        window.location.assign(tr.checkoutUrl);
      } else {
        navigate(redirectUrl);
      }
    } catch (err) {
      setError((err as Error).message);
    }
  };

  return (
    <AuthLayout redirectTo={redirectUrl} navigate={navigate}>
      <Form data={data} schema={loginRequestSchema}>
        <h2 className="text-xl">{t('auth.login', { defaultValue: 'Login' })}</h2>
        <p>
          {t('auth.loginIntro', {
            defaultValue:
              'Welcome back, enter details below to log into your community',
          })}
        </p>

        <FormInput
          path={['email']}
          placeholder="you@email.org"
          description={t('common.email', { defaultValue: 'Email' })}
        />

        <FormInput
          path={['password']}
          description={t('common.password', { defaultValue: 'Password' })}
          type={showPassword ? 'text' : 'password'}
          tail={
            <button
              type="button"
              onClick={() => setShowPassword((v) => !v)}
              aria-label={showPassword ? 'Hide password' : 'Show password'}
              className="m-0 !p-0"
            >
              {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
            </button>
          }
        />

        <span className="px-2">
          <Link action="/auth/request-reset-password" className="text-sm">
            {t('auth.forgotPassword', { defaultValue: 'Forgot Password?' })}
          </Link>
        </span>

        {error && (
          <p className="text-error rounded-md border border-error/40 p-2 text-sm">
            {error}
          </p>
        )}

        <SubmitButton action={handleSubmit} title="Log in" disable={false}>
          {t('auth.login', { defaultValue: 'Log in' })}
        </SubmitButton>
      </Form>

      <div className="flex justify-between px-2 pt-4">
        {serverInfo.communityConfig?.settings?.openRegistrations && (
          <span>
            <RouterLink to="/about" className="op-anchor text-sm">
              {t('auth.joinCommunity', { defaultValue: 'Join Community' })}
            </RouterLink>
          </span>
        )}
        {serverInfo.publicContent && (
          <span>
            <RouterLink to="/feeds/local" className="op-anchor text-sm">
              {t('auth.seeFeed', { defaultValue: 'See community feed' })}
            </RouterLink>
          </span>
        )}
      </div>
    </AuthLayout>
  );
}

// platform/app/src/routes/auth/login/+page.svelte
<script lang="ts">
  import { getToastStore } from '@skeletonlabs/skeleton';
  import { login } from '@openpeeps/svelte/api';
  import { loginRequestSchema, type LoginRequest } from '@openpeeps/common/types';
  import { Form, FormInput, SubmitButton } from '@openpeeps/ui';
  import { onMount } from 'svelte';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { Link } from '@openpeeps/ui';
  import { toast } from '@openpeeps/svelte/utils';
  import { Eye, EyeOff } from 'lucide-svelte';
  import { getServerInfo } from '@openpeeps/svelte/server';

  const toastStore = getToastStore();

  let data = $state<LoginRequest>({
    email: '',
    password: '',
  });

  let redirectUrl = '';
  getPageHeaderStore().set({
    title: 'Login',
  });

  const handleSubmit = async () => {
    await login(data)
      .then((r) => window.open(r?.checkoutUrl || redirectUrl, '_self'))
      .catch((error: { message: string }) =>
        toastStore.trigger(
          toast({
            message: error.message,
            background: 'variant-filled-error',
          }),
        ),
      );
  };

  onMount(async () => {
    const url = new URL(window.location.href);
    const redirect = url.searchParams.get('redirect');
    if (redirect) {
      redirectUrl = redirect;
    } else {
      redirectUrl = '/feeds/local';
    }
  });

  const serverInfo = getServerInfo();
  let showPassword = $state(false);
</script>

<Form {data} schema={loginRequestSchema}>
  <h2 class="text-xl">Login</h2>

  <p>Welcome back, enter details below to log into your community</p>

  <FormInput path={['email']} placeholder="you@email.org" description="Email" />

  <FormInput
    path={['password']}
    description="Password"
    type={showPassword ? 'text' : 'password'}
  >
    {#snippet tail()}
      <button
        onclick={() => (showPassword = !showPassword)}
        aria-label={showPassword ? 'Hide password' : 'Show password'}
        class="m-0 !p-0"
      >
        {#if showPassword}
          <EyeOff size={20} />
        {:else}
          <Eye size={20} />
        {/if}
      </button>
    {/snippet}
  </FormInput>
  <span class="px-2">
    <Link action="/auth/request-reset-password" class="text-sm">
      Forgot Password?
    </Link>
  </span>
  <SubmitButton action={handleSubmit} title="Log in" disable={false}
    >Log in</SubmitButton
  >
</Form>
<div class="flex justify-between px-2">
  {#if serverInfo.communityConfig.settings.openRegistrations}
    <span>
      <Link action="/about" class="text-sm">Join Community</Link>
    </span>
  {/if}
  <span>
    {#if serverInfo.publicContent}
      <Link action="/feeds/local" class="text-sm">See community feed</Link>
    {/if}
  </span>
</div>
