// libraries/react-ui/src/components/form/Label.tsx
import * as React from 'react';
import { Info } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { FormMessage } from './types';

export interface LabelProps {
  title?: string;
  messages?: FormMessage[];
  classes?: string;
  description?: string;
  forCheckbox?: boolean;
  inline?: boolean;
  dirty?: boolean;
  required?: boolean;
  htmlFor?: string;
  children?: React.ReactNode;
}

const messageColor = (m: FormMessage, dirty: boolean) => {
  if (!dirty) return '';
  switch (m.severity) {
    case 'error':
      return 'text-error-500';
    case 'warning':
      return 'text-warning-500';
    case 'info':
      return '';
  }
};

/**
 * Translation of `Label.svelte`. Renders title, optional description, child
 * input(s), and form messages.
 */
export function Label({
  title = '',
  messages = [],
  classes,
  description = '',
  forCheckbox = false,
  inline = false,
  dirty = false,
  required = false,
  htmlFor,
  children,
}: LabelProps) {
  return (
    <label
      htmlFor={htmlFor}
      className={cn(
        'flex',
        inline ? 'flex-row items-center gap-2' : 'flex-col',
        classes,
      )}
    >
      {title && (
        <span>
          {title}
          {required && <span className={cn(dirty && 'text-error-500')}>*</span>}
        </span>
      )}
      <span
        className={cn('flex flex-grow', forCheckbox ? 'items-center gap-2' : 'flex-col')}
      >
        {description && <span className="text-sm">{description}</span>}
        {children}
      </span>
      {messages.map((m, idx) => (
        <span key={idx} className={cn('flex items-center gap-2', messageColor(m, dirty))}>
          <Info className="size-4" />
          {m.text}
        </span>
      ))}
    </label>
  );
}

// libraries/ui/src/lib/form/Label.svelte
<script lang="ts">
  import type { FormMessage } from './types';
  import { Info } from 'lucide-svelte';
  interface Props {
    title?: string;
    messages?: FormMessage[];
    classes?: string;
    description?: string;
    forCheckbox?: boolean;
    inline?: boolean;
    dirty?: boolean;
    children?: import('svelte').Snippet;
    required?: boolean;
    [key: string]: unknown;
  }

  let {
    title = '',
    messages = [],
    classes = '',
    description = '',
    forCheckbox = false,
    inline = false,
    dirty = false,
    children,
    required = false,
    ...rest
  }: Props = $props();

  const messageColor = (m: FormMessage) => {
    if (dirty) {
      switch (m.severity) {
        case 'error':
          return 'text-error-500';
        case 'warning':
          return 'text-warning-500';
        case 'info':
          return '';
      }
    } else {
      return '';
    }
  };
</script>

<label
  class="label flex {inline
    ? 'flex-row items-center gap-2'
    : 'flex-col'} {classes}"
  {...rest}
>
  {#if title}
    <span>
      {title}
      {#if required}
        <span class:text-error-500={dirty}>*</span>
      {/if}
    </span>
  {/if}
  <span
    class="flex {forCheckbox ? ' items-center gap-2' : 'flex-col'} flex-grow"
  >
    <span class="text-sm">
      {description}
    </span>
    {@render children?.()}
  </span>
  {#each messages || [] as m, index (index)}
    <span class="{messageColor(m)} flex items-center gap-2">
      <Info class="size-4" />
      {m.text}
    </span>
  {/each}
</label>
