// libraries/react-ui/src/components/form/SubmitButton.tsx
import * as React from 'react';
import { Button } from '@/components/button';
import { useFormContext, useFormMessages } from './context';

export interface SubmitButtonProps {
  title: string;
  action: () => unknown | Promise<unknown>;
  children?: React.ReactNode;
  disable?: boolean;
  testId?: string;
}

export function SubmitButton({
  title,
  action,
  children,
  disable = true,
  testId,
}: SubmitButtonProps) {
  const { validate } = useFormContext();
  const messages = useFormMessages();

  React.useEffect(() => {
    void validate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const valid = Object.keys(messages).length === 0;

  return (
    <Button
      title={title}
      action={action}
      variant="variant-filled-primary"
      className="w-full"
      disabled={disable ? !valid : false}
      data-testid={testId}
    >
      {children}
    </Button>
  );
}

// libraries/ui/src/lib/form/SubmitButton.svelte
<script lang="ts" module>
  import type { ZodRawShape } from 'zod';

  type T = ZodRawShape;
</script>

<script lang="ts" generics="T extends ZodRawShape">
  import { Button } from '$lib';
  import { getFormContext } from '$lib';
  import type { Snippet } from 'svelte';

  interface Props {
    title: string;
    action: () => unknown | Promise<unknown>;
    children?: Snippet;
    disable?: boolean;
  }

  let { title, action, children, disable = true }: Props = $props();

  const { messagesStore, validate } = getFormContext<T>();

  validate();
  let valid = $state(Object.keys($messagesStore).length === 0);

  messagesStore.subscribe((data) => {
    valid = Object.keys(data).length === 0;
  });
</script>

<Button
  {title}
  {action}
  variant="variant-filled-primary"
  class="w-full"
  disabled={disable ? !valid : false}
>
  {@render children?.()}
</Button>
