// libraries/react-ui/src/components/badges/Badges.tsx
import { Badge } from './Badge';
import type { Variant } from '@/types';

export interface BadgesProps {
  data: { status: string; variant?: Variant }[];
}

export function Badges({ data }: BadgesProps) {
  return (
    <div className="flex flex-wrap gap-1">
      {data.map(({ status, variant }, idx) => (
        <Badge key={idx} status={status} variant={variant} />
      ))}
    </div>
  );
}

// libraries/ui/src/lib/badges/Badges.svelte
<script lang="ts">
  import type { Variant } from '$lib/types';
  import Badge from './Badge.svelte';

  interface Props {
    data: { status: string; variant?: Variant }[];
  }

  let { data }: Props = $props();
</script>

<div class="flex flex-wrap">
  {#each data as { status, variant }}
    <Badge {status} {variant} />
  {/each}
</div>
