// libraries/ui/src/lib/expandable-box/ExpandableBox.svelte
<script lang="ts">
	import { ChevronDown, ChevronRight } from 'lucide-svelte';
	import type { Snippet } from 'svelte';

	const {
		title,
		children,
		initialOpen = false
	}: { title: Snippet; children: Snippet; initialOpen?: boolean } = $props();

	let open = $state(initialOpen);
</script>

<div class="flex items-start gap-2">
	<button onclick={() => (open = !open)} class="w-4">
		{#if open}
			<ChevronDown />
		{:else}
			<ChevronRight />
		{/if}
	</button>
	<div class="flex-grow">
		<div>
			{@render title()}
		</div>
		{#if open}
			<div>
				{@render children()}
			</div>
		{/if}
	</div>
</div>

// libraries/react-ui/src/components/expandable-box/ExpandableBox.tsx
import * as React from 'react';
import { ChevronDown, ChevronRight } from 'lucide-react';

export interface ExpandableBoxProps {
  title: React.ReactNode;
  children: React.ReactNode;
  initialOpen?: boolean;
}

export function ExpandableBox({ title, children, initialOpen = false }: ExpandableBoxProps) {
  const [open, setOpen] = React.useState(initialOpen);
  return (
    <div className="flex items-start gap-2">
      <button
        type="button"
        className="w-4"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
      >
        {open ? <ChevronDown /> : <ChevronRight />}
      </button>
      <div className="flex-grow">
        <div>{title}</div>
        {open && <div>{children}</div>}
      </div>
    </div>
  );
}
