// platform/app/src/routes/(protected)/(conditionally-public)/feeds/local/+page.svelte
<script lang="ts">
  import { Feed, NewNoteButton } from '@openpeeps/svelte/components';
  import { infiniteLocalFeedStore, serverInfoStore } from '@openpeeps/svelte/api';
  import { i18nContext } from '@openpeeps/svelte/components';
  import { setPageHeader } from '@openpeeps/svelte/stores';
  import { getCurrentProfile } from '@openpeeps/svelte/auth';
  import { getDefaultVisibility } from '@openpeeps/svelte';

  const { t } = i18nContext();
  const currentProfile = getCurrentProfile();
  const visibility = getDefaultVisibility();
  const query = infiniteLocalFeedStore({ limit: 15 });

  const serverInfo = serverInfoStore();
  let pinnedPostId: string | undefined = $derived(
    $serverInfo.data?.communityConfig?.content?.pinnedPost,
  );
  setPageHeader({ title: t('navigation.community') });
</script>

<NewNoteButton {visibility} {currentProfile} />
<Feed {query} {pinnedPostId} />

// platform/react/src/pages/feeds/Local.tsx
import { useT, useOpenpeeps, useSetPageHeader } from '../../index';
import {
  Feed,
  useDefaultVisibility,
  useNewNotePlusButton,
  useServerInfo,
  PluginSlot,
} from '../../components';

export function FeedsLocal() {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const serverInfo = useServerInfo();
  const visibility = useDefaultVisibility();

  useNewNotePlusButton({ visibility });

  const query = openpeepsApi.useLocalFeed();
  const pinnedPostId = serverInfo.communityConfig?.content?.pinnedPost;

  useSetPageHeader(
    t('navigation.community', { defaultValue: 'Community' }),
    undefined,
    'feeds-community-heading',
  );

  return (
    <>
      <PluginSlot name="plugins.header" className="p-4 pb-0" />
      <Feed query={query} pinnedPostId={pinnedPostId ?? undefined} />
    </>
  );
}
