// platform/svelte/src/lib/components/core/jams/lobby/GuestDataForm.svelte
<script lang="ts">
	import { LabelOld, Input } from '@openpeeps/ui';
	import { Button } from '@openpeeps/ui';
	import { getServerInfo } from '$lib/server';
	import { type GuestData } from '@openpeeps/common/types';
	import { getTheme, profileName } from '@openpeeps/common/lib';
	import { getJamContext } from '$lib/components/core/jams/context';
	import { currentProfileSettingsStore, getGuestPass } from '$lib/api';

	const serverInfo = getServerInfo();
	let profileSettingsQuery = currentProfileSettingsStore()
	let profileSettings = $profileSettingsQuery.data
	const logoSmall = getTheme(serverInfo.communityConfig, profileSettings).logoSmall;

	const {
		communityConfig: {
			info: { termsAndConditions }
		}
	} = serverInfo;

	const { jamPost, jamEvent } = getJamContext();

	interface Props {
		guestData?: GuestData;
	}

	let {
		guestData = $bindable({
			displayName: '',
			email: ''
		})
	}: Props = $props();

	const onSubmit = async () => {
		await getGuestPass({ ...guestData, resource: { type: 'jam', id: jamPost.id } });
		window.location.reload();
	};
</script>

<div class="flex h-full w-full items-center justify-center">
	<div class="flex w-[90%] flex-col items-center justify-center md:w-[25%] bg-surface-50 rounded-md border p-4">
		<img src={logoSmall} alt="logo" class="mb-6 h-10" />
		<div class="text-2xl">
			{jamEvent.name} - {profileName(jamPost.profile)}
		</div>
		<div>Enter your details below to proceed to waiting room</div>

		<div class="mt-5 space-y-6">
			<LabelOld title="Full name">
				<Input bind:value={guestData.displayName} required placeholder="Full Name" />
			</LabelOld>
			<LabelOld title="Email">
				<Input bind:value={guestData.email} required placeholder="Email" />
			</LabelOld>

			<p class="">
				By continuing, you agree to the
				<a target="_blank" href={termsAndConditions || '/docs/terms-and-conditions'} class="anchor">
					Terms of Service
				</a>
				as regards jam activities
			</p>

			<Button title="Continue" action={onSubmit} variant="variant-filled-primary" class="w-full"
				>Continue</Button
			>
		</div>
	</div>
</div>

// platform/rn-components/src/components/custom/jam/pieces/guest-data-form.tsx
import { Event, PublicPost, getTheme } from '@openpeepshq/common';
import { CachedImage } from '~/components/custom/common';
import { useForm } from 'react-hook-form';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
import { Form, FormField, FormInput } from '~/components/ui/form';
import { ThemedText } from '~/components/ui/themed-text';
import { Button } from '~/components/ui/button';
import { ActivityIndicator, Dimensions, Linking, View } from 'react-native';
import React from 'react';
import { useOpenpeeps } from '@openpeepshq/react';

interface GuestDataFormProps {
  jamPost: PublicPost;
}

export const GuestDataForm: React.FC<GuestDataFormProps> = ({ jamPost }) => {
  const jamEvent = jamPost.data as Event;
  const { openpeepsApi } = useOpenpeeps();
  const { data: server, isLoading } = openpeepsApi.useServerInfo();
  const { width } = Dimensions.get('window');
  const getGuestPass = openpeepsApi.guestPassAction();
  const logoSmall = server
    ? getTheme(server.communityConfig).logoSmall
    : undefined;

  const form = useForm({
    defaultValues: {
      displayName: '',
      email: '',
      resource: {
        type: 'jams' as const,
        id: jamPost.id,
      },
    },
  });

  const guestData = form.getValues();

  const onSubmit = () => getGuestPass(guestData);

  return (
    <KeyboardAwareScrollView className="flex h-full w-full">
      {isLoading && <ActivityIndicator size={'small'} />}
      <Form {...form}>
        {logoSmall ? (
          <CachedImage
            url={logoSmall}
            style={{ width, height: width * 0.6 }}
            resizeMode="cover"
          />
        ) : null}
        <ThemedText className="text-2xl mt-2 text-center">
          {jamEvent?.name || 'Jam'}
        </ThemedText>
        <ThemedText className="my-4 text-center">
          Enter your details below to proceed to waiting room
        </ThemedText>
        <View className="flex gap-y-6 w-full px-4">
          <View className="relative w-full">
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormInput
                  label="Email"
                  placeholder=""
                  {...field}
                  className="rounded-md"
                  autoCapitalize="none"
                />
              )}
            />
          </View>

          <View className="relative w-full">
            <FormField
              control={form.control}
              name="displayName"
              render={({ field }) => (
                <FormInput
                  label="Name"
                  placeholder=""
                  {...field}
                  className="rounded-md"
                  autoCapitalize="none"
                />
              )}
            />
          </View>

          <View className="flex flex-row">
            <ThemedText>By continuing, you agree to the</ThemedText>
            <ThemedText
              className="underline ml-2"
              onPress={() => Linking.openURL('/docs/terms-and-conditions')}
            >
              Terms of Service
            </ThemedText>
          </View>

          <Button onPress={onSubmit} variant="outline" className="w-full">
            <ThemedText>Continue</ThemedText>
          </Button>
        </View>
      </Form>
    </KeyboardAwareScrollView>
  );
};
