// platform/svelte/src/lib/components/core/profile/profilePage/ProfileStats.svelte
<script lang="ts">
	import type { PublicProfile } from '@openpeeps/common/types';
	import { i18nContext } from '$lib/components/i18n';

	const { t } = i18nContext();

	interface Props {
		profile: PublicProfile;
	}

	let { profile }: Props = $props();
</script>

<div class="mt-2 flex items-center gap-x-4">
	<a href="/@{profile.handle}/followers" class="anchor cursor-pointer text-sm">
		<span class="font-semibold">
			{profile.profileStats.followersCount}
		</span>
		{t('profile.followers.title')}
	</a>
	<a href="/@{profile?.handle}/following" class="anchor cursor-pointer text-sm">
		<span class="font-semibold">
			{profile.profileStats.followingCount}
		</span>
		{t('profile.following.title')}
	</a>
</div>

// platform/rn-components/src/components/profile/ProfileStats.tsx
import React from 'react';
import { Pressable, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { PublicProfile } from '@openpeepshq/common';
import { MainStackParamList } from '~/components/navigation/types';
import { ThemedText } from '~/components/ui/themed-text';

export interface ProfileStatsProps {
  profile: PublicProfile;
}

export const ProfileStats = ({ profile }: ProfileStatsProps) => {
  const { t } = useTranslation();
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  return (
    <View className="mt-2 flex-row items-center gap-x-4">
      <Pressable
        onPress={() =>
          navigation.navigate('ProfileFollowers', { id: profile.id })
        }
      >
        <ThemedText className="text-sm">
          <ThemedText className="text-sm font-semibold">
            {profile.profileStats?.followersCount ?? 0}
          </ThemedText>{' '}
          {t('profile.followers.title')}
        </ThemedText>
      </Pressable>
      <Pressable
        onPress={() =>
          navigation.navigate('ProfileFollowing', { id: profile.id })
        }
      >
        <ThemedText className="text-sm">
          <ThemedText className="text-sm font-semibold">
            {profile.profileStats?.followingCount ?? 0}
          </ThemedText>{' '}
          {t('profile.following.title')}
        </ThemedText>
      </Pressable>
    </View>
  );
};
