// platform/rn-components/src/components/post/post-form/ArticleForm.tsx
import React from 'react';
import { View } from 'react-native';
import { useTranslation } from 'react-i18next';
import type {
  Article,
  AudienceSetting,
  PostCreationData,
} from '@openpeepshq/common';
import { HEADER_IMAGE_MAX_WIDTH } from '@openpeepshq/common/lib';
import { applyAudienceSetting, useCurrentProfile } from '@openpeepshq/react';
import { ImageInput } from '~/components/form/ImageInput';
import { Input } from '~/components/ui/input';
import { ThemedText } from '~/components/ui/themed-text';
import { OpenpeepsMarkdownInput } from './OpenpeepsMarkdownInput';
import { VisibilitySelector } from './VisibilitySelector';

export interface ArticleFormProps {
  postData: PostCreationData;
  onChange: (data: PostCreationData) => void;
  isEdit?: boolean;
}

export const ArticleForm = ({
  postData,
  onChange,
  isEdit = false,
}: ArticleFormProps) => {
  const { t } = useTranslation();
  const me = useCurrentProfile();
  const article = postData.data as Article;

  const patchArticle = (patch: Partial<Article>) =>
    onChange({ ...postData, data: { ...article, ...patch } });

  const setAudience = (settings: AudienceSetting) =>
    onChange(applyAudienceSetting(postData, settings, me));

  return (
    <View>
      <ImageInput
        usage="article-header-image"
        url={article.image}
        onChange={(image) => patchArticle({ image })}
        text={t('articles.form.uploadCover', {
          defaultValue: 'Upload your cover image',
        })}
        specsText={t('form.imageInput.recommendedWidth', {
          defaultValue: 'Recommended width {{width}} pixels',
          width: HEADER_IMAGE_MAX_WIDTH,
        })}
      />

      <View className="mt-4 gap-y-4 px-3">
        <ThemedText className="text-lg">
          {t('articles.form.title', { defaultValue: 'New Article' })}
        </ThemedText>

        <View className="gap-y-1">
          <ThemedText className="text-sm font-medium">
            {t('articles.form.title', { defaultValue: 'New Article' })}
          </ThemedText>
          <Input
            value={article.title ?? ''}
            onChangeText={(title) => patchArticle({ title })}
          />
        </View>

        <OpenpeepsMarkdownInput
          rows={16}
          maxLength={10000}
          value={article.content ?? ''}
          onChange={(content) => patchArticle({ content })}
          placeholder={t('articles.form.contentPlaceholder', {
            defaultValue:
              'Write your content here.  User markdown for formatting',
          })}
        />

        <View className="gap-y-1">
          <ThemedText className="text-sm font-medium">
            {t('articles.form.visibility', {
              defaultValue: 'Who can see this (Required)',
            })}
          </ThemedText>
          <ThemedText className="text-xs text-muted-foreground">
            {t('articles.form.visibilityNotChangeable', {
              defaultValue:
                "Once you post your article, you can't change the visibility",
            })}
          </ThemedText>
          <VisibilitySelector
            audienceSetting={postData}
            onChange={setAudience}
            disabled={isEdit}
            showDirect
          />
        </View>
      </View>
    </View>
  );
};

// platform/svelte/src/lib/components/core/post/post-form/ArticleForm.svelte
<script lang="ts">
  import { Eye } from 'lucide-svelte';
  import {
    postCreationDataSchema,
    type PostCreationData,
    type AudienceSetting,
  } from '@openpeeps/common/types';
  import { Form, FormInput } from '@openpeeps/ui';
  import { FormImageInput } from '../../form';
  import VisibilitySelector from './VisibilitySelector.svelte';
  import { i18nContext } from '$lib/components/i18n';
  import FormOpenpeepsMarkdownInput from '../../form/FormOpenpeepsMarkdownInput.svelte';
  import { getCurrentProfile } from '$lib/auth';

  interface Props {
    postData: PostCreationData;
    isEdit?: boolean;
    onchange?: (data: PostCreationData) => void;
    valid?: boolean;
  }

  let {
    postData = $bindable(),
    isEdit = false,
    onchange,
    valid = $bindable(),
  }: Props = $props();

  const { t } = i18nContext();

  const me = getCurrentProfile();

  const setAudience = (audienceSetting?: AudienceSetting) => {
    const isUserInAudience = audienceSetting?.audience?.some(
      (audienceMember) => audienceMember.id === me.id,
    );
    if (audienceSetting) {
      postData.visibility = audienceSetting.visibility;
      postData.groupId = audienceSetting.groupId;
      postData.audience = isUserInAudience
        ? audienceSetting.audience
        : [...(audienceSetting.audience ?? []), me];
    }
  };
</script>

<Form
  bind:data={postData}
  schema={postCreationDataSchema}
  {onchange}
  bind:valid
>
  <FormImageInput
    usage="article-header-image"
    displayType="full"
    maxWidth={480}
    showSelectAspectRatio={true}
    text="Upload your cover image"
    specsText="Minimum width 480 pixels"
    showAltInput={false}
    path={['data', 'image']}
    classes={'h-96'}
    showFullImage={true}
  />

  <div class="mt-4 flex flex-col gap-4 px-3">
    <h2 class="text-lg">{t('articles.form.title')}</h2>
    <FormInput
      title={t('articles.form.title')}
      type="text"
      path={['data', 'title']}
    />

    <FormOpenpeepsMarkdownInput
      placeholder={t('articles.form.contentPlaceholder')}
      maxLength={10000}
      path={['data', 'content']}
      inline
    />


    <FormInput
      title={t('articles.form.visibility')}
      description={t('articles.form.visibilityNotChangeable')}
      type="mock"
      path={[]}
    >
      {#snippet lead()}
        <Eye size={16} />
      {/snippet}
      <div class="p-0! h-10">
        <VisibilitySelector
          {postData}
          disabled={isEdit}
          {isEdit}
          {setAudience}
          showDirect
        />
      </div>
    </FormInput>
  </div>
</Form>
