// platform/react/src/components/post/post-form/ArticleForm.tsx
import { useState } from 'react';
import type {
  Article,
  AudienceSetting,
  PostCreationData,
} from '@openpeeps/common/types';
import { Input, Label } from '@openpeeps/react-ui';
import { useT } from '../../../i18n';
import { useCurrentProfile } from '../../layout/IdentityContext';
import { ImageInput } from '../../form/ImageInput';
import { OpenpeepsMarkdownInput } from './OpenpeepsMarkdownInput';
import { ComposePreviewLinks } from './ComposePreviewLinks';
import { PostAudienceSelector } from './PostAudienceSelector';
import { VisibilitySelector } from './VisibilitySelector';

export interface ArticleFormProps {
  postData: PostCreationData;
  onChange: (data: PostCreationData) => void;
  isEdit?: boolean;
}

export function ArticleForm({
  postData,
  onChange,
  isEdit = false,
}: ArticleFormProps) {
  const t = useT();
  const me = useCurrentProfile();

  const article = postData.data as Article;
  const [audienceOpen, setAudienceOpen] = useState(false);

  const patchArticle = (patch: Partial<Article>) => {
    onChange({
      ...postData,
      data: { ...article, ...patch },
    });
  };

  const setAudience = (settings: AudienceSetting) => {
    const audience = settings.audience ?? undefined;
    const includesMe = audience?.some((p) => p.id === me?.id);
    onChange({
      ...postData,
      visibility: settings.visibility,
      groupId: settings.groupId ?? undefined,
      audience:
        settings.visibility === 'direct'
          ? includesMe
            ? audience
            : [...(audience ?? []), ...(me ? [me] : [])]
          : undefined,
    });
  };

  return (
    <div>
      <ImageInput
        usage="article-header-image"
        url={article.image}
        onChange={(image) => patchArticle({ image })}
        className="h-96"
        showSelectAspectRatio
        showFullImage
        text={t('articles.form.uploadCover', {
          defaultValue: 'Upload your cover image',
        })}
        showAltInput={false}
      />

      <div className="mt-4 flex flex-col gap-4 px-3">
        <h2 className="text-lg">
          {t('articles.form.title', { defaultValue: 'New Article' })}
        </h2>

        <Label
          title={t('articles.form.title', { defaultValue: 'New Article' })}
          htmlFor="article-title"
        >
          <Input
            id="article-title"
            value={article.title ?? ''}
            onChange={(e) => patchArticle({ title: e.target.value })}
          />
        </Label>

        <OpenpeepsMarkdownInput
          rows={16}
          maxLength={10000}
          value={article.content ?? ''}
          onChange={(content) => patchArticle({ content })}
          placeholder={t('articles.form.contentPlaceholder', {
            defaultValue:
              'Write your content here.  User markdown for formatting',
          })}
        />
        <ComposePreviewLinks content={article.content} />

        <Label
          title={t('articles.form.visibility', {
            defaultValue: 'Who can see this (Required)',
          })}
          description={t('articles.form.visibilityNotChangeable', {
            defaultValue:
              "Once you post your article, you can't change the visibility",
          })}
        >
          <VisibilitySelector
            postData={postData}
            onClick={() => setAudienceOpen(true)}
            disabled={isEdit}
            showDirect
          />
        </Label>
      </div>

      {!isEdit ? (
        <PostAudienceSelector
          open={audienceOpen}
          onClose={() => setAudienceOpen(false)}
          type="article"
          visibility={postData.visibility}
          groupId={postData.groupId ?? undefined}
          audience={postData.audience ?? []}
          showDirect
          onConfirm={setAudience}
        />
      ) : null}
    </div>
  );
}

// platform/svelte/src/lib/components/core/post/post-form/ArticleForm.svelte
<script lang="ts">
  import { Eye } from 'lucide-svelte';
  import {
    postCreationDataSchema,
    type PostCreationData,
    type AudienceSetting,
  } from '@openpeeps/common/types';
  import { Form, FormInput } from '@openpeeps/ui';
  import { FormImageInput } from '../../form';
  import VisibilitySelector from './VisibilitySelector.svelte';
  import { i18nContext } from '$lib/components/i18n';
  import FormOpenpeepsMarkdownInput from '../../form/FormOpenpeepsMarkdownInput.svelte';
  import { getCurrentProfile } from '$lib/auth';

  interface Props {
    postData: PostCreationData;
    isEdit?: boolean;
    onchange?: (data: PostCreationData) => void;
    valid?: boolean;
  }

  let {
    postData = $bindable(),
    isEdit = false,
    onchange,
    valid = $bindable(),
  }: Props = $props();

  const { t } = i18nContext();

  const me = getCurrentProfile();

  const setAudience = (audienceSetting?: AudienceSetting) => {
    const isUserInAudience = audienceSetting?.audience?.some(
      (audienceMember) => audienceMember.id === me.id,
    );
    if (audienceSetting) {
      postData.visibility = audienceSetting.visibility;
      postData.groupId = audienceSetting.groupId;
      postData.audience = isUserInAudience
        ? audienceSetting.audience
        : [...(audienceSetting.audience ?? []), me];
    }
  };
</script>

<Form
  bind:data={postData}
  schema={postCreationDataSchema}
  {onchange}
  bind:valid
>
  <FormImageInput
    usage="article-header-image"
    displayType="full"
    maxWidth={480}
    showSelectAspectRatio={true}
    text="Upload your cover image"
    specsText="Minimum width 480 pixels"
    showAltInput={false}
    path={['data', 'image']}
    classes={'h-96'}
    showFullImage={true}
  />

  <div class="mt-4 flex flex-col gap-4 px-3">
    <h2 class="text-lg">{t('articles.form.title')}</h2>
    <FormInput
      title={t('articles.form.title')}
      type="text"
      path={['data', 'title']}
    />

    <FormOpenpeepsMarkdownInput
      placeholder={t('articles.form.contentPlaceholder')}
      maxLength={10000}
      path={['data', 'content']}
      inline
    />


    <FormInput
      title={t('articles.form.visibility')}
      description={t('articles.form.visibilityNotChangeable')}
      type="mock"
      path={[]}
    >
      {#snippet lead()}
        <Eye size={16} />
      {/snippet}
      <div class="p-0! h-10">
        <VisibilitySelector
          {postData}
          disabled={isEdit}
          {isEdit}
          {setAudience}
          showDirect
        />
      </div>
    </FormInput>
  </div>
</Form>
