// platform/react/src/components/post/post-form/DescriptionEditModal.tsx
import { useState } from 'react';
import type { MediaAttachmentData } from '@openpeeps/common/types';
import {
  Button,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Label,
  Textarea,
} from '@openpeeps/react-ui';
import { useT } from '../../../i18n';

export interface DescriptionEditModalProps {
  attachment: MediaAttachmentData;
  open: boolean;
  onClose: () => void;
  onSave: (description: string) => void;
}

/**
 * Edit an already-uploaded attachment's alt text / description, mirroring the
 * Svelte `DescriptionEditModal`. Used by the composer to add accessibility text
 * to images and documents after they finish uploading.
 */
export function DescriptionEditModal({
  attachment,
  open,
  onClose,
  onSave,
}: DescriptionEditModalProps) {
  const t = useT();
  const [description, setDescription] = useState(attachment.description ?? '');

  const saveAndClose = () => {
    onSave(description.trim());
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(next) => !next && onClose()}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>
            {t('form.uploadEditModal.description.title', {
              defaultValue: 'Edit description',
            })}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-1">
          <Label htmlFor="attachment-description">
            {t('common.media.altText', { defaultValue: 'Alt text' })}
          </Label>
          <Textarea
            id="attachment-description"
            rows={3}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder={t('form.uploadEditModal.description.placeholder', {
              defaultValue: 'Describe this attachment for accessibility',
            })}
          />
        </div>

        <DialogFooter>
          <Button variant="variant-ringed-primary" action={onClose}>
            {t('common.back', { defaultValue: 'Back' })}
          </Button>
          <Button variant="variant-filled-primary" action={saveAndClose}>
            {t('common.done', { defaultValue: 'Done' })}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// platform/svelte/src/lib/components/core/post/post-form/DescriptionEditModal.svelte
<script lang="ts">
	import {
		Button,
		getModalManager,
		ModalFooter,
		ModalHeader,
		ModalWrapper,
		Label,
		Textarea
	} from '@openpeeps/ui';
	import type { MediaAttachmentData } from '@openpeeps/common/types';
	import { i18nContext } from '$lib/components/i18n';

	const { t } = i18nContext();

	const modalManager = getModalManager();

	interface Props {
		attachment: MediaAttachmentData;
		close?: () => void | Promise<void>;
		setResponse?: (attachment: MediaAttachmentData) => void | Promise<void>;
	}

	let { attachment, close = () => {}, setResponse = () => {} }: Props = $props();

	const saveAndClose = async () => {
		setResponse(attachment);
		modalManager.close();
	};
</script>

<ModalWrapper>
	<ModalHeader title={t('form.uploadEditModal.description.title')} />
	<div class="flex w-full p-4">
		<Label title={t('form.uploadEditModal.description.altText')} class="w-full">
			<Textarea
				bind:value={attachment.description}
				placeholder={t('form.uploadEditModal.description.placeholder')}
			/>
		</Label>
	</div>
	<ModalFooter extraClassNames="flex justify-end w-full">
		<Button title={t('common.back')} variant="variant-ringed-primary" action={close}
			>{t('common.back')}</Button
		>
		<Button title={t('common.done')} variant="variant-filled-primary" action={saveAndClose}
			>{t('common.done')}</Button
		>
	</ModalFooter>
</ModalWrapper>
