// platform/react/src/components/post/post-form/PostTypeSwitcher.tsx
import {
  CalendarDays,
  ChartColumnBig,
  Notebook,
  ScrollText,
} from 'lucide-react';
import type { PostType, VisibilityType } from '@openpeepshq/common/types';
import { Button } from '@openpeepshq/react-ui';
import { useT } from '../../../i18n';
import { useNavigate } from '../../../contexts/router';
import { getNewPostStores } from '../../../stores/newPosts';
import { useCurrentProfile } from '../../layout/IdentityContext';

export interface PostTypeSwitcherProps {
  type: PostType;
  /** Switch the in-modal composer between the note and poll forms. */
  onSelect: (type: 'note' | 'question') => void;
  /** Dismiss the modal before navigating to a full-page composer. */
  onClose: () => void;
  showEventType?: boolean;
  showArticleType?: boolean;
  /** Current composer audience, carried into article/event pages. */
  visibility?: VisibilityType;
  groupId?: string;
}

/**
 * Icon switcher mirroring the Svelte `PostTypeSwitcher`. Note and poll swap the
 * in-modal form; event and article navigate to their dedicated pages (events
 * are gated to community owners, matching the Svelte role check).
 */
export function PostTypeSwitcher({
  type,
  onSelect,
  onClose,
  showEventType = true,
  showArticleType = true,
  visibility,
  groupId,
}: PostTypeSwitcherProps) {
  const t = useT();
  const navigate = useNavigate();
  const me = useCurrentProfile();
  const isOwner = Boolean(me?.roles?.some((role) => role.key === 'owner'));

  const goto = (path: '/articles/new' | '/events/new') => {
    const stores = getNewPostStores();
    if (path === '/articles/new') {
      stores.article = {
        ...stores.article,
        type: 'article',
        visibility: visibility ?? stores.article.visibility,
        groupId,
      };
    } else {
      stores.event = {
        ...stores.event,
        type: 'event',
        visibility: visibility ?? stores.event.visibility,
        groupId,
      };
    }
    onClose();
    navigate(path);
  };

  return (
    <div className="flex items-center gap-1">
      {type !== 'note' ? (
        <Button
          compact
          variant="ghost"
          title={t('posts.switcher.note', { defaultValue: 'Write Note' })}
          action={() => onSelect('note')}
        >
          <Notebook className="size-5" />
        </Button>
      ) : null}
      {type !== 'question' ? (
        <Button
          compact
          variant="ghost"
          title={t('posts.switcher.poll', { defaultValue: 'Add Poll' })}
          action={() => onSelect('question')}
          data-testid="posts-composer-poll-type"
        >
          <ChartColumnBig className="size-5" />
        </Button>
      ) : null}
      {showEventType && isOwner ? (
        <Button
          compact
          variant="ghost"
          title={t('posts.switcher.event', { defaultValue: 'Create an Event' })}
          action={() => goto('/events/new')}
        >
          <CalendarDays className="size-5" />
        </Button>
      ) : null}
      {showArticleType ? (
        <Button
          compact
          variant="ghost"
          title={t('posts.switcher.article', { defaultValue: 'Write Article' })}
          action={() => goto('/articles/new')}
        >
          <ScrollText className="size-5" />
        </Button>
      ) : null}
    </div>
  );
}

// platform/svelte/src/lib/components/core/post/post-form/PostTypeSwitcher.svelte
<script lang="ts">
  import { CalendarDays, ChartColumnBig, Notebook, ScrollText } from 'lucide-svelte';
  import { Button, getModalManager } from '@openpeeps/ui';
  import type { PostCreationData, PostType } from '@openpeeps/common/types';
  import { me } from '$lib/api';
  import { i18nContext } from '@openpeeps/svelte/components/i18n';
  import { getNewPostStores } from '$lib/stores';
  import { goto } from '$app/navigation';

  interface Props {
    postData: PostCreationData;
    onchange: (postData: PostCreationData) => void;
    showEventType?: boolean;
    showArticleType?: boolean;
  }

  let {
    postData,
    onchange,
    showEventType = false,
    showArticleType = false,
  }: Props = $props();

  let isReply: boolean = $derived(!!postData.inReplyToId);

  const { t } = i18nContext();
  const modalManager = getModalManager();
  const newPostStores = getNewPostStores();

  const stores = getNewPostStores();

  const transferBaseFields = (target: PostCreationData, type: PostType) => {
    target.type = type;
    target.visibility = postData.visibility;
    target.groupId = postData.groupId;
    target.audience = postData.audience;
    target.inReplyToId = postData.inReplyToId;

    if ('content' in target.data && 'content' in postData.data) {
      target.data.content = postData.data.content;
    }
    if (type === 'question' && 'options' in target.data) {
      target.data.options = [
        { type: 'note', content: '' },
        { type: 'note', content: '' },
      ];
    }
  };

  const resetPreviousState = (
    postData: PostCreationData,
    targetType: PostType,
  ) => {
    if (postData.type === targetType) return;
    switch (postData.type) {
      case 'note':
        newPostStores.resetNewNoteState();
        break;

      case 'question':
        newPostStores.resetNewQuestionState();
        break;

      case 'article':
        newPostStores.resetNewArticleState();
        break;

      case 'event':
        newPostStores.resetNewEventState();
        newPostStores.resetNewJamState();
        break;

      default:
        break;
    }
  };

  const navigateIfNeeded = (type: PostType) => {
    if (type === 'event') {
      goto('/events/new');
      modalManager.close();
    }
    if (type === 'article') {
      goto('/articles/new');
      modalManager.close();
    }
  };

  const switchType = (type: PostType) => {
    const target = stores[type];
    if (!target) return;

    transferBaseFields(target, type);
    if (!isReply) {
      resetPreviousState(postData, type);
    }
    onchange(target);
    navigateIfNeeded(type);
  };
</script>

<div class="flex items-center gap-2">
  {#if postData.type !== 'note'}
    <Button
      title={t('posts.switcher.note')}
      class="btn-icon-sm"
      action={() => switchType('note')}
    >
      <Notebook />
    </Button>
  {/if}
  {#if postData.type !== 'question'}
    <Button
      title={t('posts.switcher.poll')}
      class=" btn-icon-sm"
      action={() => switchType('question')}
    >
      <ChartColumnBig />
    </Button>
  {/if}
  {#if showEventType}
    {#if $me?.roles?.find((role) => role.key === 'owner')}
      <Button
        title={t('posts.switcher.event')}
        class="btn-icon-sm"
        action={() => switchType('event')}
      >
        <CalendarDays />
      </Button>
    {/if}
  {/if}
  {#if showArticleType}
    <Button
      title={t('posts.switcher.article')}
      class="btn-icon-sm"
      action={() => switchType('article')}
    >
      <ScrollText />
    </Button>
  {/if}
</div>
