// platform/react/src/components/post/post-form/PostAudienceSelector.tsx
import { useEffect, useMemo, useState } from 'react';
import { CheckCircle } from 'lucide-react';
import type {
  AudienceSetting,
  GroupWithMeta,
  PostType,
  PublicProfile,
  VisibilityType,
} from '@openpeepshq/common';
import { checkGroupCapabilities } from '@openpeepshq/common/lib';
import {
  Button,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@openpeepshq/react-ui';
import { useT } from '../../../i18n';
import { useAuthData, useCurrentProfile } from '../../layout/IdentityContext';
import { useServerInfo } from '../../server-data';
import { GroupCard } from '../../groups/GroupCard';
import { ProfileBadge, ProfileSelector } from '../../profile';
import { buildAudienceChoices } from './audienceChoices';

export interface PostAudienceSelectorProps {
  open: boolean;
  onClose: () => void;
  type?: PostType;
  visibility: VisibilityType;
  groupId?: string;
  audience?: PublicProfile[];
  showDirect?: boolean;
  onConfirm: (settings: AudienceSetting) => void;
}

export const PostAudienceSelector = ({
  open,
  onClose,
  type = 'note',
  visibility,
  groupId,
  audience = [],
  showDirect = true,
  onConfirm,
}: PostAudienceSelectorProps) => {
  const t = useT();
  const authData = useAuthData();
  const me = useCurrentProfile();
  const serverInfo = useServerInfo();
  const [draftVisibility, setDraftVisibility] = useState(visibility);
  const [draftGroupId, setDraftGroupId] = useState(groupId);
  const [draftAudience, setDraftAudience] = useState(audience);
  const [view, setView] = useState<'main' | 'groups' | 'audience'>('main');

  useEffect(() => {
    if (!open) return;
    setDraftVisibility(visibility);
    setDraftGroupId(groupId);
    setDraftAudience(audience);
    setView('main');
  }, [open, visibility, groupId, audience]);

  const choices = useMemo(
    () =>
      buildAudienceChoices(type, authData, t, {
        publicContent: serverInfo.publicContent,
        showDirect,
      }),
    [type, authData, t, serverInfo.publicContent, showDirect],
  );

  const groups = useMemo(
    () =>
      me?.memberships
        ?.map((m) => m.group)
        .filter(
          (grp) =>
            checkGroupCapabilities(authData, [`core-posts-create-${type}`], grp)
              .success,
        ) ?? [],
    [me, authData, type],
  );

  const selectVisibility = (value: VisibilityType) => {
    setDraftVisibility(value);
    if (value !== 'direct') setDraftAudience([]);
    if (value !== 'group') setDraftGroupId(undefined);
    if (value === 'group' && !draftGroupId) {
      setView('groups');
      return;
    }
    if (value === 'direct') {
      setView('audience');
    }
  };

  const confirm = () => {
    onConfirm({
      visibility: draftVisibility,
      groupId: draftVisibility === 'group' ? draftGroupId : undefined,
      audience:
        draftVisibility === 'direct' && draftAudience.length
          ? draftAudience
          : undefined,
    });
    onClose();
  };

  return (
    <>
      <Dialog
        open={open && view !== 'audience'}
        onOpenChange={(next) => !next && onClose()}
      >
        <DialogContent className="max-h-[85vh] max-w-lg overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              {t('posts.form.audienceTitle', {
                defaultValue: 'Who can see this?',
              })}
            </DialogTitle>
          </DialogHeader>

          {view === 'groups' ? (
            <div className="space-y-2">
              {groups.map((group) => (
                <div
                  key={group.id}
                  className="flex w-full items-center justify-between rounded-md border p-2"
                >
                  <GroupCard
                    group={group as GroupWithMeta}
                    noPadding
                    showAction={false}
                    onSelect={() => {
                      setDraftGroupId(group.id);
                      setDraftVisibility('group');
                      setView('main');
                    }}
                  />
                  {draftGroupId === group.id ? (
                    <CheckCircle className="text-primary size-5" />
                  ) : null}
                </div>
              ))}
              {groups.length === 0 ? (
                <p className="text-muted-foreground py-4 text-center text-sm">
                  {t('posts.form.noGroups', {
                    defaultValue: 'No groups available',
                  })}
                </p>
              ) : null}
            </div>
          ) : (
            <div className="space-y-2">
              {choices.map((choice) => {
                const Icon = choice.icon;
                return (
                  <button
                    key={choice.value}
                    type="button"
                    className="hover:bg-surface-100 flex w-full items-start gap-3 rounded-md border p-3 text-left"
                    onClick={() => selectVisibility(choice.value)}
                  >
                    <span className="bg-surface-100 flex size-10 items-center justify-center rounded-full">
                      <Icon className="size-5" />
                    </span>
                    <span className="flex-1">
                      <span className="block font-medium">{choice.title}</span>
                      <span className="text-muted-foreground block text-sm">
                        {choice.description}
                      </span>
                      {choice.value === 'group' && draftGroupId ? (
                        <span className="text-primary mt-1 block text-xs">
                          {groups.find((g) => g.id === draftGroupId)
                            ?.displayName ??
                            groups.find((g) => g.id === draftGroupId)?.handle}
                        </span>
                      ) : null}
                      {choice.value === 'direct' && draftAudience.length ? (
                        <span className="mt-1 flex flex-wrap gap-1">
                          {draftAudience.map((profile) => (
                            <ProfileBadge
                              key={profile.id}
                              profile={profile}
                              onRemove={() =>
                                setDraftAudience((current) =>
                                  current.filter((p) => p.id !== profile.id),
                                )
                              }
                            />
                          ))}
                        </span>
                      ) : null}
                    </span>
                    <span
                      className={`mt-1 size-4 rounded-full border ${draftVisibility === choice.value ? 'bg-primary border-primary' : ''}`}
                    />
                  </button>
                );
              })}
            </div>
          )}

          <DialogFooter>
            {view !== 'main' ? (
              <Button
                variant="variant-ringed-surface"
                action={() => setView('main')}
              >
                {t('navigation.back', { defaultValue: 'Back' })}
              </Button>
            ) : (
              <Button variant="variant-ringed-surface" action={onClose}>
                {t('common.cancel', { defaultValue: 'Cancel' })}
              </Button>
            )}
            <Button variant="variant-filled-primary" action={confirm}>
              {t('common.done', { defaultValue: 'Done' })}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ProfileSelector
        open={open && view === 'audience'}
        onOpenChange={(next) => {
          if (!next) setView('main');
        }}
        mode="multiple"
        selectedProfiles={draftAudience}
        banlist={me ? [me] : []}
        onConfirm={(profiles) => {
          setDraftAudience(profiles);
          setView('main');
        }}
        title={t('posts.form.audienceTitle', {
          defaultValue: 'Who can see this?',
        })}
      />
    </>
  );
};

// platform/svelte/src/lib/components/core/post/post-form/PostAudienceSelector.svelte
<script lang="ts">
  import { Button, stopPropagation } from '@openpeeps/ui';
  import { ModalFooter, ModalHeader, ModalWrapper } from '@openpeeps/ui';
  import { buildAudienceChoices } from '$lib/components/core/post/post-form/constants';
  import type {
    AudienceSetting,
    GroupWithMeta,
    PostType,
    PublicProfile,
    VisibilityType,
  } from '@openpeeps/common/types';
  import { me } from '$lib/api';
  import GroupCard from '$lib/components/core/groups/GroupCard.svelte';
  import { CheckCircle } from 'lucide-svelte';
  import GroupCardFromId from '$lib/components/core/groups/GroupCardFromId.svelte';
  import { i18nContext } from '$lib/components/i18n';
  import ProfileSelector from '$lib/components/core/profile/ProfileSelector.svelte';
  import { checkGroupCapabilities } from '@openpeeps/common/lib';
  import { getCurrentAuthData } from '$lib/auth';

  const { t } = i18nContext();
  const authData = getCurrentAuthData();

  interface Props {
    visibility: VisibilityType;
    groupId?: string | undefined;
    audience?: PublicProfile[];
    type: PostType;
    showDirect?: boolean;
    close: () => void;
    setResponse: (audienceSettings: AudienceSetting) => void;
  }

  let {
    visibility = $bindable(),
    groupId = $bindable(undefined),
    audience = $bindable(undefined),
    type,
    showDirect = false,
    close,
    setResponse,
  }: Props = $props();

  const prefix = `visibility.${type === 'event' ? 'event' : 'post'}.`;

  const i = (key: string) => t(`${prefix}${key}`);

  let showGroupSelector = $state(false);
  let showAudienceSelector = $state(false);

  const selectVisibility = (selection: VisibilityType) => {
    if (selection === 'group' && !groupId) {
      showGroupSelector = true;
    }
    if (selection === 'direct' && !audience) {
      audience = [];
    }
    if (selection !== 'group') {
      groupId = undefined;
    }
    if (selection !== 'direct') {
      audience = undefined;
    }
    visibility = selection;
  };

  const selectGroup = (selection: GroupWithMeta) => {
    groupId = selection.id;
    showGroupSelector = false;
  };

  const confirmAndClose = () => {
    setResponse({ visibility, groupId, audience });
    close();
  };

  const getFilteredGroups = () => {
    return (
      $me?.memberships
        ?.map((m) => m.group)
        .filter(
          (grp) =>
            checkGroupCapabilities(authData, [`core-posts-create-${type}`], grp)
              .success,
        ) || []
    );
  };

  const groups = $derived(getFilteredGroups());
  const availableAudienceChoices = $derived(
    buildAudienceChoices(type, $me, { showDirect }),
  );
</script>

<ModalWrapper>
  <ModalHeader title={i('title')} />
  <!-- body -->
  {#if showGroupSelector}
    <article class="flex flex-col p-4">
      {#each groups as group (group.id)}
        <Button
          title={t('posts.form.selectGroup')}
          action={() => selectGroup(group as GroupWithMeta)}
        >
          <GroupCard group={group as GroupWithMeta}>
            {#snippet action()}
              <div>
                {#if groupId === group.id}
                  <CheckCircle />
                {/if}
              </div>
            {/snippet}
          </GroupCard>
        </Button>
      {/each}
      {#if $me?.memberships.length === 0}
        <div class="flex justify-center py-4">
          <h4>{i('no-groups')}</h4>
        </div>
      {/if}
    </article>
    <ModalFooter>
      <div class="flex gap-x-2">
        <Button
          title={t('common.done')}
          variant="variant-ringed-surface"
          action={() => (showGroupSelector = false)}>{t('common.done')}</Button
        >
      </div>
    </ModalFooter>
  {:else if showAudienceSelector}
    <article class="flex flex-col p-4">
      <ProfileSelector bind:selectedProfiles={audience} />
    </article>
    <ModalFooter>
      <div class="flex gap-x-2">
        <Button
          title={t('common.done')}
          variant="variant-ringed-surface"
          action={() => (showAudienceSelector = false)}>{t('common.done')}</Button
        >
      </div>
    </ModalFooter>
  {:else}
    <article class="flex flex-col p-4">
      <p class="text-sm font-light">{i('description')}</p>
      <div class="mt-7">
        {#each availableAudienceChoices as setting}
          <Button
            title={setting.title}
            action={() => selectVisibility(setting.value)}
            class="w-full  p-4"
          >
            {@const SvelteComponent = setting?.icon?.ref}
            <div class="flex w-full items-center justify-between">
              <div class="flex items-center gap-3">
                <div
                  class="bg-surface-50 flex h-12 w-12 items-center justify-center rounded-full"
                >
                  <SvelteComponent class="h-6 w-6" />
                </div>
                <div class="flex flex-col items-start">
                  <p class="text-base font-medium">{setting.title}</p>
                  <p class="pr-10 text-sm font-light">
                    {setting.description}
                  </p>
                </div>
              </div>
              <div
                class="flex h-4 w-4 items-center justify-center rounded-full border border-neutral-500"
              >
                <div
                  class={`h-2 w-2 rounded-full ${visibility === setting.value ? 'bg-primary-500' : ''}`}
                ></div>
              </div>
            </div>
            {#if setting.value === 'group' && groupId}
              <div class="pl-12 text-left">
                <button
                  title={t('posts.form.changeGroup')}
                  onclick={() => (showGroupSelector = true)}
                >
                  <GroupCardFromId
                    {groupId}
                    showAction={false}
                    avatarSize={1.5}
                  />
                </button>
              </div>
            {/if}
            {#if setting.value === 'direct' && audience}
              <button
                class="w-full pl-12 text-left"
                onclick={stopPropagation(() => undefined)}
              >
                <ProfileSelector overRide bind:selectedProfiles={audience} />
              </button>
            {/if}
          </Button>
        {/each}
      </div>
    </article>
    <ModalFooter>
      <div class="flex gap-x-2">
        <Button title={t('navigation.back')} variant="variant-ringed-surface" action={close}
          >{t('navigation.back')}</Button
        >
        <Button
          title={t('common.done')}
          variant="variant-filled-primary"
          action={confirmAndClose}>{t('common.done')}</Button
        >
      </div>
    </ModalFooter>
  {/if}
</ModalWrapper>
