// platform/react/src/components/post/post-form/VisibilitySelector.tsx
import { useMemo } from 'react';
import { ChevronDown, Eye } from 'lucide-react';
import type { PostCreationData } from '@openpeeps/common/types';
import { groupName } from '@openpeeps/common/lib';
import { useT } from '../../../i18n';
import { useAuthData, useCurrentProfile } from '../../layout/IdentityContext';
import { useServerInfo } from '../../server-data';
import { GroupAvatar } from '../../groups/GroupAvatar';
import { Avatar } from '../../profile';
import { buildAudienceChoices } from './audienceChoices';

export interface VisibilitySelectorProps {
  postData: PostCreationData;
  onClick: () => void;
  disabled?: boolean;
  showDirect?: boolean;
}

export const VisibilitySelector = ({
  postData,
  onClick,
  disabled = false,
  showDirect = false,
}: VisibilitySelectorProps) => {
  const t = useT();
  const authData = useAuthData();
  const me = useCurrentProfile();
  const serverInfo = useServerInfo();

  const audienceChoices = useMemo(
    () =>
      buildAudienceChoices(postData.type, authData, t, {
        publicContent: serverInfo.publicContent,
        showDirect,
      }),
    [postData.type, authData, t, serverInfo.publicContent, showDirect],
  );

  const selectedGroup = useMemo(
    () =>
      me?.memberships?.find((m) => m.group.id === postData.groupId)?.group,
    [me?.memberships, postData.groupId],
  );

  const description = (visibility: string) =>
    audienceChoices.find((c) => c.value === visibility)?.description ?? '';

  const content = () => {
    if (postData.visibility === 'group') {
      return (
        <span className="flex min-w-0 items-center gap-1 text-sm font-normal">
          <span className="shrink-0 pr-2">{description('group')}</span>
          {selectedGroup ? (
            <span className="flex min-w-0 items-center gap-1 truncate">
              <GroupAvatar group={selectedGroup} size={1.5} borderless />
              <span className="truncate">{groupName(selectedGroup)}</span>
            </span>
          ) : null}
        </span>
      );
    }

    if (postData.visibility === 'direct') {
      const audience = postData.audience ?? [];
      return (
        <span className="flex items-center gap-1 text-sm font-light">
          <span className="pr-2">{description('direct')}</span>
          <span className="flex items-center">
            {audience.slice(0, 5).map((profile) => (
              <Avatar
                key={profile.id}
                profile={profile}
                borderless
                size={1.2}
                containerClassName="!p-0 border-none -ml-2"
              />
            ))}
            {audience.length > 5 ? (
              <span className="text-sm font-light">+{audience.length - 5}</span>
            ) : null}
          </span>
        </span>
      );
    }

    return (
      <span className="text-sm font-light">
        {description(postData.visibility)}
      </span>
    );
  };

  return (
    <div className="op-input-group grid grid-cols-[auto_1fr_auto]">
      <div className="op-input-group-shim">
        <Eye className="size-4" />
      </div>
      <button
        type="button"
        title={t('posts.form.changeAudience', {
          defaultValue: 'Change audience',
        })}
        className="hover:bg-muted/50 flex h-10 w-full min-w-0 items-center px-3 text-left disabled:cursor-not-allowed disabled:opacity-50"
        onClick={onClick}
        disabled={disabled}
      >
        {content()}
      </button>
      {!disabled ? (
        <div className="op-input-group-shim">
          <ChevronDown className="text-muted-foreground size-4" />
        </div>
      ) : null}
    </div>
  );
};

// platform/svelte/src/lib/components/core/post/post-form/VisibilitySelector.svelte
<script lang="ts">
  import { getModalManager } from '@openpeeps/ui';
  import PostAudienceSelector from './PostAudienceSelector.svelte';
  import type {
    AudienceSetting,
    PostCreationData,
    PublicProfile,
  } from '@openpeeps/common/types';
  import { Avatar, GroupCardFromId } from '$lib/components';
  import { buildAudienceChoices } from './constants';
  import PostAudienceModal from './PostAudienceModal.svelte';
  import { getCurrentProfile } from '$lib/auth';
  import { i18nContext } from '$lib/components/i18n';

  const { t } = i18nContext();
  const me = getCurrentProfile();

  const modalManager = getModalManager();

  interface Props {
    postData: PostCreationData;
    isEdit?: boolean;
    disabled?: boolean;
    showDirect?: boolean;
    setAudience: (audienceSetting?: AudienceSetting) => void;
  }

  let {
    postData,
    showDirect = false,
    disabled = false,
    isEdit = false,
    setAudience,
  }: Props = $props();

  const audienceChoices = $derived(buildAudienceChoices(postData.type, me));

  let updatedAudienceSetting = $state<AudienceSetting>(postData);

  const doSetAudience = (audienceSetting?: AudienceSetting) => {
    if (audienceSetting) {
      updatedAudienceSetting = audienceSetting;
    }
    setAudience(audienceSetting);
  };
</script>

<button
  title={t('posts.form.changeAudience')}
  onclick={() => {
    if (isEdit) {
      modalManager.show(PostAudienceModal, {
        audience: postData.audience as PublicProfile[],
      });
      return;
    }
    modalManager.show(
      PostAudienceSelector,
      {
        visibility: postData.visibility,
        groupId: postData.groupId!,
        audience: postData.audience!,
        type: postData.type,
        showDirect,
      },
      doSetAudience,
    );
  }}
  class="flex h-10 w-full items-center"
  {disabled}
>
  {#if updatedAudienceSetting.visibility === 'group'}
    <span class="flex items-center gap-1 text-sm font-normal">
      <span class="pr-2">
        {audienceChoices.find((c) => c.value === 'group')?.description}
      </span>
      {#if updatedAudienceSetting.groupId}
        <GroupCardFromId
          groupId={updatedAudienceSetting.groupId}
          showAction={false}
          avatarSize={1.5}
          noPadding
          oneLine
        />
      {/if}
    </span>
  {:else if updatedAudienceSetting.visibility === 'direct'}
    <span class="flex items-center gap-1 text-sm font-light">
      <span class="pr-2">
        {audienceChoices.find((c) => c.value === 'direct')?.description}
      </span>
      <span class="flex items-center">
        {#each (updatedAudienceSetting.audience ?? []).slice(0, 5) as profile (profile.id)}
          <Avatar
            {profile}
            borderless
            size={1.2}
            containerClass="!p-0 border-none -ml-2"
          />
        {/each}
        {#if (updatedAudienceSetting.audience?.length ?? 0) > 5}
          <span class="text-sm font-light"
            >+{(updatedAudienceSetting.audience?.length ?? 0) - 5}</span
          >
        {/if}
      </span>
    </span>
  {:else}
    <span class="text-sm font-light">
      {audienceChoices.find(
        (c) => c.value === updatedAudienceSetting.visibility,
      )?.description ?? ''}
    </span>
  {/if}
</button>
