// platform/web/src/pages/admin/Analytics.tsx
import { useT, useOpenpeeps, useSetPageHeader } from '@openpeeps/react';
import { Avatar } from '@openpeeps/react/components';
import { SignupChart } from './components/AdminCharts';
import { LoadingSpinner } from '@openpeeps/react-ui';

function StatRow({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex items-center justify-between border-b py-2">
      <span className="text-muted-foreground text-sm">{label}</span>
      <span className="text-sm font-medium">{value}</span>
    </div>
  );
}

function BreakdownCard({
  label,
  value,
}: {
  label: string;
  value: number | string;
}) {
  return (
    <div className="bg-surface-100 flex h-24 flex-col items-center justify-center rounded-md">
      <span className="text-sm">{label}</span>
      <span className="text-4xl font-semibold">{value}</span>
    </div>
  );
}

export function AdminAnalytics() {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const statsQuery = openpeepsApi.admin.useGeneralStats();

  useSetPageHeader(t('admin.analytics.title', { defaultValue: 'Analytics' }));

  if (statsQuery.isLoading) {
    return (
      <div className="text-muted-foreground flex h-32 items-center justify-center text-sm">
        <LoadingSpinner />
      </div>
    );
  }

  const stats = statsQuery.data;
  if (!stats) return null;

  const periods = ['day', 'week', 'month', 'quarter', 'year'] as const;

  const topPostsOfYear = stats.topLists.posts.year;
  const topProfilesOfYear = stats.topLists.profiles.year;

  return (
    <div className="space-y-6 p-4">
      <section>
        <h2 className="mb-2 text-lg font-medium">
          {t('admin.overview.newSignups', { defaultValue: 'New signups' })}
        </h2>
        <SignupChart stats={stats} />
      </section>

      <section>
        <h2 className="mb-2 text-lg font-medium">Active profiles</h2>
        <div className="rounded-md border p-4">
          {periods.map((p) => (
            <StatRow
              key={p}
              label={`${p}: current period`}
              value={stats.profiles.active[p].currentPeriod}
            />
          ))}
        </div>
      </section>

      <section>
        <h2 className="mb-2 text-lg font-medium">Posts</h2>
        <div className="rounded-md border p-4">
          {periods.map((p) => (
            <StatRow
              key={p}
              label={`${p}: posts`}
              value={stats.posts.all[p].currentPeriod}
            />
          ))}
        </div>
      </section>

      <section>
        <h2 className="mb-2 text-lg font-medium">
          {t('admin.overview.content', { defaultValue: 'Content' })}
        </h2>
        <div className="grid gap-4 sm:grid-cols-2">
          <BreakdownCard
            label={t('admin.overview.allPosts', { defaultValue: 'All Posts' })}
            value={stats.posts.all.all}
          />
          <BreakdownCard
            label={t('admin.overview.postsWithoutReplies', {
              defaultValue: 'Posts without replies',
            })}
            value={stats.posts.withoutReply.all}
          />
          <BreakdownCard
            label={t('admin.overview.postsWithReplies', {
              defaultValue: 'Posts with replies',
            })}
            value={stats.posts.withReplies.all}
          />
          <BreakdownCard
            label={t('admin.overview.replies', { defaultValue: 'Replies' })}
            value={stats.posts.replies.all}
          />
        </div>
      </section>

      {topProfilesOfYear.length > 0 ? (
        <section>
          <h2 className="mb-2 text-lg font-medium">
            {t('admin.overview.topProfilesOfYear', {
              defaultValue: `Top ${topProfilesOfYear.length} profiles of the year`,
              count: topProfilesOfYear.length,
            })}
          </h2>
          <div className="rounded-md border">
            {topProfilesOfYear.map((profile) => (
              <a
                key={profile.id}
                href={`/@${profile.handle}`}
                className="hover:bg-surface-100 flex items-center gap-2 border-b p-2 last:border-b-0"
              >
                <Avatar profile={profile} size={2} />
                <span className="flex-1">
                  {profile.displayName || `@${profile.handle}`}
                </span>
                <span className="text-muted-foreground text-sm">
                  score {profile.activityScore.toFixed(0)}
                </span>
              </a>
            ))}
          </div>
        </section>
      ) : null}

      <section>
        <h2 className="mb-2 text-lg font-medium">Top profiles (this month)</h2>
        <div className="rounded-md border">
          {stats.topLists.profiles.month.map((profile) => (
            <a
              key={profile.id}
              href={`/@${profile.handle}`}
              className="hover:bg-surface-100 flex items-center justify-between border-b p-2 last:border-b-0"
            >
              <span>{profile.displayName || `@${profile.handle}`}</span>
              <span className="text-muted-foreground text-sm">
                score {profile.activityScore.toFixed(0)}
              </span>
            </a>
          ))}
          {stats.topLists.profiles.month.length === 0 && (
            <p className="text-muted-foreground p-3 text-sm">No data</p>
          )}
        </div>
      </section>

      <section>
        <h2 className="mb-2 text-lg font-medium">
          {t('admin.overview.topPostsOfYear', {
            defaultValue: `Top ${topPostsOfYear.length} posts of the year`,
            count: topPostsOfYear.length,
          })}
        </h2>
        <div className="rounded-md border">
          {topPostsOfYear.map((post) => (
            <a
              key={post.id}
              href={`/posts/${post.id}`}
              className="hover:bg-surface-100 flex items-center justify-between gap-3 border-b p-2 last:border-b-0"
            >
              <span className="min-w-0 flex-1 truncate text-sm">
                {(post.data as { content?: string })?.content ||
                  `@${post.profile.handle}`}
              </span>
              <span className="text-muted-foreground shrink-0 text-sm">
                score {post.activityScore.toFixed(0)}
              </span>
            </a>
          ))}
          {topPostsOfYear.length === 0 && (
            <p className="text-muted-foreground p-3 text-sm">No data</p>
          )}
        </div>
      </section>
    </div>
  );
}

// platform/app/src/routes/(protected)/(private)/admin/analytics/+page.svelte
<script lang="ts">
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { AccessDeniedLoader, FeedPost, ProfileCard } from '@openpeeps/svelte/components';
  import { adminServerStatsStore } from '@openpeeps/svelte/api';
  import { SignupChart, CommunityOverview } from '@openpeeps/svelte/components';
  import { i18nContext } from '@openpeeps/svelte/components/i18n';

  const { t } = i18nContext();

  const statsQuery = adminServerStatsStore();

  getPageHeaderStore().set({
    title: t('admin.overview.title'),
  });
</script>

<div class="w-full p-4 mx-auto align-center mt-4 space-y-4">
  <AccessDeniedLoader queries={[$statsQuery]}>
    <h2 class="text-lg">{t('admin.overview.communityOverview')}</h2>
    <CommunityOverview statsData={$statsQuery?.data!} />

    <h2 class="text-base">{t('admin.overview.newSignups')}</h2>
    <SignupChart serverStats={$statsQuery?.data!} />

    <h2 class="text-lg">{t('admin.overview.content')}</h2>
    <div class="p-4 pb-10 border rounded">
      <h2 class="text-base">{t('admin.overview.postsRepliesReposts')}</h2>
    </div>
    <div class="w-full grid grid-cols-2 gap-4">
      <div
        class="w-full flex flex-col justify-center items-center h-24 bg-gray-200/40 rounded-md"
      >
        <h3 class="text-sm">{t('admin.overview.allPosts')}</h3>
        <h1 class="text-4xl font-semibold">
          {$statsQuery?.data?.posts.all.all ?? ''}
        </h1>
      </div>
      <div
        class="w-full flex flex-col justify-center items-center h-24 bg-gray-200/40 rounded-md"
      >
        <h3 class="text-sm">{t('admin.overview.postsWithoutReplies')}</h3>
        <h1 class="text-4xl font-semibold">
          {$statsQuery?.data?.posts.withoutReply.all ?? ''}
        </h1>
      </div>
      <div
        class="w-full flex flex-col justify-center items-center h-24 bg-gray-200/40 rounded-md"
      >
        <h3 class="text-sm">{t('admin.overview.postsWithReplies')}</h3>
        <h1 class="text-4xl font-semibold">
          {$statsQuery?.data?.posts.withReplies.all ?? ''}
        </h1>
      </div>
      <div
        class="w-full flex flex-col justify-center items-center h-24 bg-gray-200/40 rounded-md"
      >
        <h3 class="text-sm">{t('admin.overview.replies')}</h3>
        <h1 class="text-4xl font-semibold">
          {$statsQuery?.data?.posts.replies.all ?? ''}
        </h1>
      </div>
    </div>
    {#if $statsQuery.data?.topLists.profiles.year.length}
      <h3 class="text-lg mt-12">
        {t('admin.overview.topProfilesOfYear', { count: $statsQuery.data?.topLists.profiles.year.length })}
      </h3>
      {#each $statsQuery.data?.topLists.profiles.year as profile (profile.id)}
        <ProfileCard {profile} noPadding showAction={false} />
      {/each}
    {/if}
    {#if $statsQuery.data?.topLists.posts.year.length}
      <h3 class="text-lg mt-4">
        {t('admin.overview.topPostsOfYear', { count: $statsQuery.data?.topLists.posts.year.length })}
      </h3>
      {#each $statsQuery.data?.topLists.posts.year ?? [] as post (post.id)}
        <a href={`/posts/${post.repost ? post?.repost?.id : post.id}`}>
          <FeedPost {post} />
        </a>
      {/each}
    {/if}
  </AccessDeniedLoader>
</div>
