// platform/svelte/src/lib/components/core/post/types/article/CardArticle.svelte
<script lang="ts">
  import type { Article, PublicPost } from '@openpeeps/common/types';
  import { page } from '$app/state';

  interface Props {
    post: PublicPost;
  }

  const { post }: Props = $props();
  const article = $derived(post.data as Article);
</script>

<div class="hover:bg-surface-100 overflow-hidden rounded-md px-2 pt-2">
  <a href="{page.url.origin}/posts/{post.id}" class="flex flex-col gap-2">
    <span class="h-32">
      <img
        src={article.image || '/img/article-default.png'}
        alt={article?.title || article?.content}
        class="h-full w-full rounded-md object-cover"
      />
    </span>
    <span class="flex flex-col gap-1">
      <h3 class="truncate font-semibold">{article?.title}</h3>
    </span>
  </a>
</div>

// platform/react-native/src/components/custom/post/types/article/CardArticle.tsx
import { View, Image, TouchableOpacity } from 'react-native';
import React from 'react';
import { ThemedText } from '../../../../ui/themed-text';
import { Article, PublicPost } from '@openpeeps/common';
import { truncateText } from '../../../../../lib/utils';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { MainStackParamList } from '../../../../navigation/types';

interface CardArticleProps {
  post: PublicPost;
}

export const CardArticle = ({ post }: CardArticleProps) => {

  const article = post.data as Article;
  const navigation =
    useNavigation<NativeStackNavigationProp<MainStackParamList>>();

  return (
    <TouchableOpacity
      onPress={() => {
        navigation.navigate('Post', {
          id: post.id,
        });
      }}
      className="flex mb-6 w-full border-[0.5px] border-gray-100/50 rounded-lg">
      {article.image && (
        <View className="w-full h-[200px]">
          <Image
            source={{ uri: article.image }}
            className="w-full h-full rounded-t-md"
          />
        </View>)}
      <View className="grid gap-y-5 p-4">
        <ThemedText className="text-xl font-semibold">
          {truncateText(article.title, 100) || '-'}
        </ThemedText>
      </View>
    </TouchableOpacity>
  );
};
