// platform/web/src/pages/groups/Info.tsx
import { useParams } from 'react-router-dom';
import { useT, useOpenpeeps } from '@openpeeps/react';
import { GroupHeader, PostMarkdown } from '@openpeeps/react/components';

export function GroupInfo() {
  const t = useT();
  const { handle = '' } = useParams<{ handle: string }>();
  const { openpeepsApi } = useOpenpeeps();

  const groupQuery = openpeepsApi.useGroupByHandle(handle);
  const group = groupQuery.data;

  if (groupQuery.isLoading) {
    return (
      <div className="flex h-32 items-center justify-center text-sm text-muted-foreground">
        {t('common.loading', { defaultValue: 'Loading…' })}
      </div>
    );
  }
  if (!group) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <p className="text-2xl font-bold">
          {t('groups.notFound', { defaultValue: 'Group not found' })}
        </p>
      </div>
    );
  }

  return (
    <div>
      <GroupHeader group={group} />
      <div className="space-y-2 p-4">
        <section className="border-b py-2">
          <h3 className="text-lg font-semibold">Description</h3>
          <PostMarkdown source={group.description || 'No description yet'} />
        </section>
        <section className="space-y-2 border-b py-2">
          <h3 className="text-lg font-semibold">Details</h3>
          {group.capabilities?.none?.add?.includes('core-groups-read') ? (
            <>
              <h4 className="font-semibold">Public</h4>
              <p>
                Anyone on this community can see posts in the group. Group
                members can add comments and create posts
              </p>
            </>
          ) : (
            <>
              <h4 className="font-semibold">Private</h4>
              <p>
                Only group members can see posts in the group. Group members
                can add comments and create posts
              </p>
            </>
          )}
          <h4 className="font-semibold">Created</h4>
          <p>{new Date(group.createdAt).toLocaleDateString()}</p>
        </section>
        <section className="border-b py-2">
          <h3 className="text-lg font-semibold">Rules</h3>
          <PostMarkdown source={group.rules || 'No rules yet'} />
        </section>
      </div>
    </div>
  );
}

// platform/app/src/routes/(protected)/(conditionally-public)/groups/@[handle]/info/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import type { GroupWithMeta } from '@openpeeps/common/types';
  import { AccessDeniedLoader, OpenpeepsMarkdown } from '@openpeeps/svelte/components';
  import { getPageHeaderStore } from '@openpeeps/svelte/stores';
  import { groupByHandleStore } from '@openpeeps/svelte/api';
  import { groupName } from '@openpeeps/common/lib';

  let handle = page.params.handle;

  let groupQuery = groupByHandleStore(handle);
  const pageHeaderStore = getPageHeaderStore();

  let group: GroupWithMeta | undefined = $derived($groupQuery.data);
  $effect(() => {
    pageHeaderStore.set({ title: `${groupName(group)} - About` });
  });
</script>

<AccessDeniedLoader queries={[$groupQuery]}>
  {#if group}
    <div class="p-4 space-y-2">
      <div class="border-b py-2">
        <h3 class="text-lg font-semibold">Description</h3>
        <OpenpeepsMarkdown
          source={group?.description || 'No description yet'}
          linkPreviewMode="none"
        />
      </div>
      <div class="border-b py-2 space-y-2">
        <h3 class="text-lg font-semibold">Details</h3>
        {#if group?.discoverable}
          <h3>Public</h3>
          <p>
            Anyone on this community can see posts in the group. Group members
            can add comments and create posts
          </p>
          <h3 class="font-semibold">Created</h3>
          <p>
            {new Date(group?.createdAt).toLocaleDateString()}
          </p>
        {:else}
          <h3>Private</h3>
          <p>
            Only group members can see posts in the group. Group members can add
            comments and create posts
          </p>
          <h3 class="font-semibold">Created</h3>
          <p>
            {new Date(group?.createdAt).toLocaleDateString()}
          </p>
        {/if}
      </div>
      <div class="border-b py-2">
        <h3 class="text-lg font-semibold">Rules</h3>
        <OpenpeepsMarkdown
          source={group?.rules || 'No rules yet'}
          linkPreviewMode="none"
        />
      </div>
    </div>
  {/if}
</AccessDeniedLoader>
