// platform/svelte/src/lib/components/core/form/ImageInput.svelte
<script lang="ts">
  import { Camera, Image, Loader2, X } from 'lucide-svelte';
  import { getModalManager } from '@openpeeps/ui';
  import { ImageEditModal } from '.';
  import type { MediaAttachment } from '@openpeeps/common/types';
  import { uuidv7 } from 'uuidv7';
  import { uploadMediaFileMutation } from '$lib/api';
  import { hasValue } from '@openpeeps/common/lib';
  import { i18nContext } from '$lib/components/i18n';
  import { convertToWebpIfHeic } from '$lib/utils';

  const { t } = i18nContext();
  const modalManager = getModalManager();
  const uploadMediaFile = uploadMediaFileMutation();
  let previewUrl = $state('');
  let isLoading = $state(false);

  interface Props {
    usage: string;
    description?: string;
    url?: string;
    displayType?: 'full' | 'avatar' | 'button';
    classes?: string;
    text?: string;
    aspectRatio?: string;
    minWidth?: number;
    minHeight?: number;
    maxWidth?: number;
    maxHeight?: number;
    maxSizeKb?: number;
    targetDimensions?: { width: number; height: number } | undefined;
    showAltInput?: boolean;
    showSelectAspectRatio?: boolean;
    specsText?: string;
    onchange: (attachment: MediaAttachment) => void;
    showFullImage?: boolean;
    title?: string;
  }

  let {
    usage,
    description = '',
    url = undefined,
    displayType = 'full',
    classes = '',
    text = t('form.imageInput.uploadText'),
    aspectRatio = undefined,
    minWidth = 0,
    minHeight = 0,
    maxWidth = Number.MAX_SAFE_INTEGER,
    maxHeight = Number.MAX_SAFE_INTEGER,
    maxSizeKb = 512,
    targetDimensions = undefined,
    showAltInput = false,
    showSelectAspectRatio = false,
    specsText = '',
    onchange,
    showFullImage = false,
    title = t('form.imageInput.uploadTitle'),
  }: Props = $props();

  	let backgroundStyle = $state('');


  if (!specsText) {
    specsText = [
      minWidth && t('form.imageInput.minWidth', { width: minWidth }),
      minHeight && t('form.imageInput.minHeight', { height: minHeight }),
      aspectRatio && t('form.imageInput.aspectRatio', { ratio: aspectRatio }),
      maxSizeKb && t('form.imageInput.maxSize', { size: maxSizeKb }),
    ]
      .filter(Boolean)
      .join(', ');
  }

  let fileInput: HTMLInputElement | undefined = $state();

  const defaultClasses = {
    full: 'h-52 w-full relative border-dashed border',
    avatar: 'size-24 flex items-center justify-center',
    button: '',
  };

  const defaultAttachment = (
    url: string,
    filename: string,
  ): MediaAttachment => ({
    id: uuidv7(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    description,
    url,
    type: 'image',
    previewUrl: url,
    filename,
    textUrl: null,
    meta: {
      usage,
    },
  });

  const onFileSelected = async () => {
    const file = fileInput?.files?.[0];

		if (!file) {
			return
		}

		const processedFile = await convertToWebpIfHeic(file)

		isLoading = true;
		if (file && file.type.includes('image')) {

			const reader = new FileReader();
			reader.addEventListener('load', () => {
				const url = reader.result as string;
				modalManager.show(
					ImageEditModal,
					{
						attachment: defaultAttachment(url, processedFile.name),
						aspectRatio,
						minHeight,
						minWidth,
						maxHeight,
						maxWidth,
						maxSizeKb,
						showAltInput,
						showSelectAspectRatio,
						targetDimensions:
							displayType === 'avatar' ? { width: 150, height: 150 } : targetDimensions,
						cropShape: displayType === 'avatar' ? 'round' : 'rect'
					},
					(attachment?: MediaAttachment) => {
						if (attachment) {
							previewUrl = attachment.url;
							onchange(attachment);
						}
					}
				);
			});
			reader.readAsDataURL(processedFile);
		} else if (file && (file.type.includes('video') || file.name.endsWith('.mkv'))) {
			await uploadMediaFile({ file, description, usage: 'post-video' }).then(onchange);
		}
		isLoading = false;
	};
	$effect(() => {
		const updatedStyle = previewUrl
			? `background-image: url(${previewUrl})`
			: `background-image: url(${url})`;
		backgroundStyle = updatedStyle;
	});

  const iconClass =
    'flex size-10 items-center justify-center rounded-full bg-surface-200 opacity-50';
</script>

<button {title} class="{defaultClasses[displayType]} relative {classes}">
  <span class="flex size-full items-center">
    <span
      class="flex size-full flex-col items-center justify-center bg-center bg-no-repeat"
      class:bg-surface-200={displayType === 'full' && !url}
      class:bg-surface-300={displayType === 'avatar' && !url}
      class:rounded-full={displayType === 'avatar'}
      class:bg-cover={!showFullImage}
      style={backgroundStyle}
    >
      {#if displayType === 'full'}
        {#if !hasValue(url || previewUrl)}
          <Camera />
          <span class="font-bold">{text}</span>
          <span class="text-sm">{specsText}</span>
        {:else}
          <span class="flex items-center gap-4">
            <span class={iconClass}>
              <Camera />
            </span>
            <span class={iconClass}>
              <X />
            </span>
          </span>
        {/if}
      {:else if displayType === 'button' || (displayType === 'avatar' && !url)}
        <Image />
      {/if}
      {#if displayType === 'avatar'}
        <span
          class="bg-surface-200 absolute bottom-0 right-0 flex size-10 items-center justify-center rounded-full"
          class:opacity-80={url}
        >
          <Camera size={20} />
        </span>
      {/if}
    </span>
    {#if isLoading}
      <Loader2 class="ml-2 h-8 w-8 animate-spin" />
    {/if}
  </span>
  <input
    type="file"
    accept="image/*, video/*,.mkv"
    bind:this={fileInput}
    onchange={onFileSelected}
    class="absolute left-0 top-0 size-full cursor-pointer opacity-0"
    disabled={isLoading}
  />
</button>

// platform/react/src/components/form/ImageInput.tsx
import { useRef, useState } from 'react';
import { Camera, Image as ImageIcon, Loader2, X } from 'lucide-react';
import { useT } from '../../i18n';
import { useOpenpeeps } from '../../contexts/openpeeps';
import { convertToWebpIfHeic } from '../../lib/canvasUtils';
import { ImageEditModal } from './ImageEditModal';

export interface ImageInputProps {
  usage: string;
  url?: string;
  onChange: (url: string | undefined) => void;
  /** Bold call-to-action shown in the empty state. */
  text?: string;
  /** Smaller hint shown below the call-to-action. */
  specsText?: string;
  /** Show the alt-text field inside the crop modal. */
  showAltInput?: boolean;
  /** Extra classes for the drop-zone (e.g. aspect ratio overrides). */
  className?: string;
  /** When true, show the full image (contain) instead of cropping to cover. */
  showFullImage?: boolean;
  /**
   * `full` is the dashed banner drop-zone; `avatar` is a round picker with a
   * camera badge (mirrors the Svelte `displayType`).
   */
  displayType?: 'full' | 'avatar';
  /** Fixed crop ratio (`"w:h"`) forwarded to the crop modal. */
  aspectRatio?: string;
  /** Show the crop-ratio picker in the modal (free crop). */
  showSelectAspectRatio?: boolean;
}

/**
 * Image picker mirroring the Svelte `ImageInput`. `displayType="full"` is a
 * dashed box that prompts for an upload when empty and shows the image as a
 * cover with replace/remove controls once set; `displayType="avatar"` is a
 * round picker with a camera badge. Cropping happens in `ImageEditModal`; the
 * cropped file is uploaded and the resulting URL is reported via `onChange`.
 */
export function ImageInput({
  usage,
  url,
  onChange,
  text,
  specsText,
  showAltInput = false,
  className,
  showFullImage = false,
  displayType = 'full',
  aspectRatio,
  showSelectAspectRatio,
}: ImageInputProps) {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const { upload } = openpeepsApi.useMediaUpload();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [pendingImage, setPendingImage] = useState<{
    file: File;
    previewUrl: string;
  } | null>(null);
  const [loading, setLoading] = useState(false);
  const isAvatar = displayType === 'avatar';

  const pickFile = (file: File) => {
    void (async () => {
      const processed = await convertToWebpIfHeic(file);
      setPendingImage({
        file: processed,
        previewUrl: URL.createObjectURL(processed),
      });
    })();
  };

  const clearPending = () => {
    if (pendingImage) URL.revokeObjectURL(pendingImage.previewUrl);
    setPendingImage(null);
  };

  const fileInput = (
    <input
      ref={fileInputRef}
      type="file"
      accept="image/*"
      className="hidden"
      onChange={(e) => {
        const file = e.target.files?.[0];
        if (file) pickFile(file);
        e.target.value = '';
      }}
    />
  );

  const cropModal = pendingImage ? (
    <ImageEditModal
      file={pendingImage.file}
      previewUrl={pendingImage.previewUrl}
      open
      showAltInput={showAltInput}
      cropShape={isAvatar ? 'round' : 'rect'}
      aspectRatio={aspectRatio}
      showSelectAspectRatio={showSelectAspectRatio}
      onClose={clearPending}
      onConfirm={async (file) => {
        clearPending();
        setLoading(true);
        try {
          const attachment = await upload({ file, usage });
          onChange(attachment.url ?? undefined);
        } finally {
          setLoading(false);
        }
      }}
    />
  ) : null;

  if (isAvatar) {
    return (
      <div className={`relative size-24 ${className ?? ''}`}>
        <button
          type="button"
          className={`flex size-24 items-center justify-center overflow-hidden rounded-full bg-cover bg-center ${url ? '' : 'bg-muted text-muted-foreground'}`}
          style={url ? { backgroundImage: `url(${url})` } : undefined}
          onClick={() => fileInputRef.current?.click()}
          title={t('form.headerAvatarInput.avatar', {
            defaultValue: 'Profile photo',
          })}
        >
          {url ? null : <ImageIcon className="size-8" />}
        </button>
        <span
          className={`bg-surface-2 pointer-events-none absolute bottom-0 right-0 flex size-9 items-center justify-center rounded-full ${url ? 'opacity-80' : ''}`}
        >
          <Camera className="size-5" />
        </span>
        {loading ? (
          <span className="bg-muted/80 absolute inset-0 z-20 flex items-center justify-center rounded-full">
            <Loader2 className="size-6 animate-spin" />
          </span>
        ) : null}
        {fileInput}
        {cropModal}
      </div>
    );
  }

  return (
    <div
      className={`bg-surface-2 relative flex h-52 w-full items-center justify-center overflow-hidden rounded border border-dashed bg-center bg-no-repeat ${showFullImage ? 'bg-contain' : 'bg-cover'} ${className ?? ''}`}
      style={url ? { backgroundImage: `url(${url})` } : undefined}
    >
      {url ? (
        <div className="relative z-10 flex items-center gap-4">
          <button
            type="button"
            title={t('form.imageInput.replace', {
              defaultValue: 'Replace image',
            })}
            className="bg-surface-2/80 flex size-10 items-center justify-center rounded-full"
            onClick={() => fileInputRef.current?.click()}
          >
            <Camera className="size-5" />
          </button>
          <button
            type="button"
            title={t('form.imageInput.remove', {
              defaultValue: 'Remove image',
            })}
            className="bg-surface-2/80 flex size-10 items-center justify-center rounded-full"
            onClick={() => onChange(undefined)}
          >
            <X className="size-5" />
          </button>
        </div>
      ) : (
        <button
          type="button"
          className="text-muted-foreground flex size-full flex-col items-center justify-center gap-1"
          onClick={() => fileInputRef.current?.click()}
        >
          <Camera className="size-8" />
          <span className="font-bold">
            {text ??
              t('form.imageInput.uploadText', { defaultValue: 'Upload Image' })}
          </span>
          {specsText ? <span className="text-sm">{specsText}</span> : null}
        </button>
      )}

      {loading ? (
        <span className="bg-muted/80 absolute inset-0 z-20 flex items-center justify-center">
          <Loader2 className="size-8 animate-spin" />
        </span>
      ) : null}

      {fileInput}
      {cropModal}
    </div>
  );
}
