// platform/svelte/src/lib/components/form/LocationInput.svelte
<script lang="ts" module>
	import type { ZodRawShape } from 'zod';

	type T = ZodRawShape;
</script>

<script lang="ts">
	import {
		Button,
		deepGet,
		deepSet,
		getFormContext,
		Input,
		Label,
		LoadingIcon,
		pathToString
	} from '@openpeeps/ui';
	import { MapPin } from 'lucide-svelte';
	import type { GeocodingResult, Location } from '@openpeeps/common';
	import type { FormEventHandler } from 'svelte/elements';
	import { geocode } from '$lib/api/location';
	import { i18nContext } from '$lib/components/i18n';

	const { t } = i18nContext();

	const { messagesStore, data, validate } = getFormContext<T>();

	interface Props {
		title?: string;
		description?: string;
		path: (number | string)[];
		placeholder?: string;
		dirty?: boolean;
		disabled?: boolean;
		readonly?: boolean;
	}

	let {
		title = '',
		description = '',
		path,
		placeholder = title,
		dirty = $bindable(false),
		disabled = false,
		readonly = false
	}: Props = $props();

	let name = $state((deepGet(data, path) as Location)?.text || '');

	let debounceTimeout: ReturnType<typeof setTimeout> | undefined;
	let debouncedGeocode = (query: string) => {
		if (debounceTimeout) {
			clearTimeout(debounceTimeout);
		}
		if (query.length < 3) {
			return undefined;
		}
		return new Promise<GeocodingResult[]>((resolve) => {
			debounceTimeout = setTimeout(async () => {
				const results = await geocode(query.trim());
				resolve(results);
			}, 1500);
		});
	};

	let suggestionsPromise: Promise<GeocodingResult[]> | undefined = $state(undefined);

	const onSelection = (geocodingResult: Partial<GeocodingResult> & { name: string }) => {
		dirty = true;
		const location = {
			text: geocodingResult.name,
			coordinates: geocodingResult.center
		};
		deepSet(data, path, location);
		name = geocodingResult.name;
		suggestionsPromise = undefined;
		validate();
	};

	const updateAndValidate: FormEventHandler<HTMLInputElement> = (e) => {
		const text = e.currentTarget.value;
		dirty = true;
		suggestionsPromise = debouncedGeocode(text);
		deepSet(data, path, { text });
		validate();
	};
</script>

<Label
	{title}
	{description}
	messages={dirty ? $messagesStore[pathToString(path)] : []}
	classes="relative"
>
	<div class="input-group input-group-divider grid-cols-[auto_1fr_auto] rounded-full">
		<div class="input-group-shim"><MapPin class="size-4" /></div>
		<Input
			bind:value={name}
			type="text"
			{placeholder}
			{disabled}
			{readonly}
			oninput={updateAndValidate}
		/>
	</div>
	{#if suggestionsPromise}
		<div class="card absolute bottom-16 flex w-full flex-col items-start gap-3 p-2 text-sm">
			{#await suggestionsPromise}
				<div class="flex w-full flex-col items-center justify-center gap-2 p-4">
					<span>{t('location.lookup', { name })}</span>
					<LoadingIcon />
				</div>
			{:then suggestions}
				<Button
					class="border-surface-300 hover:bg-surface-hover-token w-full rounded p-2 text-left"
					action={() => onSelection({ name })}
				>
					{name}
				</Button>
				{#each suggestions! as geocodingResult, index (index)}
					<Button
						class="border-surface-300 hover:bg-surface-hover-token w-full rounded p-2 text-left"
						action={() => onSelection(geocodingResult)}
					>
						{geocodingResult.name}
					</Button>
				{/each}
			{/await}
		</div>
	{/if}
</Label>

// platform/react/src/components/form/LocationInput.tsx
import { useEffect, useRef, useState } from 'react';
import { MapPin } from 'lucide-react';
import {
  Button,
  Input,
  Label,
  LoadingIcon,
  cn,
  deepGet,
  deepSet,
  pathToString,
  useFormContext,
  useFormMessages,
} from '@openpeeps/react-ui';
import type { GeocodingResult, Location } from '@openpeeps/common';
import { useT } from '../../i18n';

export interface LocationInputProps {
  title?: string;
  description?: string;
  path: (number | string)[];
  placeholder?: string;
  disabled?: boolean;
  readOnly?: boolean;
  /** Forwarded to the geocoder. Pass an async fn that returns suggestions. */
  geocode: (query: string) => Promise<GeocodingResult[]>;
  /** Debounce in ms for the geocode lookup. Defaults to 1500. */
  debounceMs?: number;
}

/**
 * React port of @openpeeps/svelte/components/form/LocationInput.svelte. Wires
 * a Form-context input to a debounced geocoder + suggestion popover.
 */
export function LocationInput({
  title = '',
  description = '',
  path,
  placeholder,
  disabled = false,
  readOnly = false,
  geocode,
  debounceMs = 1500,
}: LocationInputProps) {
  const { data, validate } = useFormContext();
  const messages = useFormMessages();
  const t = useT();
  const [dirty, setDirty] = useState(false);

  const initialName = (deepGet(data, path) as Location | undefined)?.text ?? '';
  const [name, setName] = useState(initialName);
  const [suggestions, setSuggestions] = useState<GeocodingResult[] | null>(
    null,
  );
  const [pending, setPending] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(
    () => () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    },
    [],
  );

  const onSelection = (sel: Partial<GeocodingResult> & { name: string }) => {
    setDirty(true);
    deepSet(data as object, path, {
      text: sel.name,
      coordinates: sel.center,
    } as Location);
    setName(sel.name);
    setSuggestions(null);
    void validate();
  };

  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const text = e.currentTarget.value;
    setName(text);
    setDirty(true);
    deepSet(data as object, path, { text });
    void validate();

    if (debounceRef.current) clearTimeout(debounceRef.current);
    if (text.length < 3) {
      setSuggestions(null);
      setPending(false);
      return;
    }
    setPending(true);
    debounceRef.current = setTimeout(() => {
      void geocode(text.trim()).then((r) => {
        setSuggestions(r);
        setPending(false);
      });
    }, debounceMs);
  };

  return (
    <Label
      title={title}
      description={description}
      messages={dirty ? messages[pathToString(path)] : []}
      classes="relative"
    >
      <div
        className={cn(
          'op-input-group grid grid-cols-[auto_1fr_auto] rounded-full',
        )}
      >
        <div className="op-input-group-shim">
          <MapPin className="size-4" />
        </div>
        <Input
          value={name}
          type="text"
          placeholder={placeholder ?? title}
          disabled={disabled}
          readOnly={readOnly}
          onChange={onChange}
        />
      </div>
      {(pending || suggestions) && (
        <div className="op-card absolute bottom-16 flex w-full flex-col items-start gap-3 p-2 text-sm">
          {pending ? (
            <div className="flex w-full flex-col items-center justify-center gap-2 p-4">
              <span>{t('location.lookup', { name })}</span>
              <LoadingIcon />
            </div>
          ) : (
            <>
              <Button
                className="border-surface-300 hover:bg-muted w-full rounded border p-2 text-left"
                action={() => onSelection({ name })}
              >
                {name}
              </Button>
              {suggestions?.map((res, idx) => (
                <Button
                  key={idx}
                  className="border-surface-300 hover:bg-muted w-full rounded border p-2 text-left"
                  action={() => onSelection(res)}
                >
                  {res.name}
                </Button>
              ))}
            </>
          )}
        </div>
      )}
    </Label>
  );
}
