// platform/web/src/pages/feeds/Local.tsx
import { useT, useOpenpeeps } from '@openpeeps/react';
import {
  Feed,
  NewNoteButton,
  useCurrentProfile,
  useDefaultVisibility,
  useServerInfo,
} from '@openpeeps/react/components';

export function FeedsLocal() {
  const t = useT();
  const { openpeepsApi } = useOpenpeeps();
  const currentProfile = useCurrentProfile();
  const visibility = useDefaultVisibility();
  const serverInfo = useServerInfo();

  const query = openpeepsApi.useLocalFeed({ limit: 15 });
  const pinnedPostId = serverInfo.communityConfig?.content?.pinnedPost;

  return (
    <div className="space-y-4 p-4">
      <h1 className="text-2xl font-semibold">
        {t('navigation.community', { defaultValue: 'Community' })}
      </h1>
      <NewNoteButton
        visibility={visibility}
        currentProfile={currentProfile}
      />
      <Feed query={query} pinnedPostId={pinnedPostId ?? undefined} />
    </div>
  );
}

// platform/app/src/routes/(protected)/(conditionally-public)/feeds/local/+page.svelte
<script lang="ts">
  import { Feed, NewNoteButton } from '@openpeeps/svelte/components';
  import { infiniteLocalFeedStore, serverInfoStore } from '@openpeeps/svelte/api';
  import { i18nContext } from '@openpeeps/svelte/components';
  import { setPageHeader } from '@openpeeps/svelte/stores';
  import { getCurrentProfile } from '@openpeeps/svelte/auth';
  import { getDefaultVisibility } from '@openpeeps/svelte';

  const { t } = i18nContext();
  const currentProfile = getCurrentProfile();
  const visibility = getDefaultVisibility();
  const query = infiniteLocalFeedStore({ limit: 15 });

  const serverInfo = serverInfoStore();
  let pinnedPostId: string | undefined = $derived(
    $serverInfo.data?.communityConfig?.content?.pinnedPost,
  );
  setPageHeader({ title: t('navigation.community') });
</script>

<NewNoteButton {visibility} {currentProfile} />
<Feed {query} {pinnedPostId} />
